### ISSUE TITLE
Crash when connected to facebook group

### ISSUE THREAD

**Issue by mrkno** [Schmavery/facebook-chat-api#100]
This issue is copied from https://github.com/mrkno/Kassy/issues/34. It only seems to occur on >v1.0.2 as far as our limited testing can determine. I tested internationalisation and it didn't seem to have any difficulties but given time constraints testing was not extensive.

<hr>

so it is working fine , when i am using it in personal chat , but when i add the profile that is on the bot , the script crashes and gives me this error:

ERR! ERROR in listen --> TypeError: Cannot call method 'toString' of undefined
ERR! ERROR in listen --> at Object.formatTyp (/home/kawaii/Kassy/node_modules/facebook-chat-api/utils.js:294:24)
ERR! ERROR in listen --> at parsePackets (/home/kawaii/Kassy/node_modules/facebook-chat-api/src/listen.js:97:42)
ERR! ERROR in listen --> at Array.forEach (native)
ERR! ERROR in listen --> at /home/kawaii/Kassy/node_modules/facebook-chat-api/src/listen.js:86:12
ERR! ERROR in listen --> at tryCatcher (/home/kawaii/Kassy/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
ERR! ERROR in listen --> at Promise._settlePromiseFromHandler (/home/kawaii/Kassy/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:507:31)
ERR! ERROR in listen --> at Promise._settlePromiseAt (/home/kawaii/Kassy/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:581:18)
ERR! ERROR in listen --> at Promise._settlePromises (/home/kawaii/Kassy/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:697:14)
ERR! ERROR in listen --> at Async._drainQueue (/home/kawaii/Kassy/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:123:16)
ERR! ERROR in listen --> at Async._drainQueues (/home/kawaii/Kassy/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:133:10)
ERR! ERROR in listen --> at Async.drainQueues (/home/kawaii/Kassy/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)
ERR! ERROR in listen --> at process._tickCallback (node.js:415:13)
ERR! ERROR in listen --> [TypeError: Cannot call method 'toString' of undefined]
[TypeError: Cannot call method 'toString' of undefined]

Overall a great program/script here, but i'm mostly going to use if for a group chats , if you can fix it i would love it <3 . And i should add that some of the names of the people in the chat room are in Bulgarian, that uses diffrent alphabet than the english one. There are hole diffrrent.

**Comment by bsansouci** [comment]
Hey @mrkno can you print the `event` after line 290 in `utils.js`? We updated the `typ` event after what seemed like a change on FB's end here 2059829317ed40d0c46872ddea763e05c441d4af but change might only exist for certain people.

**Comment by Schmavery** [comment]
@mrkno turning off `listenEvents` should be a workaround for now, but we're still interested to know more about this problem so that we can fix it.

**Comment by mrkno** [comment]
@Schmavery sorry for the delay - I've been quite busy lately with a few other things.

I did some testing and printed out the value of event after line 290 as requested earlier using v1.0.3.
```
{
  "st": 1,
  "from": 100000645113290,
  "thread": "874047089376806",
  "thread_fbid": 874047089376806,
  "from_mobile": false,
  "realtime_viewer_fbid": 100009621438986,
  "type": "ttyp"
}
```
The stack trace then follows the same as above.
I was able to create a new group chat that did not cause this problem, but when I originally reproduced the error it was also on a new chat so I don't know what to make of that....

It seems to be trying to call `toString()` on `event.to` which in the above event doesn't exist.

Hope thats some help towards fixing the problem. I would look into it in more detail myself, but as mentioned I have quite a few other things to do at the moment.

**Comment by Schmavery** [comment]
@mrkno Thanks for the information.  We're also a little busy so we'll look into it as soon as we get a chance :smile:

**Comment by Schmavery** [comment]
@bsansouci Looks like Facebook changed their signature for typ events in groups.  Looks like we can change [this line](https://github.com/Schmavery/facebook-chat-api/blob/master/utils.js#L294) from
`threadID: event.to.toString(),`
to
`threadID: (event.to || event.thread_fbid).toString(),` 
to fix this.

**Comment by bsansouci** [comment]
I think they only rolled out the update to part of the population. It's `event.to` on my end and I childishly assumed it would be the same everywhere. I agree with this fix.

**Comment by Schmavery** [comment]
@mrkno Thanks for the heads up on this bug, please reopen if this doesn't fix it. :)
