### ISSUE TITLE
restarting listener after stopping it without logout

### ISSUE THREAD

**Issue by rikka94** [Schmavery/facebook-chat-api#101]
api.listen(callback); //I did this to start a listener work

(api.listen())(); //i call this , the listener is stopped

api.listen(callback); //then i call this again, listener didn't restart

DId i use the method wrongly ? How do i restart the message listener ?

Thanks..

**Comment by bsansouci** [comment]
Get @rikka94, `api.listen(callback)` returns a function to stop that given callback (not all callbacks). So you should do `var stop = api.listen(callback)` and later when you need to stop that listen you can do `stop()`. 
If you need multiple callbacks running simultaneously you can also do that, and each function returned by `listen` is specific to the callback given.

**Comment by Schmavery** [comment]
We don't actually support multiple callbacks right now actually, can you explain what you're trying to do?

**Comment by rikka94** [comment]
I am currently writing a wrapper library in .NET using [edgeJS](https://github.com/tjanczuk/edge).

I've completed the sending and receiving message event handling part, now i am looking for a way to toggle the message listener on/off.

What i've been doing now i am storing the 'api' from the login callback into a GLOBAL variable so that i can access it from different script within same process.

for example, in the first script , i starting the listener
```javascript
var api = GLOBAL.api;
//other code
api.listen(callback) ; //at here the listener is started
```

and then, in the second script , i stopping the listener
```javascript
var api = GLOBAL.api;
(api.listen())(); //I tried this to stop it and it work for some reason, maybe i was wrong here.
```
then at here if i calling the first script again, listener didn't restart.

That's probably the whole situation.
Thanks.

**Comment by Schmavery** [comment]
If all you're trying to do is stop the callback, you're definitely going to want to call the stopListening callback like @bsansouci explained.  Calling listen() with no arguments has undefined behaviour right now.

**Comment by rikka94** [comment]
i don't have issue stopping the callback but i need to restart it after stopping.

Anyway i got dirty solution myself by blocking the callback using a boolean.

Thanks for the help

**Comment by Schmavery** [comment]
So after calling stopListening, you aren't able to register a new callback?  I'm assuming you get no errors but you just never get any events?

**Comment by rikka94** [comment]
Yea no error is show, just can't get event after stopping and register again..

Did you able to restart it ?
