### ISSUE TITLE
Persistent login

### ISSUE THREAD

**Issue by nripendra** [Schmavery/facebook-chat-api#104]
Hi,

Is there a way to do a persistent login, such that I don't need to login every-time my application starts? 

Mine is a gui application... 

Regards.

**Comment by Schmavery** [comment]
You should be able to do this using the `api.getAppState()` function and then passing it into the [login](https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#logincredentials-options-callback) (check out the section "Example (AppState loaded from file)")

**Comment by nripendra** [comment]
Thanks! I'll give it  a try.

**Comment by Schmavery** [comment]
Cool, please reopen this issue if it doesn't work out ;)
