### ISSUE TITLE
Mark as read broken

### ISSUE THREAD

**Issue by nripendra** [Schmavery/facebook-chat-api#105]
Hi,

It seems mark as read got recently broken??

Seems to be move to some other url by facebook...

```
errorSummary: 'This content is no longer available',
errorDescription: 'The content you requested cannot be displayed right now. It may be temporarily unavailable, the link you clicked on may have expired, or you may not have permission to view this page.',
```
Was working quite fine few days ago.

Thanks,
Nripendra

**Comment by nripendra** [comment]
Going through fb requests in network panel, the url seems right. Not sure where and why error is coming from.

**Comment by Schmavery** [comment]
Is there any chance that it still works to mark them as read?  We were getting false errors in addUserToGroup earlier.

**Comment by nripendra** [comment]
No, its not working, I have confirmed using fb web page.

**Comment by nripendra** [comment]
Ok, it could be an issue in my code.. 
After some poking around. I see following as form request.. 
```
id[undefined]: true
```

should have been the threadID.
I'll look more into the issue why threadID is undefined and come back to you.

**Comment by Schmavery** [comment]
If you want to show us a code sample that exhibits this problem, it'll be easier for us to diagnose.  :)

**Comment by nripendra** [comment]
Hmm, actually found the issue. The property of user used to be "id", now it's userID so that seem to be causing the issue. :) 

The exact code is in github itself.. [here](https://github.com/nripendra/fb-messenger/blob/develop/src/components/conversation.tsx#L63)

**Comment by Schmavery** [comment]
Sounds like it's not a problem with the api then?  Can I resolve this issue?  Unfortunately v1 had a number of breaking changes, but at least it's a lot more consistent now. :)

**Comment by nripendra** [comment]
Yes, fixing that line fixed the issue. Closing the issue now.
