### ISSUE TITLE
Seen notification

### ISSUE THREAD

**Issue by nripendra** [Schmavery/facebook-chat-api#107]
I was thinking it would be part of "event" type but doesn't seem to be the case?

**Comment by Schmavery** [comment]
Sorry, I don't really understand what you're asking for here.
Are you seeing an undocumented type of event?
Or is this a feature request?

**Comment by nripendra** [comment]
It could be termed a feature request if we don't have this type of event already.
I want to notify user, when a sent message has been marked as read on other side.

It is basically markAsRead in reverse direction..

Please let me know if it's still not clear.

**Comment by bsansouci** [comment]
@nripendra tell me if this works for you.

**Comment by Schmavery** [comment]
Assuming this works, it needs to be documented.

**Comment by nripendra** [comment]
I'll check and comment when I get time. Thanks!
