### ISSUE TITLE
Error on getting access token

### ISSUE THREAD

**Issue by blazeu** [Schmavery/facebook-chat-api#11]
Using version 0.1.9

```
node_modules/facebook-chat-api/index.js:787
tps://www.facebook.com/connect/login_success.html#access_token=")[1].split("&"
                                                                    ^
TypeError: Cannot read property 'split' of undefined
    at Request._callback (node_modules/facebook-chat-api/index.js:787:147)
```

**Comment by jpacora** [comment]
The same here

**Comment by Schmavery** [comment]
Can you print out the contents of `ret` right before [line 801 of index.html](https://github.com/Schmavery/facebook-chat-api/blob/0adcf87329f27e1e505d4976cd839f22d7d9ecd0/index.js#L801)?
It looks like the api is having trouble generating a graph access token, unfortunately I don't get this problem on our test account.

You could also see if it's possible for you to log into the account you're using and access this URL: https://developers.facebook.com/tools/explorer/145634995501895/?method=GET&path=me%3Ffields%3Did%2Cname&version=v2.3

**Comment by blazeu** [comment]
here's ```ret```

```
{ __ar: 1,
  payload: null,
  jsmods: 
   { require: 
      [ [ 'Cookie',
          'setIfFirstPartyContext',
          [ [length]: 0 ],
          [ '_js_datr',
            'ycxRVSRRbi3N2ZVc9lYSmISs',
            1494496201000,
            '/',
            '.facebook.com',
            false,
            [length]: 6 ],
          [length]: 4 ],
        [ 'ServerRedirect',
          'redirectPageTo',
          [ [length]: 0 ],
          [ 'https://www.facebook.com/connect/login_success.html#access_token=CAACEdEose0cBACxqyKqInMW34UX29aReKITUcZB0S3FBowSGUZA1FkywPIu5Wk1gZCeqGmyqD4RFZCtHMptB4JD7cJK9YqXLWUOEcM0VjgqB9RJMeyaZCEesILzzkRe8DVcL4mFbvua2xtxs7yLap0ZCbBELZBQqYApxOX5ELH9U8pYNBedwCybQSohbEKtdtsLNsnShCTlHwZDZD&expires_in=4199',
            true,
            [length]: 2 ],
          [length]: 4 ],
        [length]: 2 ] },
  js: [ 'UMpUI', [length]: 1 ],
  bootloadable: {},
  resource_map: 
   { UMpUI: 
      { type: 'js',
        src: 'https://fbstatic-a.akamaihd.net/rsrc.php/v2/yQ/r/wInu57m6uFQ.js' } },
  ixData: {},
  lid: '0' }
```
it seems like it should be getting ```ret.jsmods.require[1][3][0]```
instead of ```ret.jsmods.require[0][3][0]``` on line [801](https://github.com/Schmavery/facebook-chat-api/blob/0adcf87329f27e1e505d4976cd839f22d7d9ecd0/index.js#L801)

**Comment by Tankenstein** [comment]
Same problem here.

**Comment by Schmavery** [comment]
Thanks for the info guys, I think I'll be able to push a fix within an hour or two.

**Comment by Schmavery** [comment]
OK I published a fix to version 0.1.10.
Does this fix the problem for anyone?

**Comment by Tankenstein** [comment]
Yes! fixed for me.

**Comment by blazeu** [comment]
fixed.
