### ISSUE TITLE
Error on login - wrong email/password

### ISSUE THREAD

**Issue by rgwsk65** [Schmavery/facebook-chat-api#114]
Hey, I get this error today and I fixed it by changing "www.facebook" to "web.facebook" in all files

**Comment by bsansouci** [comment]
That's very strange. Can you add `require('fs').writeFileSync('testing.html', res.body)` here https://github.com/Schmavery/facebook-chat-api/blob/3851842759cf009d2998163bd06fccfc66c3d9ab/index.js#L152 and check what the `testing.html` page looks like?
My best guess is that your account got blocked, and somehow visiting `web.facebook` bypasses that block. Our error "Error on login - wrong email/password" is very general, and could be totally unrelated to a mismatching email/password.

**Comment by rgwsk65** [comment]
I switched back www.facebook* and everything is okay. Probably that could be a block, because i switched user agent to mine preferred ;). Thank you for your response ;)

**Comment by bsansouci** [comment]
No problem! That's a very weird behavior though. Would you mind still printing to a file whenever you can reproduce that? I'd love to see what happens so we can handle that edge case  more smoothly.
