### ISSUE TITLE
Event on login progress

### ISSUE THREAD

**Issue by nripendra** [Schmavery/facebook-chat-api#118]
Login process looks fine for CLI, but on GUI it looks like something went wrong because it takes quite sometime to complete. 

Could it be possible to add some kind of event notification for login progress? My idea is to show something like approx. progressbar on my UI.

**Comment by Schmavery** [comment]
Does it really takes that long?  It usually doesn't take longer than a couple seconds for me.  Can you display a spinner or something?

**Comment by nripendra** [comment]
@Schmavery I'd like to point out that I'm based at Nepal. Broadband here may not be as fast. For me login process takes about 15-20 seconds. Even with spinner it looks broken.

While testing there has been instance where things were really broken due to my code changes. But I was waiting, since login usually takes some time.

In contrast to GUI, in CLI I do get some progress feedback like "Logging in...", "Logged in", "Request to pull 1", "Request to pull 2", "Request to thread_sync" and "Done logging in.", which clearly shows some progress being made during loging.

**Comment by bsansouci** [comment]
An event system would be a significant change for us. It could be done if enough people request it, but for now I'd suggest you "hack" into the logger. You can simply inject your own logging function that'll check the messages logged and react to those events. Check out [this page](https://github.com/npm/npmlog), it explains the npmlog api.

**Comment by nripendra** [comment]
@bsansouci Thanks for suggestion. I'll look into it.

**Comment by Schmavery** [comment]
Closing.  Feel free to open if you need more help.
