### ISSUE TITLE
Listen own message

### ISSUE THREAD

**Issue by Tingyus** [Schmavery/facebook-chat-api#12]
Is it possible to add a function ( maybe just in api.listen ) to read user's own message ( send from web ) , this way , it's easier to make a chat assistant , thanks

**Comment by Schmavery** [comment]
Working on this now.  You're going to want to be careful with this feature...

![bewareselflisten](https://cloud.githubusercontent.com/assets/2154522/7782523/9cd648e0-00ea-11e5-8209-9484c0d3154f.png)

**Comment by Schmavery** [comment]
@Tingyus does this help your problem?
You can set the api to listen to itself with this command:
```
api.setOptions({
  selflisten: true
});
```

**Comment by Tingyus** [comment]
thanks , it works perfectly , I am going to make my chat assistant :)
