### ISSUE TITLE
forceLogin not used?

### ISSUE THREAD

**Issue by Weetbix** [Schmavery/facebook-chat-api#122]
Am I crazy or is the forceLogin option never used by facebook-chat-api?

**Comment by Schmavery** [comment]
@bsansouci I was under the impression that we are using this option to auto-unblock in some cases.
Namely https://github.com/Schmavery/facebook-chat-api/blob/master/index.js#L215-L219, but doesn't look like it's actually being used.  Do you know if this was removed?

Regardless, we'll probably leave it in incase it comes up in the future.  `forceLogin` doesn't make any guarantees, it just "tries harder" when logging in, ideally.

**Comment by Weetbix** [comment]
Looks like it may have been accidentally removed while refactoring here: https://github.com/Schmavery/facebook-chat-api/commit/b66a95081be9cd0e3202a7df95bad90398112327#diff-168726dbe96b3ce427e7fedce31bb0bcL265

Seems like the behaviour now is to always force login, regardless of the forceLogin option (which the docs say defaults to false).

I think re-adding the throw statement if the option is false would be the way to go, or at least update the docs to remove the option or state it's not used.

**Comment by Schmavery** [comment]
Thanks for finding this.  I'd like @bsansouci to chime in on this before we make any moves, we'll give him a couple days considering the time of year ;)

I agree for now that we should re-add the throw.

**Comment by bsansouci** [comment]
90a06ed5fa3a0269193ccb3d52f12a58a47a43ec
