### ISSUE TITLE
api.logout fails

### ISSUE THREAD

**Issue by andyjbas** [Schmavery/facebook-chat-api#126]
[When trying to compose the logout form](https://github.com/Schmavery/facebook-chat-api/blob/master/src/logout.js#L18-L20), the filter function fails while looking for the label of `Log Out`. The label `Log out` **does** exist, however.

**Comment by bsansouci** [comment]
Hey @andyjbas, could you add `console.log(v)` [above this line](https://github.com/Schmavery/facebook-chat-api/blob/526ebfe9730d67a0020fb6ef564137f79f4bbe4a/src/logout.js#L19) and copy paste the result  here?
It seems to work fine on my end. @Schmavery on another note, I found a field `value` inside those objects which contains `logout` which sounds more stable that the `label` field we're using [here](https://github.com/Schmavery/facebook-chat-api/blob/526ebfe9730d67a0020fb6ef564137f79f4bbe4a/src/logout.js#L19)

Here's the logout object
```js
{
  class: 'navSubmenu',
  'data-gt': '{"ref":"async_menu","logout_menu_click":"menu_logout"}',
  testid: 'logout',
  value: 'logout',
  ctor: {
    __m: 'MenuItem'
  },
  markup: {
    __m: '__markup_3310c079_2_b'
  },
  label: 'Log Out',
  title: '',
  className: 'navSubmenu'
}
```

**Comment by andyjbas** [comment]
``` javascript
{ class: 'navSubmenu',
    'data-gt': '{"ref":"async_menu","logout_menu_click":"menu_logout"}',
    testid: 'logout',
    value: 'logout',
    ctor: { __m: 'MenuItem' },
    markup: { __m: '__markup_3310c079_9_e' },
    label: 'Log out',
    title: '',
    className: 'navSubmenu' },
```

I agree about the `value` field.

**Comment by Schmavery** [comment]
The value field sounds like a good fix to me.
