### ISSUE TITLE
api.getUserInfo() is not returning expected data.

### ISSUE THREAD

**Issue by trvrsalom** [Schmavery/facebook-chat-api#128]
When calling api.getUserIndo() with either an array of ids or a single id, it is unable to be parsed by makeParseable and JSON.parse, due to a 404 error: `Not Found <br /><a href="http://www.facebook.com/">Back to Facebook.</a>`. Trying to manually remove this message from the rest of the JSON, returns to a whole bunch of data, but not the expected data.

**Comment by bsansouci** [comment]
I just tried to run the tests and `getUserInfo` worked fine here. Could you show how you use it? Are you using the most recent code (master on github, not npm)?
Also could you paste the "whole bunch of data" that you get.

**Comment by trvrsalom** [comment]
I updated via npm, and now it works fine.

I managed to lose the "whole bunch of data" that I was getting, however it contained information about all threads and users.

**Comment by bsansouci** [comment]
Good news!
