### ISSUE TITLE
Refactor and modularize

### ISSUE THREAD

**Issue by matteocontrini** [Schmavery/facebook-chat-api#13]
The code is really difficult to understand and I guess to mantain for you.
My suggestion is to move pieces of the code in other files, creating sub-modules or "extensions" to the main file.

For example, when you create the `api` like this:

```js
var api = {};
api.setOptions = function() { ... }
api.listen = function() { ... }
```

The file gets really long and it is hard to understand when a function starts and ends. If every function of that api object had a file, everything would be better.

File: extensions/listen.js
```js
function listen() {
    ...
}
module.exports = listen;
```

And so on for every function. Then in index.js:

```js
api.listen = require('./extensions/listen.js');
// and so on
```

I hope you'll consider the suggestion.

Thank you for the work, it is great but it needs to improve on this aspect.

**Comment by bsansouci** [comment]
Hey! Thanks for the input, we've been planning to release a refactored version in the near future.

Always curious to know what people are working on :)

**Comment by bsansouci** [comment]
Do you find this helps?

**Comment by matteocontrini** [comment]
That's better but why are you passing utils as parameter for example? Just require it inside the "src" files, modules are cached so you get the same thing.

**Comment by matteocontrini** [comment]
Another thing: why the created `api` object is not created as an [actual class](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Introduction_to_Object-Oriented_JavaScript) that can have many instances?

**Comment by bsansouci** [comment]
Because the API object doesn't need to be instantiated, it's just a collection of functions.

**Comment by matteocontrini** [comment]
In fact that's how things work now. But a logical approach would be to allow multiple instance of a class, because now in a single application you can't have more than one instance of your API.

The fact that the module exports a `login` is a bit weird IMHO. I'd expect something like this:

```js
var Chat = require('facebook-chat-api');
var fb = new Chat({ username: '', password: '', otherOption: '' });
fb.login(function(err)) {
  // I can use 'fb' now
}
// And now I can create another Chat instance if I need it
```

Just a suggestion seeing how usually things work, with other modules :wink:

**Comment by bsansouci** [comment]
You can already call login as many times as you want, there is nothing in the global scope. A new API object is returned every time.

I can't really see a use case for changing the API to become more OO in this case.

**Comment by matteocontrini** [comment]
Sorry, I've seen `globalOptions` and, being the code nested in many levels, I couldn't find where it was declared :/
Anyway, as you prefer ;)

**Comment by bsansouci** [comment]
No problems! We're working on making the login function clearer because it's a little bit daunting right now.
