### ISSUE TITLE
No Nodejs

### ISSUE THREAD

**Issue by petr-stety-stetka** [Schmavery/facebook-chat-api#132]
Is here way, how use facebook-chat-api without nodejs, only with javascript?

**Comment by bsansouci** [comment]
cc @Schmavery.
I don't think there is anything that makes it impossible. The "easiest" way would probably be to mock out the `request` module and use something like webpack to bundle everything in one file. This isn't really a priority right now, but feel free to send us a PR. We might look into it if enough people request this feature.

**Comment by Schmavery** [comment]
I agree with Ben here, not a priority, but I've personally wished we supported this for a while and I'd love if someone took a crack at it.  Not sure what the best way to go about it is, but it would be great to be able to have this API work in a browser.

**Comment by mehcode** [comment]
> [...] would probably be to mock out the request module

Or use something like `superagent` or `fetch` that is isomorphic.

**Comment by ErmanSayin** [comment]
This wouldn't work because Facebook has CSRF protection

**Comment by bsansouci** [comment]
I think @ErmanSayin is right, this would result in CSRF errors... I'm not sure how to bypass that in a sane/safe way. I'm closing this issue because of it. Feel free to reopen if something comes up!
