### ISSUE TITLE
Accepting Friend Requests?

### ISSUE THREAD

**Issue by nishilshah17** [Schmavery/facebook-chat-api#136]
Is there anyway to accept friend requests using this API? If I wanted to develop that feature, how would I get started?

**Comment by Schmavery** [comment]
Currently this is not in the scope of this project.  Our goal is to make a clean interface for facebook chat functionality, not fill in all the gaps of the official API.
It's possible that someone here (@bsansouci) will have an idea of how to go about this.  Generally what we've done in the past is opened up the developer tools in the browser and watched which requests are performed when making the action you want to imitate.  In your case, you would see which requests are made when you accept a friend request. If you can fake all the values that are sent correctly, facebook shouldn't be able to tell the difference.
@bsansouci it's stuff like this that makes me wish we had merged #64...
