### ISSUE TITLE
Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by gmork** [Schmavery/facebook-chat-api#138]
Error with stacktrace:
```
Unhandled rejection TypeError: Cannot read property 'filter' of undefined
    at ../node_modules/facebook-chat-api/src/listen.js:169:40
    at ../node_modules/facebook-chat-api/src/searchForThread.js:27:18
    at tryCatcher (../node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (../node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (../node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (../node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (../node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (../node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (../node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

This happens for a specific group chat my user is in (5 participants, including myself). It could be that that thread was archived before receiving messages on it again though.

**Comment by bsansouci** [comment]
Mmmmh seems like `res` can only ever be empty when there's an error. Looking at the code, [this line](https://github.com/Schmavery/facebook-chat-api/blob/00788a221de0d07be1571cab9834ada60be71681/src/listen.js#L165) should probably return.
I pushed d45b6e73460168a503c0747ab8897a4d739b7f26, can you pull and check if that's fixed?

**Comment by gmork** [comment]
This branch does seem to fix the error. Any idea why this group chat returns an error when receiving messages throug the listen api? In this case: `{"error":"Could not find thread ``."}`?

Off-topic: 
On the master branch there's the following error
```
../node_modules/facebook-chat-api/utils.js:195
      ["p_" + userID]: 0
      ^
SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (../node_modules/facebook-chat-api/index.js:3:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by Schmavery** [comment]
Under what circumstances do you run into this error?  Do you get it for all group chats?  It looks kind of like this chat group has the name empty string.

@bsansouci the second one looks like a node version issue.  Do we have our dependencies set up right?  @gmork I'd suggest updating node to fix this probably.

**Comment by gmork** [comment]
npm update did result in a lot of updated dependencies, but not node itself. I'll check in a minute if this solved the problem on the master branch. As for the former issue, I added some debug output in the searchForThread.js:

```
tmpForm: {"client":"web_messenger","query":"","offset":0,"limit":21,"index":"fbid"}

resData: 
{
  "__ar": 1,
  "payload": {
    "search_threads": {
      "": [
        
      ]
    },
    "mercury_payload": {
      "payload_source": "server_search"
    }
  },
  "jsmods": {
    "require": [
      [
        "Cookie",
        "setIfFirstPartyContext",
        [
          
        ],
        [
          "_js_datr",
          "aW6RViwWVAwoMj6vo5KAfWE6",
          63072000000,
          "/",
          false
        ],
        [
          
        ]
      ]
    ]
  },
  "bootloadable": {
  },
  "ixData": {   
  },
  "lid": "6237888357409078582"
}
```

It is indeed correct that the thread has no name, though, it seems like no chat on FB has a name unless you explicitly give it one. After changing the name of the conversation everything worked again. Are there any other query parameters for the search_thread form which you can use to query a thread? This doesn't seem to happen for other threads (with less people in it).

**Comment by gmork** [comment]
As for the problem on the master branch, `ch{["p_" + userID]: 0}` seems syntaxically wrong using `"use strict"`. Changing it to `chobject = new Object; chobject["p_" + userID] = 0;` and then passing `chobject` as a function parameter seems to do the trick!

**Comment by bsansouci** [comment]
@gmork To answer your last concern, what version of nodejs do you have? I have v4.1.1 which supports variables as keys in literals.

**Comment by gmork** [comment]
That did seem to do the trick, thanks! It seemed I was running a very outdated nodejs version (0.12). Any suggestions on the searchForThread.js issue? Maybe better to change this to a feature request instead of a bug then? ;-)

**Comment by Schmavery** [comment]
If you could open a new issue for your problem with searchForThread, that would make it a lot easier for us to keep tech.
If you think we can consider the initial issue solved, we can close this issue and keep all the discussions clean.

**Comment by gmork** [comment]
Sounds perfect, will do. Keep up the good work guys!
