### ISSUE TITLE
getThreadList returns imageSrc=null

### ISSUE THREAD

**Issue by mehcode** [Schmavery/facebook-chat-api#145]
```
ERR! Error in getThreadList TypeError: Cannot read property 'replace' of null
ERR! Error in getThreadList     at formatThread (/srv/node_modules/facebook-chat-api/utils.js:456:39)
ERR! Error in getThreadList     at Array.map (native)
ERR! Error in getThreadList     at /srv/node_modules/facebook-chat-api/src/getThreadList.js:36:55
ERR! Error in getThreadList     at tryCatcher (/srv/node_modules/bluebird/js/main/util.js:26:23)
ERR! Error in getThreadList     at Promise._settlePromiseFromHandler (/srv/node_modules/bluebird/js/main/promise.js:507:31)
ERR! Error in getThreadList     at Promise._settlePromiseAt (/srv/node_modules/bluebird/js/main/promise.js:581:18)
ERR! Error in getThreadList     at Promise._settlePromises (/srv/node_modules/bluebird/js/main/promise.js:697:14)
ERR! Error in getThreadList     at Async._drainQueue (/srv/node_modules/bluebird/js/main/async.js:123:16)
ERR! Error in getThreadList     at Async._drainQueues (/srv/node_modules/bluebird/js/main/async.js:133:10)
ERR! Error in getThreadList     at Immediate.Async.drainQueues [as _onImmediate] (/srv/node_modules/bluebird/js/main/async.js:15:14)
ERR! Error in getThreadList     at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by bsansouci** [comment]
It seems like you have a different version than master. As of right now, master contains a lot of fixes so can you try that and see if you still get this error?
Also could you give us some steps to reproduce this if it still occurs on master?

**Comment by mehcode** [comment]
@bsansouci Yes. I'm currently on the last released version. I'll upgrade to master.

---

```js
    await new Promise((resolve) => {
      this.facebook.getThreadList(0, null, (err, arr) => {
        if (err) {
          this.log.error(err);
          return;
        }

        const threadIDs = _.pluck(_.filter(arr, (thread) => {
          return thread.participants.length === 2;
        }), "threadID");

        // Ask for information on all "users" (who could be friends)
        this.facebook.getUserInfo(threadIDs, (err, obj) => {
          if (err) {
            this.log.error(err);
            return;
          }

          // [...]
          
          resolve();
        });
      });
    });
```

**Comment by Schmavery** [comment]
@bsansouci Given the error, I'd imagine facebook has changed the signature and no longer returns a `snippet_sender` property on the object. https://github.com/Schmavery/facebook-chat-api/blob/master/utils.js#L575

**Comment by bsansouci** [comment]
Just pushed a change that should prevent it from crashing. We can't seem to reproduce this issue on our side.  Can you call `api.setOptions({logLevel:verbose})` and then `api.getThreadList(...)` and copy paste the output here?

**Comment by wklm** [comment]
is it ok, that this method (getThreadList) returns imageSrc=null? In browser I can see them

**Comment by wklm** [comment]
+ getThreadList returns 
"participants":["1553954290","100004344516230"],
"participantIDs":["1553954290","100004344516230"],

so one of them is redundant. Can I fix it in repo?

**Comment by Schmavery** [comment]
@wklm as you can see in the docs, participants has been changed to participantIDs (for consistency) and participants has been maintained for now so as not to break backward compatibility.

**Comment by Schmavery** [comment]
It seems to me that imageSrc will always be null unless a custom image is used for the conversation, in which case it will contain the url to the image.
