### ISSUE TITLE
getThreadHistory returns no thread history

### ISSUE THREAD

**Issue by isn0gud** [Schmavery/facebook-chat-api#148]
`getThreadHistory` does return an empty array instead of the latest messages. Receiving and sending messages works fine. Did I miss something?

```
api.getThreadHistory(userHandle, 0, 5, new Date().getTime(), function (err, data) {
...
});
```

**Comment by mehcode** [comment]
```
api.getThreadHistory(userHandle, 0, 5, null, function (err, data) {
...
});
```

The fourth parameter, timestamp, is "get all messages after <timestamp>".

**Comment by bsansouci** [comment]
Good catch @mehcode. Sorry about the bad docs @isn0gud :/
