### ISSUE TITLE
Can't set headers after they are sent

### ISSUE THREAD

**Issue by maeishoj** [Schmavery/facebook-chat-api#149]
Hey there, 

I have the following:
```js
login({
    email: "xxxxxxxxxxxxxxxx",
    password: "xxxxxxxxxxxxxxxxx"
}, function callback(err, api) {
    if (err) return console.error(err);
    // api.setOptions({listenEvents: true})

    api.listen(function callback(err, message) {
        console.log(message)
        // api.sendMessage(message.body, message.threadID);
        return res.send({
            response: message
        });
    });
});
```
When I get the first message after I logged in, it's all good, but the 2nd incoming message throws :

ERR! ERROR in listen -->  Error: Can't set headers after they are sent.
ERR! ERROR in listen -->    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:350:11)

....

Why is that? what's wrong with what I am doing?

**Comment by bsansouci** [comment]
Could you show the full stack trace? Are you sure you can simply do `res.send({...})` multiple times? I'm guessing you're using express, then you can only reply to a request once.

**Comment by Schmavery** [comment]
@bsansouci this might be the retry code being hit.

**Comment by maeishoj** [comment]
@bsansouci oh, thinking about it, it makes sense! sorry! If I return once, the connection to client is closed, and therefore even if the listener is still running, it cannot re-use that response it already used! :/ what was I thinking.... The api listener should be instead running in it's own processes in the server and use websockets or something to push those notifications to the user when available.. Does it sound reasonable?

**Comment by bsansouci** [comment]
@maeishoj We want to keep this API as unopinionated as possible concerning the way its used. If you need to push messages to a client you're going to have to use web sockets yes. It's pretty trivial to implement using our api:
```js
 api.listen(function callback(err, message) {
        socket.emit('message', message);
    });
```

The api doesn't necessarily need to run on another process, nodejs is designed to handle events and run callbacks...

**Comment by maeishoj** [comment]
:+1: 

Perfect.
