### ISSUE TITLE
Requires `request-promise` but does not depend on it.

### ISSUE THREAD

**Issue by jackwilsdon** [Schmavery/facebook-chat-api#15]
Line 4 of utils.js on version 2.0 still requires request-promise, however it is not included in the package.json. It looks like c54c677 was not included in the 2.0 `npm` release.

**Comment by jackwilsdon** [comment]
So it turns out 67ef22 (version 2.0) was uploaded to npm before c54c677 was pushed to the repository (no longer requiring on request-promise), however it looks like request-promise was never a dependency of facebook-chat-api.

**Comment by Schmavery** [comment]
Good catch, thanks.
