### ISSUE TITLE
Error sending image.

### ISSUE THREAD

**Issue by matgott** [Schmavery/facebook-chat-api#153]
Hi everyone! I used this example code: 

var login = require("facebook-chat-api");

login({email: "matiascaloia@hotmail.com", password: "159875339251214"}, function callback (err, api) {
    if(err) return console.error(err);

    // Note this example uploads an image called image.jpg
    var yourID = 100002198660063;
    var msg = {
      body: "Manda fotito tambien",
      attachment: fs.createReadStream(__dirname + 'images/img1.jpg')
    }
    api.sendMessage(msg, yourID);
});

but, doesn't works:

info Logging in...
info Logged in
info Request to pull 1
info Request to pull 2
info Request to thread_sync
info Done logging in.
ERR! Error in login: ReferenceError: fs is not defined
ERR! Error in login:     at callback (C:\Users\Mati\Desktop\facebook-chat-api-master\ap.js:10:19)
ERR! Error in login:     at C:\Users\Mati\node_modules\facebook-chat-api\index.js:389:14
ERR! Error in login:     at tryCatcher (C:\Users\Mati\node_modules\bluebird\js\main\util.js:26:23)
ERR! Error in login:     at Promise._settlePromiseFromHandler (C:\Users\Mati\node_modules\bluebird\js\main\promise.js:507:31)
ERR! Error in login:     at Promise._settlePromiseAt (C:\Users\Mati\node_modules\bluebird\js\main\promise.js:581:18)
ERR! Error in login:     at Async._drainQueue (C:\Users\Mati\node_modules\bluebird\js\main\async.js:128:12)
ERR! Error in login:     at Async._drainQueues (C:\Users\Mati\node_modules\bluebird\js\main\async.js:133:10)
ERR! Error in login:     at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Mati\node_modules\bluebird\js\main\async.js:15:14)
ERR! Error in login:     at processImmediate [as _immediateCallback] (timers.js:383:17)
ERR! Error in login:  [ReferenceError: fs is not defined]
[ReferenceError: fs is not defined]

**Comment by Schmavery** [comment]
This example uses the built-in nodejs file system module `fs`, which you'll have to import.
```js
var fs = require("fs");
```
We'll consider adding this to the docs.

**Comment by matgott** [comment]
var fs = require("fs"); is in index.js. I thought that with that was enough. Now work. Thanks !

**Comment by Schmavery** [comment]
Generally in when writing in nodejs, you're going to have to require separately in every file that you use a module.  The modules are cached so you don't need to worry about loading them many times.
