### ISSUE TITLE
Long latency times

### ISSUE THREAD

**Issue by txs** [Schmavery/facebook-chat-api#158]
I can't get the listen event working.
If I have message posted. it doesn't show the message

It only track once when people see the message.
the Answer info got is about 1000 - 30000. Is it because it's too slow?

**Comment by Schmavery** [comment]
I'm sorry, it's hard to tell what problem you're having here.  Can you post an example of some code and what you're expecting it to do and what's happening instead?

**Comment by txs** [comment]
I have this problem solved. But the message get speed is pretty slow and will failed after a long time. Is there a solution?

**Comment by Schmavery** [comment]
We've had issues with people having long latency times in the past.  @bsansouci could this potentially be a problem with always using 0-edge-chat.facebook.com?

**Comment by bsansouci** [comment]
Mmmh totally possible. We should look into hitting the server that FB would want us to hit :p

**Comment by txs** [comment]
so use it with 0,1,2,3 :P ?

2016-01-26 2:02 GMT+08:00 Benjamin San Souci <notifications@github.com>:

**Comment by Schmavery** [comment]
I'd generally say that generating random numbers out of nowhere is probably not the way to solve this problem :D

**Comment by Schmavery** [comment]
Though kidding aside, @txs, if you're able to demonstrate better performance hitting a different server, that would be a big motivator for us to look into it.

**Comment by txs** [comment]
IDK  if it will  be better. Maybe it will be a cool experiment

**Comment by bsansouci** [comment]
Thanks for your input. We'll track this issue under #161.
