### ISSUE TITLE
Crashes when receiving a message from M

### ISSUE THREAD

**Issue by benzweig** [Schmavery/facebook-chat-api#159]
happened to notice this when M pinged my while i was testing a bot.

    Unhandled rejection TypeError: Cannot read property 'threadID' of undefined

this might be unfixable due to how facebook handles M, but i thought i'd bring it up as no one had yet.
thanks for the dope project!

**Comment by bsansouci** [comment]
Hey @benzweig, thanks for finding out about this issue! Can you enable verbose logging (with options `{logLevel: 'verbose'}`), try to get M to message you again and paste the logs here?

**Comment by Schmavery** [comment]
Ping.. Is anyone still getting this error?

**Comment by Schmavery** [comment]
I'm going to close this for now... if someone is able to get us more information about what data gets received from bot messages, please reopen :)

**Comment by benzweig** [comment]
yo @Schmavery! i'm a little reluctant to test this out, as after running a simple bot for a day or two i got flagged by facebook and had to click on pictures of cats when sending links. what a nightmare

if i know i won't be using facebook for a while, i'll def pass along more detailed info!

**Comment by Schmavery** [comment]
Alright, thanks for letting us know.  Our bots haven't been flagged but that obviously has a lot to do with what they're doing :stuck_out_tongue:
