### ISSUE TITLE
Stickers are received as empty messages

### ISSUE THREAD

**Issue by jackwilsdon** [Schmavery/facebook-chat-api#16]
When sending a sticker, the following information is received by the bot;

```javascript
{ type: 'message',
  sender_name: 'Jack Wilsdon',
  sender_id: MY_ID,
  participant_names: [ 'Jack' ],
  participant_ids: [ MY_ID ],
  body: '',
  thread_id: MY_ID,
  location: null }
```

Is there a way to detect a sticker and identify which sticker it is?

**Comment by bsansouci** [comment]
We added a `sticker_id` and a `sticker_url` field to the object that you receive in your `listen` callback. Type will be `"sticker"`.
