### ISSUE TITLE
Hit the right server

### ISSUE THREAD

**Issue by Schmavery** [Schmavery/facebook-chat-api#161]
We currently only ever hit 0-edge-chat.facebook.com.
This could be causing a couple of issues, like #156 and #158.

**Comment by mehcode** [comment]
Going to wager a guess that the problems are actually the static usage of `seq` and `partition`:

https://github.com/Schmavery/facebook-chat-api/blob/master/src/listen.js#L24-L25

As those parameters smell to be used for something _important_. `*-edge-chat` is a static CNAME to `star.c10r.facebook.com` which is a DNS-based load / region balancer. The specific `*-edge-chat` you use has no bearing on the IP that is resolved. The client seems to pull one out of a hat (using Math.random) and then use local storage so it doesn't change for at least ~1.6 minutes (I haven't been looking at this long enough to see the at most time).

**Comment by mehcode** [comment]
#156 looks like facebook chat was simply offline or that the local DNS resolution failed. As `getaddrinfo` failed to retrieve address information for the CNAME.

#158 could mean facebook was having issues. I don't see enough testing to justify a problem with the library (and not a blip in facebook's network).

---

Looking through those issues I'm thinking there isn't any real "problem" with just using 0-edge-chat but as the client does cycle through `seq` and `partition` I assume they are needed for something or other.

**Comment by Schmavery** [comment]
Thanks for your investigation @mehcode 
We haven't taken the time to investigate partition (afaik @bsansouci) because it's always been -2 when we've seen it.
Maybe switching to another *-edge-chat when a call fails?  Not sure, but it would be nice to be able to handle #156.  If we can find out how the client figures out the range of numbers to choose from, that would be cool.

**Comment by mehcode** [comment]
>  If we can find out how the client figures out the range of numbers to choose from, that would be cool.

```
Math.floor(Math.random() * MAX_CONNECTIONS) % 7
```

`max_conn` is from the reconnect call which is consistently `6` over here.

That number (from 0 to 6) is then stored in local storage along with a timestamp to make sure you stay on that channel for at least `100 * 1000` milliseconds if you refresh. I didn't leave the inspector open long enough (I did for a couple hours) to see if it switched on its own.

**Comment by Schmavery** [comment]
Sorry, just to clarify, are you getting this code from the client or intuiting it from your observations of the packets?  I don't really see how `Math.floor(Math.random() * MAX_CONNECTIONS) % 7` is different from `Math.floor(Math.random() * 7)` other than maybe a slight difference in distribution.  Then again, there's some pretty weird code in the fb client.

**Comment by mehcode** [comment]
I'm getting the code from the client. It is a bit weird. `Ctrl-Shift-F` in chrome and search for ".allocate" -- you'll find the spot where it asks for the number. I then stepped in there and poked around.

**Comment by Schmavery** [comment]
I don't think this is currently a priority.  If someone feels otherwise, feel free to chime in.
