### ISSUE TITLE
Hitting the error "ERR! ERROR in sendMessage -->    errorSummary: 'Security Check Required'"

### ISSUE THREAD

**Issue by palaa159** [Schmavery/facebook-chat-api#163]
I made a chat bot that receives a POST request and send a message to the specified Facebook ID. After a while, Facebook has blocked it from sending with 

ERR!
 ERROR in sendMessage -->  { __ar: 1,
ERR! ERROR in sendMessage -->    error: 1357007,
ERR! ERROR in sendMessage -->    errorSummary: 'Security Check Required',
ERR! ERROR in sendMessage -->    errorDescription: 'A security check is required to proceed.',
ERR! ERROR in sendMessage -->    payload: 
ERR! ERROR in sendMessage -->     { __dialogID: 'u_c_0',
ERR! ERROR in sendMessage -->       __dialogx: 

I tried logging in with my browser and I can still manually send messages to anyone.

Any clues on 'Security Check Required'?

Thanks Folk!

**Comment by Schmavery** [comment]
Are you spamming messages?

**Comment by Schmavery** [comment]
@bsansouci When we rewrite error handling, this is another candidate for one we could catch and rethrow.

**Comment by palaa159** [comment]
well I did not repeatedly send out messages. It was intended to be a notification channel for users. How can I get away with this problem? I logged in from a browser and there's no security check to proceed; it seems fine on the browser but not with the API.

Please help. Thanks.

**Comment by Schmavery** [comment]
Can you provide a minimal working example of this problem?

**Comment by guosheng-lin** [comment]
I am also troubled with the same error . Especially if you write a URL to msg.body. Is it like a link to other sites will not be able to send been recognized as spam ?

**Comment by darrenhebner** [comment]
I hit the same problem. The app worked fine for about an hour. I did end up sending about 80 messages to one user (a test account I created) before Facebook blocked me. Any idea how to get around this? Thanks again for the awesome API!

`ERR! ERROR in sendMessage -->  { __ar: 1,
ERR! ERROR in sendMessage -->    error: 1357007,
ERR! ERROR in sendMessage -->    errorSummary: 'Security Check Required',
ERR! ERROR in sendMessage -->    errorDescription: 'A security check is required to proceed.',
ERR! ERROR in sendMessage -->    payload:
ERR! ERROR in sendMessage -->     { __dialogID: 'u_6_0',
ERR! ERROR in sendMessage -->       __dialogx:
ERR! ERROR in sendMessage -->        { instances: [Object],
ERR! ERROR in sendMessage -->          markup: [Object],
ERR! ERROR in sendMessage -->          elements: [Object],
ERR! ERROR in sendMessage -->          require: [Object],
ERR! ERROR in sendMessage -->          define: [Object] } }, `

**Comment by Schmavery** [comment]
The only solution I can imagine to this is to try to log out and then log back in.  Does that help?  Getting around spam-blocking mechanisms isn't really the purpose of this API.

**Comment by bsansouci** [comment]
I agree with @Schmavery, getting around spam-blocking mechanisms is a whole other can of tuna that we don't want to open. If it's for testing purposes try having multiple accounts and add a delay between messages. It sucks because it'll take forever but it's better than nothing.

**Comment by Schmavery** [comment]
I'm going to close this for now as it doesn't seem there is much we can do.
