### ISSUE TITLE
Package Breaking, JS Object Error

### ISSUE THREAD

**Issue by mjkaufer** [Schmavery/facebook-chat-api#164]
Error on line 194 of `utils.js`, https://github.com/Schmavery/facebook-chat-api/blob/master/utils.js#L194

I'll fix this

**Comment by mjkaufer** [comment]
Also unrelated, I think message types are not working property, but that's not as bad.

**Comment by mjkaufer** [comment]
Check out https://github.com/Schmavery/facebook-chat-api/pull/165

**Comment by bsansouci** [comment]
I responded on the PR. Our package specifies that you need nodejs ≥ 4.x, which I _think_ is when they started supporting this. Please correct me if I'm wrong.

**Comment by mjkaufer** [comment]
Sorry - I must have missed that

**Comment by mjkaufer** [comment]
Yeah, I was running 0.12.2, which would explain the issue - everything works wonderfully now

**Comment by bsansouci** [comment]
<3
