### ISSUE TITLE
TypeError: api.getUserID is not a function

### ISSUE THREAD

**Issue by Zeinox** [Schmavery/facebook-chat-api#166]
Hello,
I am very new to Java Script and am trying to set up the Kassy bot for a Facebook group chat.  All the default modules work for the most part but I am currently working on a vote kick module and though I have figured out how to hardcode a set time and answer options, I am struggling to obtain the user's id in order to kick them.  I am receiving the error "TypeError: api.getUserID is not a function".

Section of the code with the problem:

```js
exports.print = function(api, event) {
	if (!this.config[event.thread_id]) {
		api.sendMessage('No votes in progress?', event.thread_id);
		return;
	}
	var votes = this.config[event.thread_id].votes;
	var answers = this.config[event.thread_id].answersText;
	var message = '';
	for (var v in votes) {
		message += answers[v] + ' \t→ ' + votes[v] + '\n';
	}
	var ratio = (votes[0]) / (votes[0]+votes[1]);
	//if(ratio >= (2/3))
	{
              <<error starts in this location
        api.getUserID("John Smith", function(err, data) {
        if(err) return callback(err);

        // Send the message to the best match (best by Facebook's criteria)
        var userID = data[0].userID;
    });

		//api.sendMessage('Bye' + '\n', event.thread_id);
		//api.getUserID(this.config[event.thread_id].question);
		//api.removeUserFromGroup(kickee, event.thread_id);
		api.sendMessage(userID, event.thread_id);
	}
	api.sendMessage(ratio + '\n', event.thread_id);
	api.sendMessage(this.config[event.thread_id].question + '\n', event.thread_id);
	api.sendMessage(message, event.thread_id);
};
```

Please forgive me if this is an obvious error, because when I said I was really new to js I meant I just started learning it with this program...today.

Also if this isn't the place to post problems like this can you please direct me to where I can post this?

**Comment by Schmavery** [comment]
Hey @Zeinox .  Congrats on becoming javascript programmer ;)
In Kassy, it looks like they don't actually let you directly use our api.  Your api object will only have the functions defined [here](https://github.com/mrkno/Kassy/blob/575fd77bce55e6910d015b7918f732cf18e1dfc1/doc/ModuleCreation.md#api).  Good luck!
