### ISSUE TITLE
getFriendsList and getOnlineUsers returns the same list.

### ISSUE THREAD

**Issue by tomexsans** [Schmavery/facebook-chat-api#169]
while testing getOnlineUsers and getFriendsList i noticed that the **getOnlineUsers **return the same lists. Could you confirm because my test shows the same list.

**Comment by Schmavery** [comment]
Generally these should return the same users but with different information about them.  `getOnlineUsers` gives information about the current status of the user (you might want to check the `status` field).  The `getFriendsList` function returns general information about the user account.
