### ISSUE TITLE
Control event.body by event.userID -- PLEASE

### ISSUE THREAD

**Issue by andrecordeiro** [Schmavery/facebook-chat-api#174]
Good night folks,

I am creating a chat in which there is a menu and submenu. I need to control which menu option ( event.body ) , each chat user is . For example , the user 1 ( event.userID == 1 ) selects the menu ( event.body == ' A') and choose option 1 ( event.body == ' 1' ) . User 2 ( event.userID == 2 ) selects the menu B ( event.body == ' B' ) and choose option 3 ( event.body == ' 3' ) . I tried to create a global variable , and update as each option entered by each user , however, when a user updates this variable , all the others take this value . I do not know how to control it. If anyone can help me thank you very much . With just a Works User with Two or More System is herself.Thank you. André

**Comment by Schmavery** [comment]
I'm sorry, I'm having trouble understanding what you're trying to do and how our API could help.  I can't imagine a situation where you'd want to mutate `event`...

**Comment by andrecordeiro** [comment]
It would be a menu for a pizzeria. Where the user selects the taste of pizza , how to pay the shipping address and so on. I need to control what each user is doing on the chat.

**Comment by Schmavery** [comment]
Our API focuses on sending and receiving messages.  You will have to program logic on your end to handle any menu operations you want.  If each user has to have data stored separately for them, it doesn't make sense to put this into a global variable.  Instead, you could potentially use a map as I've described above.  Without seeing the implementation, it's hard to say what will fix your problem.

**Comment by andrecordeiro** [comment]
You got to see the picture and the video that I put ? It would be exactly what I need . I tried to implement something As Picture I'm attaching now, but I can NOT . I need to know what the User typed and what SenderId this person. Some object exists in the API that I can create a property to store this information and I can capture in case "message" :?

Sorry, but I did not understand when you said : " Potentially use the map" .

![capturar](https://cloud.githubusercontent.com/assets/7633970/12997419/30abb856-d120-11e5-91be-5f8800c5ae8f.PNG)

**Comment by andrecordeiro** [comment]
Just like you said : "Like a javascript object {userID1: option1, userID2: option2}"
