### ISSUE TITLE
Get Location

### ISSUE THREAD

**Issue by andrecordeiro** [Schmavery/facebook-chat-api#176]
is there any way to capture the location of the person in the chat?

**Comment by Schmavery** [comment]
https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#listen
If the location is available, it will be in the message.  It is not always available.

**Comment by andrecordeiro** [comment]
and Is There Any Another way I can capture a location without using a Location facebook ? For example , Making a Call a service que Some web back to something Location OR do Gender.

**Comment by andrecordeiro** [comment]
when I click to send my location, this string is sent to the server : https://fbexternal-a.akamaihd.net/static_map.php?v=17&size=545x280&zoom=15&markers=-25.367732%2C-49.220971&language=en%27, which contains the latitude and longitude . How do I read this URL in the application and extract the markers ?

**Comment by Schmavery** [comment]
I'm sorry, you'll have to figure this out another way.  Currently we don't know of any other way to get the location using our api.
