### ISSUE TITLE
Time format 

### ISSUE THREAD

**Issue by nellenoff** [Schmavery/facebook-chat-api#179]
Currently working with the getThreadList to return the timestamp of specific threads. Anyone know the format of the time stamp to convert it to MM/DD/YY HH:MM:SS?

**Comment by Schmavery** [comment]
The time stamp should be the unix epoch time measured in milliseconds.  If you do `new Date(timestamp)`, it should give you an object that can be manipulated to give you what you're looking for.

**Comment by nellenoff** [comment]
Thanks a ton, very helpful
