### ISSUE TITLE
Bypass captcha with several accounts

### ISSUE THREAD

**Issue by marilafo** [Schmavery/facebook-chat-api#18]
Hi, I am Nicolas and I already sent you an email about that.
Briefly, I'm working on a bot which send messages to several people. Like your "Marc Zuckerbot" but sometimes captcha is needed (because recipients are not in my friend list), so I want to bypass the captcha.
For do that, I would like to use several Facebook accounts. The bot send messages with the first account and when it is blocked by captcha, it uses the second account, etc.
The problem is that the captcha is set up for all the accounts. Nevertheless cookies are reset during the log in. So I don't understand why captcha is omnipresent on every accounts. After that, I tried to use this accounts (send messages) with my web browser and captcha is not asked.
So I would like understand why there is a "different interpretation" between my bot and my web browser.
Thank you for your help !

**Comment by bsansouci** [comment]
Salut Nicolas, je ne penses que nous pouvons t'aider sans avoir ton code. Nous n'avons jamais testé sous ce use-case la.

**Comment by marilafo** [comment]
Je t'ai envoyé un email contenant mon script.

**Comment by bsansouci** [comment]
Ok je pense qu'il n'y a pas de problèmes avec le code. Par contre tu spam clairement toutes les 60 secondes, donc c'est normal que FB te shutdown. Quand tu login avec ton browser, essaye de spam toutes les 60sec puis tu verras FB va te demander un captcha ;)
Désolé je penses pas que nous pouvons t'aider :/

**Comment by marilafo** [comment]
Oui j'avais bien compris ça. Le problème n'est pas l'apparition du captcha. Mais pourquoi, avec le même compte Facebook, il apparaît avec le script et pas avec le browser ? J'aimerais comprendre pourquoi Facebook interprète de manière différente les 2 clients. Logiquement, si je spamme avec le script, je dois être aussi être bloqué avec le browser (même si j'ai rien fait avec le browser) et vice versa. Je pense que c'est en rapport avec les cookies, et c'est pour ça que je pense que vous m'aidez.

**Comment by bsansouci** [comment]
Ce que je voulais dire c'etait que FB te bloque probablement quand tu spam beaucoup. Est-ce que FB te bloque dès le premier message ou apres quelques messages?
Comme j'ai dit dans le message d'avant, si tu envoie le meme message a une personne regulierement avec le browser, FB va probablement te demander de mettre repondre a un captcha.

**Comment by marilafo** [comment]
FB me bloque au bout d'une dizaine de personnes contactés.
Oui c'est même sûr, j'ai déjà testé.
Mais j'aimerais comprendre comment FB fait pour savoir si les requêtes viennent du script ou du browser ? Les cookies sont sensés être les mêmes et la variable "user-agent" présente dans le header des requêtes est la même aussi...

**Comment by bsansouci** [comment]
Je penses simplement que FB va dynamiquement to bloquer en fonction de ce que tu fais. Si tu envoie trop de message dans une session ils vont commencer a te demander des captcha. Si tu attends un peu, ils vont se calmer. On fait de notre mieux pour emuler ce que le browser fait, si tu trouve une difference nous sommes heureux d'accepter des Pull Request :D

**Comment by bsansouci** [comment]
Je vais fermer ce thread parce que je ne penses pas que nous pouvons t'aider directement.

**Comment by marilafo** [comment]
Justement, ils ont tendance à se calmer quand je spamme par browser, si j'attends quelques heures ou quelques jours. Mais pas via le script, je suis "bloqué à vie" tant que je réponds pas au captcha. C'est pour ça que je me pose la question.
Merci quand même ! Bonne continuation ;)
