### ISSUE TITLE
Error in getThreadList

### ISSUE THREAD

**Issue by swifteg** [Schmavery/facebook-chat-api#181]
It was working perfectly and then all of a sudden it broke down with the following errors.

`ERR! Error in getThreadList TypeError: Cannot read property 'replace' of null
ERR! Error in getThreadList     at formatThread (E:\svoya_igra_js\node_modules\facebook-chat-api\utils.js:575:39)
ERR! Error in getThreadList     at Array.map (native)
ERR! Error in getThreadList     at E:\svoya_igra_js\node_modules\facebook-chat-api\src\getThreadList.js:37:55
ERR! Error in getThreadList     at tryCatcher (E:\svoya_igra_js\node_modules\bluebird\js\main\util.js:26:23)
ERR! Error in getThreadList     at Promise._settlePromiseFromHandler (E:\svoya_igra_js\node_modules\bluebird\js\main\promise.js:507:31)
ERR! Error in getThreadList     at Promise._settlePromiseAt (E:\svoya_igra_js\node_modules\bluebird\js\main\promise.js:581:18)
ERR! Error in getThreadList     at Promise._settlePromises (E:\svoya_igra_js\node_modules\bluebird\js\main\promise.js:697:14)
ERR! Error in getThreadList     at Async._drainQueue (E:\svoya_igra_js\node_modules\bluebird\js\main\async.js:123:16)
ERR! Error in getThreadList     at Async._drainQueues (E:\svoya_igra_js\node_modules\bluebird\js\main\async.js:133:10)
ERR! Error in getThreadList     at Immediate.Async.drainQueues [as _onImmediate] (E:\svoya_igra_js\node_modules\bluebird\js\main\async.js:15:14)
ERR! Error in getThreadList     at processImmediate [as _immediateCallback] (timers.js:383:17)
ERR! Error in getThreadList  [TypeError: Cannot read property 'replace' of null]
[TypeError: Cannot read property 'replace' of null]`

The error is happening here.
`return callback(null, resData.payload.threads.map(utils.formatThread));`

**Comment by swifteg** [comment]
Ok, the problem occurs if you have a thread where someone gets added to the chat and the last message is
`_someone_ added _someone_.`

After adding a new message to the thread, the problem disappeared.

**Comment by jobbogamer** [comment]
I'm having this same issue, but there are no conversations where the last message matches what was mentioned above.

**Comment by swifteg** [comment]
Same happened after someone had left the chat (before there were any new messages).

**Comment by Schmavery** [comment]
I believe this is due to snippetSender being null in this case.
This should be a resolved issue in master, we just need to push a new version to npm.  If you could update to the master branch and verify it solves your issue, that would be great.

**Comment by Schmavery** [comment]
This fix should now be in 1.0.7
