### ISSUE TITLE
ParseAndCheckLogin error when there are more than four people in a conversation

### ISSUE THREAD

**Issue by asdfasdfvful** [Schmavery/facebook-chat-api#182]
Everything was working well until about a week ago. Now, whenever there are more than four people in the conversation, I am getting this error:

`ERR! Error in getUserInfo Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
ERR! Error in getUserInfo     at C:\Users\user1\PA\AB\node_modules\facebook-chat-api\utils.js:505:42
ERR! Error in getUserInfo     at tryCatcher (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\util.js:26:23)
ERR! Error in getUserInfo     at Function.Promise.attempt.Promise.try (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\method.js:31:24)
ERR! Error in getUserInfo     at C:\Users\user1\PA\AB\node_modules\facebook-chat-api\utils.js:490:24
ERR! Error in getUserInfo     at tryCatcher (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\util.js:26:23)
ERR! Error in getUserInfo     at Promise._settlePromiseFromHandler (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\promise.js:507:31)
ERR! Error in getUserInfo     at Promise._settlePromiseAt (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\promise.js:581:18)
ERR! Error in getUserInfo     at Promise._settlePromises (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\promise.js:697:14)
ERR! Error in getUserInfo     at Async._drainQueue (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\async.js:123:16)
ERR! Error in getUserInfo     at Async._drainQueues (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\async.js:133:10)
ERR! Error in getUserInfo     at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\async.js:15:14)
ERR! Error in getUserInfo     at processImmediate [as _immediateCallback] (timers.js:383:17)
ERR! Error in getUserInfo  [Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.]
Unhandled rejection Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
    at C:\Users\user1\PA\AB\node_modules\facebook-chat-api\utils.js:505:42
    at tryCatcher (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\util.js:26:23)
    at Function.Promise.attempt.Promise.try (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\method.js:31:24)
    at C:\Users\user1\PA\AB\node_modules\facebook-chat-api\utils.js:490:24
    at tryCatcher (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)`

The project is in the AB folder. I've tried reinstalling npm and readding the node_modules but it still doesn't seem to be working.

**Comment by bsansouci** [comment]
This seems like the same issue as #178. Making a request to `/chat/user_info` returns an error. Could you do what I said [here](https://github.com/Schmavery/facebook-chat-api/issues/178#issuecomment-186692896) and upload the file as @ErmanSayin did?

**Comment by asdfasdfvful** [comment]
@bsansouci 

Here. Hopefully I did it correctly

`[{"key":"datr","value":"F6TQVlYGB8GlbkgVbAoP661P","domain":"facebook.com","path":"/","hostOnly":false,"creation":"2016-02-26T19:14:29.258Z","lastAccessed":"2016-02-26T19:14:33.533Z"},{"key":"c_user","value":"100011157690930","expires":"2016-05-26T19:14:31.000Z","maxAge":7776000,"domain":"facebook.com","path":"/","secure":true,"hostOnly":false,"creation":"2016-02-26T19:14:29.936Z","lastAccessed":"2016-02-26T19:14:33.533Z"},{"key":"fr","value":"02SBgaOzCy1sn4KcM.AWWfLuXfebLGUOlCRZD7h3f-cNs.BW0KQX.0o.AAA.0.AWWV-GRh","expires":"2016-05-26T19:14:31.000Z","maxAge":7776000,"domain":"facebook.com","path":"/","httpOnly":true,"hostOnly":false,"creation":"2016-02-26T19:14:29.937Z","lastAccessed":"2016-02-26T19:14:33.533Z"},{"key":"xs","value":"37%3AgiXHUj2j-XHiGA%3A2%3A1456514071%3A7879","expires":"2016-05-26T19:14:31.000Z","maxAge":7776000,"domain":"facebook.com","path":"/","secure":true,"httpOnly":true,"hostOnly":false,"creation":"2016-02-26T19:14:29.938Z","lastAccessed":"2016-02-26T19:14:33.533Z"},{"key":"csm","value":"2","expires":"2016-05-26T19:14:31.000Z","maxAge":7776000,"domain":"facebook.com","path":"/","hostOnly":false,"creation":"2016-02-26T19:14:29.939Z","lastAccessed":"2016-02-26T19:14:33.533Z"},{"key":"s","value":"Aa4evP_mbBQi2Isw.BW0KQX","expires":"2016-05-26T19:14:31.000Z","maxAge":7776000,"domain":"facebook.com","path":"/","secure":true,"httpOnly":true,"hostOnly":false,"creation":"2016-02-26T19:14:29.940Z","lastAccessed":"2016-02-26T19:14:33.533Z"},{"key":"pl","value":"n","expires":"2016-05-26T19:14:31.000Z","maxAge":7776000,"domain":"facebook.com","path":"/","secure":true,"httpOnly":true,"hostOnly":false,"creation":"2016-02-26T19:14:29.941Z","lastAccessed":"2016-02-26T19:14:33.533Z"},{"key":"lu","value":"ggwMP1prz1ezwLfIHmsel5Dg","expires":"2018-02-25T19:14:31.000Z","maxAge":63072000,"domain":"facebook.com","path":"/","secure":true,"httpOnly":true,"hostOnly":false,"creation":"2016-02-26T19:14:29.941Z","lastAccessed":"2016-02-26T19:14:33.533Z"},{"key":"p","value":"-2","domain":"facebook.com","path":"/","hostOnly":false,"creation":"2016-02-26T19:14:31.757Z","lastAccessed":"2016-02-26T19:14:33.533Z"},{"key":"presence","value":"EDvF3EtimeF1456514071EuserFA21B11157690930A2EstateFDutF0Et2F_5b_5dElm2FnullEuct2F1456514071759EtrFnullEtwF1691178983EatF1456514071759CEchFDp_5f1B11157690930F0CC","domain":"facebook.com","path":"/","secure":true,"hostOnly":false,"creation":"2016-02-26T19:14:31.761Z","lastAccessed":"2016-02-26T19:14:33.533Z"},{"key":"a11y","value":"%7B%22sr%22%3A0%2C%22sr-ts%22%3A1456514071762%2C%22jk%22%3A0%2C%22jk-ts%22%3A1456514071762%2C%22kb%22%3A0%2C%22kb-ts%22%3A1456514071762%2C%22hcm%22%3A0%2C%22hcm-ts%22%3A1456514071762%7D","domain":"facebook.com","path":"/","secure":true,"hostOnly":false,"creation":"2016-02-26T19:14:31.762Z","lastAccessed":"2016-02-26T19:14:33.533Z"},{"key":"datr","value":"F6TQVlYGB8GlbkgVbAoP661P","domain":"facebook.com","path":"/","hostOnly":false,"creation":"2016-02-26T19:14:29.258Z","lastAccessed":"2016-02-26T19:14:33.533Z"},{"key":"c_user","value":"100011157690930","expires":"2016-05-26T19:14:31.000Z","maxAge":7776000,"domain":"facebook.com","path":"/","secure":true,"hostOnly":false,"creation":"2016-02-26T19:14:29.936Z","lastAccessed":"2016-02-26T19:14:33.533Z"},{"key":"fr","value":"02SBgaOzCy1sn4KcM.AWWfLuXfebLGUOlCRZD7h3f-cNs.BW0KQX.0o.AAA.0.AWWV-GRh","expires":"2016-05-26T19:14:31.000Z","maxAge":7776000,"domain":"facebook.com","path":"/","httpOnly":true,"hostOnly":false,"creation":"2016-02-26T19:14:29.937Z","lastAccessed":"2016-02-26T19:14:33.533Z"},{"key":"xs","value":"37%3AgiXHUj2j-XHiGA%3A2%3A1456514071%3A7879","expires":"2016-05-26T19:14:31.000Z","maxAge":7776000,"domain":"facebook.com","path":"/","secure":true,"httpOnly":true,"hostOnly":false,"creation":"2016-02-26T19:14:29.938Z","lastAccessed":"2016-02-26T19:14:33.533Z"},{"key":"csm","value":"2","expires":"2016-05-26T19:14:31.000Z","maxAge":7776000,"domain":"facebook.com","path":"/","hostOnly":false,"creation":"2016-02-26T19:14:29.939Z","lastAccessed":"2016-02-26T19:14:33.533Z"},{"key":"s","value":"Aa4evP_mbBQi2Isw.BW0KQX","expires":"2016-05-26T19:14:31.000Z","maxAge":7776000,"domain":"facebook.com","path":"/","secure":true,"httpOnly":true,"hostOnly":false,"creation":"2016-02-26T19:14:29.940Z","lastAccessed":"2016-02-26T19:14:33.533Z"},{"key":"pl","value":"n","expires":"2016-05-26T19:14:31.000Z","maxAge":7776000,"domain":"facebook.com","path":"/","secure":true,"httpOnly":true,"hostOnly":false,"creation":"2016-02-26T19:14:29.941Z","lastAccessed":"2016-02-26T19:14:33.533Z"},{"key":"lu","value":"ggwMP1prz1ezwLfIHmsel5Dg","expires":"2018-02-25T19:14:31.000Z","maxAge":63072000,"domain":"facebook.com","path":"/","secure":true,"httpOnly":true,"hostOnly":false,"creation":"2016-02-26T19:14:29.941Z","lastAccessed":"2016-02-26T19:14:33.533Z"},{"key":"p","value":"-2","domain":"facebook.com","path":"/","hostOnly":false,"creation":"2016-02-26T19:14:31.757Z","lastAccessed":"2016-02-26T19:14:33.533Z"},{"key":"presence","value":"EDvF3EtimeF1456514071EuserFA21B11157690930A2EstateFDutF0Et2F_5b_5dElm2FnullEuct2F1456514071759EtrFnullEtwF1691178983EatF1456514071759CEchFDp_5f1B11157690930F0CC","domain":"facebook.com","path":"/","secure":true,"hostOnly":false,"creation":"2016-02-26T19:14:31.761Z","lastAccessed":"2016-02-26T19:14:33.533Z"},{"key":"a11y","value":"%7B%22sr%22%3A0%2C%22sr-ts%22%3A1456514071762%2C%22jk%22%3A0%2C%22jk-ts%22%3A1456514071762%2C%22kb%22%3A0%2C%22kb-ts%22%3A1456514071762%2C%22hcm%22%3A0%2C%22hcm-ts%22%3A1456514071762%7D","domain":"facebook.com","path":"/","secure":true,"hostOnly":false,"creation":"2016-02-26T19:14:31.762Z","lastAccessed":"2016-02-26T19:14:33.533Z"}]`

**Comment by ErmanSayin** [comment]
@asdfasdfvful You're not meant to send your cookies publicly

**Comment by asdfasdfvful** [comment]
I'll remove it for now. But I still have the file if anyone needs to check it. Unfortunately I've just started with javascript and coding in general so I'm not sure what it means.

**Comment by bsansouci** [comment]
Those cookies allow anyone to login as that person ;)
Can you send them by email to `benjamin.sansouci@gmail.com`?

**Comment by Schmavery** [comment]
I'm going to close this as a duplicate and refer you to #178 for updates.
