### ISSUE TITLE
Behaviour of sendMessage

### ISSUE THREAD

**Issue by Schmavery** [Schmavery/facebook-chat-api#184]
There's some discussion that has arisen as to what the behaviour of `sendMessage` should be (see #83, #183).  The function currently works by passing an object with certain properties set on it ('attachment', 'url', 'sticker'...).  This object is then fed through a chain of else-ifs which check these properties in a secret order ('attachment' > 'url' > 'sticker'...).  For reference, [this is roughly the relevant block of code](https://github.com/Schmavery/facebook-chat-api/blob/master/src/sendMessage.js#L105-L148).

I'd like to propose removing the 'else's from this control flow and simply try to handle all types of message at once (this is even supported by the client in some cases, as seen in #83).  Furthermore I want to take the behaviour of `setOptions` and throw an error if the passed-in object has any unsupported properties, or in the case that we cannot support the combination of two properties.  I find this prevents mysterious errors due to silly typos and stops values getting lost for no reason.

**Comment by bsansouci** [comment]
I like the idea of allowing some unknown usecases by default, but I'm scared that we'll have to prevent a lot of edge cases. Also how would we describe the edge cases of `cannot support the combination of two properties` other than a bunch of `if`s?

**Comment by Schmavery** [comment]
I'm mostly hoping that there wouldn't be too many of those cases, I guess.  If the need arose, we could technically write some logic that would allow us to define an array of unsupported combinations or properties...
```js
var input = {body: "Test"};
// Fake unsupported combinations
var unsupported = [
    ['body', 'sticker'],
    ['attachment', 'url']
];

if (unsupported.some(c => c.every(v => input.hasOwnProperty(v)))) 
    throw new Error('Unsupported');
```
