### ISSUE TITLE
Can api listen my own message ?

### ISSUE THREAD

**Issue by HowardLoTW** [Schmavery/facebook-chat-api#185]
Hello, 

When I reply to others, I would like to log my reply message
Is it possible to make this work ? 
Since the api can listen others message, the behaviors are the same, right ?

Thanks.

**Comment by bsansouci** [comment]
Hey! Yes you can, take a loot at `selfListen` inside [setOptions](https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#apisetoptionsoptions). Just do `api.setOptions({selfListen: true})`.

**Comment by HowardLoTW** [comment]
You save my life !!! 
Thanks a lot :+1:

**Comment by HowardLoTW** [comment]
Hi ! Is it possible to listen what time do I read others' messages ?
Thanks.

**Comment by Schmavery** [comment]
Set `listenEvents` to true and check for the `read_receipt` event.

**Comment by HowardLoTW** [comment]
Yes. I have set both of listenEvents and selfListen to true. It's ok to listen other people's read_receipt, but it's not ok when I read other people's message. It could not listen my own read_receipt.

**Comment by bsansouci** [comment]
Why do you need to know when you read your own messages?

**Comment by HowardLoTW** [comment]
Currently I am developing a messaging mobile app based on facebook-chat-api.
This app could give you a push notification which indicates someone's emotion (e.g: happy, angry, sad ... ) when someone sends a message to you. 
The reason that I develop this app is for researching some HCI issues, so I would like to log the users read time and response time to see how this functionality influence users :-)

**Comment by HowardLoTW** [comment]
I think you have some misunderstanding.
I want to know when do I read "other person's" messages.

**Comment by HowardLoTW** [comment]
Hi , I have another question.
Is it possible to login by facebook login api (e.g. user just simpily clicks facebook login button) without giving email and password to access the facebook-chat-api functionality ?

Thanks

**Comment by Schmavery** [comment]
No

**Comment by bsansouci** [comment]
You know when you read other people's messages based on how the user interacts with the UI if I'm understanding correctly. You're in control of how the user sees the message. I don't see why this has to do with this api. 

As @Schmavery said, this is a hard limitation enforced by FB. We can't bypass it.
