### ISSUE TITLE
Bluebird 3

### ISSUE THREAD

**Issue by kristianespina** [Schmavery/facebook-chat-api#186]
Hello,

There is a conflict at the bluebird module..
running `npm install` results to:
`npm WARN unmet dependency requires bluebird@'^2.9.27' but will load`
`npm WARN unmet dependency which is version 3.3.3`

**Comment by bsansouci** [comment]
Do you have another version of bluebird installed globally?

**Comment by kristianespina** [comment]
Thank you for your reply,

Do you mean `npm install bluebird --global`... I don't have, however
I think I've updated my bluebird version when I ran 'npm install --save bluebird' :/

Maybe I should downgrade the bluebird to v^2 because I've been getting errors like this recently XD
`ERR! Error in login: TypeError: Cannot read property 'headers' of undefined
ERR! Error in login:     at C:\Users\Skye\Desktop\hehe\entropy-assistant\node_modules\facebook-chat-api\utils.js:538:22
ERR! Error in login:     at tryCatcher (C:\Users\Skye\Desktop\hehe\entropy-assistant\node_modules\bluebird\js\release\util.js:16:23)
ERR! Error in login:     at Promise._settlePromiseFromHandler (C:\Users\Skye\Desktop\hehe\entropy-assistant\node_modules\bluebird\js\release\promise.js:503:31)`

**Comment by bsansouci** [comment]
Mmmh can you paste your full stack trace? And your code that reproduces this? This doesn't seem linked to bluebird itself.

**Comment by kristianespina** [comment]
I'm sorry the late reply, here is it
http://pastebin.com/zTw9eQpc

**Comment by bsansouci** [comment]
Can you remove your node_modules and just run `npm i`? Also, can you paste the code you're running?

**Comment by kristianespina** [comment]
I think I found where I went wrong XD ahahaha
There's no node_modules folder on my facebook-chat-api...
For some reason I think all of my dependencies went on 1 folder
I have this
`node_modules/facebook-chat-api
node_modules/bluebird`
Instead of this
`node_modules/facebook-chat-api/node-modules/bluebird`

Thank you for your help...
I dont know what I did to result to that hahaa..

**Comment by bsansouci** [comment]
If you're using npm, you shouldn't have to install bluebird separately. You should be able to remove _your_ node_modules and run `npm i facebook-chat-api` and that'll install everything that's required (no need to update anything).
