### ISSUE TITLE
message.threadID null in groups

### ISSUE THREAD

**Issue by trgwii** [Schmavery/facebook-chat-api#187]
Title really says it all, if I receive a message from a group, the threadID-property is null.

Edit: It seems that this only happens if a non-friend of the api user has created the group, and the bot is added to the group later.

Using facebook-chat-api version 1.0.7

**Comment by bsansouci** [comment]
Hey @trgwii, thanks for reporting this! Can you add `console.log(m)` __after__ [this line](https://github.com/Schmavery/facebook-chat-api/blob/e1550e793fb7e5678cacc341504fb445758d82ae/utils.js#L346) and paste here just the result of that when you receive a message from that chat?

**Comment by trgwii** [comment]
Here you go:

`{ message:
   { subject: null,
     body: '.',
     timestamp: 1457097085480,
     mid: 'mid.1457097085471:60eb110a1b05b30d60',
     tid: 'id.826121630799731',
     sender_fbid: 1640610814,
     offline_threading_id: '6111508134193875719',
     sender: '1640610814@facebook.com',
     sender_name: 'Thomas Rory Gummerson',
     tags: 'source:messenger:web,cg-enabled,inbox',
     source: 'source:unknown',
     attachmentIds: null,
     forward: 0,
     replyActionType: 0,
     action_id: '1457097085561000000',
     prev_last_visible_action_id: '1457097083817000000',
     mercury_author_id: 'fbid:1640610814',
     mercury_author_email: '1640610814@facebook.com',
     is_spoof_warning: false,
     mercury_source: 'source:messenger:web',
     mercury_source_tags: [],
     mercury_coordinates: null,
     html_body: '',
     short_source: 1,
     is_unread: true,
     has_attachment: false,
     attachments: [],
     attachment_map: {},
     share_map: null,
     ranges: [],
     threading_id: '<1457097085522:0-e7cff3e742e2d40e@mail.projektitan.com>',
     api_tags: [ 'inbox', 'source:web' ],
     ephemeral_ttl_mode: null,
     timestamp_absolute: 'Today',
     timestamp_datetime: '2:11pm',
     timestamp_relative: '2:11pm',
     timestamp_time_passed: 0,
     group_thread_info:
      { participant_ids: [Object],
        participant_names: [Object],
        participant_total_count: 5,
        name: '3D Printer',
        pic_hash: '' },
     should_buzz: false,
     is_silent: false,
     other_user_fbid: null,
     thread_fbid: '826121630799731' },
  event: 'deliver',
  html: '',
  msg_body: '',
  is_unread: true,
  folder: 'inbox',
  thread_row: '',
  unread_counts:
   { other: 0,
     montage: 0,
     hidden: 0,
     pending: 0,
     spam: 0,
     sent: 0,
     inbox: 1 },
  new_participants: '',
  sequence_id: 301,
  realtime_viewer_fbid: 100008322246360,
  type: 'messaging' }`

**Comment by Schmavery** [comment]
https://github.com/Schmavery/facebook-chat-api/blob/b1c364cc2b3c80a03c8329b1345ae346a82aa148/utils.js#L355

Here is the relevant line, looks like they've changed the format of the `tid` field to start with 'mid' instead of 'id'.  Should be fairly simple to fix, just change the line to the following to remove the dependency on the prefix.  Can you make this change locally and check if it fixes it?  Feel free to submit a PR if it does.
```js
threadID: originalMessage.tid ? originalMessage.tid.split('.')[1] : originalMessage.other_user_fbid,
```

**Comment by Schmavery** [comment]
@trgwii Can you sync to master and try this fix?

**Comment by GAMELASTER** [comment]
Well, i think the thread_info no more send a thread informations, so only way to get participiants is to fetch it when thread_sync or unread_threads is executed. Then maybe in "roger" informations is a users information, but... hmm. When I rewriting this to .NET library (unfinished), I cached all informations (so i not must everytime to execute thread_info for info about people etc..), and similiar a web Messenger works, so I think this is needed for good working.

**Comment by Schmavery** [comment]
I don't understand, this change has nothing to do with participants...

**Comment by avikj** [comment]
I was having a similar problem but I updated my utils.js with this edit 
https://github.com/Schmavery/facebook-chat-api/commit/192e635979fe71ee18dfbf6683beb52b70f3f8ae
and now it works as expected.

**Comment by Schmavery** [comment]
Thanks for confirming @avikj

**Comment by Schmavery** [comment]
Pushed this fix to npm.
