### ISSUE TITLE
Add a new feature: listen when do I read the others' message

### ISSUE THREAD

**Issue by HowardLoTW** [Schmavery/facebook-chat-api#189]
Hello,

 I found that the api can listen when the other people read my message through ```api.listen(callback)``` where event type is ```read_receipt ```, but it could not listen when do I read the other's people.

So, I just do some hacks and add this new feature to the node modules in my own project.
now when I read someone's message, it will also trigger ```api.listen(callback)``` where event type is ```read```.
 
I was wondering that if you are interested checking out this new feature :-) ? 
if yes I will then send you a pull request.

Thanks :-)

**Comment by Schmavery** [comment]
Sure, it will be easier to understand what you mean with a pull request.

**Comment by Schmavery** [comment]
I'm going to close this issue and we can track it using the pull request. Thanks.
