### ISSUE TITLE
app id

### ISSUE THREAD

**Issue by jijoamt** [Schmavery/facebook-chat-api#19]
We can see that an app_id is being used in this function graphAPIReadReq()  in index.js. Can we change it and use our own app id? when i tried to change it, i am getting this error  "Error retrieving access token, continuing..." .  What should i do to change the app id?

**Comment by jackwilsdon** [comment]
It looks like `145634995501895` is the Facebook Graph Api Explorer's app ID. Not sure how or even if you can change it.

**Comment by Schmavery** [comment]
Our access token is a bit of a hack, it might be changed in the future but for now you'll get better results using an actual Facebook graph api package like [this one] (https://github.com/Thuzi/facebook-node-sdk).
