### ISSUE TITLE
Question: How do you get the end points?

### ISSUE THREAD

**Issue by mjmohammet** [Schmavery/facebook-chat-api#191]
Hello all,

Thank you for your efforts in this interesting project.

I would like to ask how do you get the URL endpoints? I tried to track the requests using chrome network inspector and couldn't find the ones mentioned in the your API.

I would like to help but I need a starting point. The code is very clear and organised by the way. 

Thanks.

**Comment by Schmavery** [comment]
Which ones can't you find?

**Comment by mjmohammet** [comment]
1. Accept message requests for non-friends.
2. Extend the functionality of this API to include: Get user's public information

**Comment by Schmavery** [comment]
I'm sorry, I meant which endpoints that we mention in the api?  We don't explicitly support accepting message requests for non-friends right now, though I suppose that is something that should be added at some point.  "Getting public information" we already do to some degree.

**Comment by mjmohammet** [comment]
Well, I mean the followings by end points:
https://www.facebook.com/ajax/mercury/send_messages.php
https://www.facebook.com/ajax/mercury/search_threads.php
https://www.facebook.com/chat/user_info/
..
..
sorry what should they be called?

I'm aware of the functions for getting public information but I mean extending the information to include the location, languages spoken, colleges attended, and etc...

Thanks

**Comment by Schmavery** [comment]
That is what I had understood when you said endpoints, but I don't understand why you can't see them in chrome.  This is what I see when I send a message.

![image](https://cloud.githubusercontent.com/assets/2154522/13547034/8c3419b4-e275-11e5-86dc-f5fd3d997801.png)

This is a chat api, so getting user information is for the most part outside our scope.  As far as I know, almost all that information is visible using the official api.

**Comment by mjmohammet** [comment]
Sorry for the obvious question...

Thanks to your well-organised API I was able to add a function called: acceptMessageRequest and declineMessageRequest.

Is it okay to make a pull request?

Thank you.

**Comment by Schmavery** [comment]
Definitely, please make a pull request and then we can give feedback/merge it :)

**Comment by Schmavery** [comment]
Going to close this and wait for your PR.  Reopen if you need anything else.

**Comment by roymap** [comment]
Can't wait for this pull request!
