### ISSUE TITLE
Invisible status

### ISSUE THREAD

**Issue by radekludacka** [Schmavery/facebook-chat-api#194]
Hello,
I have just a comment to documentation. **api.listen(callback)** event type "presence" returns not only "active", "idle", "offline" states, but also "invisible" state. May I ask you, is there any documentation what e.g. otherstatus or fbappstatus, etc. means or what influence it's "behavior". 
Thanks.

**Comment by Schmavery** [comment]
Sorry, we're basically just exposing to you what facebook exposes to us so we don't really know what those values mean.  If you figure it out, let us know and we'll add it to the docs!
