### ISSUE TITLE
message.senderName null in response from listen

### ISSUE THREAD

**Issue by Schmavery** [Schmavery/facebook-chat-api#197]
Not sure what the cleanest way to fix this is.  We're already doing more requests than I'd like in listen.  The best option may be to deprecate this property.

**Comment by blazeu** [comment]
Reimplement [this](https://github.com/Schmavery/facebook-chat-api/blob/a4ca5a7056c45fe6c4243c53a5bb30fd35c1d1b6/src/listen.js#L182-L198) to use a caching system.

Then we could get the senderName from the stored participant data.

**Comment by Schmavery** [comment]
We considered caching back when we implemented the fix for >5 participants and ended up decided it added a lot of complexity... might be worth revisiting the decision.  My main concern with caching is that it can be tricky to do it right.. and it frequently ends up making the system less transparent/predictable regarding memory and computation costs.  Doesn't mean it's impossible, that's just why we haven't done it that way so far.

**Comment by Schmavery** [comment]
Going to track this using #219

**Comment by Schmavery** [comment]
@blazeu If this is something you feel strongly about, please leave a comment in #219 :smile:
