### ISSUE TITLE
getAppState doesn't include messenger.com cookies

### ISSUE THREAD

**Issue by GAMELASTER** [Schmavery/facebook-chat-api#198]
I just trying the new features, for first time the change of color works (i set a black color), but after this i still get a response 
```
ERR! Error in changeThreadEmoji { error: 'Not logged in.' }
{ error: 'Not logged in.' }
ERR! Error in changeThreadColor { error: 'Not logged in.' }
{ error: 'Not logged in.' }
```
I think its because using a "messenger.com" domain, what got another cookies as facebook.com.
I think we can fully move all request from facebook.com to messenger.com, messenger.com (i think) had all facebook.com scripts + more other scripts, and looks the messenger.com is more updated than facebook.com chat.

**Comment by Schmavery** [comment]
I think we might as well try to support both facebook.com and messenger.com, it should give us the biggest number of features.
The problem you're hitting is likely that we haven't yet handled the page where you allow messenger to login using facebook.  It's possible that some request happens on this page.  Basically this feature is still under development but you're welcome to contribute.

**Comment by Schmavery** [comment]
Wait, is this when using appState to log in?

**Comment by GAMELASTER** [comment]
Yep its an AppState, i fixed this by my pull request (what you closed), where at load I duplicated cookies and changed domain to messenger.com, because getAppState return only facebook.com cookies. Later I pull request with patch of getAppState.

**Comment by Schmavery** [comment]
Ok.  Thanks for submitting a fix, but as I explained in the PR, I don't think this is the right way to fix the problem.  This shouldn't be too hard to fix and we'll try to get to it when possible.

**Comment by Schmavery** [comment]
@GAMELASTER can you confirm the [this change](https://github.com/Schmavery/facebook-chat-api/commit/b32c74e9952f679dcb05e69094bfc79046f5877c) fixes the problem?

**Comment by GAMELASTER** [comment]
@Schmavery appState login dont work still (after relog too, its saves only 2 messenger.com cookies (datr and something), but after relogin with email and pass, saving into appState is all fine
