### ISSUE TITLE
Now getting error on login (was working fine until now)

### ISSUE THREAD

**Issue by Hatish** [Schmavery/facebook-chat-api#20]
Hi,

My app was logging into facebook and getting + sending messages with no problem. Then I started intermittently getting the error below. Now I get it all the time.

info Logging in... 
info Logged in 
info Initial requests... 
info Request to null_state 
info Request to reconnect 
info Request to pull 1 
ERR! TypeError: Cannot read property 'sticky' of undefined 
[TypeError: Cannot read property 'sticky' of undefined] '[facebook login name here]'

Appreciate your time :)

**Comment by bsansouci** [comment]
This fix should do it ;)

**Comment by Hatish** [comment]
Thanks a lot :D

Awesome api, awesome support. :+1:

**Comment by bsansouci** [comment]
We're really happy you're enjoying it! We're super interested in seeing what you're doing with it ;)

**Comment by Hatish** [comment]
We're a South African company using the api within node to talk to our back-end service which communicates with our support app. So instead of people going into a store, they can simply use facebook and other chat channels to chat with store personnel. All in all, its pretty cool :)

**Comment by Schmavery** [comment]
That's awesome!  Let us know if you ever end up wanting any extra features :)
