### ISSUE TITLE
Facebook security check

### ISSUE THREAD

**Issue by mrkrumhausen** [Schmavery/facebook-chat-api#201]
I created a chatbot that receives and sends messages to users using a FB page. The bot is hosted on a server with a different IP than my personal pc. After posting a few messages, Facebook requires me to go through a security check every time I want to post a link, see screenshot
<img width="762" alt="screen shot 2016-03-14 at 18 14 19" src="https://cloud.githubusercontent.com/assets/2011006/13754709/408fc56e-e9d5-11e5-945d-54325706019b.png">

Since the bot can't do that it's not able to send links anymore. Any suggestions?

**Comment by Schmavery** [comment]
This sucks, but obviously the point of this api isn't to circumvent captchas.  
[This](https://www.facebook.com/notes/facebook-security/an-explanation-of-captchas/36280205765/) may be out of date, but it seems to indicate that the problem has more to do with spammy messaging behaviour or untrusted links...  Maybe try to minify the url using tinyurl or something?
There's a chance facebook has found a way to detect us, but I'd say that's unlikely, 'cause they probably don't care enough to try and block us.

**Comment by Schmavery** [comment]
[This link](https://www.facebook.com/notes/facebook-engineering/fighting-spam-with-pure-functions/10151254986618920) may be even more relevant.

**Comment by mrkrumhausen** [comment]
Okay thanks. It's just a bunch of instagram links, so it should be untrusted links.

It must be connected either the IP or how the bot behaves (posts really fast)

**Comment by Schmavery** [comment]
I would definitely suggest not spamming links ;)

**Comment by bsansouci** [comment]
@mrkrumhausen You could try to send less links and throttle the speed of the response. We can't help bypass the spamming policies.

**Comment by mrkrumhausen** [comment]
Our service [Sure](besure.io) is similar to [Assist](assi.st) so we are sending Google, instagram links, etc. for each result. I'll see if I can figure something out. Thanks for the links.
