### ISSUE TITLE
[Request] Update npm package to gain "read" event feature

### ISSUE THREAD

**Issue by HowardLoTW** [Schmavery/facebook-chat-api#203]
Hello, 

Could you please update the npm package ?
Since my project is deployed to the heroku server, I need the npm module to have this new feature.

Thanks.

**Comment by GAMELASTER** [comment]
#200 NPM update maybe will be after testing of change color and emoji. But I think it is ready to update, cookies for messenger.com is right, and I tested this functions alot and no problem

**Comment by Schmavery** [comment]
Am I to understand that [this] (http://stackoverflow.com/questions/17509669/how-to-install-nodejs-package-from-github-directly) doesn't work on heroku?

**Comment by Schmavery** [comment]
npm is updated.

**Comment by HowardLoTW** [comment]
Thanks a ton !
