### ISSUE TITLE
[Help Wanted]When im away from my keyboard bot to run and reply to new messages

### ISSUE THREAD

**Issue by TheRealUnknownDeveloper** [Schmavery/facebook-chat-api#204]
Hey there !

Is there a function that i can activate when im away from my keyboard to reply to all incoming messages with

UnknownDeveloper is inactive please contact him later ! If it's urgent contact him on the phone something like that.

Thanks and sorry for posting this in the wrong section/

**Comment by Schmavery** [comment]
Hey, this might be possible using the new `read` event, but I'm not entirely familiar with its behaviour.  I believe @HowardLoTW is attempting to do something similar.  You would need to keep track of incoming messages and watch to see if you read them from another device within a certain period of time.

I don't think it's possible to do this using status because right now the api appears as online when logged in.

**Comment by GAMELASTER** [comment]
Hi,
Use [WinApi](https://www.npmjs.com/package/winapi) package from NPM in timer, what will check a last Input time. When it is bigger than X seconds, login to facebook and all redirect... When its comeback, it will logout.. And loop!

Good Luck!

**Comment by bsansouci** [comment]
@GAMELASTER this is one way to do it, but you're assuming he's running the bot locally and on windows. @TheRealUnknownDeveloper I can see two ways of properly writing this:
1) we get an event when you go "offline" from FB's perspective, at which point we can pipe you the event so you can just set the options `{listenEvents: true, selfListen: true}` and you activate your automatic reply when you get an offline event, and turn it back on when you get an online event
2) we don't get an event when you're offline, at which point there's two ways: either you just set `{selfListen: true}` and start a timer whenever you send a message (you as a user) and countdown until a reasonable time after which you're probably gone and turn on auto reply. Or you you have a timer when you _receive_ a message, and if you don't reply in 5 min it sends a message on your behalf...

I think solution 2.1 is the better one, though not optimal...

(if you want something for customer service you could hack it by having two bots in the chat, and the other bot will receive the event that _you_ went offline for sure at which point you're basically done)

**Comment by HowardLoTW** [comment]
If `facebook-chat-api` could receive `offline` event, it would be easy to implement this functionality.
I saw that there's a api called `api.getOnlineUsers([callback])` and I was wondering that if it could aslo get yourself's status. If it could, that would solve your problem. Just "activate" your auto reply bot when you detect yourself is offline now. Or you can hack into the repo, checkout the function `listen()` in  `facebook-chat-api/src/listen.js`. There's the code as follows : 
```
if(resData.ms) {
        msgsRecv += resData.ms.length;
        var atLeastOne = false;
        resData.ms.sort(function(a, b) {
          return a.timestamp - b.timestamp;
        }).forEach(function parsePackets(v) {
          switch (v.type) { ......... <==== Here you can log out "v" object check that if it will trigger offline event which this repo hasn't this event type yet. If it catches the user himself "offline" event, you can contribute to this repo, haha
```

**Comment by GAMELASTER** [comment]
@bsansouci, yes. Also I did something similiar, I useda raspberry pi what sending sockets to my pc about last active input etc...

And it's another way. In messenger.com is option to get last active time, so u can use this.

**Comment by TheRealUnknownDeveloper** [comment]
@GAMELASTER Sorry dude im on Mac maybe host it on linux to run all the time but I like @bsansouci ideas which are very nice. @HowardLoTW idea is good too and im not sure who's to choose since they are both good. And for your idea to use WinAPI i found another solution which is called the [AFK](https://www.npmjs.com/package/afk) module. If you other guys have other ideas sure post them here

**Comment by GAMELASTER** [comment]
Im sure it's something for mac too. But as I said upper, you can use from messengers information "Last active X minutes ago". If it isn't implemented yet in library,I Will do that.

**Comment by Schmavery** [comment]
I'm going to close this issue because it's not related to any problem or design of the api, but feel free to continue the discussion.

@GAMELASTER the api appears online when it's logged in... not sure how you're planning to make that work.
