### ISSUE TITLE
removedUserFromGroup fails with (assuming) no permissions

### ISSUE THREAD

**Issue by CaughtEx** [Schmavery/facebook-chat-api#205]
As you can see from the error below, I have had no luck in using api.removeUserFromGroup(userID, threadID). No matter who I try to kick from group conversations, it doesn't seem to kick them at all, instead saying that I don't have access to the page. This could be due to a fault of my own, but I'm using perfectly valid IDs (such as 100007996060303), which are obtained from something like api.getThreadList, or message.author.

`ERR! ERROR in removeUserFromGroup -->  { __ar: 1,
ERR! ERROR in removeUserFromGroup -->    error: 1357031,
ERR! ERROR in removeUserFromGroup -->    errorSummary: 'This content is no longer available',
ERR! ERROR in removeUserFromGroup -->    errorDescription: 'The content you requested cannot be displayed at the moment. It may be temporarily unavailable, the link you clicked on may have expired or you may not have permission to view this page.',
ERR! ERROR in removeUserFromGroup -->    payload: null,
ERR! ERROR in removeUserFromGroup -->    bootloadable: {},
ERR! ERROR in removeUserFromGroup -->    ixData: {},
ERR! ERROR in removeUserFromGroup -->    lid: 'redacted' }`

**Comment by CaughtEx** [comment]
Ok, I've just realised this is my fault. Apologies

_Looks like I caught the exception_

**Comment by Schmavery** [comment]
Awesome.  In the future, here are some things to check (I had already typed them when I saw your response so I figured why not).

Does addUser/sendMessage work using the same threadID?  Can you verify that the user was not, in fact, actually removed from the group even though the call failed?  We've had issues in the past with facebook returning error when the call was successful.
