### ISSUE TITLE
Add getThreadInfo function.

### ISSUE THREAD

**Issue by ghost** [Schmavery/facebook-chat-api#209]
Hello,

After reviewing the docs, I think there's no method to get the participants id directly in a thread...

The only method is to get a message event, and get them from "participantIDs" value.

Can you include them into the thread history function or into a new function like thread infos ?

**Comment by Schmavery** [comment]
Hmm, it appears that you're right.  Too bad we didn't make the getThreadHistory simply a getThreadInfo that contains the history as a field... I think it would be reasonably to create a `getThreadInfo` function to cover this case. @bsansouci thoughts?

**Comment by Schmavery** [comment]
I think v2 should deprecate fields like senderName and everything we lost with the introduction of delta events, and return a very cut-down message object to listen.  Then this getThreadInfo can be called when necessary to get this information.  It's a breaking change, but maybe one that is necessary/practical.

**Comment by Schmavery** [comment]
Please address any followup concerns with this issue in #219
