### ISSUE TITLE
Error Connection Lost

### ISSUE THREAD

**Issue by andrecordeiro** [Schmavery/facebook-chat-api#210]
Because this error occurs ? The application runs for a long time , but always occurs this error. Can you help me please? What should I do to avoid ? Thank you very much.
![error_node](https://cloud.githubusercontent.com/assets/7633970/13906901/add24832-eec0-11e5-9b3d-105b66efef43.png)

**Comment by PaulBGD** [comment]
This is an issue with the mysql project, not this project.

**Comment by Schmavery** [comment]
@PaulBGD is probably right, in any case, without some minimum reproduceable code sample, it will be hard to troubleshoot this issue.

On second thought, what might be happening is that the api is throwing an exception that you're not catching.  Hard to tell.

**Comment by Schmavery** [comment]
Hope you're able to fix your problem!  Please reopen if you can give some evidence that this is a problem with the api :)
