### ISSUE TITLE
AddUserToGroup doesn't seem to be working well

### ISSUE THREAD

**Issue by asdfasdfvful** [Schmavery/facebook-chat-api#213]
here is my code
```js
function userUnTimeout(api, message, id, name) {
  api.addUserToGroup(id, message.threadID, function callback(err) {
    if (name == null) {
      name = '(I forgot the name)'; //since the name isn't working too well now
    }
    if (err) {
      return console.error(err);
    }
    api.sendMessage('Welcome back ' + name, message.threadID);
  });
}
```
and here is the error (from heroku):

`2016-03-21T20:03:38.950975+00:00 app[web.1]: ERR! ERROR in addUserToGroup -->  { __ar: 1,
2016-03-21T20:03:38.951204+00:00 app[web.1]: ERR! ERROR in addUserToGroup -->    errorSummary: 'Unable to add user',
2016-03-21T20:03:38.951289+00:00 app[web.1]: ERR! ERROR in addUserToGroup -->    errorDescription: 'The user could not be added to the conversation. Please try again later.',
2016-03-21T20:03:38.951367+00:00 app[web.1]: ERR! ERROR in addUserToGroup -->    payload: null,
2016-03-21T20:03:38.953608+00:00 app[web.1]:   errorDescription: 'The user could not be added to the conversation. Please try again later.',
2016-03-21T20:03:38.953608+00:00 app[web.1]:   payload: null,
2016-03-21T20:03:38.953609+00:00 app[web.1]:   ixData: {},
2016-03-21T20:03:38.953610+00:00 app[web.1]:   lid: '6264599004516994337' }`

The issue also happens in a local npm start.
As of now, it has worked once, so I'm not entirely sure if this is a facebook error or not. I have tested this in a group with 3 people (including me), where I will remove one and then add them back.

If this issue is specific to me, I'd love to know how I can change that!

Edit 1: I have now tried it in a bigger group of ~ 10 and it has the same issue. I however am able to add a user back manually.

**Comment by Schmavery** [comment]
Does sendMessage work using the same threadID? Using the same userID? This would be to verify that the IDs are actually the IDs of the things you think they are.
Can you verify that the user was not, in fact, actually added to the group even though the call failed? We've had issues in the past with Facebook returning error when the call was successful.

The name issue looks like #197

**Comment by asdfasdfvful** [comment]
threadID works for sure. I've tested userID for one of them before, as it is another bot, and it worked so the id should be good.

The user was not added back, but I'll try again and refresh just to make sure.

**Comment by Schmavery** [comment]
Ok, in the case that my questions don't expose any issues with what you're doing, we would need as much info as possible in order to be able to reproduce this problem.  Maybe the user you're adding isn't friends with the adder and so we're getting some strange Message Request behaviour?  Are you using the api as a page?

**Comment by asdfasdfvful** [comment]
It worked this time, but this might be a specific occurence

![capture](https://cloud.githubusercontent.com/assets/6251823/13934384/4eb4942c-ef88-11e5-9323-1a8c55b1c920.PNG)

The user above, and all the other users I've tested with are not friends with the bot. However, this same bot can successfully remove them, so I'm assume that if it uses the same id it should be able to add them back. The bot is being run from the account, not as a page.

**Comment by asdfasdfvful** [comment]
I just tested it on myself and it worked. Does the user have to be a friend of the bot then?

**Comment by Schmavery** [comment]
Is there any indication of the failed attempts to add on the account of the person who is being added?  These users may be getting a Message Request or something like that.  I'm not sure of the behaviour currently.

**Comment by asdfasdfvful** [comment]
I logged onto the bot account and I see no indications of message requests or anything that looks abnormal in the messages.

**Comment by Schmavery** [comment]
I'm not sure I understand how it could work for one account but not others.  Can you diagnose what makes the working accounts different from the non-working ones?

**Comment by asdfasdfvful** [comment]
Currently, it has worked for me (friend of my bot), in a group of 10 or so. Other users in that group are not friends with the bot and have not been successfully added back. In another group with that bot, another bot (ivonbot), and me, it has worked for ivonbot twice (but it has failed quite a few times before that). There is nothing that distinguishes ivonbot from my friends though, as none of them are friends with my own bot.

**Comment by asdfasdfvful** [comment]
Upon some more testing, it seems as though the bot is able to add a user back if it has already messaged them privately before. The workaround is to notify the user privately. I have only tested this on one occurrence though, and will keep testing later.

**Comment by bsansouci** [comment]
When people aren't friends with the bot, things get finicky and we haven't been very good at testing it. Could you make chat with 3 people: the bot, a user who's friends with the bot and one who isn't. Try to remove and add back each of the other 2 people. If this works for both try with a chat with more than 5 people.
We'll explore on our side.

**Comment by asdfasdfvful** [comment]
I'll check that out. It does seem that if the bot messages the person one on one before removal, it can add the person back. I've tried it about 10 times now and it's worked almost every time (except for 1, but that might have just been coincidental). The facebook callback doesn't always say it's successful though, but it still works.
