### ISSUE TITLE
got error when send message

### ISSUE THREAD

**Issue by nguyenhaian** [Schmavery/facebook-chat-api#214]
Got error 1545012. This might mean that you're not part of the conversation 234864753528224

"error":{"__ar":1,"error":1545012,errorSummary: 'Temporary Failure',errorDescription: 'There was a temporary error, please try again.',"transientError":1,"payload":null,"bootloadable":{},"ixData":{},"lid":"6264934140837742137"}

When I send messages to my friends, it works very well, but I got error when trying to send to others people.

**Comment by Schmavery** [comment]
This is probably related to us not handling message requests properly.. Can you confirm that you can send messages to people who aren't your friends but with whom you have previously had conversations?

**Comment by nguyenhaian** [comment]
I'm not sure. I have tried some cases.
1. send to my friends: always works.
2. send to people who is not my friends: rarely works. If it works, it appeared as chat request, that's ok. (only 3 of 3000 people received my message)
3. I make a conversation by facebook web first, then I send by the sdk, it still not work.

<img width="673" alt="fbchatapierr1" src="https://cloud.githubusercontent.com/assets/7018242/13973734/9c72d8a8-f0d8-11e5-872f-2b234b2ff52f.png">

Actually, my target is all people who commented on my post, then I use your sdk to send to all of them using for loop like this:

`for(var i = 0; i < data.target.length; i++){
    var threadID = data.target[i];

    var conversationData = {
        message_id:savedMessage._id,
        sender: sender.acc,                    
        receiver: threadID,
        hasreceived: false,
        hasread: false,
        hasreplied: false,
        sent_time: Date.now(),
        receive_time: Date.now()
    };

    var conversation = new Conversation(conversationData);
    conversation.save(function(err, savedConv){
        if (err){
            io.emit('createConversationResult',{result:false,acc:savedConv.sender,from:user,error:err});
            return console.error(err);  
        }
        if(!savedConv.receiver || savedConv.receiver.length < 5){
            io.emit('sendMessageResult', {result:false,msgid:savedConv.message_id,target:savedConv.receiver});
            return console.log("target undefined. ");
        }
        
        myapi.sendMessage(data.message, savedConv.receiver, function callback (err, messageInfo) {
            if(err) {
                io.emit('sendMessageResult',{result:false,msgid:savedConv.message_id,target:savedConv.receiver,error:err});
                return console.error(err); 
            }
            savedConv.hasreceived = true;
            savedConv.save();
            io.emit('sendMessageResult',{result:true,msgid:savedConv.message_id,target:savedConv.receiver});
        });
        process.stdout.write('.');
    });
}`

**Comment by Schmavery** [comment]
I'm still not entirely sure what could be causing this, but sending 3000 messages as fast as possible seems like a recipe for a bad time.

**Comment by nguyenhaian** [comment]
Thanks for your quick response. I also send to only one person who did not get my message. But I still got the same error.

**Comment by Schmavery** [comment]
Unfortunately this code sample is also not self-contained enough for me to actually verify that the api is being used correctly / reproduce the problem on my local machine.

**Comment by nguyenhaian** [comment]
This is my all code. I've tried to send to only one person, but still get errors.
Run the server and using below url to send a message.

http://localhost:3010/send/1213368892006696

You should try some others people.
1213368892006696
1130365923660757
10206096872209821
10209237822447947
1268488516499337
1567584700219030

[link](http://pastebin.com/NxkrchJy)

`var express = require('express');
var app = express();
var server = require('http').createServer(app);
var bodyParser = require('body-parser');
var login = require("facebook-chat-api");

/*************************************************************/
// KHAI BAO BIEN
// bien goi fb api
var myapi = null

/*************************************************************/
// SETTING
// goi file trong cung thu muc
app.use(express.static(__dirname));
// parse application/x-www-form-urlencoded
app.use(bodyParser.urlencoded({ extended: true }));
// parse application/json
app.use(bodyParser.json());

/*************************************************************/
/*************************************************************/
// KHAI BAO WEB REDIRECT & SERVICE
// Create simple echo bot
function loginfb(onSuccess, onFailed){
    login({email: "youremail", password: "yourpassword"}, function callback (err, api) {
        if(err) {
            onFailed(err);
            return console.error(err);
        }
        
        api.listen(function callback(err, message) {
            console.log("<--- message: " + JSON.stringify(message));
        });

        console.log("myapi is ready!");
        myapi = api;
        onSuccess();
    });
}

function sendMsg(threadID, msg, onSuccess, onFailed){
    // Send the message to the best match (best by Facebook's criteria)
    myapi.sendMessage(msg, threadID, function callback (err, messageInfo) {
        if(err) {
            return onFailed(err);
        }

        onSuccess();
    });
}

function output(res,jobj) {
    console.log(JSON.stringify(jobj));
    res.json(jobj);
}

app.get('/send/:fbid', function(req, res){
    // res.json(req.params);
    if(myapi == null) {
        loginfb(function onSuccess(){
            // login success
            sendMsg(req.params.fbid, "Hi, buddy!", function onSuccess(){
                // send success
                output(res,{sendResponse:true,msg:"send message done"});
            }, function onFailed(err){
                // send failed
                output(res,{sendResponse:false,err:err});
            });
        }, function onFailed(err){
            // login failed
            output(res,{LoginResponse:false,err:err});
        });
    } else {
        sendMsg(req.params.fbid, "Hi, buddy!", function onSuccess(){
            // send success\
            output(res,{sendResponse:true,msg:"send message done"});
        }, function onFailed(err){
            // send failed
            output(res,{sendResponse:false,err:err});
        });
    }

   
});

/*************************************************************/
// START WEBSERVER
server.listen(3010, function(){
  console.log('listening on *:3010');
});`

what I've got is:

`{
"sendResponse": false,
"err": {
"__ar": 1,
"error": 1545012,
"errorSummary": "Temporary Failure",
"errorDescription": "There was a temporary error, please try again.",
"transientError": 1,
"payload": null,
"bootloadable": {},
"ixData": {},
"lid": "6265119157766587234"
}
}`

**Comment by Schmavery** [comment]
Hey, thanks for posting more details, but I think I was unclear what I meant about self-contained.  Can you check whether a very simple example works to send a message?  For instance, you could try the examples in the docs:

```js
// Create simple echo bot
login({email: "FB_EMAIL", password: "FB_PASSWORD"}, function callback (err, api) {
    if(err) return console.error(err);

    api.sendMessage("Test", THREADID);
});
```

This is likely the best way for us to determine whether there is a real problem with the api.

**Comment by nguyenhaian** [comment]
unfortunately, it still doesn't work.

`var login = require("facebook-chat-api");

login({email: "FB_EMAIL", password: "FB_PASSWORD"}, function callback (err, api) {
    if(err) {
        return console.error(err);
    }
    
    api.listen(function callback(err, message) {
        console.log("<--- message: " + JSON.stringify(message));
    });

    console.log("myapi is ready!");

    api.sendMessage("Hi, buddy!", 1213368892006696, function callback (err, messageInfo) {
        if(err) {
            return console.error(err);
        }
        console.log("send message done.");
    });
});
`

You should try to run it. What I get was:
`WARN Got error 1545012. This might mean that you're not part of the conversation 1213368892006696 
{ __ar: 1,
  error: 1545012,
  errorSummary: 'Temporary Failure',
  errorDescription: 'There was a temporary error, please try again.',
  transientError: 1,
  payload: null,
  bootloadable: {},
  ixData: {},
  lid: '6265139147955183176' }`

**Comment by Schmavery** [comment]
Ok, that's too bad.  If it had worked it would have probably been a simpler fix.
All there really is to do now is open up Chrome (or some browser) devtools, and go to the network tab and select XHR requests, then send a message exactly the same way (to the same person) as you're trying to do with the api.  You should be able to see a number of requests appear, likely the send_messages.php endpoint is the only one you need to worry about but it's impossible to know for sure.  If you can attach the information for this request, we might be able to identify the issue.

**Comment by nguyenhaian** [comment]
Can you tell me what information I need to attack?
I have tried to send a message on Chrome, there is some information of the send_message.php.

1. curl
`curl 'https://www.facebook.com/ajax/mercury/send_messages.php?__pc=EXP1%3ADEFAULT&dpr=2' -H 'origin: https://www.facebook.com' -H 'accept-encoding: gzip, deflate' -H 'x-msgr-region: ASH' -H 'accept-language: en-US,en;q=0.8,vi;q=0.6' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36' -H 'content-type: application/x-www-form-urlencoded' -H 'accept: */*' -H 'referer: https://www.facebook.com/megan.c.muth' -H 'authority: www.facebook.com' -H 'cookie: datr=fu1LVuN9IGqloDoh1W3H_ZkL; _ga=GA1.2.2125841604.1448288601; pl=n; lu=gQsgO_FNmiCTxR7VAw-ZsJPw; a11y=%7B%22sr%22%3A0%2C%22sr-ts%22%3A1447953647470%2C%22jk%22%3A0%2C%22jk-ts%22%3A1447953647470%2C%22kb%22%3A0%2C%22kb-ts%22%3A1458642725262%2C%22hcm%22%3A0%2C%22hcm-ts%22%3A1447953647470%7D; c_user=100000261224556; fr=0aJWg1K78CDexpchU.AWVdJPoJx7WwTjxeMC1uvcyvX-s.BWfgKy.JN.Fbp.0.AWVT_5iG; xs=243%3A6Todn4j6QnqiKg%3A2%3A1454301183%3A14062; csm=2; s=Aa4u7QRYbjJttoUY.BW53SS; p=-2; act=1458719984937%2F8; wd=1334x487; presence=EDvF3EtimeF1458720208EuserFA21B00261224556A2EstateFDt2F_5bDiFA2user_3a1BB07912318A2ErF1C_5dElm2FA2user_3a1BB07912318A2Euct2F1458717287487EtrFnullEtwF2196087245EatF1458720208825G458720208907CEchFDp_5f1B00261224556F32CC' --data 'message_batch[0][action_type]=ma-type%3Auser-generated-message&message_batch[0][thread_id]&message_batch[0][author]=fbid%3A100000261224556&message_batch[0][author_email]&message_batch[0][timestamp]=1458720210347&message_batch[0][timestamp_absolute]=Today&message_batch[0][timestamp_relative]=3%3A03pm&message_batch[0][timestamp_time_passed]=0&message_batch[0][is_unread]=false&message_batch[0][is_forward]=false&message_batch[0][is_filtered_content]=false&message_batch[0][is_filtered_content_bh]=false&message_batch[0][is_filtered_content_account]=false&message_batch[0][is_filtered_content_quasar]=false&message_batch[0][is_filtered_content_invalid_app]=false&message_batch[0][is_spoof_warning]=false&message_batch[0][source]=source%3Achat%3Aweb&message_batch[0][source_tags][0]=source%3Achat&message_batch[0][body]=hi&message_batch[0][has_attachment]=false&message_batch[0][html_body]=false&message_batch[0][specific_to_list][0]=fbid%3A100000007912318&message_batch[0][specific_to_list][1]=fbid%3A100000261224556&message_batch[0][signatureID]=6c355642&message_batch[0][ui_push_phase]=V3&message_batch[0][status]=0&message_batch[0][offline_threading_id]=6118316013139528403&message_batch[0][message_id]=6118316013139528403&message_batch[0][manual_retry_cnt]=0&message_batch[0][other_user_fbid]=100000007912318&client=mercury&__user=100000261224556&__a=1&__dyn=5V5yAW8-aFoAwmgDxyIGzGomyp9EbEyGgyi8zCC-C26m6oKezob4q68K5UcU-2CEf8vkwy3eEjKcDKuEjK5okz8uwTADDBBwDK4VqCzEbe78O49Elxq6U&__req=1m&fb_dtsg=AQGfhpsy4AHt%3AAQFLGTyhH-oL&ttstamp=265817110210411211512152657211658658170767184121104724511176&__rev=2243920' --compressed`

2. response
`for (;;);{"__ar":1,"payload":{"actions":[{"client_thread_id":null,"message_id":"mid.1458720210515:0bd1b7aecbcdfab131","client_message_id":"6118316013139528403","status":1,"timestamp":1458720211635,"timestamp_absolute":"Today","timestamp_relative":"3:03pm","timestamp_datetime":"3:03pm","timestamp_time_passed":0,"attachments":[],"thread_id":null,"thread_fbid":null,"other_user_fbid":"100000007912318","action_type":"ma-type:send-message"}],"payload_source":"server_send_message"},"bootloadable":{},"ixData":{},"lid":"6265155601957306455"}`

3. Headers
`General
Request URL:https://www.facebook.com/ajax/mercury/send_messages.php?__pc=EXP1%3ADEFAULT&dpr=2
Request Method:POST
Status Code:200 
Remote Address:31.13.95.36:443
Response Headers
cache-control:private, no-cache, no-store, must-revalidate
content-encoding:gzip
content-security-policy:default-src * data: blob:;script-src *.facebook.com *.fbcdn.net *.facebook.net *.google-analytics.com *.virtualearth.net *.google.com 127.0.0.1:* *.spotilocal.com:* 'unsafe-inline' 'unsafe-eval' fbstatic-a.akamaihd.net fbcdn-static-b-a.akamaihd.net *.atlassolutions.com blob: chrome-extension://lifbcibllhkdhoafpjfnlhfpfgnpldfl;style-src * 'unsafe-inline' data:;connect-src *.facebook.com *.fbcdn.net *.facebook.net *.spotilocal.com:* *.akamaihd.net wss://*.facebook.com:* https://fb.scanandcleanlocal.com:* *.atlassolutions.com attachment.fbsbx.com ws://localhost:* blob: 127.0.0.1:*;
content-type:application/x-javascript; charset=utf-8
date:Wed, 23 Mar 2016 08:03:31 GMT
expires:Sat, 01 Jan 2000 00:00:00 GMT
p3p:CP="Facebook does not have a P3P policy. Learn why here: http://fb.me/p3p"
pragma:no-cache
public-key-pins-report-only:max-age=500; pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="; pin-sha256="r/mIkG3eEpVdm+u/ko/cwxzOMo1bk4TyHIlByibiA5E="; pin-sha256="q4PO2G2cbkZhZ82+JgmRUyGMoAeozA+BSXVXQWB8XWQ="; report-uri="http://reports.fb.com/hpkp/"
set-cookie:wd=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=-1458720209; path=/; domain=.facebook.com; httponly
status:200
strict-transport-security:max-age=15552000; preload
vary:Accept-Encoding
x-content-type-options:nosniff
x-fb-debug:wggWQtglyI09QWtBYPNiutWiVO1ErldWZCXncPwYST3RydE10mgq0m1xAgmW/YZakpgZGxQK/bp/VwSgLbKG0w==
x-frame-options:DENY
x-xss-protection:0
Request Headers
:authority:www.facebook.com
:method:POST
:path:/ajax/mercury/send_messages.php?__pc=EXP1%3ADEFAULT&dpr=2
:scheme:https
accept:*/*
accept-encoding:gzip, deflate
accept-language:en-US,en;q=0.8,vi;q=0.6
content-length:1607
content-type:application/x-www-form-urlencoded
cookie:datr=fu1LVuN9IGqloDoh1W3H_ZkL; _ga=GA1.2.2125841604.1448288601; pl=n; lu=gQsgO_FNmiCTxR7VAw-ZsJPw; a11y=%7B%22sr%22%3A0%2C%22sr-ts%22%3A1447953647470%2C%22jk%22%3A0%2C%22jk-ts%22%3A1447953647470%2C%22kb%22%3A0%2C%22kb-ts%22%3A1458642725262%2C%22hcm%22%3A0%2C%22hcm-ts%22%3A1447953647470%7D; c_user=100000261224556; fr=0aJWg1K78CDexpchU.AWVdJPoJx7WwTjxeMC1uvcyvX-s.BWfgKy.JN.Fbp.0.AWVT_5iG; xs=243%3A6Todn4j6QnqiKg%3A2%3A1454301183%3A14062; csm=2; s=Aa4u7QRYbjJttoUY.BW53SS; p=-2; act=1458719984937%2F8; wd=1334x487; presence=EDvF3EtimeF1458720208EuserFA21B00261224556A2EstateFDt2F_5bDiFA2user_3a1BB07912318A2ErF1C_5dElm2FA2user_3a1BB07912318A2Euct2F1458717287487EtrFnullEtwF2196087245EatF1458720208825G458720208907CEchFDp_5f1B00261224556F32CC
origin:https://www.facebook.com
referer:https://www.facebook.com/megan.c.muth
user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36
x-msgr-region:ASH
Query String Parameters
view source
view URL encoded
__pc:EXP1:DEFAULT
dpr:2
Form Data
view source
view URL encoded
message_batch[0][action_type]:ma-type:user-generated-message
message_batch[0][thread_id]:
message_batch[0][author]:fbid:100000261224556
message_batch[0][author_email]:
message_batch[0][timestamp]:1458720210347
message_batch[0][timestamp_absolute]:Today
message_batch[0][timestamp_relative]:3:03pm
message_batch[0][timestamp_time_passed]:0
message_batch[0][is_unread]:false
message_batch[0][is_forward]:false
message_batch[0][is_filtered_content]:false
message_batch[0][is_filtered_content_bh]:false
message_batch[0][is_filtered_content_account]:false
message_batch[0][is_filtered_content_quasar]:false
message_batch[0][is_filtered_content_invalid_app]:false
message_batch[0][is_spoof_warning]:false
message_batch[0][source]:source:chat:web
message_batch[0][source_tags][0]:source:chat
message_batch[0][body]:hi
message_batch[0][has_attachment]:false
message_batch[0][html_body]:false
message_batch[0][specific_to_list][0]:fbid:100000007912318
message_batch[0][specific_to_list][1]:fbid:100000261224556
message_batch[0][signatureID]:6c355642
message_batch[0][ui_push_phase]:V3
message_batch[0][status]:0
message_batch[0][offline_threading_id]:6118316013139528403
message_batch[0][message_id]:6118316013139528403
message_batch[0][manual_retry_cnt]:0
message_batch[0][other_user_fbid]:100000007912318
client:mercury
__user:100000261224556
__a:1
__dyn:5V5yAW8-aFoAwmgDxyIGzGomyp9EbEyGgyi8zCC-C26m6oKezob4q68K5UcU-2CEf8vkwy3eEjKcDKuEjK5okz8uwTADDBBwDK4VqCzEbe78O49Elxq6U
__req:1m
fb_dtsg:AQGfhpsy4AHt:AQFLGTyhH-oL
ttstamp:265817110210411211512152657211658658170767184121104724511176
__rev:2243920`

Hope you can find something.

**Comment by Schmavery** [comment]
I just had a chance to look this over, and unfortunately that request looks like that's exactly what the api is currently sending.

I guess it could be a cookie issue... maybe @bsansouci can take a look because I can never remember which cookies we support.  This request seems to use the following ones:
`datr, _ga, pl, lu, a11y, c_user, fr, xs, csm, s, p, act, wd, presence`

**Comment by GAMELASTER** [comment]
- xs (ol)
- c_user (ol)
- csm (ol)
- m_user (ol)
- presence (ol)
- p (ol)
- s (ol)
this is needed.

**Comment by Schmavery** [comment]
How have you determined that these are the "necessary cookies"?  I don't even see some of these (like m_user) in my browser.

**Comment by nguyenhaian** [comment]
I'm waiting for the answer. Please help me.

**Comment by Schmavery** [comment]
First off, @nguyenhaian, feel free to submit a pull request with a fix as soon as you find one.
My current guess is that facebook has [detected that you are spam](https://www.facebook.com/help/336759363070078/) and you are being filtered out of most peoples' message requests 

![image](https://cloud.githubusercontent.com/assets/2154522/14037253/c0e1b7e6-f1fe-11e5-9998-3f623db13337.png)

**Comment by GAMELASTER** [comment]
@Schmavery I just tried to delete some cookies and checked if im still logged in, and that m_user is mistake (when I was testing it, I did really bad list)

**Comment by Schmavery** [comment]
@nguyenhaian have you tried creating a new account and sending a message to only one or two people?  If this works, your account has probably been flagged or something.

**Comment by Schmavery** [comment]
I'm going to close this for now since it seems like no one has been able to get a repro.  Please try the suggestions above if you're still having problems.  You could also try updating to the latest version of the api and seeing if that helps.

**Comment by nguyenhaian** [comment]
ok, thank you, Schmavery.

**Comment by PixelHir** [comment]
sorry for a necro but
Started receiving it recently,
`2019-07-17T13:26:35.976381+00:00 app[worker.1]: WARN sendMessage Got error 1545012. This might mean that you're not part of the conversation 2295833323827304`
Seems random, I think it might mean that the user is being ratelimited, since it started happening after my bot got more popular
