### ISSUE TITLE
multiple instances

### ISSUE THREAD

**Issue by andrecordeiro** [Schmavery/facebook-chat-api#218]
Hello . I did two chatbot , one for each customer. I started both on the same server . But when sending a message to the first chatbot , the second chatbot answers and vice versa . How can I have more than one chatbot running on the same server?
Best regards.

**Comment by bsansouci** [comment]
Hey @andrecordeiro, what is your current use case? If you want to answer multiple customers at the same time you don't need multiple bots, you can create one and do some dispatching depending on the `threadID` of the message.

If you need multiple bots, it should still work independently... Can you give us a tiny piece of code to reproduce this?

@Schmavery Do you think there would be collision between the cookie jars? If all the `require("request")` point to the same module and we somehow end up using the same jar for everyone then that's a bug. Any other ideas why this might be an issue?

**Comment by andrecordeiro** [comment]
Hey @bsansouci both use:
var login = require("facebook-chat-api");
var request = require("request")
var fs = require("fs");
var moment = require('moment');
var mysql = require('mysql');

I have not changed anything in the way of call , followed his examples:

![1](https://cloud.githubusercontent.com/assets/7633970/14022829/5ba6dc82-f1c0-11e5-90e0-727868362455.PNG)
![2](https://cloud.githubusercontent.com/assets/7633970/14022834/62b0b7b4-f1c0-11e5-91e9-c0a05a44c4b0.PNG)

**Comment by Schmavery** [comment]
Are they both logged into the same account?

**Comment by Schmavery** [comment]
@bsansouci I'm pretty sure we pass around cookie jars explicitly, so they're not just persisted by the module...  I think this is more likely to be an issue with not filtering messages, as you suggested.

**Comment by andrecordeiro** [comment]
not , are recorded in different accounts.

**Comment by andrecordeiro** [comment]
I decided as follows: the same chatbot.js I make two calls , one for each account. I do not know if it's the right way I understand it, but at first it worked. the problem is that when I stop the script for all customers. hehe , but no problems .

chatbot.js
login({email: "cliente1@hotmail.com", password: "xxxx"}, {pageID: "page1"}, function callback (err, api){ my code 1 }
login({email: "cliente2@hotmail.com", password: "xxxx"}, {pageID: "page1"}, function callback (err, api) { my code 2}

**Comment by Schmavery** [comment]
Wait, was that a mistake or are they both logged into page1?

**Comment by andrecordeiro** [comment]
each connects a different pageID . sorry

**Comment by andrecordeiro** [comment]
good morning friends. this is the right way for me to use multiple chatbots? the problem is that I can not stop each. if I stop the script, for everything.

**Comment by bsansouci** [comment]
Hey @andrecordeiro we tried to reproduce this and couldn't. When logging in with two different accounts everything worked as expected. Try checking your code once more :/
