### ISSUE TITLE
Two-factor authentication

### ISSUE THREAD

**Issue by Liryna** [Schmavery/facebook-chat-api#22]
Hi,

Is it possible to add Two-factor authentication compatibility ?
Or there is a technical issue to implement it ?

Thank again for this awesome api !

**Comment by Schmavery** [comment]
Hi @Liryna!
Are you talking about login approvals?  As explained [here](https://www.facebook.com/notes/facebook-engineering/introducing-login-approvals/10150172618258920)?

**Comment by Liryna** [comment]
yes!

**Comment by blazeu** [comment]
there's currently no official facebook chat api,.
using access token for chat is impossible AFAIK.

if you want to hide your login information, you can store it in your machine's env var.

**Comment by Liryna** [comment]
>if you want to hide your login information, you can store it in your machine's env var.

http://man7.org/linux/man-pages/man5/proc.5.html
strings /proc/[pid]/environ

So Two-factor authentication feature would give more security to this api.

**Comment by Schmavery** [comment]
@blazeu is right, we currently can't see a way to use an access token for chat.
We're looking into adding 2-factor auth, just trying to figure out the most logical way to add it to the existing api.

**Comment by issmirnov** [comment]
It might be useful to add this info to your README. My first thought when I saw this repo was amazement that it requires storing your actual password rather than using an auth token.

On a side note, great job! Was actually thinking of building one like this myself, started looking around and turns out some awesome people have already done it. Looking forward to taking it for a spin.

**Comment by bsansouci** [comment]
You have a point. This started as a fun hackathon project, so it was always obviously "hacky" to us. We'll update the Readme.

Thanks! We'd love to see what you're gonna build.

**Comment by MarkehMe** [comment]
We keep our passwords safe with a mix of encryptions and storing data on a separate restricted database server. 

PGP is the final encryption we use, heres a nice library: https://github.com/openpgpjs/openpgpjs

We have 3 servers, master, database, worker. 

In short: Master has the public key, encrypts and stores the password in the database, then the worker (no public access) has the private key. 

These also a lot of other encryption methods and odd security things we do - but I'm sure you will think of more creative ways to do it!

**Comment by bsansouci** [comment]
Hey guys, login approvals is pushed on the pre-release branch. Let us know if you have any issues with it.

**Comment by Schmavery** [comment]
@Liryna ^
