### ISSUE TITLE
Does not work with new Facebook account

### ISSUE THREAD

**Issue by avikj** [Schmavery/facebook-chat-api#220]
I have set up the basic echo bot shown in the example code as follows: 
```javascript
var login = require("facebook-chat-api"),
    fs = require('fs');

var loginInfo = JSON.parse(fs.readFileSync("secretData.json"));

// Create simple echo bot
login(loginInfo, function callback (err, api) {
    if(err) return console.error(err);

    api.listen(function callback(err, message) {
    	console.log(message.body);
        api.sendMessage(message.body, message.threadID);
    });
});
```

and my secretData.json file is the following (partially redacted):
```json
{                                           
        "email": "HIDDEN_EMAIL@example.com", 
        "password": "PASSWORD_HIDDEN"          
}                                           
```
This allows me to listen on events to my personal facebook account, and it works fine.
However, when I change the email and password to a dummy account that I was going to use for testing, it logs in fine but does not receive any events when messages are received. The only difference between the two cases is that a different account is being used.

Is there any reason why it would not work for a new account?

**Comment by Schmavery** [comment]
Facebook recently changed the way they receive messages.  Please update to the master branch here on github and see if that helps.

**Comment by avikj** [comment]
I updated to master on github and now it works fine. Thanks for the prompt reply.

**Comment by Schmavery** [comment]
Cool, that's great!  The fix in master right now is fairly temporary, as this change just happened very recently.  As soon as we get a solid plan for the future of the api (#219) we'll make a new release with a fix to npm.
