### ISSUE TITLE
api.sendTypingIndicator's end function is undefined

### ISSUE THREAD

**Issue by ErmanSayin** [Schmavery/facebook-chat-api#222]
When I use `api.sendTypingIndicator`, the `end` function in the callback returns `undefined`.

> api.sendTypingIndicator(message.threadID, function(err, end){
>         // `err` and `end` is `undefined`
> });

Also it should be pointed out in the README that sending a message will also stop the indicator

**Comment by Mavyre** [comment]
Having the same problem here with these vars being undefined.

**Comment by Schmavery** [comment]
@bsansouci https://github.com/Schmavery/facebook-chat-api/blob/master/src/sendTypingIndicator.js#L51 Beeeeeen xD

Can you guys check that the end function is returned?

**Comment by bsansouci** [comment]
*facepalm*
Sorry guys.

**Comment by GAMELASTER** [comment]
End working, just
var end = sendTypingIndicator(function(err)
{
   //dosomething
   end();
});
