### ISSUE TITLE
updatePresence makes participantIDs undefined

### ISSUE THREAD

**Issue by asdfasdfvful** [Schmavery/facebook-chat-api#223]
As the title mentions, if I set updatePresence to true, message.participantIDs (which previously worked), will be undefined. I apologize if I'm missing something.

**Comment by Schmavery** [comment]
@asdfasdfvful please confirm that this still happens with the latest version.  As I just made some substantial changes to listen, I'm going to assume it works now and close this issue, but please reopen if I'm wrong.

**Comment by asdfasdfvful** [comment]
I tried updating yesterday (since I wanted to test nicknames) but I actually got the same error with participantIDs. I didn't really understand the update though so I didn't change any of my code.

**Comment by Schmavery** [comment]
I just pushed code that could affect this minutes ago.

**Comment by asdfasdfvful** [comment]
Okay. I'll try again

**Comment by asdfasdfvful** [comment]
I cloned the git, then copied it to the facebook module subfolder, then did npm update

Here is the error:

`ERR! ERROR in listen -->  TypeError: Cannot read property 'length' of undefined
ERR! ERROR in listen -->      at callback (C:\Users\user1\PA\AB\allanbot.js:149:31)
ERR! ERROR in listen -->      at parsePackets (C:\Users\user1\PA\AB\node_modules\facebook-chat-api\src\listen.js:161:22)
ERR! ERROR in listen -->      at Array.forEach (native)
ERR! ERROR in listen -->      at C:\Users\user1\PA\AB\node_modules\facebook-chat-api\src\listen.js:108:12
ERR! ERROR in listen -->      at tryCatcher (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\util.js:26:23)
ERR! ERROR in listen -->      at Promise._settlePromiseFromHandler (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\promise.js:507:31)
ERR! ERROR in listen -->      at Promise._settlePromiseAt (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\promise.js:581:18)
ERR! ERROR in listen -->      at Promise._settlePromises (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\promise.js:697:14)
ERR! ERROR in listen -->      at Async._drainQueue (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\async.js:123:16)
ERR! ERROR in listen -->      at Async._drainQueues (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\async.js:133:10)
ERR! ERROR in listen -->      at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\async.js:15:14)
ERR! ERROR in listen -->      at processImmediate [as _immediateCallback] (timers.js:383:17)
ERR! ERROR in listen -->   [TypeError: Cannot read property 'length' of undefined]
Unhandled rejection TypeError: Cannot read property 'body' of undefined
    at callback (C:\Users\user1\PA\AB\allanbot.js:133:16)
    at C:\Users\user1\PA\AB\node_modules\facebook-chat-api\src\listen.js:213:9
    at tryCatcher (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\user1\PA\AB\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)`

Line 149 of my code:     
if (message.participantIDs.length > 2) {

**Comment by Schmavery** [comment]
wait... are you checking the type of the event before this?  A `presence` event won't have a participantIDs field, as shown in the docs.

**Comment by asdfasdfvful** [comment]
I currently have it tested without updatePresence

api.setOptions({
    forceLogin: true,
    selfListen: true
    // updatePresence: true
  });

**Comment by Schmavery** [comment]
Haha wow I'm sorry it's been a long day and I just realized I've been blanking.
We actually just removed participantIDs from the signature of the message object.  Please see #219 for details.  You can call `getThreadInfo` if you really want this information.
You also made me just realize that I should add a field that says if this message came from a group chat or not.  Thanks for the input!

**Comment by asdfasdfvful** [comment]
Ah thanks. You might want to remove the participant id section from the read me under messages as well. Thanks so much for all of your work!

**Comment by Schmavery** [comment]
Noted!
