### ISSUE TITLE
Sending messages to self received twice

### ISSUE THREAD

**Issue by avikj** [Schmavery/facebook-chat-api#227]
Facebook allows you to send messages to yourself. When I listen on these messages after setting selfListen to true, the api.listen callback is called twice. I suspect that this is due to the fact that one of them is for receiving the message and the other is for sending. Any fix for this?

**Comment by Schmavery** [comment]
Which version are you using?  Could this be a problem with the recently added delta events?
If not, I don't think this is something worth fixing...  Either disable selfListen or filter the events yourself, I'd say.

**Comment by GAMELASTER** [comment]
I tested it, again, I got only one receive (I used setOption to set selfListen, disableDelta is on default value)
