### ISSUE TITLE
Getting Error on sendMessage

### ISSUE THREAD

**Issue by abhisuri97** [Schmavery/facebook-chat-api#228]
```
ERR! ERROR in sendMessage -->  { error: 'JSON.parse error. Check the `detail` property on this error.',
ERR! ERROR in sendMessage -->    detail: [SyntaxError: Unexpected end of input],
ERR! ERROR in sendMessage -->    res: '' }
```

**Comment by bsansouci** [comment]
Hey @abhisuri97 can you paste the code you're using to send the message? What version are you using?
Can you also try again but add `api.setOptions({logLevel: "verbose"})` before sending the message.

**Comment by abhisuri97** [comment]
nevermind upgrading to the latest version fixed it!
