### ISSUE TITLE
response error

### ISSUE THREAD

**Issue by jijoamt** [Schmavery/facebook-chat-api#23]
I am using a previous version of the library where all functions reside in index.js itself.
Right now , after the get request from https://0-edge-chat.facebook.com/pull , am getting the following response  always. what can be done to get the actual response, when a chat is being sent to the logged in user. 
'{"t":"refresh","reason":110,"seq":0}'

**Comment by Schmavery** [comment]
Is there a reason why you can't update to a more recent version of the api?  Facebook changes every now and then, breaking our api and forces us to make updates to keep up.

**Comment by bsansouci** [comment]
@jijoamt ping

**Comment by Schmavery** [comment]
Gonna close this, please reopen if necessary :)

**Comment by jijoamt** [comment]
I have updated the library and was able to get messages yesterday. But today am not able to login. it says "Wrong username/password"  . seems headers.location is missing.

**Comment by Schmavery** [comment]
Facebook recently made a change to how they handle cookies on login.  This should be fixed on npm as of e9b0088.  Please update and try again. :)
