### ISSUE TITLE
getThreadHistory

### ISSUE THREAD

**Issue by EvanStoddard23** [Schmavery/facebook-chat-api#230]
When I call `api.getThreadHistory(event.threadID, 0, 1, weekAgo, function callback(error, history)` I'm getting 3 messages prior to start date of a week ago instead of from the start date until now. Given the documentation, I was under the impression it'd return only the first message _after_ the timestamp.

**Comment by Schmavery** [comment]
Probably not much we can do about this... unless someone sees some obvious off-by-one error in our code, this is going to be an error on facebook's side that you're pretty much going to have to handle on your side.  Sorry about that.
