### ISSUE TITLE
Sending logs

### ISSUE THREAD

**Issue by avikj** [Schmavery/facebook-chat-api#231]
Is it possible to send *log messages* using this api? By listening on events, I have found that the following is the format of a log messages for a score in Messenger's new basketball game:
```json
{
    "type": "event",
    "threadID": "1516745715319484",
    "logMessageType": "log:generic-admin-text",
    "logMessageData": {
        "untypedData": {
            "score": "13",
            "game_type": "basketball",
            "new_high_score": ""
        },
        "message_type": "game_score"
    },
    "logMessageBody": "You scored 13 points playing basketball.",
    "author": "100007376595181"
}
```
Is there any way to replicate this except actually create and send the message programmatically?

**Comment by Schmavery** [comment]
So you want to send some arbitrary score?

**Comment by GAMELASTER** [comment]
@avikj well, maybe it is possible, for sample, I know how to simulate to send an Image to looks like a from some application (for sample GIF Keyboard etc.), but about basketball im not sure.

**Comment by bsansouci** [comment]
I'm not sure this is possible because this is a message that the server sends after an event happens. We'd need to figure out how to trigger the event that makes the server send that message. I don't think we should be trying to make an API to play basket ball :p

**Comment by bsansouci** [comment]
If we're misunderstanding, don't hesitate to make a PR :)
