### ISSUE TITLE
Add user to group

### ISSUE THREAD

**Issue by jorgemejia** [Schmavery/facebook-chat-api#235]
I´m getting problems with this method. The console response with There was a temporary error , try again.
Error:
#1545012

transientError:
#1

**Comment by Schmavery** [comment]
My initial guess is that this is a duplicate of #98.  Can you check whether the user was added even though the error occurred?

**Comment by jorgemejia** [comment]
I read about it, is there a way to send message to a user?

**Comment by Schmavery** [comment]
`api.sendMessage()`?  I don't understand...

**Comment by jorgemejia** [comment]
I loged in with the API and I want to send a message to x user is it possible? I used the method sendMessage but the message appears like self message and I want to send message to 'x' person.

**Comment by Schmavery** [comment]
Yes?  Please read the docs and make sure you're sending the message to the correct ID.
