### ISSUE TITLE
"ERR! Error in getUserInfo { error: 'Not logged in.' }" with multiple pageID logins?

### ISSUE THREAD

**Issue by bestkao** [Schmavery/facebook-chat-api#236]
I'm running to an issue here with multiple logins when I'm working with multiple pages that I own. The first page sends a 'Hey!' message successfully, but I'm not getting 'There!' from my other page. It's a rather contrived example here but yeah. Perhaps it might be related to #229?

```
var login = require("facebook-chat-api");

var credentials = {email: "FB_EMAIL", password: "FB_PASSWORD"};
var pageIDs = ["FB_PAGEID1", "FB_PAGEID2"];
var clientID = "FB_ID";

login(credentials, {pageID: pageIDs[0]}, function callback (err, api) {
  if(err) return console.error(err);

  var msg = {body: "Hey!"};
  api.sendMessage(msg, clientID);
});

login(credentials, {pageID: pageIDs[1]}, function callback (err, api) {
  if(err) return console.error(err);

  var msg = {body: "There!"};
  api.sendMessage(msg, clientID);
});
```

```
[nodemon] 1.9.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
info Logging in...
info Logging in...
info Logged in
info Request to reconnect
info Logged in
info Request to reconnect
info Request to pull 1
info Request to pull 1
info Request to pull 2
info Request to pull 2
info Request to thread_sync
info Request to thread_sync
info Done logging in.
ERR! Error in getUserInfo { error: 'Not logged in.' }
info Done logging in.
```

**Comment by Schmavery** [comment]
This is going to be a silly question, but I'm assuming each login works individually?

**Comment by bestkao** [comment]
Yep

**Comment by bestkao** [comment]
Just an update, it seems to work temporarily if I logout & log back in on the same machine via Chrome. It works, but it's a huge headache to develop with if I have to do that with every change. :disappointed:

**Comment by Schmavery** [comment]
Hmm.. it seems to me that if doing anything with Chrome affects the way the api behaves, this is a bug on facebook's end that we won't be able to do anything about.  If you make any more discoveries of better workarounds, let us know and maybe we can see what we can do to include them in the api.

**Comment by bestkao** [comment]
Will do, thanks for taking a look!
