### ISSUE TITLE
getThreadInfo displays some incorrect info

### ISSUE THREAD

**Issue by asdfasdfvful** [Schmavery/facebook-chat-api#242]
I've tested this in a few conversations, and it seems as though it will always return false for isGroup (isGroup is working fine in messages). The threadName also seems to return one of the participants' name rather than the actual title.

**Comment by Schmavery** [comment]
>I've tested this in a few conversations, and it seems as though it will always return false for isGroup (isGroup is working fine in messages)

I don't understand, can you be more explicit?  Are you saying it works in 2-user threads but not group threads?  So it always returns false no matter what?

Are you logged in as a page?  I'm assuming you're synced to master, not npm, right?

**Comment by Schmavery** [comment]
@asdfasdfvful Ok I think you're right about the `name` issue, I made a false assumption there.  I think you'll find that that only happens when a group thread doesn't have a title.  (My mistake is that I didn't realize that group threads will no user-set title will have a null/empty title field).

There isn't an isGroup for getThreadInfo... I guess I could add one, but that would explain why you don't see it xD

**Comment by asdfasdfvful** [comment]
1. All the groups I've tested actually have a set title, but it didn't show.
2. I printed the object using JSON.stringify, and it showed an isGroup variable. 

I only need this to extract the body text, so it's fine as is, but I thought I'd let you know about these too things that I saw in the process.

It might have to do something with the "participantNames" section as well, as currently it only shows the sender name. Attached below is one of the messages returned from the callback.

![capture](https://cloud.githubusercontent.com/assets/6251823/14302701/b97112dc-fb71-11e5-85a7-2ce458f5803c.PNG)

**Comment by Schmavery** [comment]
Very interesting.. I'll have to take another look at the code when I get a chance.

**Comment by Schmavery** [comment]
@asdfasdfvful That message doesn't look like a delta-style message at all.. what version are you synced to?  Can you update to master and try again?
Also, looking through the code, I basically have no idea how you could be getting `isGroup` on the current version.  Very confused.

**Comment by asdfasdfvful** [comment]
I git pulled yesterday and copied it over to the module folder (without the git part), then did npm update. Nicknames is working in this one so I believe it is with the delta-style?

I did the following to get to this section:

`api.getThreadHistory(message.threadID, 1, 11, Date.now(), function callback(err, history) {
        if(err) return console.error(err);
        jLog(history);
      });`

(jLog is console.log(JSON.stringify(history));)

I will update and take another look

**Comment by bsansouci** [comment]
Hey @asdfasdfvful, I've never heard of anyone using code from github that way. The way I've done it in the past is simply having `"facebook-chat-api": "git://github.com/schmavery/facebook-chat-api"` as a dependency inside my `package.json` (as explained [here](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies)).

**Comment by Schmavery** [comment]
Sorry, now I'm even more confused.  You were asking about `getThreadInfo`, but now you're showing me `getThreadHistory`.  You're right that `isGroup` on `getThreadHistory` is probably messed up.  It was added quickly as an afterthought and still needs some work.  I don't believe this is a documented property and master is not meant to be as stable as npm.

If you want to sync to master, please do yourself a favour and [do it properly](https://docs.npmjs.com/files/package.json#github-urls).

**Comment by asdfasdfvful** [comment]
@bsansouci  hm. Does that keep the dependency up to date with every commit?

I did it like this because when I first posted an issue here someone told me to clone and copy the repo over.

@Schmavery  oh... this was my bad. I was referring to getThreadHistory and wrote the wrong thing in the title. Sorry about that.

**Comment by Schmavery** [comment]
Thanks for following through with us and getting us the details we needed to establish whether there was an issue or not.  I'll try to get some of those things fixed soon :)
