### ISSUE TITLE
SendMessage URLs are not working

### ISSUE THREAD

**Issue by asdfasdfvful** [Schmavery/facebook-chat-api#244]
Below is an example of what I did. I tried just about everything else as well (url in the body, url with a body, with an empty body, etc).

I also tested it with an incorrect url (potato), and it seems as though there were no error logs, so something may have changed. This was working prior to the recent updates.

![capture](https://cloud.githubusercontent.com/assets/6251823/14344409/626d4118-fc75-11e5-955f-2eaa7e651b33.PNG)

**Comment by bsansouci** [comment]
Hey @asdfasdfvful, what do you mean by "not working"?

**Comment by asdfasdfvful** [comment]
The message isn't sending. (the first one does, but the second one doesn't)

**Comment by bsansouci** [comment]
Can you add a callback to log the error (like `api.sendMessage(msg, message.threadID, console.log)`) and show what it prints?

**Comment by asdfasdfvful** [comment]
`{ __ar: 1,
  error: 1357007,
  errorSummary: 'Security Check Required',
  errorDescription: 'A security check is required to proceed.',
  payload:`

I have the full log if you need it.

**Comment by Schmavery** [comment]
This is known facebook behaviour #233 #201
Please try modifying your sending habits to fix the problem :smile:

**Comment by asdfasdfvful** [comment]
Hm weird. I haven't exactly spammed links and I can send links myself. Thanks for the quick replies though!

**Comment by Schmavery** [comment]
Yeah, sorry we don't have a better solution for you, but there's not a while lot we can do about security checks right now :/
