### ISSUE TITLE
app.listen broken

### ISSUE THREAD

**Issue by pete10** [Schmavery/facebook-chat-api#245]
I think Facebook have changed something on their end such that the app.listen for messages is broken.

It was working fine for me and now the simple echo script is not replying for me.

Is someone able to confirm whether this is working or not?

var login = require("facebook-chat-api");

// Create simple echo bot
login({email: "FB_EMAIL", password: "FB_PASSWORD"}, function callback (err, api) {
    if(err) return console.error(err);
    api.listen(function callback(err, message) {
        api.sendMessage(message.body, message.threadID);
    });
});

Thanks

Peter

**Comment by Schmavery** [comment]
#243 #217 #219
I'll leave this one open so people don't keep opening issues.

**Comment by pete10** [comment]
Great, issue sorted for me, thanks very much. Il be sure to update my files more frequently. Thanks for the help!

**Comment by Schmavery** [comment]
As I said, in a few days we'll push to npm and this won't be a problem anymore.  We wanted to take a couple days to make sure they didn't introduce any new bugs first. :)
