### ISSUE TITLE
Quick question: sendTypingIndicator not available for pages?

### ISSUE THREAD

**Issue by cristiancarp** [Schmavery/facebook-chat-api#246]
Tried and it didn't worked (it showed the typing indicator from the actual account to the person I was trying). After testing I also noticed that there might not be such an option on Facebook, am I right?

Thanks!

**Comment by Schmavery** [comment]
This is possible.  Are you saying that you don't see a typing indicator in the browser when you type a message from a page?  Maybe we should add a check to sendTypingIndicator to make it fail when you're logged in as a page... Either that or add some note to the docs.

**Comment by cristiancarp** [comment]
Thank you for replying

Nope, not seeing a typing indicator in the browser when typing from a page. I see the typing indicator in on my account chat window instead (from the admin user of the page). The threadID is correct but somehow it recognizes it as message from account, not from page. (maybe I'm doing something wrong?)

**Comment by Schmavery** [comment]
Funny that it has that behaviour in the browser as well.  If that's the case, I think this is a bug with facebook and not us.
Thanks for reporting the issue! :smile:
