### ISSUE TITLE
Profile photo thumbnails

### ISSUE THREAD

**Issue by wklm** [Schmavery/facebook-chat-api#248]
Hey guys, 
is it possible to get a photo thumbnail bigger then 32x32? 

Bests,
Wojtek 

edit: Okay, i just found out that it is possible with graph api, like 'https://graph.facebook.com/' + profile_id + '/picture?width=100'

May I add a field profilePhoto to getUserById and send you a pull request?

**Comment by GAMELASTER** [comment]
Hey,

I tried to do this, actually its a bigger problem. But I try to look at it some time :-)

**Comment by wklm** [comment]
@GAMELASTER could you please take a look at edited part of my post?

**Comment by GAMELASTER** [comment]
@wklm sorry, I wrong understands your question first time, then I get it so I deleted my post.

**Comment by wklm** [comment]
@GAMELASTER 

no problem :) Could you please tell me how does workflow look like? 

1. fork repo
2. add my new branch
3. add new functionality
4. send pull request

Right?

**Comment by GAMELASTER** [comment]
@wlkm
Im little newbie to Git too, but yes, do it as you mention upper :-)

**Comment by Schmavery** [comment]
If this is possible using the graph api, I don't understand why it needs to be supported by this api.

**Comment by wklm** [comment]
@Schmavery yeah you'r actually right :+1:

**Comment by Schmavery** [comment]
#133 or #139? 😛
