### ISSUE TITLE
getThreadHistory start parameter doesn't seem to work as expected

### ISSUE THREAD

**Issue by cvigoe** [Schmavery/facebook-chat-api#249]
I've experimented with different values for the start parameter of getThreadHistory and it doesn't seem to return the messages corresponding to the given start value. For example, given 9 as the value for start, and 10 as the value for end, I expected the api to return the message sent in the thread 9 messages ago and the message sent 10 messages ago, however it returns the most recent sent message, the second most recent sent message and the third most recent sent message. Is this happening to anyone else?

**Comment by GAMELASTER** [comment]
#242 maybe this?

**Comment by Schmavery** [comment]
@GAMELASTER I don't see how #242 is related to ordering...
This is more likely to be related to #239 #238 #230

**Comment by Schmavery** [comment]
If there is some consistent behaviour that can be established here, it's possible that the docs are wrong.  Other than that, we don't have a lot of control over what facebook returns to us.
