### ISSUE TITLE
api.getThreadInfo not defined

### ISSUE THREAD

**Issue by iamropo** [Schmavery/facebook-chat-api#253]
`api.getThreadInfo` is not defined. The corresponding file is not found in the `src` directory.

**Comment by GAMELASTER** [comment]
https://github.com/Schmavery/facebook-chat-api/blob/master/src/getThreadInfo.js
https://github.com/Schmavery/facebook-chat-api/blob/master/index.js#L81
???

**Comment by iamropo** [comment]
Oops, Looks like I was looking at something else.
