### ISSUE TITLE
Message type  'delta' breaking 

### ISSUE THREAD

**Issue by KapteinBabbalas** [Schmavery/facebook-chat-api#256]
The deltaflow msg type is breaking the lisner.js code
I've spend hour to try and fix but my javascript knowledge is not so good.
Does anybody else have this issue?
I'm using this code with edge.js from here [](https://github.com/rikka94/Facebook-Chat-Api-DotNet)

![capture](https://cloud.githubusercontent.com/assets/2060705/14653263/8170e7ec-0678-11e6-877a-5e7ad6fa50db.JPG)

**Comment by Schmavery** [comment]
Hi, it's hard to see what's happening here.  Can we see a small code example so that we can reproduce this problem.

**Comment by KapteinBabbalas** [comment]
I didn't change anything in javascript the source code.But the problem is in listen.js `  case 'delta':
                            if (v.delta.class !== "NewMessage" || ctx.globalOptions.pageID) {
                                return;
                            }
                                              
                           var fmtMsg = utils.formatDeltaMessage(v);                        

                            if (!ctx.globalOptions.selfListen && fmtMsg.senderID === ctx.userID) {
                                return;
                            }

                            return globalCallback(null, fmtMsg);
                            break;`

**Comment by KapteinBabbalas** [comment]
I can PM you the test account's  credentials to logon yourself If you want to.

**Comment by Schmavery** [comment]
Sorry I must not have been clear... we know what our own code looks like, I meant for you to send the code you're using to call into our API.
I just ran our tests and everything passed so unless facebook is rolling out some new change, the problem is as likely as not in your code.

**Comment by KapteinBabbalas** [comment]
It is .NET code .I'm using this : https://github.com/rikka94/Facebook-Chat-Api-DotNet.
The .net code uses Edge.js to call your code.

The code was working and then it stopped firing the onMessageReceived events after I logged into the account from messenger on my phone. Maybe it is on the .NetSide. I will investigate further.

**Comment by GAMELASTER** [comment]
@KapteinBabbalas 
Ah, this is obsolete and not contains a Delta pulls. Some time ago I started to doing port this library to .NET Portable Library, but I dont have alot a time to continue this + its not contains an Delta Listen.

I suggest you use the pure NodeJS instead of that library.

**Comment by Schmavery** [comment]
Why not open an issue on that repo then? :P
It looks like it hasn't been updated in a while.. Maybe it's using an outdated version of our api?
