### ISSUE TITLE
Bot not working anymore, Facebook seems to have changed the event body

### ISSUE THREAD

**Issue by bdcuck** [Schmavery/facebook-chat-api#258]
Like the title says, the bot stopped working and in my console I don't see the event.message type anymore if I console.log it. It seems like Facebook has changed this, at least for me.
Could someone verify if this is the issue?

Edit: it logs event types like "typ" and "read_reciept" but not "message" anymore.

I have also tested it on a much older account that has never been used as a bot, same issue.

**Comment by bsansouci** [comment]
Hey @bdcuck what version of the api are you using? Can you paste your code?

**Comment by bdcuck** [comment]
The facebook-chat-api package.json looks like this:
`{
  "_args": [
    [
      "facebook-chat-api",
      "/home/pi/Documents/Bots"
    ]
  ],
  "_from": "facebook-chat-api@latest",
  "_id": "facebook-chat-api@1.0.8",
  "_inCache": true,
  "_installable": true,
  "_location": "/facebook-chat-api",
  "_nodeVersion": "0.10.25",
  "_npmOperationalInternal": {
    "host": "packages-12-west.internal.npmjs.com",
    "tmp": "tmp/facebook-chat-api-1.0.8.tgz_1458353338536_0.5855234216433018"
  },
  "_npmUser": {
    "email": "avery.schmavery@gmail.com",
    "name": "schmavery"
  },
  "_npmVersion": "2.7.4",
  "_phantomChildren": {},
  "_requested": {
    "name": "facebook-chat-api",
    "raw": "facebook-chat-api",
    "rawSpec": "",
    "scope": null,
    "spec": "latest",
    "type": "tag"
  },
  "_requiredBy": [
    "#USER"
  ],
  "_resolved": "https://registry.npmjs.org/facebook-chat-api/-/facebook-chat-api-1.0.8.tgz",
  "_shasum": "eba76aee057b4651a651fe990751eff18ca65286",
  "_shrinkwrap": null,
  "_spec": "facebook-chat-api",
  "_where": "/home/pi/Documents/Bots",
  "author": {
    "name": "Avery, David, Maude, Benjamin"
  },
  "bugs": {
    "url": "https://github.com/Schmavery/facebook-chat-api/issues"
  },
  "dependencies": {
    "bluebird": "^2.9.27",
    "cheerio": "^0.19.0",
    "npmlog": "^1.2.0",
    "request": "^2.53.0"
  },
  "description": "Facebook chat API that doesn't rely on XMPP.  Will NOT be deprecated April 30th 2015.",
  "devDependencies": {
    "mocha": "^2.2.5"
  },
  "directories": {},
  "dist": {
    "shasum": "eba76aee057b4651a651fe990751eff18ca65286",
    "tarball": "https://registry.npmjs.org/facebook-chat-api/-/facebook-chat-api-1.0.8.tgz"
  },
  "engines": {
    "node": "4.x"
  },
  "gitHead": "a4ca5a7056c45fe6c4243c53a5bb30fd35c1d1b6",
  "homepage": "https://github.com/Schmavery/facebook-chat-api",
  "keywords": [
    "facebook",
    "chat",
    "api"
  ],
  "license": "MIT",
  "main": "server.js",
  "maintainers": [
    {
      "email": "avery.schmavery@gmail.com",
      "name": "schmavery"
    }
  ],
  "name": "facebook-chat-api",
  "optionalDependencies": {},
  "readme": "ERROR: No README data found!",
  "repository": {
    "type": "git",
    "url": "git://github.com/Schmavery/facebook-chat-api.git"
  },
  "scripts": {
    "start": "node server.js",
    "test": "mocha"
  },
  "version": "1.0.8",
  "warnings": [
    {
      "code": "ENOTSUP",
      "pkgid": "facebook-chat-api@1.0.8",
      "required": {
        "node": "4.x"
      }
    },
    {
      "code": "ENOTSUP",
      "pkgid": "facebook-chat-api@1.0.8",
      "required": {
        "node": "4.x"
      }
    }
  ]
}`

Code for my bot is http://pastebin.com/6u2bMbXF
It was working fine yesterday, and I would see all events in console, now I don't see message event and message.body anymore all of a sudden. Must be something Facebook has changed is my guess.

**Comment by Schmavery** [comment]
1.0.8 is out of date.  Please update to 1.1.0.  Note that this has a couple of small breaking changes.

**Comment by bdcuck** [comment]
I see, I recieve the message now again but ParticipantNames are gone. I'll figure out how to deal with that, thanks.

**Comment by bsansouci** [comment]
Yup, FB doesn't send those anymore but you can use `getThreadHistory` to get `participantNames` :)

**Comment by Schmavery** [comment]
Not sure about getThreadHistory, but getThreadInfo will give you the IDs which you can use with getUserInfo to get the names.
