### ISSUE TITLE
[BUG] fromMobile is not correct

### ISSUE THREAD

**Issue by HowardLoTW** [Schmavery/facebook-chat-api#263]
Hello, 

I've found that when I type some text from my iPhone using the Facebook Messenger app,
both `fromMobile` and `from_mobile` field in the `typ` event object are all `false`.

I'm using the npm facebook-chat-api ^1.0.8 version.

Thanks.

**Comment by HowardLoTW** [comment]
I just log the chat event in `listen.js` to observe that whether Facebook has changed or create a new messaging format. And I found that : 

If I type on my computer:
`{"st":1,"from":100000574428847,"to":100000971915598,"from_mobile":false,"realtime_viewer_fbid":100000971915598,"type":"typ"}`

If I type on my phone:
`{"type":"typ","from":100000574428847,"st":1} `

It seems that if I type on my phone, 
the `typ` event object will not contain `from_mobile` field.

**Comment by HowardLoTW** [comment]
Same as the version 1.1.0

**Comment by GAMELASTER** [comment]
Hey,

This is thing at the Facebook side, so we cant do anything with this, but I think the some other parameter got the information about from where the message has been sent, I think the value contains a "messenger" word. I will try to look it so fast I can !

**Comment by bsansouci** [comment]
Are you using the messenger app or the website? This might be for mobile web and not for the native app, which would really suck. 
If this is the case we should remove that field.

**Comment by HowardLoTW** [comment]
@bsansouci I'm using Facebook Messenger native app on iPhone.
