### ISSUE TITLE
error: 1545010

### ISSUE THREAD

**Issue by cvigoe** [Schmavery/facebook-chat-api#265]
Think this might be a facebook issue but wondering if anyone else has come across this error when trying to get any data after successfully logging in:

```
error: 1545010,
errorSummary: 'Messages Unavailable',
errorDescription: 'Sorry, messages are temporarily unavailable. Please try again in a few minutes.',
```
<img width="919" alt="screen shot 2016-04-27 at 3 06 28 am" src="https://cloud.githubusercontent.com/assets/6818920/14848874/ba20ecd4-0c24-11e6-856c-482d8e04ec9d.png">

**Comment by GAMELASTER** [comment]
Last days the whole Messenger have some problems (not sending the messages etc.), so maybe take it some time

**Comment by cvigoe** [comment]
@Schmavery any idea if this is a facebook-chat-api issue or something else? Seems to be effecting only some accounts. I haven't changed any of the application code and this issue only seems to be showing up in the last 2 weeks.

**Comment by Schmavery** [comment]
What version of the api are you using?   Do you see any issues in the browser when using those accounts?

**Comment by cvigoe** [comment]
@Schmavery I'm using the master branch. No issues arise in the browser for those accounts. When someone tries to sign in to my app using the api (which involves logging in and then requesting thread history),  one of the following happens:

1) it successfully logs in and successfully gets the thread history
2) it fails to log in, Facebook locks the account and requires a sign in in the browser to verify the log in attempt
3) it successfully logs in but fails to get the thread history, returning the error message in the screenshot above after the API call to getThreadHistory.

The app is live on https://href.herokuapp.com
The code for the app is on https://github.com/cvigoe/href

**Comment by cvigoe** [comment]
Outcome 2) seems to happen more often on the heroku server compared to when I test it locally, although it still does happen when locally tested, just not as often. This is a separate issue to this issue I'm reporting here though.

Outcome 3) is what I'm asking about here

**Comment by Schmavery** [comment]
Do you ever get both outcomes 1 and 3 on the same account?  If so, I think we can say it's a Facebook problem.
Outcome 2 is a known issue that we have noticed to be worse with heroku as well but there's not much we can do.

**Comment by cvigoe** [comment]
No, I haven't been able to get both outcomes for the same account, it's strange because this is only something that's started to happen in the last 2 weeks

**Comment by cvigoe** [comment]
@Schmavery is this the first time you've heard of this sort of behavior? (getting "error: 1545010 ...")

**Comment by Schmavery** [comment]
I think we may have seen it before but I can't remember under what circumstances.  I'd imagine it's a fairly catch all error that they return whenever anything goes wrong with the request.  This may be as a result of those accounts getting a different version of Facebook (they have some a/b testing and phased roll-out strategy)
If that is the case, this will require additional investigation to determine what the change is on Facebook's end.  Would it be possible for you to send credentials to a test account experiencing the problem along with a very small code sample that produces the problem when you run it to @bsansouci?

**Comment by cvigoe** [comment]
@Schmavery hmm, I would happily do that if I could but all of the test accounts I've made don't encounter this issue, it's only something that other users are encountering when trying to use https://href.herokuapp.com - I have credentials of a specific user that always triggers this issue but I don't think they'd be too pleased if I posted their credentials publicly - if there was some way you guys can troubleshoot the issue whilst not exposing the specific credentials I might be able to help? I imagine what you're saying is probably what's happening

**Comment by Schmavery** [comment]
.. You really shouldn't be storing the credentials of your users, dude. Without the account it's unlikely that we can do anything about this.  The fix would involve logging in using the account in the browser and seeing what requests are made there.  It is *not okay* to do this with someone's account without permission.

**Comment by cvigoe** [comment]
@Schmavery I'm not storing any creds don't worry, wouldn't dream of getting involved with those murky waters. This person is a close friend who has given me their credentials to troubleshoot with - I use my account and her account when testing the project. Is there something I could do to look for to help you guys figure out what's going on?

**Comment by Schmavery** [comment]
It would basically involve logging in in the browser, opening the dev tools and looking for the request to threadlist_info.php and seeing how it is different than the one we are making.

**Comment by Schmavery** [comment]
Feel free to reopen.  Always willing to accept a PR with a fix.

**Comment by sapph1re** [comment]
This error may also appear when requesting too many threads. Try reducing the number of threads in getThreadList.

**Comment by erayaydin** [comment]
Its also happens in facebook's web chat
