### ISSUE TITLE
Cannot receive messages using listen

### ISSUE THREAD

**Issue by axydavid** [Schmavery/facebook-chat-api#267]
Hi!
I can no longer receive messages using listen.
More specifically I can't get the contents of body which is the message content.
I can still get all other information such as threadyID, userID etc.
I can still receive mesages on messenger/facebook but not using the API.
I forgot to mention that I can still send messages as usual using the API.

**Comment by GAMELASTER** [comment]
Maybe because the new delta messaging. This is under progress feature.

Contributions are welcome :-)

**Comment by axydavid** [comment]
canyou be more precise? Delta messaging?

**Comment by GAMELASTER** [comment]
https://github.com/Schmavery/facebook-chat-api/issues/217#issuecomment-200666335

**Comment by axydavid** [comment]
I'll see if I can do stuff aboutit, altough the API is lastest version

**Comment by bsansouci** [comment]
What do you mean you can't get the body? Is it always empty? Ask @GAMELASTER said try turning deltaMessages off by calling `api.setOptions({disableDelta: true})`

**Comment by bsansouci** [comment]
oh wait, my bad, this is no longer a thing. Try synching the repo to this commit 22b47ad93231af96bea37ae5fda12f389e31a65e (by changing your package.json's dependency on facebook-chat-api to be `"git://github.com/schmavery/facebook-chat-api.git#22b47ad93231af96bea37ae5fda12f389e31a65e"`).

**Comment by axydavid** [comment]
@bsansouci I have no idea how to do that, im still fairly new to NPM and NODE, but I'll google it and tell you guys how it went.

**Comment by bsansouci** [comment]
For the network tab on the chrome dev tools: https://developers.google.com/web/tools/chrome-devtools/profile/network-performance/resource-loading
For what HTTP requests are made of: http://learn.onemonth.com/understanding-http-basics
What you'll be doing is basically looking at what the browser does when you comment on something, and then replicating it server-side. Forking our API will be the fastest way because we handle setting all of the right headers and cookies to make FB's servers happy.
Don't hesitate to ask questions here.

**Comment by axydavid** [comment]
I already did that, I got the message content in msg: "blablabla".
However I don't know how to update the code to mirror that, neither do I know hoe to change json depency

**Comment by bsansouci** [comment]
(sorry I deleted my previous comment as it was on the wrong issue :p)

**Comment by axydavid** [comment]
where is the package.json for facebook API located in windows?

**Comment by bsansouci** [comment]
You need to change **your** project's package.json, which would be at the root of your project.

**Comment by axydavid** [comment]
I see, so from Visual studio.

**Comment by axydavid** [comment]
Weird, I did not do anything but it's working again.....

**Comment by bsansouci** [comment]
Nice! Closing.
