### ISSUE TITLE
Various questions / notes

### ISSUE THREAD

**Issue by demurgos** [Schmavery/facebook-chat-api#270]
Hi,
This is not really an issue, but I would like to ask you various questions and leave some notes about the current code. They  are not necessarily related and I may have some more later. I'll post my other minor questions and remarks on this topic.

I am currently reviewing the code in `utils.js`:

- `_formatAttachment`

 - There is a comment `TODO: THIS IS REALLY BAD` but does not explain what is the problem.
 - How do I know which properties are available on the attachments ?
 - Solve the `facebookUrl: attachment1.url, // wtf is this?` comment
 - This function not only formats the attachment but merges two objects, maybe rename this function ? Why are there two objects to be merged ? I've seen that sometime you only have the first one.
 - Why are video attachments not documented ?

- `presenceEncode` and the related functions seems to have been copied from the minimified Facebook's code.
It is quite cryptic and could be more commented. I guess that you reverse engineered it. Maybe add some of your observations ?

- `getFrom` does not seem to handle the case when endToken is not found. Is the current behaviour normal ?

- `makeParsable`: This sounds scary, why are we applying a regex on some HTML ? Also it looks like its used with JSON.parse. What is happening here ?

- `genTimestampRelative`: why is `generate` abbreviated here while it's not in some other functions (ie. `generateThreadingID`) ? It's not that important, but it's just consistency

- `make_defaults`: The way it captures values from the html (with getFrom) feels a bit hacky :/

- `mergeWithDefaults`: There is some unreachable code because of the duplication of `if(!obj)`, no ?

- `saveCookies` should use `forEach` instead of map (it just iterates other the array)

**Comment by Demurgos** [comment]
In `src/getThreadInfo.js`, the `threadData` in the payload exposes `custom_color` instead of `customColor`.
https://github.com/Schmavery/facebook-chat-api/blob/master/src/getThreadInfo.js#L41

**Comment by bsansouci** [comment]
> How do I know which properties are available on the attachments ?
They aren't defined anywhere and we have no way of guaranteeing they'll stay the same...

> presenceEncode
This is indeed copy pasted from the minified JS, we don't really care about what it's doing. Most of utils is copy pasted really...

> makeParsable
Simply removes `for(;;);` from the beginning of the JSON response. This is a common [security technique](http://stackoverflow.com/questions/2669690/why-does-google-prepend-while1-to-their-json-responses).

> makeDefaults
It's been working fine for over a year ;)

> Always with the tests, there is a risk to call done multiple times with the current construct to to test events (if multiple errors are fired).
¯\_(ツ)_/¯
