### ISSUE TITLE
Create new group

### ISSUE THREAD

**Issue by dunnietje** [Schmavery/facebook-chat-api#271]
Hey Avery,
thanks for the awesome work, I have a question for you: how could I create a new group with this library and get the threadID?

Thanks!
Marco

**Comment by bsansouci** [comment]
Hey @dunnietje, thanks for the support. @Schmavery's out of town but should be back soon.
If I remember correctly you should get in the callback of `sendMessage` an object with [those fields](https://github.com/Schmavery/facebook-chat-api/blob/4580d87884e7db90b595806180c4037131f093ba/src/sendMessage.js#L134-L137), one of which is `threadID` :D

**Comment by Schmavery** [comment]
That's right, you should be able to pass an array of user IDs to sendMessage, which will create a new group chat and get back an object containing the thread ID.

**Comment by dunnietje** [comment]
Thanks for the superfast reply @bsansouci and @Schmavery, I'll give it a try. 

I think I should change group name with api.setTitle, isn't it?

**Comment by bsansouci** [comment]
Yes. But there's one thing to keep in mind. If you're messaging people your bot doesn't know, the message will actually be a "message request" which won't appear with the other messages. It's very likely that `api.setTitle` will die too.

**Comment by dunnietje** [comment]
Yes I know, but my need is to create a group called "Something" with only the bot in it. 

As I can see, to create a group you need 3+ users, then I'll have to add another two users and remove them. Or maybe look for a workaround.

Is the `api.setTitle` needed to call it "Something"?

**Comment by dunnietje** [comment]
`api.setTitle` is not the function I'm looking for, I'll continue trying :(

**Comment by dunnietje** [comment]
Ok everything works fine. Thanks guys!

I'll use a workaround with 2 sim cards and messenger profiles to add two temporary users for the group ;)
Let me know if you got more ideas.

**Comment by bsansouci** [comment]
Haha brilliant. I was going to say that you can't name a chat with 2 people, but I guess that works!

**Comment by Schmavery** [comment]
Is it possible to create a single-user group chat in the browser?  If not, I think this is an acceptable workaround for now.

**Comment by dunnietje** [comment]
Nope it's not 😭 

My workaround is:
- Send a message to Fakeuser1 and Fakeuser2 with `api.sendMessage` 
- Delete previous message with `api.deleteMessage`
- Change name of the group/channel to 'Something' with `api.setTitle`
- Remove Fakeuser1 and Fakeuser2 with `api.removeUserFromGroup`

In this way I can use `api.addUserToGroup` to add more users. My approach is with a REST endpoint.

The real problem to use this thing as a product is: this kind of groups miss admin features and everyone is able to rename channel, boot people from the crowd or kick the bot. I could workaround these things with something like a botnet (if you're familiar with IRC eggdrops you know what I mean)

Thanks for your support mate.
