### ISSUE TITLE
Listen.js see who read the message in a group chat?

### ISSUE THREAD

**Issue by axydavid** [Schmavery/facebook-chat-api#272]
Hi, I'm not really sure if this  is an issue but  I was trying to figure out how to check who read a message in a group chat using listen.js however I can't seem to find the functionality anywhere.
Am I really that bad at reading the wiki or it's not implemented?
I do not receive anything of type read/read_receipt.

**Comment by bsansouci** [comment]
hey @axydavid did you set `api.setOptions({listenEvents: true})` ([here](https://github.com/Schmavery/facebook-chat-api/blob/4580d87884e7db90b595806180c4037131f093ba/DOCS.md#setOptions) are all of the options)

**Comment by axydavid** [comment]
Yupp, I can see when someone types. But not if anyone read my message.

**Comment by axydavid** [comment]
many thanks!
