### ISSUE TITLE
Changing emoji seems to no longer work with updates.

### ISSUE THREAD

**Issue by AllanWang** [Schmavery/facebook-chat-api#275]
I'm not sure if there's anything to log, but it was working before and is no longer working once the messenger app updated.

[Code for reference](https://github.com/AllanWang/AllanBot-Public/blob/master/src/chatEmoji.js#L9)

**Comment by GAMELASTER** [comment]
For me works nice still (but I got a Messenger updates later).
What messenger app got in update? (for a verify if I got update)

**Comment by AllanWang** [comment]
My apologies, it was a variable issue on my side.
