### ISSUE TITLE
getThreadInfo has issues reading info from old threads

### ISSUE THREAD

**Issue by AllanWang** [Schmavery/facebook-chat-api#277]
The bot still has access to the threads where there are issues, but they are usually threads that have been inactive for a while. It leads to the following error:

`ERR! Error in getThreadInfo TypeError: Cannot read property 'name' of undefined
ERR! Error in getThreadInfo     at C:\Users\user1\PA\ABB\node_modules\facebook-chat-api\src\getThreadInfo.js:36:46
ERR! Error in getThreadInfo     at tryCatcher (C:\Users\user1\PA\ABB\node_modules\bluebird\js\main\util.js:26:23)
ERR! Error in getThreadInfo     at Promise._settlePromiseFromHandler (C:\Users\user1\PA\ABB\node_modules\bluebird\js\main\promise.js:507:31)
ERR! Error in getThreadInfo     at Promise._settlePromiseAt (C:\Users\user1\PA\ABB\node_modules\bluebird\js\main\promise.js:581:18)
ERR! Error in getThreadInfo     at Promise._settlePromises (C:\Users\user1\PA\ABB\node_modules\bluebird\js\main\promise.js:697:14)
ERR! Error in getThreadInfo     at Async._drainQueue (C:\Users\user1\PA\ABB\node_modules\bluebird\js\main\async.js:123:16)
ERR! Error in getThreadInfo     at Async._drainQueues (C:\Users\user1\PA\ABB\node_modules\bluebird\js\main\async.js:133:10)
ERR! Error in getThreadInfo     at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\user1\PA\ABB\node_modules\bluebird\js\main\async.js:15:14)
ERR! Error in getThreadInfo     at processImmediate [as _immediateCallback] (timers.js:383:17)
ERR! Error in getThreadInfo  [TypeError: Cannot read property 'name' of undefined]`

Is there anything else I can do for testing?

[Code for reference](https://github.com/AllanWang/AllanBot-Public/blob/master/src/dataCollection.js)

**Comment by bsansouci** [comment]
Hey @AllanWang, we pushed a little fix to make sure the api doesn't crash. Can you try it again?

**Comment by AllanWang** [comment]
I can confirm that there are no longer error logs
