### ISSUE TITLE
Add lastRead map to getThreadInfo result

### ISSUE THREAD

**Issue by YuChunLOL** [Schmavery/facebook-chat-api#279]
Hello, 

Since `getThreadHistory` only can get message object, I'm wondering that is it possible to get "read" related event object ? 

Thanks.

**Comment by Schmavery** [comment]
Can you describe a reasonable use for this?

**Comment by HowardLoTW** [comment]
@Schmavery This purpose is currently for user behavior related research for me. 
I think there's also another uses for this, but I haven't thought yet.

**Comment by Schmavery** [comment]
@bsansouci looked into a fix for this a little yesterday.  It looks like it would involve adding fields to getThreadInfo with information about what the last read message is for each user in the thread.
