### ISSUE TITLE
Error when markAsRead()

### ISSUE THREAD

**Issue by krokofant** [Schmavery/facebook-chat-api#280]
Usage of markAsRead()
`api.markAsRead(message.threadID, (err) => {});`

Logged error
```
	sy-bot-2 ERR!
	sy-bot-2  Error in markAsRead { __ar: 1,
	sy-bot-2 ERR! Error in markAsRead   error: 1357004,
	sy-bot-2 ERR! Error in markAsRead   errorSummary: 'Ett fel har inträffat.',
	sy-bot-2 ERR! Error in markAsRead   errorDescription: 'Försök med att stänga och sedan öppna webbläsarfönstret på nytt.',
	sy-bot-2 ERR! Error in markAsRead   payload: null,
	sy-bot-2 ERR!
	sy-bot-2  Error in markAsRead   bootloadable: {},
	sy-bot-2 ERR! Error in markAsRead   ixData: {},
	sy-bot-2 ERR! Error in markAsRead   lid: 'XXXXXXXXXXXX (censored)' }
	sy-bot-2 ERR!
	sy-bot-2  Error in getUserInfo { error: 'JSON.parse error. Check the `detail` property on this error.',
	sy-bot-2 ERR! Error in getUserInfo   detail: [SyntaxError: Unexpected token <],
	sy-bot-2 ERR! Error in getUserInfo
```

**Comment by GAMELASTER** [comment]
Please, can you translate that error message?

**Comment by bsansouci** [comment]
@GAMELASTER google translate can detect the language ;)
@krokofant have you been running your bot for a long time? If so this might be the same issue as before where the cookies get invalidated. Does this happen even after a fresh login?

**Comment by krokofant** [comment]
@GAMELASTER
Error: An error has occured
Description: Try to close and then open the web browser window again

@bsansouci Yes. It seemd like it still got new messages but it could not mark messages as read.

**Comment by Schmavery** [comment]
Just to confirm, restarting the bot fixed this issue or no?

**Comment by krokofant** [comment]
@Schmavery Yes. I'll watch over it the coming week to see if it occurs again. I thought I'd create an issue right away considering facebook might change stuff at any time.

**Comment by Schmavery** [comment]
Feel free to reopen.  I think this is the same type of problem as #202, where some cookies are expiring.
