### ISSUE TITLE
api can't handle threads that have an alternative ID format

### ISSUE THREAD

**Issue by cvigoe** [Schmavery/facebook-chat-api#282]
Most threads have IDs in the form: "1234567890". I've seen a rare thread that has an ID in the form: "id.1234567890". When a thread has this format of ID, any attempt to getFullThread or getUserInfo or any call that relies on a thread ID with this ID format will cause the api to fail. The two screenshots show the difference between the two formats. array[] is an array of threads after a call to getThreadList(). You can see that array[186] has a thread ID in the "normal" form, and array[187] has the rare form. Posting this here in case @Schmavery & co. want to make any changes to accommodate this form of ID and also in case anyone else hasn't noticed this and encounters problems because of it.
<img width="451" alt="screen shot 2016-06-03 at 5 45 48 pm" src="https://cloud.githubusercontent.com/assets/6818920/15796514/d0a4078c-29b3-11e6-8479-a6497b328641.png">
<img width="393" alt="screen shot 2016-06-03 at 5 45 25 pm" src="https://cloud.githubusercontent.com/assets/6818920/15796515/d339795a-29b3-11e6-8aef-ba1aabd4b0bd.png">

**Comment by Schmavery** [comment]
Hmm, we should be stripping off the "id." prefix.  Someone will have to take another look through the getThreadList() code and make sure we're formatting it correctly.  As a workaround for now, manually removing the "id." should result in an id that will work in those calls.

**Comment by bsansouci** [comment]
We "fixed" this issue for messages here https://github.com/Schmavery/facebook-chat-api/blob/f98f3489f73edefb4041213bd3bb94b48b11aed1/utils.js#L375. I think the exact same fix should work for threads. Feel free to submit a PR :)

**Comment by Schmavery** [comment]
This should be fixed by #439.  Reopen if you still have problems :)
