### ISSUE TITLE
List archived threads

### ISSUE THREAD

**Issue by matthiashhh** [Schmavery/facebook-chat-api#283]
As far as I can see, getThreadList only lists threads in the inbox. There are no way to list archived threads, I believe. I was able to get around this by changing 'inbox' to 'action:archived' in getThreadList .js code. It would be great if this functionality could be implemented.

**Comment by Schmavery** [comment]
Please feel free to submit a PR where getThreadList accepts an optional boolean "archived" parameter.

**Comment by AllanWang** [comment]
maybe we should change the pending boolean to a string parameter to support this. I will look into this later on.

**Comment by Schmavery** [comment]
I think we have this now.  Thanks a lot @AllanWang !
