### ISSUE TITLE
"Wrong username/password." when running the code locally

### ISSUE THREAD

**Issue by adiscodes** [Schmavery/facebook-chat-api#284]
So I'm trying to login but it only works on the heroku server, whenever i try to run it locally it says wrong username/password.

This is the form data sent to login:

```
{ lsd: 'AVrMOHmM',
  default_persistent: '0',
  lgnrnd: '134147_WGCm',
  lgnjs: 1465764108,
  locale: 'en_US',
  next: 'https://www.facebook.com/',
  lgndim: 'eyJ3IjoxNDQwLCJoIjo5MDAsImF3IjoxNDQwLCJhaCI6ODM0LCJjIjoyNH0=',
  email: '******',
  pass: '******',
  timezone: '-180' }
```

I'm sure email and password are correct. Any help debugging this? 

Thanks.

**Comment by Schmavery** [comment]
Can you try to log in using your browser?  Could be an IP block maybe?

**Comment by adiscodes** [comment]
I can login from the browser. I tried an openshift server in the US that is also giving me wrong username/password. The heroku server is in Europe, as am I. Maybe it's something about location but I don't understand why it won't work from localhost.

**Comment by Schmavery** [comment]
That's very bizarre.  Can you reproduce this with another password that ends in ;
It seems to me that the most likely explanation is that the password was typed in wrong, though you mentioned you were pretty sure it wasn't.

**Comment by adiscodes** [comment]
Yup, it's the password, still can't figure out why though.

**Comment by Schmavery** [comment]
@bsansouci Hey Ben when you get a chance can you try to change one of our bots' passwords to end in ";"?
If anyone else can verify this problem exists, it will help us know if this is some fluke one-off problem or not.  At least @adiscodes found a workaround for now :)

**Comment by bsansouci** [comment]
I just tried and logged on successfully from the browser and from both of my laptops using the api.
This might's been some encoding issue but I'm not totally sure where it could've happen.

**Comment by Schmavery** [comment]
Thanks for checking, Ben.
I wonder if it could be a versioning issue... some strange bug in different versions of node or a required npm package.  Would obviously also depend on how you're storing/retrieving the password as this might be different in heroku vs local. @adiscodes thoughts?

**Comment by Schmavery** [comment]
If no one else is getting a repro on this, I might close it as being a one-off problem... @adiscodes please feel free to comment or reopen if you get any additional information.  Same goes for anyone else experiencing this problem.
