### ISSUE TITLE
Get larger images from `getFriendsList`

### ISSUE THREAD

**Issue by helloworld** [Schmavery/facebook-chat-api#285]
`getFriendsList` returns a field `profilePicture` with a url that looks like this: 

`https://scontent-iad3-1.xx.fbcdn.net/v/t1.0-1/c9.0.32.32/p32x32/10645251_10150004552801937_4553731092814901385_n.jpg?oh=6d257f01da9e9075daec6e49b6eb2904&oe=57CC2026`

Is there anyway to get a larger version of this picture? I noticed the `c9.0.32.32` and the `p32x32`, but manually changing those does not work 😦 

Is there any workaround for this?

**Comment by Schmavery** [comment]
Feel free to experiment and post back here with any discoveries :smile:

**Comment by Kezz101** [comment]
Does anyone know what the `oh=` and `oe=` parts do? Because you seem to get a larger profile image using p50x50 (again, you can't manually change it though) with different values for `oh` and `oe`

**Comment by Schmavery** [comment]
Does this endpoint not work? https://developers.facebook.com/docs/graph-api/reference/user/picture/

**Comment by GAMELASTER** [comment]
@Kezz101 I think that GET parameters is some of "verification" hash to get access to this image only for people what "can see" this image, and then its have some time expiration. 
The big image url maybe is can get from graph, because the profile photo is always public and big.

**Comment by Schmavery** [comment]
I feel like this is probably more of a job for the graph api and is not really related to chat.  Feel free to reopen if you disagree.
