### ISSUE TITLE
Get profile picture of current user

### ISSUE THREAD

**Issue by KeNt178** [Schmavery/facebook-chat-api#286]
We can only get the profile pictures of our friends but not our own.

**Comment by KeNt178** [comment]
500 stars, bravo !

**Comment by Schmavery** [comment]
https://github.com/Schmavery/facebook-chat-api/issues/248

**Comment by Schmavery** [comment]
I'm going to close this because I think there's a good workaround.  Please don't hesitate to reopen if you run into problems.
