### ISSUE TITLE
Get all shared pictures

### ISSUE THREAD

**Issue by lapinozz** [Schmavery/facebook-chat-api#288]
Add function to retrieve all pictures sent in a thread, here's my browser request:

`POST /ajax/messaging/attachments/sharedphotos.php?dpr=1 thread_id=1380****51&offset=90&limit=30`

**Comment by Schmavery** [comment]
Sounds cool!  I'd imagine if we implemented this people would get throttled pretty hard.
We accept pull requests for new features :smile:

**Comment by GAMELASTER** [comment]
Well, this I wanted to do some time ago, but it is harder to parse than it looks. This (I think) just return urls with small thumbnails, and for get full size is a next request to get XY images from chat in fullscreen.

**Comment by enhdless** [comment]
It seems that after the image ID is obtained from the request mentioned above, the browser takes that id and POSTs to `https://www.facebook.com/ajax/messaging/attachments/sharedphotos.php?thread_id=***&image_id=***&dpr=1`, and the full size image url can be found there.

**Comment by GAMELASTER** [comment]
Well, yeah, its changed as last time, requesting is little simplier. But anyway, parsing the whole message from Query is little harder, you can look in `jsmods.require[0][3].query_results` etc..

**Comment by ravkr** [comment]
we can close this now

**Comment by ravkr** [comment]
I think we can close this now
