### ISSUE TITLE
Its possible cancel a previous login or reconect when with same credentials?

### ISSUE THREAD

**Issue by fccoelho7** [Schmavery/facebook-chat-api#289]

**Comment by Schmavery** [comment]
Sorry I'm not sure what you mean.  Please provide more details.
We provide a logout method and you can login to a previous session using getAppState.

**Comment by fccoelho7** [comment]
When an user is created or updated, I set a listener to wait for clients. But, this is generating various different messages because are two or more listeners of same credentials. Im searching a way to stop the previous listener and start a new.

**Comment by Schmavery** [comment]
Maybe providing a short code example of what you're trying to do would help.
`api.listen` returns a `stopListening` function that will cancel the listen.

```js
var stopListening = api.listen(function(err, event) {
        if(err) return console.error(err);

        switch(event.type) {
          case "message":
            if(event.body === '/stop') {
              api.sendMessage("Goodbye...", event.threadID);
              return stopListening();
            }
            api.markAsRead(event.threadID, function(err) {
              if(err) console.log(err);
            });
            api.sendMessage("TEST BOT: " + event.body, event.threadID);
            break;
          case "event":
            console.log(event);
            break;
        }
    });
```

**Comment by fccoelho7** [comment]
@Schmavery in my case, are various accounts (different facebook accounts) logged in. I thought clear the cookie that refers to user that I'm trying logout.

**Comment by Schmavery** [comment]
Still having trouble understanding the specific scenario you're describing, a small code example is probably clearest.
`api.logout()` will invalidate the current session's cookie.

**Comment by fccoelho7** [comment]
In my system I've many users, each user has facebook login credentials. A loop search for users and log in one by one. If someone user edit their facebook account on admin, I need stop listener and create a new with new credentials.

**Comment by fccoelho7** [comment]
My app get every user and log in with FaceBook. The default messages of every user is on database. I make a 'for' with users list and login one by one. I can't logout because the user is dynamic, I need a reference to stop listening or logout, the listener that I want.

**Comment by Schmavery** [comment]
It sounds like this problem is specific to your application.  Without seeing the code, it will be hard to help.

**Comment by nadien** [comment]
Same here. I need to destruct session if is active.
I handle various users and when they click 2 times the button it will create 2 sessions.
So, how can destruct specific session if it's active?

**Comment by Schmavery** [comment]
api.logout() will invalidate the current session's cookie

**Comment by nadien** [comment]
@Schmavery 
Can I logout outside the function login()?

I want to logout from front-end button an active session

**Comment by Schmavery** [comment]
should be fine, feel free to give it a try
