### ISSUE TITLE
SendSticker not working

### ISSUE THREAD

**Issue by Schmavery** [Schmavery/facebook-chat-api#29]
error:
```
{ __ar: 1,
  error: 1545012,
  errorSummary: 'Temporary Failure',
  errorDescription: 'There was a temporary error, please try again.',
  transientError: 1,
  payload: null,
  bootloadable: {},
  ixData: {},
  lid: '0' }
```

**Comment by bsansouci** [comment]
They added threading_id (which is just message_id) and offline_threading_id. I'm working on finding how the latter is generated.
What's weird is that sending a message also needs those two, but sendMessage works...

**Comment by Schmavery** [comment]
Turns out that sendSticker only works if the corresponding sticker pack is added to the bot account.
