### ISSUE TITLE
Embed facebook-chat-api in a chrome extension

### ISSUE THREAD

**Issue by KeNt178** [Schmavery/facebook-chat-api#290]
Hello,

I'd like to use your api into a chrome extension. I tried to [browserify](http://browserify.org/) it but it blocks on the npmlog module you are using. Do you have any ideas on how to embed all your api in a single package without having to run a server beside ?

Thanks a lot,
Quentin

**Comment by GAMELASTER** [comment]
Last time when I try to browserify this module I failed. Instead of NPM log you can use simple console.log... I dont remember all steps what I do, so I cant help you more

**Comment by bsansouci** [comment]
Hey @KeNt178, I think you can easily mock the `require('npmlog')` if you dig into [webpack](http://webpack.github.io).
@GAMELASTER you were trying to run it entirely client side right? If so you probably had problems with cross site requests being not allowed. Chrome extensions don't have that problem so you should be fine @KeNt178.

**Comment by Schmavery** [comment]
How does it "block"?  Are you getting an error?
#103
https://github.com/npm/npmlog#logstream

**Comment by KeNt178** [comment]
I got the error "cannot find module 'bufferutil', I typed 'npm install bufferutil utf-8-validate --save' to download it. Then I succeeded to browserify it. Don't know if the server is running yet but it worked !

**Comment by Schmavery** [comment]
Uhh ok. Let us know if it ends up working.
