### ISSUE TITLE
Respond to chats without being sent one first.

### ISSUE THREAD

**Issue by trev4ev** [Schmavery/facebook-chat-api#292]
Is it possible for this to allow bots to send messages without receiving one first?

**Comment by avikj** [comment]
Yes, but this would require you to know the message thread's ID. For private messages, your threadID for the chat with a person would be their FB ID, which could be found [here](http://findmyfbid.com/).
For group chats, its the part in the messenger.com url after /t/. For example, if my group chat url is https://www.messenger.com/t/123456789, then the threadID is 123456789.

**Comment by GAMELASTER** [comment]
http://findmyfbid.com is good helper for thread id

**Comment by Schmavery** [comment]
https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#getUserID provides an example of doing this.

**Comment by Schmavery** [comment]
Going to close this for now.
