### ISSUE TITLE
Mute/unmute chat

### ISSUE THREAD

**Issue by renxinhe** [Schmavery/facebook-chat-api#294]
I'm not sure how difficult/easy it is to toggle mute and unmute on a specific chat. I have a "mute timer" project in mind, and couldn't find an easy way to inject into the chat html/php on [facebook.com](url). I was so excited to find this API, but after a bit of looking around, it doesn't seem like there is a mute feature.

**Comment by Schmavery** [comment]
It would be a matter of sniffing the packets that the browser sends to facebook.com when muting/unmuting the chat and then reproducing them.  I haven't looked into it, but I'd imagine it'd be doable.  I'd consider accepting a PR for a api.changeMutedStatus similar to api.changeArchivedStatus.

**Comment by GAMELASTER** [comment]
Yeah, actually it's contains a Messenger.com
```
https://www.messenger.com/ajax/mercury/change_mute_thread.php?dpr=1
POST
thread_fbid:100000XXXXXX540
mute_settings:-1 //-1 nonstop, 0 = disable, 1800 = 30 minutes, 3600 = hour etc..
payload_source:mercury
```
Then just check some property in Listen event for filtering if it is muted

**Comment by bsansouci** [comment]
@renxinhe you should definitely contribute and add this! This looks like a small addition. 
Here's what you'll want to do:
- copy `markAsRead.js` and make `muteChat.js`
- replace `https://www.facebook.com/ajax/mercury/change_read_status.php` with `https://www.messenger.com/ajax/mercury/change_mute_thread.php`
- make `form` contain the `thread_fbid` and the `mute_settings` which should be both arguments to the function (I'm guessing `mute_settings` is the number of seconds you want the chat to be muted).
- fix all discrepancies

I'm sure @GAMELASTER would love to help you, if this is your first contribution.

**Comment by renxinhe** [comment]
@bsansouci thanks for the help!
This is my first time looking into open source. I've been trying to hard code some request over via Postman to mute a chat. No luck yet. But I'll look into `markAsRead.js` and see if I can pull something together.
