### ISSUE TITLE
Threads without a custom title sometimes have no names.

### ISSUE THREAD

**Issue by AllanWang** [Schmavery/facebook-chat-api#296]
I might have posted this before, but when there is a conversation among a group of people and the title isn't changed, getting the title (getThreadInfo, info.name) sometimes returns a blank string ("").

For my tests, I have 3 or 4 people in a given conversation, and I'm friends with all the users. I do remember that before, it would sometimes set the title to just one of the people in the group.

There are no errors shown and the other information from the thread info seems to be all good.

[This ](https://github.com/AllanWang/AllanBot-Public/blob/master/src/dataCollection.js#L22)is the function I used.

**Comment by Schmavery** [comment]
This seems like fairly expected behaviour to me...

**Comment by Schmavery** [comment]
If this is actually a problem, feel free to reopen.

**Comment by AllanWang** [comment]
My initial report was probably incorrect.

I'm taking a look at [the line that supplies the name](https://github.com/Schmavery/facebook-chat-api/blob/master/src/getThreadInfo.js#L36), and even though I don't know which data is what exactly, I'm wondering the following:

1. If userData.name is my name, and threadData.name is the thread's name, shouldn't threadData.name be default as long as it isn't null?

2. If the thread is unnamed and it's a one on one conversation, shouldn't the name default to the name of the other user? I'm getting mixed results on this one, but looking at my data over 80% of the one on one conversations have the name undefined as well.

**Comment by bsansouci** [comment]
@AllanWang I think the problem is that we don't always have `userData.name` which is why it's guarded by ifs. I don't think we should be automatically querying for your name and fill it up, it seems like something that you can almost trivially do (and make your own wrapper of `listen`). 
I'd be ready to add this if most people want it, but I'm not convinced it's always useful. You should use the `threadID` to identify a thread. The name should only ever be used for display.

**Comment by AllanWang** [comment]
Are you saying that it is expected that the name of the other user in a one on one conversation isn't always available in getThreadInfo?

I've been trying to add my own extra query ([example](https://github.com/AllanWang/AllanBot-Public/blob/master/src/dataCollection.js#L33)), but I just thought it would be there be default.

Nevertheless, I'm still wondering why userData.name is sometimes empty when I can call getUserInfo with the same threadID and get the name from there, just like how it is done in getThreadInfo.
