### ISSUE TITLE
getThreadInfo() error when chat room isn't named

### ISSUE THREAD

**Issue by yuyuvn** [Schmavery/facebook-chat-api#299]
when I call getThreadInfo() in a room that isn't named, it throw this error:
```
TypeError: Cannot read property 'name' of undefined
```

**Comment by GAMELASTER** [comment]
#296 uhmm..

**Comment by Schmavery** [comment]
I probably need to push this fix to npm.  Thanks @yuyuvn

**Comment by Schmavery** [comment]
@bsansouci did you say you were having problems with getUserInfo? If so, that could be causing the problems here and in #296.
We probably want to write some failsafe code to still return a sane result even if getUserInfo fails.

**Comment by AllanWang** [comment]
It's a bit weird since it works if I get the ID from getThreadInfo and then put the id into getUserInfo. In this case, the threadID and the userID used are the same, as expected.

**Comment by Schmavery** [comment]
Can you verify that these problems still occur with v1.2.0?

**Comment by yuyuvn** [comment]
I'll check again

**Comment by yuyuvn** [comment]
it work
