### ISSUE TITLE
Add feature to retrieve user info from every friend added to a friend list

### ISSUE THREAD

**Issue by nguyenbrian** [Schmavery/facebook-chat-api#306]
![Lists](http://i.imgur.com/SIuniDR.png)
I originally tried to query the friend lists data in order to get user IDs using the Graph API but quickly found out that isn't supported with 2.0.

It'd be cool if we could retrieve every friend in a friend list with a function like getList().

Alternatively, maybe this could just be added onto `getFriendsList()` as another field under a user such as `lists: blah, blahblah`

**Comment by Schmavery** [comment]
My gut response to this is that it doesn't seem like a chat-related feature to me and so is out of the scope of this API.  If the getFriendsList() call already has access to this data and we're simply not returning it, I could understand adding it in, but I think other than that it is unlikely that we will do any work to add this feature.

If you're set on having this, you can always fork this repo and add it yourself to your own branch, using our login and cookie management code.

**Comment by Schmavery** [comment]
Going to close this for the reasons above.  Feel free to comment back here if you manage to get it to work in case someone in the future wants to do the same thing :smile:
