### ISSUE TITLE
Messenger code

### ISSUE THREAD

**Issue by robertbodley** [Schmavery/facebook-chat-api#310]
Hi,

Would it be possible to get anyones messenger code?

Here is the link to a code but I cannot get it for other pages: https://www.facebook.com/messenger_code/generate/?image_format=image%2Fpng&image_size=420&profile_id=775983449156910&ext=1470916727&hash=AeReSbRohn3m0lge

Would appreciate any response.

Thanks!

**Comment by Schmavery** [comment]
Where can you see this code in the browser?
This link doesn't work for me.

**Comment by robertbodley** [comment]
Go to a Facebook page your own > Click Messages in the top navigation bar > click the "i" that is just below the messages for that page.

This also might help: http://www.socialmediaexaminer.com/how-to-use-facebook-messenger-for-business/

Thanks!

**Comment by Schmavery** [comment]
It doesn't seem like it would be possible to get the code for pages you don't own using this method.  I meant, is there any way to see the code for pages you don't own in the browser?  We'd probably accept a pull request with this feature.

**Comment by robertbodley** [comment]
I am not sure if that is possible but would be awesome if you could somehow make it possible.

**Comment by Schmavery** [comment]
We can't do anything with the api that you can't do in a browser :)
I'll close this for now and feel free to reopen it if you find a way.

**Comment by robertbodley** [comment]
I have found I can do it for my Facebook page through this link: https://www.facebook.com/messenger_code/generate/?image_format=image%2Fpng&image_size=420&profile_id=775983449156910&ext=1478248723&hash=AeQuAEGz8px66y3y, I don't think you will be able to see it but that links directly to my messenger code for my brand page. 

This explains it: http://www.socialmediaexaminer.com/how-to-use-facebook-messenger-for-business/

I am not sure if this helps? 

Thanks again.

**Comment by Schmavery** [comment]
Seems like this allows you to get your own code?  It's possible this could be exposed using the api, but so far there hasn't been a huge request for page features.  That said, we definitely always encourage pull requests and are happy to give you all the help you need making this change.
Wasn't the original desire to be able to get other peoples' messenger codes?  Maybe I misread the article you linked, but I couldn't find that functionality.
