### ISSUE TITLE
404 error when sending messages

### ISSUE THREAD

**Issue by nmggithub** [Schmavery/facebook-chat-api#314]
It appears FB has changed their API. This module no longer works as expected.

**Comment by nmggithub** [comment]
@kjellberg Same issue. Should I close this?

**Comment by someshmishra** [comment]
Hi,

I am too facing this issue. Please help

**Comment by nmggithub** [comment]
@someshmishra it is fixed with @Mini-Geek 's pull request. Please reinstall and it should work

**Comment by Theblood** [comment]
@someshmishra follow theses steps :+1: 

` cd node_modules
 rm -rf facebook-chat-api
​ git clone https://github.com/Schmavery/facebook-chat-api.git
 cd ​facebook-chat-api
 npm install`

**Comment by Schmavery** [comment]
@Theblood @someshmishra I have already pushed the changes to npm so just update to 1.2.0 please.  No need to sync to master.
