### ISSUE TITLE
Unable to login to facebook and wrong error message

### ISSUE THREAD

**Issue by amirmamaghani** [Schmavery/facebook-chat-api#32]
I'm using your simple login example and I've got this message:
```
info Getting login form data 
info Logging in... 
ERR! TypeError: expecting an array, a promise or a thenable

    See http://goo.gl/s8MMhc

```

After some investigation I spotted that error occurs at index.js:45 (i'm not getting any location so my login credentials are wrong?)

But my credentials are ok so I rendered HTML body of response and I'm seeing an error message that says cookies aren't enabled on my browser. What now? Am I doing something wrongly?

**Comment by JLarky** [comment]
@amirmamaghani please take a look at #30

**Comment by Schmavery** [comment]
@amirmamaghani Can you update and check if it works now?  I just published the changes to the latest version on npm.

**Comment by amirmamaghani** [comment]
Yop, thx a lot, it is working now! :)
