### ISSUE TITLE
api.getFriendsList doesn't show all friends

### ISSUE THREAD

**Issue by cookkkie** [Schmavery/facebook-chat-api#321]
3 friends on ~100 friends aren't showed in the list. Any idea ? 
I can definitely see that they are actual facebook friends on their wall and on messenger. But they don't show up at all in the response list.

**Comment by Schmavery** [comment]
It doesn't look like we do any filtering on the friends that are returned, so this is likely facebook that is not returning us all of the information.  Maybe there's a way for people not to mark their account as not public in this way or something?  Some of the permissions stuff in facebook is a little fiddly.
