### ISSUE TITLE
Try my chrome extension!

### ISSUE THREAD

**Issue by KeNt178** [Schmavery/facebook-chat-api#322]
Hey guys,

I've uploaded the chrome extension using *facebook-chat-api* that I am currently working on. The idea is to share any active tab to a friend the most rapidly.
Feel free to give it a try!
- [**Klink**](https://github.com/KeNt178/klink)

All feedbacks/helps are warmly welcomed.

Thanks for your time, I hope you'll enjoy the experience.

**Comment by Schmavery** [comment]
Looks cool @KeNt178, feel free to submit a PR adding your project to the list at the end of our README :smile:

**Comment by Schmavery** [comment]
Thanks for the PR :)

**Comment by KeNt178** [comment]
The pleasure is mine
