### ISSUE TITLE
how I can accept messages with this api

### ISSUE THREAD

**Issue by Theblood** [Schmavery/facebook-chat-api#324]
hello friends, could help with code

**Comment by bsansouci** [comment]
Hey!
I'm assuming you want to accept message requests. You can get all the pending message requests by given `"pending"` to [getThreadList](https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#getThreadList) and accept them with [acceptMessageRequest](https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#apihandlemessagerequestthreadid-accept-callback)

**Comment by Theblood** [comment]
@bsansouci thanks *-* ! :+1:
