### ISSUE TITLE
Supports get info of the followers as a page?

### ISSUE THREAD

**Issue by josaal17** [Schmavery/facebook-chat-api#328]
Hello,

I can see that support send messages as a page. But my question is if support for a page (get followers list) or (get followers user info)?

Thanks

**Comment by Schmavery** [comment]
Is this information not accessible through the official facebook graph api?

**Comment by josaal17** [comment]
I think the only option is "fan_count" in the official facebook graph api! 
If I'm wrong please correct me.

Thanks

**Comment by Schmavery** [comment]
Hmm, I'm not an expert in the graph api, so I'm not sure.  What do you need this data for?  Generally our chat api is focused on chat, so we don't usually add features like this.

**Comment by josaal17** [comment]
I need this data for extract the userID and send messages to fans(followers).

Same to methods of users in this api

api.getUserID
api.getUserInfo

But for Page.

**Comment by Schmavery** [comment]
You can't send messages to followers of a page without them first messaging you.

**Comment by Schmavery** [comment]
Hey @josaal17, I'm going to close this because I don't think we'll be adding it to the api, but please feel free to continue the conversation about it if you feel very strongly.
We'd also be happy to give you some pointers about how to figure out how to do this on your own if that would be helpful.
