### ISSUE TITLE
api.markAsRead fails silently

### ISSUE THREAD

**Issue by Mini-Geek** [Schmavery/facebook-chat-api#329]
Maybe the Facebook API changed. The unit test still passes, but I don't see it reflected by the Facebook site or Android Messenger app. The request sent by the current site includes the following params, and this API only includes `ids[threadId]`.

ids[REMOVED]=true
watermarkTimestamp=1473520952998
titanOriginatedThreadId=REMOVED
shouldSendReadReceipt=true
commerce_last_message_type=non_ad

**Comment by Schmavery** [comment]
Interesting, thanks.  Can you try adding these params to our call and seeing if that fixes it?

**Comment by Mini-Geek** [comment]
I tried that, the one parameter I'm struggling to understand is titanOriginatedThreadId. Its format appears to match the unused utils.generateThreadingID method. Can you tell me about that method? What is the clientID that should be passed in? Here's what I've got so far:

    form["ids[" + threadID + "]"] = true;
    form["watermarkTimestamp"] = new Date().getTime();
    form["shouldSendReadReceipt"] = true;
    form["commerce_last_message_type"] = "non_ad";
    form["titanOriginatedThreadId"] = utils.generateThreadingID("abcd");

This causes a loop of "WARN parseAndCheckLogin: Got status code 500 retrying...". Looking into it, it's a generic HTML error page with a "Sorry, something went wrong." message, so I'm guessing Facebook doesn't like my clientID value, or something else about the request.

**Comment by Schmavery** [comment]
Can you try ctx.clientID

**Comment by Mini-Geek** [comment]
Adding ctx.clientID lets the call go through. But with or without the four new params, the read notifications are working in a few chats (both individual and group) I have going, but not working in one particular group chat. However, I noticed that read notifications are not working through the official app in this particular chat, either. I'm satisfied that this is currently a bug with Facebook and not with your API.

I still don't know what the issue is with this group chat and read notifications, but I think this issue can be closed for now.

**Comment by Schmavery** [comment]
Thanks for investigating this, @Mini-Geek, it really helps a lot.
Hopefully facebook can get this cleared up on our end and it's good to have some initial investigation into a fix.
Does the group chat for which it fails succeed when you don't add the parameters?  If the parameters make markAsRead strictly better, I'd love to get a pull request so that we can add them to our api.

**Comment by Mini-Geek** [comment]
To be clear: From a purely "does it work" perspective, I can't say that the changes make it any better or worse. From a "does it match the current API as closely as possible" perspective, I'd say the changes are strictly better. I have submitted it as #332, if you'd like to merge it. Or don't merge it, I don't mind either way. =)
