### ISSUE TITLE
reportPullReturned ya za

### ISSUE THREAD

**Issue by JLarky** [Schmavery/facebook-chat-api#33]
I'm looking at https://github.com/Schmavery/facebook-chat-api/blob/master/time.js#L77 and trying to understand why nowhere in the code `ya` or `za` are set. As I understand it, that will cause `continuousPullFails` to be incremented instead of `pullCount`

**Comment by bsansouci** [comment]
We copy pasted this from Facebook's minified code. To be honest, I think this isn't useful. Try to remove all the calls to `reportPullReturned` and check if it works.

**Comment by Schmavery** [comment]
This seems to be working fine as is.  Maybe it's a good candidate to be cleaned up in the future but right now it doesn't seem like it needs to be a priority.
