### ISSUE TITLE
getThreadList not flagging pending group chats properly when added by non-friend

### ISSUE THREAD

**Issue by ErmanSayin** [Schmavery/facebook-chat-api#331]
When the user gets kicked from a group chat, then it gets added by a non-friend, it is a pending message request, but whilst using `getThreadList` (3rd argument is `'pending'`, also tried `'archived'`), the thread is basically not there.

Whilst looking at inbox messages, the thread is there, but there's no way to determine if the thread is pending.

I need to receive messages from everywhere, so I want to use `handleMessageRequest`, but I can't determine which threads need to be handled. Attaching an event handler does kinda work, but it will simply won't work when the bot isn't running.

**Comment by Schmavery** [comment]
What does the browser do to retrieve these threads?

**Comment by Schmavery** [comment]
Is anyone else running into this issue or was it some transient bug on facebook's end?

**Comment by Schmavery** [comment]
It's pretty hard to diagnose these bugs without more data and we've changed a lot since september so hopefully this works better now!  I'm going to close it but we can definitely reopen if you're still having problems 😄
