### ISSUE TITLE
How you know to what chat send message/do actions

### ISSUE THREAD

**Issue by checkium** [Schmavery/facebook-chat-api#334]
How you define what chat group/"one-person" chat to send messages or do actions like listening?

**Comment by checkium** [comment]
Two More Questions:
If there are multiple persons with the same name, how I can get the userID of a specific one?
and
How I can listen for if someone removed/added someone to the group?

**Comment by Schmavery** [comment]
Our [api docs](https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md) and [README](https://github.com/Schmavery/facebook-chat-api/blob/master/README.md) have most of the information you should need, as well as some examples.  Feel free to ask more specific questions about what you see there :)
