### ISSUE TITLE
After removing and readding bot to group, it stops working.

### ISSUE THREAD

**Issue by checkium** [Schmavery/facebook-chat-api#336]
Title says it all

**Comment by Schmavery** [comment]
Can you make sure it works in the browser?  Facebook has had issues with this in the past.  A short code sample would also be super helpful to make sure everything is set up right and see if we can reproduce the bug.

**Comment by checkium** [comment]
yes, it works, but I fixed it by a "hacky" way, when I get the event I got added to a group, I simply restart my listener.

**Comment by Schmavery** [comment]
Hmm.. hopefully this was just a temporary issue.  Hard to reproduce with this much information.  Thanks for reporting that you found a workaround :)
