### ISSUE TITLE
SyntaxError: clientside with Browserify

### ISSUE THREAD

**Issue by adhambadr** [Schmavery/facebook-chat-api#338]
Since fb blocks an account that would suddenly login from my server (i guess bc ip / location or am i missing something here?)
Im trying to build the library using browserify & uglify, but getting this error 
`Parse error at -:53031,7
SyntaxError: Unexpected token: string (p_)
Error
    at new JS_Parse_Error (eval at <anonymous>`

my build command is 
`browserify src/script.jsx -t babelify -g  --extension=jsx | uglifyjs -o public/script.min.js`

did anyone succeed in getting everything running only client-side ?

**Comment by adhambadr** [comment]
duplicate to #103

**Comment by Schmavery** [comment]
Did you get this to work?  I don't think those issues are related.  I would guess that the problem you're having is that we use some ES6 language features.

**Comment by adhambadr** [comment]
it is kinda, I used the solution suggested at then, patched node_modules > fb-chat-api > node_modules > npmlog > log.js
`
// workaround
var Stream = require('stream');
var streamWrite = function (chunk, encoding, callback) {
    if (Buffer.isBuffer(chunk)) {
        chunk = chunk.toString(encoding);
    }
    console.log(chunk);
    if (callback)
        callback();
    return true;
};

var st = new Stream();
st.write = streamWrite;
var st2 = new Stream();
st2.write = streamWrite;

//  Instead of 
// process.stdout = new Stream();
// process.stderr = new Stream();
// As of Node 6+ you can not set process.stdout

var ansi = require('ansi')
log.cursor = ansi(st)
log.stream = st2

`javascript

**Comment by adhambadr** [comment]
however it is _still_ not working because of cross origin requests being blocked from the browser, working on a work-around for that

**Comment by Schmavery** [comment]
Ok good.  I think this is the fix that we originally suggested for this.
Cross origin problems aren't really a consequence of this library itself, I'm pretty sure.

**Comment by adhambadr** [comment]
well yes of course, but how do you create a product that anyone but yourself can use (login) without getting fb security detect and block the login or maybe the account ? do you have any suggestions ?

**Comment by bsansouci** [comment]
To go around the cross origin request problems you can make a chrome/safari extension (which allow that).
