### ISSUE TITLE
Making "Got answer in [...]" optional

### ISSUE THREAD

**Issue by ImJustToNy** [Schmavery/facebook-chat-api#340]
Hello!

Firstly, great library!
Next, can we please get option to hide "Got answer in [...]" message optional?
I mean [this one](https://github.com/Schmavery/facebook-chat-api/blob/master/src/listen.js#L71).

Thanks!

**Comment by Schmavery** [comment]
Can you just set the logLevel? 
https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#setOptions

**Comment by ImJustToNy** [comment]
Thank you!
