### ISSUE TITLE
Lib stops listening for messages

### ISSUE THREAD

**Issue by anisblk** [Schmavery/facebook-chat-api#341]
After a random number of hours, it doesn't receive message events anymore. I have to restart the app so that it works.

Though I still get things like
```
info Got answer in  1607
info Got answer in  xxxx
...
```

Any idea? Thanks in advance ;) .

**Comment by Schmavery** [comment]
Probably related to #202 😢

**Comment by Schmavery** [comment]
Closing as related bug.
