### ISSUE TITLE
api.listen not picking up messages

### ISSUE THREAD

**Issue by lyneca** [Schmavery/facebook-chat-api#343]
This code:
```javascript
login = require('facebook-chat-api')
login({email: '[email]', password: '[password]'}, function(err, api) {
  api.setOptions({selfListen: true})
  api.listen(function(err, msg) {
    console.log(msg.body)
  });
});

```
only activates when a `read_receipt` event fires.

**Comment by Schmavery** [comment]
Are you saying that setting selfListen is required for this to happen?

**Comment by lyneca** [comment]
Well, I've just tried the same code again and it's worked. Possibly something on messenger's end or something changed on mine.

**Comment by Schmavery** [comment]
Thanks for following up @lyneca :)
It can be hard to track down these issues sometimes.
