### ISSUE TITLE
How to receive all message requests?

### ISSUE THREAD

**Issue by Larry850806** [Schmavery/facebook-chat-api#344]
I use `api.listen` to listen the message from my friends. But when someone is not my friend, It will not trigger callback in `api.listen` . What I want to do is to receive all message requests. How do I do that?

**Comment by Schmavery** [comment]
PRs #247 and #193 did some work to add functionality for message requests but were unfortunately abandoned before all the issues were ironed out.  I'd imagine they still work to some degree, so feel free to check them out and get back to us with any results you have.  Feel free to let us know if you have any problems and we can help iron them out and hopefully get this functionality merged into master! :)

**Comment by AllanWang** [comment]
[Here](https://github.com/AllanWang/AllanBot-Public/blob/2c9ed220c6794d1f3be2d089581edb4bae72db76/src/dataCollection.js#L46) is a workaround I've made to accept pending messages. It checks every minute or so, which isn't optimal. I may see if I can possible add this function to api.listen

**Comment by Schmavery** [comment]
https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#getThreadList
Does getThreadList with "pending" work for you @Larry850806 ?

**Comment by Schmavery** [comment]
Since there is functionality of getThreadList that is meant to solve this problem, I'm going to assume you just couldn't find the function and that it's a viable workaround.  Please let us know if you have any more problems :)
