### ISSUE TITLE
Do not receive msg.

### ISSUE THREAD

**Issue by mmuneer** [Schmavery/facebook-chat-api#346]
I am trying to run the following example:

```
var login = require("facebook-chat-api");
login({email: "xxx", password: "xxx"}, function callback (err, api) {
    if(err) return console.error(err);

    var yourID = yyy;
    var msg = {body: "Hey!"};
    api.sendMessage(msg, yourID);
});

```
I see the following message in my console: 
```
info Logging in... 
info Logged in 
info Request to reconnect 
info Request to pull 1 
info Request to pull 2 
info Request to thread_sync 
info Done logging in. 

```

The user doesn't receive any message. Am I missing something?

**Comment by mmuneer** [comment]
Never mind. It took a while(~ 2hours), but it did come through. Closing the  Issue

**Comment by Schmavery** [comment]
Hmm, that doesn't sound great.  It should usually be faster than that.  Thanks for letting us know.
