### ISSUE TITLE
Uploading remote images via streams

### ISSUE THREAD

**Issue by ivkos** [Schmavery/facebook-chat-api#347]
I'm trying to send image attachments to a chat. The tricky part is that the images are not local, so they need to be piped via streams using [request](https://github.com/request/request).

I'm doing this:

``` js
    execute(msg, query) {
        return this.getImageUrls(query)
            .then(urls => urls.map(url => {
                const pass = new stream.PassThrough();
                request.get(url).pipe(pass);
                return pass;
            }))
            .then(streams => ({
                body: query,
                attachment: streams
            }))
            .then(theMessage => this.api.sendMessage(theMessage, msg.threadID));
    }
```

I'm not sure if `PassThrough` is the right kind of stream for this job, but the upload fails with:

```
ERR! Error in uploadAttachment Error: read ECONNRESET
ERR! Error in uploadAttachment     at exports._errnoException (util.js:1026:11)
ERR! Error in uploadAttachment     at TLSWrap.onread (net.js:569:26)
ERR! Error in uploadAttachment  { Error: read ECONNRESET
ERR! Error in uploadAttachment     at exports._errnoException (util.js:1026:11)
ERR! Error in uploadAttachment     at TLSWrap.onread (net.js:569:26)
ERR! Error in uploadAttachment   cause: 
ERR! Error in uploadAttachment    { Error: read ECONNRESET
ERR! Error in uploadAttachment        at exports._errnoException (util.js:1026:11)
ERR! Error in uploadAttachment        at TLSWrap.onread (net.js:569:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' },
ERR! Error in uploadAttachment   isOperational: true,
ERR! Error in uploadAttachment   code: 'ECONNRESET',
ERR! Error in uploadAttachment   errno: 'ECONNRESET',
ERR! Error in uploadAttachment   syscall: 'read' }
{ Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TLSWrap.onread (net.js:569:26)
  cause: 
   { Error: read ECONNRESET
       at exports._errnoException (util.js:1026:11)
       at TLSWrap.onread (net.js:569:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' },
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  syscall: 'read' }
```

Streaming local images works fine though:

``` js
        this.api.sendMessage({
            attachment: fs.createReadStream("/path/to/image.jpg")
        }, msg.threadID);
```

Am I doing something wrong, is it a bug of the module, or it's just not possible to pipe remote images?

Thank you.

**Comment by bsansouci** [comment]
Hey @ivkos, I'm looking into this. Quick question though, are you sure the URLs you get are valid images?

**Comment by Schmavery** [comment]
One good test what @bsansouci said might be to download the image and then try uploading it from local disk.  That way we know that it's not the image that's the problem.

**Comment by ivkos** [comment]
@bsansouci Yes, the URLs are valid images. The current workaround I'm using is exactly what @Schmavery suggested (first downloading the images then uploading them from disk) and it works. It appears the images are not the problem.

Could it be something related to the streams' properties? For example, the `ReadStream` that `fs.createReadStream()` returns has `highWaterMark` set to 64 kb, while the default value for readable streams is 16 kb. [[Source]](https://nodejs.org/dist/latest-v6.x/docs/api/fs.html#fs_fs_createreadstream_path_options)

I'm running the code on:
* Windows 10.0.14393
* Node.js v6.9.1

**Comment by Schmavery** [comment]
Unfortunately I'm not super familiar with all of the intricacies of node streams, so I'm not sure how much I can help here..  Thanks for looking into this, it seems like a very useful thing for people.  
@bsansouci do you remember anything funny from back when you implemented upload?  I wonder if there's any way we can do this by simply passing facebook the url and letting them download it... they might have some upload api like this? (wishful thinking)

**Comment by Schmavery** [comment]
I'm starting to wonder if we might be able to bypass this node issue by making facebook do the work for us.  If you look at the network message that gets sent when you send a link to an image/gif, it seems to contain some metadata that has information about the link.  The image is then displayed with the message.  It might be worth looking into whether you can specify a remote url to an image in the metadata with no message text and have the desired thing show up in the chat.  Worth a shot.  When I tried it, the metadata looked something like this:

![image](https://cloud.githubusercontent.com/assets/2154522/20096541/2fe35276-a55f-11e6-92e7-f5dd11847af8.png)


I'd be curious to wire up the api to be able to send a message exactly like this except with an empty "body" field and see what happens...

**Comment by mitchcapper** [comment]
So I noticed this issue and something odd.  It looks like you are trying to wire up giphy with FB (or at least your example does).  The first time you send a gif URL to FB it does not play, it just shows a static preview.  If you send the exact same URL again it then works.    It seems the FB backend has to do some fetching to make the auto-play work and that happens after first fetch.  On the actual platform this is probably avoided as the sender's client will preview the gif (thus doing the fetch) before sending it.  Not sure if this could be emulated somehow.  Technically you could dump a gif to a /dev/null type user first to cause FB to do its auto-play setup and then send it to the real user.

An example
``msg is: {
        "body": "",
        "url": "http://media2.giphy.com/media/3XiQswSmbjBiU/giphy-downsized.gif"
}
``
First time you send will not play, second time you send it will.  First time will succeed once FB has previewed the url so choose a different giphy if it works on first try to see issue.

**Comment by GAMELASTER** [comment]
Facebook converting GIFs into mp4, same as audio

**Comment by mitchcapper** [comment]
Maybe we need to do an emulated preview segment like an actual client and then wait a few seconds before re-sending the url to get proper behavior.

**Comment by Schmavery** [comment]
Hmm, thanks for doing some investigation @mitchcapper.  This seems a little strange.  Maybe we're missing a call somehow, and when the message gets received this call gets made automatically by the browser...  not sure.

**Comment by mitchcapper** [comment]
I think it has to do with FB's caching.  A normal user going to send a giphy (or other item) to someone else first sees it in their preview when composing the message (and the initial request causes the caching before that I would assume).  Thus once sent to another user it is already cached.  Of course I don't know how long their cache lasts (as in theory a user viewing a message after a cache preview expires would still get an initial single frame).

**Comment by bsansouci** [comment]
If I had to guess, I think this issue is due to a misuse of the nodejs APIs rather than FB.

I was able to make this work with a readStream in each case here #353.

**Comment by Schmavery** [comment]
Going to go with Ben's guess for now.  Feel free to reopen if you have further issues :)
