### ISSUE TITLE
Event log:unsubscribe removed participants

### ISSUE THREAD

**Issue by tokelpl** [Schmavery/facebook-chat-api#349]
When i have log unsubscribe event and in logMessageData i have removed particioants i csnt get fbid i got undefined why ?

**Comment by bsansouci** [comment]
Do you mean [threadID](https://github.com/Schmavery/facebook-chat-api/blob/c7ccb343d6ae034838d0d3b3d395c6db78223f6d/utils.js#L395)

**Comment by tokelpl** [comment]
I mean removed participants when i have log:unsubscribe event and i have logMessageData i there i have removed_participants and i cant get fbid

**Comment by tokelpl** [comment]
I mean event.logMessageData.removed_participants = [ 'fbid' : 123456789] i cant get that fbid

**Comment by Schmavery** [comment]
Thanks for helping clarify. Could you provide a short code example of what you're trying to do?  It's possible that facebook has updated the signature of event objects.
From what I can see, the schema of event.logMessageData should be {"removed_participants":["fbid:100001439708199"]}.  Note that removed participants points to an array of strings, not a number.  Hopefully this helps.

**Comment by tokelpl** [comment]
I dont have any code because i only have console.log(removed_participants) and it give me ['fbid: 27262825'] and i wanna get that id (i am kind of a noob in node)

**Comment by bsansouci** [comment]
Try from master, I just committed https://github.com/Schmavery/facebook-chat-api/commit/00b3c006b8f2920d35c4c90ec1f84409c9416dd6.

**Comment by tokelpl** [comment]
Yeah, now i get unexpected token: ... in utils.js right in the line that you modified

**Comment by tokelpl** [comment]
/root/bot/node_modules/facebook-chat-api/utils.js:398
      ...m.log_message_data,
      ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/bot/node_modules/facebook-chat-api/index.js:3:13)
    at Module._compile (module.js:556:32)

**Comment by tokelpl** [comment]
I made it, here is my modified utils http://tomekk.pl/utils.js

**Comment by tokelpl** [comment]
Not working, i do not replaced files..

**Comment by Schmavery** [comment]
Hey @tokelpl, looks like the problem is your version of node is older than @bsansouci 's.  Is your fix working for you now?

**Comment by tokelpl** [comment]
it,s strange, i am using node 7.0.0 and i have errors..

**Comment by tokelpl** [comment]
root@vz278880:~/bot# node --version
v7.0.0
root@vz278880:~/bot# node app.js
/root/bot/node_modules/facebook-chat-api/utils.js:399
    }) : {},
    ^
SyntaxError: Unexpected token }
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:545:28)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/bot/node_modules/facebook-chat-api/index.js:3:13)
    at Module._compile (module.js:573:32)

**Comment by tokelpl** [comment]
Or maybe i have too new version ? What version of node you are using ?

**Comment by Schmavery** [comment]
This new error looks like @bsansouci messed up.  I'll doublecheck.

**Comment by tokelpl** [comment]
But, can this be related to node version ?

**Comment by tokelpl** [comment]
I saw @bsansouci commit and downloaded and it's working ! Thank!

**Comment by bsansouci** [comment]
@tokelpl Sorry for the typo, I made the change from the github online editor blindly :s

**Comment by tokelpl** [comment]
But now i have another problem console.log(logMessageData) give me { removed_participants: [ undefined ] } and only this i dont have luck xd

**Comment by bsansouci** [comment]
Gosh, try now :/

**Comment by tokelpl** [comment]
It works perfectly :D Thanks For The Help!
