### ISSUE TITLE
Other Users Messenger Codes

### ISSUE THREAD

**Issue by robertbodley** [Schmavery/facebook-chat-api#350]
I am hoping you can help. Is it possible to get other peoples messenger codes using an API or link? Any input would be appreciated.

**Comment by Schmavery** [comment]
Is there a way to do this in the web?

**Comment by robertbodley** [comment]
Not that I have found on the web but you can get other peoples in the messenger app (3D touch on one of your favorites)

**Comment by Schmavery** [comment]
Right now we're unfortunately only able to support functionality that can be accessed in the web.  Feel free to reopen this when it becomes possible to do in a browser :)
