### ISSUE TITLE
Error 500 changeThreadEmoji

### ISSUE THREAD

**Issue by tokelpl** [Schmavery/facebook-chat-api#352]
I am getting this error pls help
![image](https://cloud.githubusercontent.com/assets/2154522/20072321/bf4334d2-a4dc-11e6-938e-8fa67d1ddf23.png)

**Comment by Schmavery** [comment]
Is this on a phone?

**Comment by Schmavery** [comment]
I'm trying to change thread emoji in the browser right now and getting a 500 there too... might be a facebook bug.

**Comment by Schmavery** [comment]
This seems to work in the browser now... wanna check again?

**Comment by AstroCB** [comment]
It seems to throw this error when you try to set it to an unsupported emoji (at least as far as I can tell).

**Comment by Schmavery** [comment]
Ah, thanks for letting us know @AstroCB.  @tokelpl can you try setting it to one that you can set it to in the browser?  I'm going to consider this resolved as I managed to get it to work on my end.  Please follow up if you have any more problems :)

**Comment by BenMirtchouk** [comment]
Just as a note, setting it to %F0%9F%85%B0(🅰) as well as %F0%9F%85%B1(🅱) gives a 500, but they do show up as supported in the browser (messenger.com)
