### ISSUE TITLE
Request: Event Reminder

### ISSUE THREAD

**Issue by bearbear12345** [Schmavery/facebook-chat-api#356]
instead of having to type place holder text "event tomorrow 1234567" to get the "set event reminder" button, I'd like an api function which could do the same! 

like args would be time,  date,  title,  threadid

**Comment by Schmavery** [comment]
I'm not sure I understand what the function you want does.  Does it just send a message with a certain format?  If so, it seems like it would be a one-liner in whatever program you're writing.
If there's another functionality in the web that lets you set events, then we would probably be happy to accept this as a PR :)  Let us know if we can help.

**Comment by bearbear12345** [comment]
refer to the attached image 

![screenshot_2016-11-19-06-45-14](https://cloud.githubusercontent.com/assets/1159091/20444236/577bddee-ae24-11e6-9c92-552ca6a51499.png)

basically it does a call to somewhere to create the event reminder

**Comment by bearbear12345** [comment]
result - > ![screenshot_2016-11-19-06-51-25](https://cloud.githubusercontent.com/assets/1159091/20444494/609a0d46-ae25-11e6-8532-6968053fefa0.png)

**Comment by Schmavery** [comment]
I think I understand the concept of event reminders.  I'm still unsure of what this does.  Does it create the button, send a message, or automatically click the "set event reminder" button?
It looks like these are phone screenshots.  As usual, any actions that can only be performed on a phone cannot be performed by the api.  In order to write an api function, we need to be able to perform the action in the browser, either on facebook.com or messenger.com.

**Comment by bearbear12345** [comment]
The rundown of event reminders is... 
Person 1 talks to person 2 with a message, facebook messenger detects some sort of time present in the message and offers a button to create an event reminder in that chat thread. 
Upon creations the time, date, name, going/not going status can be changed.

--

I've tried debugging via Fiddler but getting no results here

**Comment by Schmavery** [comment]
I can see how this works on mobile, I still can't make it work in the web client.
I still don't understand if you want an api function to make this button appear, or an api function to click this button.

**Comment by GAMELASTER** [comment]
I tried many times to sniff real Messenger app packets, never has been successful, mainly because missing the decoding key for HTTPS communication, but not sure if it's using a HTTPS

**Comment by bearbear12345** [comment]
I want an API function to basically click the button (regardless of it appearing or not)
So basically aim of this function is to automate the creation of an event reminder, I was assuming through some HTTP POSTs or similar.. 

Because sometimes when I need an event reminder it doesn't appear, and I have to write some dummy text like "Let's meet up tomorrow at 9:30am", in order to click it, which slows down my workflow

**Comment by Schmavery** [comment]
As @GAMELASTER said, it's much harder to copy functionality from the app, so one way or another, we're going to unfortunately have to leave this issue until it is possible to do in the web.
Personally, I don't think it's worth exposing an api function that could be a one-liner in the user code (sending a formatted message).  Functionality to click the button, I could imagine adding.
Feel free to reopen this as soon as it's possible to do in the web.  Thanks guys! @bearbear12345
