### ISSUE TITLE
Attachments sometimes returned as 'error'

### ISSUE THREAD

**Issue by Weetbix** [Schmavery/facebook-chat-api#357]
Looks like sometimes when fetching message history, the facebook api will return an error for one of the attachments in a message, which throws an error in the api here: 
https://github.com/Schmavery/facebook-chat-api/blob/master/utils.js#L338 

This is the contents of the stringified attachment: `{"attach_type":"error"}`

I am consistently returned about 17 of these while fetching ~72,000 messages, although a week ago fetching the same messages didn't return any errored attachments.

IMO it would be better for the API to gracefully continue without throwing an error, potentially removing the attachment from the message (or keep it).

**Comment by Schmavery** [comment]
Hmm yes, this would definitely be good to strip out.  There are a number of issues (#313),  open right now requiring us to clean up the results from getThreadHistory.  Unfortunately we haven't had the time to address these, but if someone wanted to take this on (even a small amount of progress is super helpful!) we would be glad to help and very grateful.
