### ISSUE TITLE
Support for bypassing catch-all error handler

### ISSUE THREAD

**Issue by LINKIWI** [Schmavery/facebook-chat-api#358]
In [`listen.js:213`](https://github.com/Schmavery/facebook-chat-api/blob/bcaeb9a16015d1c1e9591c87adac7bba0d4a992c/src/listen.js#L213), there is a global-level `catch` on all exceptions thrown in the `api.listen` callback.

```js
.catch(function(err) {
      if (err.code === 'ETIMEDOUT') {
        log.info("Suppressed timeout error.");
      } else {
        log.error("ERROR in listen --> ", err);
        globalCallback(err);
      }
      if (currentlyRunning) {
        currentlyRunning = setTimeout(listen, Math.random() * 200 + 50);
      }
});
```

Is there any support for bypassing this handler and re-throwing the exception, to allow logic higher up the stack to handle it? My implementation has several layers of complex logic contained with the `listen` callback, and there are legitimate cases for which the exception should be allowed to be thrown at the `listen` callback level. Instead, all exceptions get caught *inside* `listen()`.

**Comment by bsansouci** [comment]
Hey @LINKIWI, errors have definitely been an issue for us. What you seem to be asking is if we can propagate the error/exception up, is that right? If so, the callback (here `globalCallback`) receives as its first parameter the error, so you can whatever you want with it.

**Comment by Schmavery** [comment]
Why can't you handle this exception inside the listen callback?  I'd be interested in seeing a simplified example of one of these legitimate cases.  I think that would help us understand what your problem is.

**Comment by LINKIWI** [comment]
> What you seem to be asking is if we can propagate the error/exception up, is that right? If so, the callback (here globalCallback) receives as its first parameter the error, so you can whatever you want with it.

Totally my bad, I completely missed that the exception is propagated back up through the `globalCallback`. This is what I'm looking for--thanks!

**Comment by Schmavery** [comment]
😄
