### ISSUE TITLE
Is it possible to listen to thread emoji changes?

### ISSUE THREAD

**Issue by addobandre** [Schmavery/facebook-chat-api#361]
api.listen() does not appear to capture these events (even with selfListen and listenEvents enabled). Is there any way to do this?

**Comment by Schmavery** [comment]
Hey @addobandre ! I think would be a great first problem for someone to solve.  It shouldn't be too hard, just print to the console here https://github.com/Schmavery/facebook-chat-api/blob/master/src/listen.js#L44 and see if any message gets sent when the emoji changes.  Then all you have to do is reformat the event and return it.  Give it a shot! We'd love to help.

**Comment by addobandre** [comment]
Got it: it's a "delta" event (type: "change_thread_icon").

Since it's a bit late here in Portugal I'll work on a PR tomorrow.
In the meantime, please give some feedback on what I'm thinking for the event structure
```javascript
{
  type: "change_thread_icon",
  threadIcon: m.delta.messageMetadata.untypedData.thread_icon
  // The following parameters seem to be standard
  // extracted using the same code from formatDeltaMessage(m) in utils.js (line 352)
  // https://github.com/Schmavery/facebook-chat-api/blob/master/utils.js#L352
  threadID: string,
  messageID: string,
  senderID: string,
  timestamp: string,
  isGroup: boolean
}
```

As you can see, most of the parameters are the same as those found in formatDeltaMessage(m): should I split that function into a general-purpose "delta" event formatter and specialty "message" and "change_thread_icon" function? Something like `formatDeltaBase(m)` returning an object with all the "basic" fields, that would get populated inside `formatDeltaMessage(m)` and `formatDeltaThreadIconChange(m)`.
Or just merge everything into `formatDeltaMessage(m)`?

**Comment by Schmavery** [comment]
This looks fine @addobandre, feel free to implement however makes the most sense and we will merge or make comments accordingly :) :)

**Comment by addobandre** [comment]
PR #369 fixes this

**Comment by Schmavery** [comment]
Awesome

**Comment by bsansouci** [comment]
Merged that PR
