### ISSUE TITLE
updatePresence returning 'undefined' for 'statuses' field

### ISSUE THREAD

**Issue by lyneca** [Schmavery/facebook-chat-api#362]
With the `updatePresence` option on, `api.listen()` returns the following when a user comes online:

```
{ type: 'presence',
  timestamp: [timestamp],
  userID: '[user ID]',
  statuses: undefined }
```

when [in the docs](https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#presence) it says that it should return
>An object with the following fields: fbAppStatus, messengerStatus, otherStatus, status and webStatus. All can contain any of the following values: "active", "idle", "invisible", "offline".

Is this a bug, am I doing something wrong, or is it just FBM being frivolous?

**Comment by lyneca** [comment]
I think the error is at [line 651](https://github.com/Schmavery/facebook-chat-api/blob/master/utils.js#L651) of `utils.js`.

```js
function formatPresence(presence, userID) {
  return {
    type: "presence",
    timestamp: presence.la * 1000,
    userID: userID,
    statuses: presence.a // <--
  };
}
```
I did some snooping in the messenger.com and facebook.com requests and there isn't a `p` key in the presence response for the numbers - only a numeric `a` key which I believe is 0 for active and 2 for idle/away. I haven't tested it yet though, mostly because I don't know how to test local changes to node.js packages 😛 

Here's a response I got when someone became online:
`for (;;); {"t":"msg","seq":3139,"u":[user id],"ms":[{"overlay":{"[user id]":{"la":1482908493,"vc":10,"s":"push","a":2}},"type":"buddylist_overlay"}]}`

And here's one I got when someone went idle (after five minutes):
`for (;;); {"t":"msg","seq":3160,"u":[user id],"ms":[{"overlay":{"[user id]":{"la":1482908493,"vc":10,"s":"push","a":0}},"type":"buddylist_overlay"}]}`

**Comment by lyneca** [comment]
It looks like facebook no longer sends seperate data for 'active on facebook.com', 'active on messenger.com', 'active on mobile' etc and just combines them into a single 'is user active parameter'.

**Comment by lyneca** [comment]
yep that fixed it, I'll send a pull request with an update for the docs.

**Comment by ALiangLiang** [comment]
Excuse me. What is 'presence.a' means? It's ever seen 0 and 2. :)
