### ISSUE TITLE
Not able to login

### ISSUE THREAD

**Issue by shabnambanu1234** [Schmavery/facebook-chat-api#365]
Hi,

    Using your APIs I am trying to login to my fb account from a python script but I am not able to login . Does this API still works? Here is my code:

import fbchat

client = fbchat.Client("100014895393956", "***********")  // password hidden before pasting here

Thanks,
Shabnam

**Comment by GAMELASTER** [comment]
This is JavaScript API.
Send your Issue here:
https://github.com/carpedm20/fbchat

**Comment by shabnambanu1234** [comment]
Sorry yes I pasted here by mistake .

**Comment by Schmavery** [comment]
👍
