### ISSUE TITLE
changeThreadColor() callback parameter listed as optional, but errors out if not included

### ISSUE THREAD

**Issue by AstroCB** [Schmavery/facebook-chat-api#366]
According to the docs, the `callback` parameter for [`changeThreadColor()`](https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#apichangethreadcolorcolor-threadid-callback) is optional, but it throws a whole mess of errors if not included.

**Comment by Schmavery** [comment]
Looks like you're right, thanks for catching this.  Any chance you want to submit a PR it to be properly optional?  We offer lots of emoji hearts in return.

**Comment by AstroCB** [comment]
Sure! #367
