### ISSUE TITLE
How could you use request module instead of zombie?

### ISSUE THREAD

**Issue by tpphu** [Schmavery/facebook-chat-api#37]
Hi,
I see in your project you choose request module to request to Facebook, and I know you have to handle a lot of issues about: cookie, parse form etc...
Why do you not use zombie for?

**Comment by bsansouci** [comment]
Hey, by zombie do you mean this: http://zombie.js.org/? It looks like a framework for testing, not sure why we'd use that. Maybe you meant phantomjs: http://phantomjs.org/
Mainly we wanted to learn how Facebook was doing it's thing. We also didn't really want to depend on such a huge library. We'll give it another look.

**Comment by Schmavery** [comment]
I think he meant this: https://www.npmjs.com/package/zombie
There's a lot of stuff that happens on facebook that has nothing to do with chat.  The way we handled it, we explicitly only make the calls we need to make.  The idea was to keep the API fairly light-weight.  We may or may not have succeeded.  Like @bsansouci said, we also wanted to get a better understanding for exactly what is happening.

**Comment by Schmavery** [comment]
I'm closing this because it doesn't appear to be an actual issue... more a curious inquiry.  Feel free to continue discussion. :)

**Comment by bsansouci** [comment]
@schmavery It's the same package ;)

**Comment by tpphu** [comment]
Thank you, I really appreciate your answers, I know it not actually a issues, I just don't understand everything.
One more again, Thank so much for your answers.
