### ISSUE TITLE
doesn't run on react-native

### ISSUE THREAD

**Issue by uragecz** [Schmavery/facebook-chat-api#371]
I am trying to work with this api with react-native, but after import - `var login = require("facebook-chat-api"); `i am getting error 
![1](https://cloud.githubusercontent.com/assets/15018124/21766525/5727f396-d66f-11e6-8eb1-3c4ab66046b7.PNG)
![2](https://cloud.githubusercontent.com/assets/15018124/21766530/5bdee160-d66f-11e6-868e-b734f5545c29.PNG)
I tried clean installation again, but same error, any experiences with this error?

**Comment by uragecz** [comment]
So i fixed this error message by setting debug mode on, but now i am getting new error 
![3](https://cloud.githubusercontent.com/assets/15018124/21767178/cd3a2fec-d672-11e6-8990-8518f14b944d.PNG)

**Comment by Schmavery** [comment]
Unfortunately I don't know much about how RN works on Android and I don't see any reference to our code in those errors.  That line shouldn't even run any of our code, technically.  Do other npm modules work when you include them like that?

**Comment by uragecz** [comment]
Yes, other modules works fine, just this throws error :/

**Comment by Schmavery** [comment]
Ohhhh, it can't find the `fs` module.  I thiiink it's safe for me to remove that actually, I don't see any reference to it anymore in index.js...
