### ISSUE TITLE
Set up continuous integration testing

### ISSUE THREAD

**Issue by Schmavery** [Schmavery/facebook-chat-api#374]

**Comment by Schmavery** [comment]
Tried a while today to get his working using travis but facebook keeps seeing logins from strange locations and blocking the account.  Might try again later to get it working with cookies.

**Comment by Schmavery** [comment]
I'm not sure that there's a stable way to do this.  Shelving the idea for now.

**Comment by ravkr** [comment]
maybe using proxy/tunneling would help?

**Comment by Schmavery** [comment]
It might, but I didn't really have the time to look into it.
