### ISSUE TITLE
Guide me to get or post message to other url and get data back to facebook chat api

### ISSUE THREAD

**Issue by xmannv** [Schmavery/facebook-chat-api#375]
Hello,

I am a newcomer here and nodejs also, i really interested in this facebook chat api, but i tried to search and search and applied many cases about get and post from nodejs. But all failed, so can you guys show me the way to post from this chat api to an url and take data back. 

Thank you so much !

**Comment by Schmavery** [comment]
Do you know what a callback is?
This probably isn't the best place to get help for general node questions, but feel free to post the code you're trying to run and we can take a look.

**Comment by Schmavery** [comment]
I'm going to close this for now, feel free to reopen/comment with any more specific questions. 😄
