### ISSUE TITLE
Do api.changeThreadColor and api.changeNickname still work?

### ISSUE THREAD

**Issue by AlexCloudDev** [Schmavery/facebook-chat-api#378]
Hi,
i'm working on porting all functionalities of the facebook-chat-api to a Python fbchat api and everything works well, except these two functions(and likely api.changeThreadEmoji too).
I haven't tested the original functions in java so far and to narrow down the problem i want to ask:
Can anybody confirm they are working?
Thx

**Comment by AstroCB** [comment]
What kind of errors are you getting?

**Comment by AlexCloudDev** [comment]
Hi
I'm getting no error codes. 
The request my script creates and sends to the fb servers seems correct. The servers answer with an ok, like to the other requests (e.g. add user to chat..., which work), but the nickname/threadColor doesn't change. 
I guess it has something to do with the way this three specific functions, which affect manipulating group chats and were added afterwards, are treat differently by using the messenger URL in contrast to the other requests using the fb URL.

Either this three functions are handled differently and my implementation doesn't take this in consideration or the java functions are also broken because of an fb update or never worked at all.
Idk 
Thx for contributing

**Comment by Schmavery** [comment]
@AstroCB are these functions working for you?
@AlexCloudDev sorry, I keep forgetting to test this on my machine that has the tests set up (on mobile now).  I'd suggest you install the api and test manually on your own facebook account.  This will be the most accurate test of functionality (as it sometimes depends on the account used).

**Comment by AstroCB** [comment]
@Schmavery Yes, they're working fine for me.

**Comment by Schmavery** [comment]
@AstroCB thanks!
I'll close this since it technically answers @AlexCloudDev's question.  Feel free to follow up with any more relevant comments/questions!

**Comment by AlexCloudDev** [comment]
Ok, thx for confirmation. I have to take a closer look into my code.

**Comment by Schmavery** [comment]
@AlexCloudDev I'd still suggest trying the api with your facebook account if you continue to have problems.  Sometimes Facebook rolls out a change slowly so it will work for one account and not another.
