### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by bobland1** [Schmavery/facebook-chat-api#380]
Loving the work :) I have an issue how do i install this and run it? Also is it possible for me to ask on how to get the bot to do certain things

**Comment by bobland1** [comment]
I have linux with docker and docker compose

**Comment by Schmavery** [comment]
Hi @bobland1, are you having a specific issue with the instructions in [README.md](https://github.com/Schmavery/facebook-chat-api/blob/master/README.md)?

**Comment by bobland1** [comment]
Yeah, i run the line of code to install it installs how do i run it? Or how do i customize it? Like i want to have a very funny rude bot. So it will reply to people when they use certain keywords Like 'Bookey' or If they send a paragraph or a meme it will reply with something which i can customize and change

**Comment by bobland1** [comment]
Instead of using #commands to make it say something. Thanks

**Comment by Schmavery** [comment]
This api might not be the sort of thing you're looking for.  In order to use it, you'll need to know how to write javascript.  The api just gives you the ability to listen and send messages from the account that it is logged in as.  All other functionality you'll have to write yourself.

**Comment by bobland1** [comment]
I know some but not all ahah. Would you be able to help me?

**Comment by Schmavery** [comment]
We're always willing to help solve problems with the api, but you'll have to be willing to do some reading of the docs yourself if you want to learn the fastest 😉 
I would suggest starting with trying to get the example code (from the top of the README) running.  That should give you most of the building blocks you'll need to get started.

**Comment by bobland1** [comment]
Okay thanks anyway man :)

- Dan

On 30 Jan 2017, at 20:32, Avery Morin <notifications@github.com<mailto:notifications@github.com>> wrote:


We're always willing to help solve problems with the api, but you'll have to be willing to do some reading of the docs yourself if you want to learn the fastest ?
I would suggest starting with trying to get the example code (from the top of the README) running. That should give you most of the building blocks you'll need to get started.

-

**Comment by bobland1** [comment]
Any API which would help with what I want? And how hard is it to do? I'm currently using Botyo and that works great editing that would probably be he best idea right? If so how :D thanks again

**Comment by Schmavery** [comment]
Ahh.. maybe it is better to ask these questions on the Botyo repo.  I can't answer any questions about how Botyo works.
If you have any questions about the documentation for this api, please feel free to ask.
