### ISSUE TITLE
Add polls?

### ISSUE THREAD

**Issue by AstroCB** [Schmavery/facebook-chat-api#381]
Looks like Facebook added polls to desktop Messenger; would it be possible to add them to the API?

Not too sure how adding new features works.

**Comment by GAMELASTER** [comment]
Polls?

**Comment by Schmavery** [comment]
Yes, I'd imagine it would be possible to add support for this and we would accept a PR with the change.
If you want to look into it, I'd suggest opening up your browser's dev tools and seeing which requests get made when you do various things with polls (creating them, adding answers, voting etc.).  Figuring out the right requests is the first step to implementing.

**Comment by GAMELASTER** [comment]
Sorry but still I don't get which pools? I don't see anything update on mine Messenger (probably not pushed for my country :-/ )

**Comment by AstroCB** [comment]
@GAMELASTER

<img width="313" alt="screen shot 2017-01-30 at 3 02 29 pm" src="https://cloud.githubusercontent.com/assets/6151790/22439317/27864860-e6fd-11e6-8e88-be7ef99f6427.png">

**Comment by GAMELASTER** [comment]
@AstroCB lol, I don't have polls or games, same on phone messenger...

**Comment by Schmavery** [comment]
Hopefully it rolls out to everyone soon!
