### ISSUE TITLE
Fix support for voice message attachments

### ISSUE THREAD

**Issue by Vinetos** [Schmavery/facebook-chat-api#383]
All in the title, is it possible to get a recorded voice message (in stream ? .waw ?)

**Comment by Schmavery** [comment]
You can test this by setting up an echo bot (like [here](https://github.com/Schmavery/facebook-chat-api#apilistencallback)) and seeing if there is any response from sending the bot a voice message.  You might want to add a default case to that switch statement just in case.
Unfortunately I'm on my phone right now so I can't test it for you 😝 

If I had to guess, there might be some tweaks necessary to make this work, as I don't think anyone else has needed this functionality yet.  Let us know how it goes!

**Comment by Vinetos** [comment]
OK thanks you, I'm on my phone too ^^ I'll try that tomorrow :P

**Comment by Vinetos** [comment]
Ok, for now, all audio's and image's messages are considered with body === undefined and attachments not empty. Now I have a problem: How to convert the object from attachments to send it with api.sendMessage ? (I'm sorry but I'm new on JS ^^)

Here's my code:
`login({email: "EMAIL", password: "PASSWORD"}, function callback(err, api) {
    if (err) return console.error(err);

    api.setOptions({listenEvents: true});

    var stopListening = api.listen(function (err, event) {
        if (err) return console.error(err);

        switch (event.type) {
            case "message":
                if (event.body === '/stop') {
                    api.sendMessage("Goodbye...", event.threadID);
                    return stopListening();
                }
                api.markAsRead(event.threadID, function (err) {
                    if (err) console.log(err);
                });
                if(event.attachments.length !== 0) {
                    // Has Attachments
                    var msg = {attachment: event.attachments};
                    api.sendMessage(msg, event.threadID);// Got error: { error: 'Attachment should be a readable stream and not Object.' }
                } else {
                    api.sendMessage(event.body, event.threadID);
                }
                break;
            case "event":
                console.log(event);
                break;
        }
    });
});`

**Comment by Schmavery** [comment]
I see.  Thanks for doing some great initial work to check this out.  Really appreciate the detail you put into your response.

It looks like I was right and this will take some tweaking to get working.  I  can see by the fact that the body is undefined while the type is 'message' that there's something a little wrong with how the attachment is being handled.  I'm not sure what the format of the attachment is, but it might be worth printing out to have a look.

As far as sending it, the attachments field expects a readable stream to a file or something similar.  I can imagine a couple of approaches here, including downloading the attachment and finding a way to convert it to a stream.

However, I would wonder if maybe it would be worth it/easier for us to implement support for forwarding messages and attachments.  It seems like this is what you're trying to do here?

**Comment by Vinetos** [comment]
Yes that's right. I think it will be a good thing. 
For now, I'll just trying to make an echo bot. After, I use redis.io to communicate with a Java application (I want to make a chatter not). NodeJS send thre body (or URL for image/audio) and receive a String. I'll be add some features like share picture so I think it's a good idea :)

**Comment by Vinetos** [comment]
He is how I verify if it's a audio message:
(It's very hard-coded x))
```javascript
var file = event.attachments[0];
                    if (file.type === 'file' && String(file.name).includes('.mp4') && file.url !== undefined)  ```

**Comment by Schmavery** [comment]
Awesome! So the the file you get is a url that points to the actual data, I guess.
I'd imagine as a workaround for now, you could download that file locally and then resend it using `sendMessage({attachment: file}, ...)` or something.  Otherwise this is probably related to #347

**Comment by bsansouci** [comment]
This is a great first task. I think the gist of it would be to check how FB manages sharing such an audio file by looking at the network tab when sharing a voice recording with another user (record a voice message, send it, then share it with someone else and look at the requests).
