### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by bobland1** [Schmavery/facebook-chat-api#385]
I'm making my own version of these now. Its working all fine apart from the send a message with an image i get an error when ever some one calls the keyword

It will error and crash

**Comment by bobland1** [comment]
Ayy don't worry I've fixed that issue now :) forgot to add require JS :) one thing I'd love to know is that if it is possible to make a self learning ai using this api

**Comment by bsansouci** [comment]
@bobland1 Hey Bob! Glad you fixed your issue.

This api allows you to receive and send messages, so you can do anything with the data that you receive. If you want to learn about how to make a self learning ai you should look into "unsupervised learning". It's a very broad topic of research nowadays and will require you to understand some mathematical concepts but nothing's unattainable :D.
If that scares you, you should look into "markov chains". You'll find some much simpler algorithms that take text as input and allow you generate some text as output. The generate text will most likely not be coherent but still be a lot of fun to play around with (and is very simple to implement).

If you make a bot you should most definitely share it here, we'll gladly add it to the list of projects that use this API.

**Comment by bobland1** [comment]
So are you saying I can implement Markov chains into this API? If so how?

**Comment by bobland1** [comment]
Also if I wanted to make a bot kick someone on a trigger word but then re add them 10 mins later how would I do that? 

Sorry for the questions just I'm very into stuff like this and love to know new things y'know

**Comment by Schmavery** [comment]
A lot of these questions have more to do with general coding than the api itself.  The api is simply designed to let you listen to messages and respond to them with text that you provide.  The text you provide is up to you to generate ;P
If you're into the idea of markov chains, I'd suggest doing some reading about them to understand how they work.  You could provide some text to "train" the markov chain, then have your code generate some text to send to the chat.  Hope that helps.
