### ISSUE TITLE
Error in markAsRead for Fan Pages (maybe due to a permissions issue?)

### ISSUE THREAD

**Issue by throoze** [Schmavery/facebook-chat-api#387]
Hi I'm getting the following error when executing `markAsRead`

```
ERR! Error in markAsRead { __ar: 1,
ERR! Error in markAsRead   __sf: 'i0',
ERR! Error in markAsRead   error: 1357031,
ERR! Error in markAsRead   errorSummary: 'Este contenido ya no está disponible',
ERR! Error in markAsRead   errorDescription: 'El contenido solicitado no puede mostrarse en este momento. Puede que no esté disponible, que el enlace que hayas pulsado haya caducado o que no tengas permiso para ver esta página.',
ERR! Error in markAsRead   payload: null,
ERR! Error in markAsRead   bootloadable: {},
ERR! Error in markAsRead   ixData: {},
ERR! Error in markAsRead   lid: '6382249397858049269' }
```

the code is very basic, as follows:

```
var stopListening = api.listen(function(err, event) {
        if(err) return console.error(err); 
        switch(event.type) {
			case "message":				
				api.markAsRead(event.threadID, function(err) {
					//if(err) console.log(err);
				});
				 // redirect the message to my app server
				break;
			case "event":
				console.log(event.type);
				break;
        }
    });
```

As expected, messages are not being marked as read, when I check the Fan Page messages board.

Is there any kind of permissions I need to give my Fan Page so the call to `markAsRead` don't return this errors? or should I be checking something somewhere else?

Thanks for your help!

**Comment by bsansouci** [comment]
Mmmh it could be that `markAsRead` is broken for pages. Can you reply to messages from the page?

**Comment by throoze** [comment]
Yes, I can send and receive messages normally, but I keep getting the same error for each message sent by a customer. Is there any chance that this can be fixed? Where should I look in the code for this? I don't have much knowledge about facebook API, but I could at least take a look at it. Thanks for your quick response!

**Comment by bsansouci** [comment]
I see. Try commenting this line https://github.com/Schmavery/facebook-chat-api/blob/11311dc41fd3b1f3ea4aac0f38056438fb0f62d9/src/markAsRead.js#L17 inside your `node_modules` and see if that changes anything.
If you open chrome, go to your page (where you see all of the messages you've received), open the dev console, then go to `network` tab (and hit record) you'll see all of the requests that the browser's sending. Log in with another account in another tab and send a message to the page.
Check the request that you make when you receive the message, you should see a URL like `https://www.facebook.com/ajax/mercury/change_read_status.php?dpr=2`. Click on it and look at the `form data` that is sent alongside the request and see if there's any difference between than and what we're sending in [markAsRead](https://github.com/Schmavery/facebook-chat-api/blob/11311dc41fd3b1f3ea4aac0f38056438fb0f62d9/src/markAsRead.js).

**Comment by throoze** [comment]
I'll do it when I have some free time (I hope this week). I first need to finish what I'm doing before the deadline xD. I'll let you know as soon as I've tested it.

**Comment by bsansouci** [comment]
Continue conversation in #500

**Comment by bsansouci** [comment]
Oh sorry this is for `markAsRead`. Let's not hijack the other conversation then.

Is this still happening?
