### ISSUE TITLE
api.changeThreadEmoji(emoji, threadID, [callback])

### ISSUE THREAD

**Issue by bobland1** [Schmavery/facebook-chat-api#388]
if (isInString(message, "bookey chatcolour ")) {
			var colour = message.body.toLowerCase().replace("bookey chatcolour ","");
			api.changeThreadColor(colour,message.ThreadID, function callback(err) {
        			if(err) return console.error(err);
    		});
}
I want to get it so it will get the hexcode after 'bookey chatcolour'

**Comment by Schmavery** [comment]
Does it work if you put in a test value for colour? like "#000000" or similar?
First step to debugging is always splitting the problem in two if possible :)  If we can figure out if your problem if in the api or in the input, then we only have to think half as hard!

**Comment by bobland1** [comment]
no it doesnt. Nothing happens. Bookey doesnt respond or anything

**Comment by Schmavery** [comment]
Interesting.  I'm assuming you're not getting an error printed to the console.
Is anyone else experiencing this?

**Comment by bobland1** [comment]
No error no, says null though and carrys on. I have typed it right havnt i

**Comment by Schmavery** [comment]
Oh, I just noticed that you typed "ThreadID" with a capital T.  Can you replace that with "threadID"?

**Comment by bobland1** [comment]
okay :) Ill try again with the hex code as well

**Comment by bobland1** [comment]
Okay that works! Thanks now i need it to change the #FFFFFF to what the user chose

**Comment by bobland1** [comment]
Oh dw. It works now! Thanks man :) sorry for any inconvenience

**Comment by bsansouci** [comment]
Glady to hear you've figured it out!
