### ISSUE TITLE
get users first name

### ISSUE THREAD

**Issue by bobland1** [Schmavery/facebook-chat-api#389]
```
var friend = api.getUserInfo(message.senderID, function(err, ret) {
		if(err) return console.error(err);
		for(var prop in ret) {
        		if(ret.hasOwnProperty(prop) && ret[prop].firstname) {
			   	api.sendMessage("test"+sender.firstname, message.threadID);
        		}
      		}
    	});
```
dont know why but when ever this is called it will will say the message and then "undefined" have i done something wrong

**Comment by Schmavery** [comment]
First off, be careful setting `friend` equal to the result of `getUserInfo`.  `getUserInfo` doesn't return anything directly.
Also, I don't see sender defined anywhere.. could that be the problem?

**Comment by bobland1** [comment]
I saw that as soon as I uploaded sorry I didn't correct and no it didn't fix it. When that was corrected it doesn't send a message at all. Ignores it if u will. 

Btw thank you so much for answering my concerns. Hope you arnt getting to fed up with me ahah. I'm just very new to Node.js. I'm willing btw if I could send my code privately for you to review it. It'll be nice to have some feedback on my progress

**Comment by Schmavery** [comment]
We're happy to help as we're able :smile: 
You should always be able to edit your comment/issue using the button in the top right.
What code do you have now that doesn't work?

**Comment by bobland1** [comment]
if (isInString(message, "bookey") {
var friend = api.getUserInfo(message.senderID, function(err, ret) {
if(err) return console.error(err);
		for(var prop in ret) {
        		if(ret.hasOwnProperty(prop) && ret[prop].firstname) {
			   	api.sendMessage("test"+sender.firstname, message.threadID);
        		}
      		}
});
}

**Comment by Schmavery** [comment]
By the way, surrounding your code snippet with ``` will make it format better.
I'm not sure what you're trying to do here.  As I said above, you shouldn't be assigning the result of getUserInfo to anything, because that function doesn't return anything.  The result of calling getUserInfo is set to `ret` in the callback you pass in.
Why are you iterating over the values of ret?  I would have expected code more like the following but again, I'm not sure what you're trying to achieve.
```
if (isInString(message, "bookey") {
api.getUserInfo(message.senderID, function(err, ret) {
    if(err) return console.error(err);
    api.sendMessage("test"+ret.firstname, message.threadID);
});
}
```

Edit: Ohhh.. I see you were trying to copy the code from the example.  In the example, we're passing in an _array_ of userIDs, so it returns us a mapping of userids to user objects.  Then we iterate through this to find all the users who have their birthday today, and send them a message.  I hope that helps you understand :)

**Comment by bobland1** [comment]
if (isInString(message, "bookey") {
api.getUserInfo(message.senderID, function(err, ret) {
    if(err) return console.error(err);
    api.sendMessage("test"+ret.firstname, message.threadID);
});
}

When using this i still get "test unidentified" as the message

**Comment by bobland1** [comment]
I want it to display "test" and lets say the name is alan it will display "test alan"

**Comment by Schmavery** [comment]
Maybe you can `console.log` the `ret` object before calling `sendMessage` to see what you're getting back from getUserInfo.  😄

**Comment by bobland1** [comment]
Yeah i see. It does work. All the ret stuff works. But if ret.firstName is called. The message would have undefined in the place the name should be

**Comment by Schmavery** [comment]
I'm just curious to see what fields are filled out for ret.
It's possible that `firstName` may have been broken by a change by facebook.

**Comment by bobland1** [comment]
maybe. In the log is does show that firstName: "alan". so im not sure

**Comment by bobland1** [comment]
if (isInString(message, "test")) {
        api.getUserInfo(message.senderID, function(err, ret) {
        if(err) return console.error(err);
        console.log(ret);
        api.sendMessage("test  FUCK YOU "+ret.firstName+".",message.threadID);
        });
        }

**Comment by Schmavery** [comment]
Hmm.. I find this pretty confusing. @bsansouci wanna take a second look?
I don't understand how you could be seeing a value for `firstName` when you `console.log(ret)` but have it be `undefined` when you use it in the next time.
Sorry this has been so tricky to debug!  That's just how it goes sometimes :smile:

**Comment by bobland1** [comment]
Yeah its okay mean i understand :)

**Comment by bobland1** [comment]
I'm gonna use JSON to see if that fixes the issue

**Comment by bobland1** [comment]
Another query though is how can I make it so there is a delay between messages so I can set an order. I thought sleep(1000) soul of worked but it delays them all for 1 second then sends them all at the same time

**Comment by bobland1** [comment]
Alsooo, sorry bout these questions btw, but have you removed the long and lat from searchthreadinfo?

**Comment by bobland1** [comment]
{ '100007819751912':
   { name: 'Dan Riddell',
     firstName: 'Dan',
     vanity: 'dan.riddell.503',
     thumbSrc: 'https://scontent.xx.fbcdn.net/v/t1.0-1/c4.7.32.32/p40x40/15726331_1841538386116802_6734879490065841193_n.jpg?oh=37aa8640ac814b6e31eea8e70a59a9d8&oe=5929F908',
     profileUrl: 'https://www.facebook.com/dan.riddell.503',
     gender: 2,
     type: 'friend',
     isFriend: true,
     isBirthday: false } }

This returns when i get console.log(ret)

If i do ret.firstName it returns undefined

**Comment by bobland1** [comment]
Oh thanks man! You've been a great help

**Comment by bobland1** [comment]
On the other queries I had what would you think would be the best route of action

**Comment by bobland1** [comment]
Don't worry fixed it ahah ;) thanks for your help. But with the long and lat thing is that still available or was it removed?

**Comment by Schmavery** [comment]
The best way to handle questions like that is by printing out the object you get from the api or checking the docs.  As far as I remember, information about location was removed from the api, but I could be wrong.
Going to close this now, glad we found the answer to your problem 😄
