### ISSUE TITLE
getThreadList return empty names

### ISSUE THREAD

**Issue by kamdz** [Schmavery/facebook-chat-api#390]
Hi, I have in my app this code: 
```javascript
app.post('/list', (request, response) => {
  login({appState: JSON.parse(request.body.appState) }, function callback (err, api) {
    if(err) return console.error(err);
    api.getThreadList(0, 10, 'inbox', function(err, arr) {
      if(err) return console.error(err);
      response.send(arr);
    });
  });
});
```
and it's return to me array with 10 elements, but most of them have property: `name: ""`. Only group threads have their names. Single threads with just one person doesn't have anything (even the name of this participant) that I can display on my front. What to do?

**Comment by kamdz** [comment]
Ok, I know where the problem is. Custom nicknames... I will try to fix it and then I will do pull request :)

**Comment by kamdz** [comment]
But, in case that thread is standard (no group, no custom names) it's still doesn't have any specific property to show :/

**Comment by Schmavery** [comment]
Isn't this field supposed to be for the name of the thread, not the name of the participants?  I guess in the case of a 1-person thread we could make this the name of the person you're chatting with, but that seems like more of an open question.  Maybe I'm misunderstanding the problem.

**Comment by kamdz** [comment]
Oh, I see. Check my pr now :)
