### ISSUE TITLE
No feedback when running

### ISSUE THREAD

**Issue by sgoldmann** [Schmavery/facebook-chat-api#392]
Hello everyone,

I just tried to run this api after installing ```npm``` and setting up all necessary login credentials. Unfortunately, when calling the script with ```npm test.js``` its not giving me any feedback. I just get a new line in command window.

Any advice from you?

Thanks.

**Comment by bobland1** [comment]
node test.js works

**Comment by Schmavery** [comment]
Soo does this work then?  If not feel free to comment/reopen.
