### ISSUE TITLE
Most attachment properties for photos are empty

### ISSUE THREAD

**Issue by AstroCB** [Schmavery/facebook-chat-api#393]
I've been working with attachments a little bit and for whatever reason, no matter what kind of images I send, the API seems to have most of the properties uninitialized.

Here's an example of what I'm getting from `message.attachments` in `listen`:
```js
{
    type: 'photo',
    name: 'image-1872259249684607',
    hiresUrl: undefined,
    thumbnailUrl: 'https://scontent.xx.fbcdn.net/v/t34.0-0/s100x100/{LONG_IMAGE_URL}',
    previewUrl: 'https://scontent.xx.fbcdn.net/v/t34.0-0/p280x280/{LONG_IMAGE_URL}',
    previewWidth: 670,
    previewHeight: 280,
    ID: '',
    filename: undefined,
    mimeType: undefined,
    url: undefined,
    width: undefined,
    height: undefined
}
```

As you can see, some pretty important properties are missing, like the full-size image URL/dimensions/filename. I'm not sure if this is an API issue or a Facebook issue, but it'd be nice to at least find a way to get the image URL and remove the others if they'll never be populated.

**Comment by Schmavery** [comment]
Is this fixed by #369? If that works I'll publish to npm so that everyone can get the fix automatically 😄

**Comment by AstroCB** [comment]
Ah, yes, it seems to. Thanks!

**Comment by Schmavery** [comment]
Awesome, I'll try to remember to publish shortly 😄

**Comment by AstroCB** [comment]
Sounds good!

**Comment by AstroCB** [comment]
Any idea when it'll be pushed?

**Comment by Schmavery** [comment]
Sorry guys, got sick last week and totally forgot about this.  I'll merge in the latest fixes to the docs and logging and publish today.

**Comment by AstroCB** [comment]
No worries! Hope you feel better.
