### ISSUE TITLE
it error please help

### ISSUE THREAD

**Issue by gameguardadmin** [Schmavery/facebook-chat-api#394]
ERR! Error in getUserInfo { error: 'JSON.parse error. Check the `detail` property on this error.',
ERR! Error in getUserInfo   detail:
ERR! Error in getUserInfo    SyntaxError: Unexpected token < in JSON at position 0
ERR! Error in getUserInfo        at JSON.parse (<anonymous>)
ERR! Error in getUserInfo        at C:\Users\GAMEGUARDADMIN\Desktop\new\node_modules\facebook-chat-api\utils.js:596:20
ERR! Error in getUserInfo        at tryCatcher (C:\Users\GAMEGUARDADMIN\Desktop\new\node_modules\bluebird\js\main\util.j
s:26:23)
ERR! Error in getUserInfo        at Function.Promise.attempt.Promise.try (C:\Users\GAMEGUARDADMIN\Desktop\new\node_modul
es\bluebird\js\main\method.js:31:24)
ERR! Error in getUserInfo        at C:\Users\GAMEGUARDADMIN\Desktop\new\node_modules\facebook-chat-api\utils.js:577:24
ERR! Error in getUserInfo        at tryCatcher (C:\Users\GAMEGUARDADMIN\Desktop\new\node_modules\bluebird\js\main\util.j
s:26:23)
ERR! Error in getUserInfo        at Promise._settlePromiseFromHandler (C:\Users\GAMEGUARDADMIN\Desktop\new\node_modules\
bluebird\js\main\promise.js:510:31)
ERR! Error in getUserInfo        at Promise._settlePromiseAt (C:\Users\GAMEGUARDADMIN\Desktop\new\node_modules\bluebird\
js\main\promise.js:584:18)
ERR! Error in getUserInfo        at Promise._settlePromises (C:\Users\GAMEGUARDADMIN\Desktop\new\node_modules\bluebird\j
s\main\promise.js:700:14)
ERR! Error in getUserInfo        at Async._drainQueue (C:\Users\GAMEGUARDADMIN\Desktop\new\node_modules\bluebird\js\main
\async.js:123:16)
ERR! Error in getUserInfo        at Async._drainQueues (C:\Users\GAMEGUARDADMIN\Desktop\new\node_modules\bluebird\js\mai
n\async.js:133:10)
ERR! Error in getUserInfo        at Immediate.Async.drainQueues (C:\Users\GAMEGUARDADMIN\Desktop\new\node_modules\bluebi
rd\js\main\async.js:15:14)
ERR! Error in getUserInfo        at runCallback (timers.js:651:20)
ERR! Error in getUserInfo        at tryOnImmediate (timers.js:624:5)
ERR! Error in getUserInfo        at processImmediate [as _immediateCallback] (timers.js:596:5),
ERR! Error in getUserInfo   res: '<html><head><title>Redirecting...</title><script>__DEV__=0;_script_path = "XChatUserIn
foAsyncController";var uri_re=/^(?:(?:[^:\\/?#]+):)?(?:\\/\\/(?:[^\\/?#]*))?([^?#]*)(?:\\?([^#]*))?(?:#(.*))?/,target_do
main=\'\';window.location.href.replace(uri_re,function(a,b,c,d){var e,f,g;e=f=b+(c?\'?\'+c:\'\');if(d){d=d.replace(/^(!|
%21)/,\'\');g=d.charAt(0);if(g==\'/\'||g==\'\\\\\')e=d.replace(/^[\\\\\\/]+/,\'/\');}if(e!=f){if(window._script_path)doc
ument.cookie="rdir="+window._script_path+"; path=/; domain="+window.location.hostname.replace(/^.*(\\.facebook\\..*)$/i,
\'$1\');window.location.replace(target_domain+e);}});</script><script type="text/javascript">/*<![CDATA[*/(function(){fu
nction si_cj(m){setTimeout(function(){new Image().src="https:\\/\\/error.facebook.com\\/common\\/scribe_endpoint.php?c=s
i_clickjacking&t=4367"+"&m="+m;},5000);}if(top!=self && !false){try{if(parent!=top){throw 1;}var si_cj_d=["apps.facebook
.com","apps.beta.facebook.com"];var href=top.location.href.toLowerCase();for(var i=0;i<si_cj_d.length;i++){if (href.inde
xOf(si_cj_d[i])>=0){throw 1;}}si_cj("3 https:\\/\\/www.facebook.com\\/");}catch(e){si_cj("1 \\thttps:\\/\\/www.facebook.
com\\/");window.document.write("\\u003Cstyle>body * {display:none !important;}\\u003C\\/style>\\u003Ca href=\\"#\\" oncl
ick=\\"top.location.href=window.location.href\\" style=\\"display:block !important;padding:10px\\">\\u0e44\\u0e1b\\u0e17
\\u0e35\\u0e48 Facebook.com\\u003C\\/a>");/*PcQqKbxR*/}}}())/*]]>*/</script><script>window.location.replace("https:\\/\\
/www.facebook.com\\/common\\/invalid_request.php?__req=3");</script><meta http-equiv="refresh" content="0;url=https://ww
w.facebook.com/common/invalid_request.php?__req=3" /></head><body></body></html>' }

**Comment by Schmavery** [comment]
Can you give any more information?  Code example that reproduces this bug?

**Comment by gameguardadmin** [comment]
I use code

```
var login = require("facebook-chat-api");

// Create simple echo bot
login({email: "FB_EMAIL", password: "FB_PASSWORD"}, function callback (err, api) {
    if(err) return console.error(err);

    api.listen(function callback(err, message) {
        api.sendMessage(message.body, message.threadID);
        console.log(message);
    });
});
```
[http://imgur.com/a/lCmnG](http://imgur.com/a/lCmnG)

**Comment by Schmavery** [comment]
Can you check the `err` value by doing something like this?  You could also print out `message` before calling `sendMessage` (which is the function that is throwing this error) to see what we're working with.
```
var login = require("facebook-chat-api");

// Create simple echo bot
login({email: "FB_EMAIL", password: "FB_PASSWORD"}, function callback (err, api) {
    if(err) return console.error(err);
    api.listen(function callback(err, message) {
        if(err) return console.error(err);
        console.log(message);
        api.sendMessage(message.body, message.threadID);
    });
});
```

We should probably tweak this in the docs @ravkr

**Comment by ravkr** [comment]
@Schmavery I'm not sure if there is anything to tweak there :/
we probably need to debug `api.getUserInfo`

**Comment by Schmavery** [comment]
I meant tweaking the examples to make sure they always check for `err` (maybe they already do).

**Comment by ravkr** [comment]
oh, I added error checks almost everywhere :smiley:

**Comment by gameguardadmin** [comment]
{ type: 'message',
  senderID: '100010670580537',
  body: 'test',
  threadID: '100010670580537',
  messageID: 'mid.1489515811000:3dd144f949',
  attachments: [],
  timestamp: '1489515811000',
  isGroup: false }
ERR! getUserInfo { error: 'JSON.parse error. Check the `detail` property on this error.
',
ERR! getUserInfo   detail:
ERR! getUserInfo    SyntaxError: Unexpected token < in JSON at position 0
ERR! getUserInfo        at Object.parse (native)
ERR! getUserInfo        at D:\pageofthailand\node_modules\facebook-chat-api\utils.js:59
6:20
ERR! getUserInfo        at tryCatcher (D:\pageofthailand\node_modules\bluebird\js\main\
util.js:26:23)
ERR! getUserInfo        at Function.Promise.attempt.Promise.try (D:\pageofthailand\node
_modules\bluebird\js\main\method.js:31:24)
ERR! getUserInfo        at D:\pageofthailand\node_modules\facebook-chat-api\utils.js:57
7:24
ERR! getUserInfo        at tryCatcher (D:\pageofthailand\node_modules\bluebird\js\main\
util.js:26:23)
ERR! getUserInfo        at Promise._settlePromiseFromHandler (D:\pageofthailand\node_mo
dules\bluebird\js\main\promise.js:510:31)
ERR! getUserInfo        at Promise._settlePromiseAt (D:\pageofthailand\node_modules\blu
ebird\js\main\promise.js:584:18)
ERR! getUserInfo        at Promise._settlePromises (D:\pageofthailand\node_modules\blue
bird\js\main\promise.js:700:14)
ERR! getUserInfo        at Async._drainQueue (D:\pageofthailand\node_modules\bluebird\j
s\main\async.js:123:16)
ERR! getUserInfo        at Async._drainQueues (D:\pageofthailand\node_modules\bluebird\
js\main\async.js:133:10)
ERR! getUserInfo        at Immediate.Async.drainQueues (D:\pageofthailand\node_modules\
bluebird\js\main\async.js:15:14)
ERR! getUserInfo        at runCallback (timers.js:651:20)
ERR! getUserInfo        at tryOnImmediate (timers.js:624:5)
ERR! getUserInfo        at processImmediate [as _immediateCallback] (timers.js:596:5),
ERR! getUserInfo   res: '<html><head><title>Redirecting...</title><script>__DEV__=0;_sc
ript_path = "XChatUserInfoAsyncController";var uri_re=/^(?:(?:[^:\\/?#]+):)?(?:\\/\\/(?
:[^\\/?#]*))?([^?#]*)(?:\\?([^#]*))?(?:#(.*))?/,target_domain=\'\';window.location.href
.replace(uri_re,function(a,b,c,d){var e,f,g;e=f=b+(c?\'?\'+c:\'\');if(d){d=d.replace(/^
(!|%21)/,\'\');g=d.charAt(0);if(g==\'/\'||g==\'\\\\\')e=d.replace(/^[\\\\\\/]+/,\'/\');
}if(e!=f){if(window._script_path)document.cookie="rdir="+window._script_path+"; path=/;
 domain="+window.location.hostname.replace(/^.*(\\.facebook\\..*)$/i,\'$1\');window.loc
ation.replace(target_domain+e);}});</script><script type="text/javascript">/*<![CDATA[*
/(function(){function si_cj(m){setTimeout(function(){new Image().src="https:\\/\\/error
.facebook.com\\/common\\/scribe_endpoint.php?c=si_clickjacking&t=3633"+"&m="+m;},5000);
}if(top!=self && !false){try{if(parent!=top){throw 1;}var si_cj_d=["apps.facebook.com",
"apps.beta.facebook.com"];var href=top.location.href.toLowerCase();for(var i=0;i<si_cj_
d.length;i++){if (href.indexOf(si_cj_d[i])>=0){throw 1;}}si_cj("3 https:\\/\\/www.faceb
ook.com\\/");}catch(e){si_cj("1 \\thttps:\\/\\/www.facebook.com\\/");window.document.wr
ite("\\u003Cstyle>body * {display:none !important;}\\u003C\\/style>\\u003Ca href=\\"#\\
" onclick=\\"top.location.href=window.location.href\\" style=\\"display:block !importan
t;padding:10px\\">\\u0e44\\u0e1b\\u0e17\\u0e35\\u0e48 Facebook.com\\u003C\\/a>");/*fiNu
oLkK*/}}}())/*]]>*/</script><script>window.location.replace("https:\\/\\/www.facebook.c
om\\/common\\/invalid_request.php?__req=3");</script><meta http-equiv="refresh" content
="0;url=https://www.facebook.com/common/invalid_request.php?__req=3" /></head><body></b
ody></html>' }

[http://imgur.com/a/ezFUw](url)

**Comment by Schmavery** [comment]
Does this happen immediately after running the api or after some time?

**Comment by Schmavery** [comment]
You still having problems @gameguardadmin ?

**Comment by Schmavery** [comment]
Closing for now as this is a very generic error that is hard to reproduce without additional information.  Please feel free to follow up when you have time and I can always reopen the issue.
