### ISSUE TITLE
createPolls not a Function

### ISSUE THREAD

**Issue by nischkar** [Schmavery/facebook-chat-api#398]
Getting this message:
"TypeError: api.createPoll is not a function"

**Comment by AstroCB** [comment]
That function hasn't been pushed to npm yet, but it should be soon (#393).

**Comment by ravkr** [comment]
to test new features you can use:
```bash
npm install Schmavery/facebook-chat-api
```

**Comment by Schmavery** [comment]
Pushed 1.3.0 to npm! 🌮
