### ISSUE TITLE
Chat events

### ISSUE THREAD

**Issue by jackwilsdon** [Schmavery/facebook-chat-api#4]
Is it possible to extend the API to allow events to be listened for? By "events" I mean things like people joining/leaving a chat, chat title changing, etc.

**Comment by Schmavery** [comment]
Hey Jack, we're looking into this (between exams!).  Definitely functionality we consider worth adding.  Are you trying to build something in particular with these features?

**Comment by bsansouci** [comment]
Hey @jackwilsdon, sorry it took so long but here it is finally. Just do `api.setOptions({listenEvents: true})` before calling api.listen. This will make api.listen receive events and message, which can be differentiated with their `type` field.

Let us know if you need any more help.
