### ISSUE TITLE
Message payload doesn't contain buttons data when there is only one card

### ISSUE THREAD

**Issue by noamshemesh** [Schmavery/facebook-chat-api#402]
Thanks for a great library!

I'm trying on version 1.2.0, to fetch buttons from an attachment that I receive from a bot.  In the attachment (see below) there are 3 buttons but I can only get the title "search engines"

This is partial payload from this library:
```javascript
{ ...
  attachments:
   [ { ...
       type: 'share',
       source: 'Page - testing',
       title: 'search engines',
   } ],
  ...
}
```

This is the attachment:
![image](https://cloud.githubusercontent.com/assets/5119937/22930703/448e3eda-f2ca-11e6-8acf-6ebfdd8abcc0.png)

When I'm sniffing facebook chat network I can see that the buttons are part of `call_to_actions` property under an `attachments[0]/mercury/share/target/items[0]` - item with the property `name: "search engines"`

When a bot sends me more than one attachment ("carousel"), I can see the subattachments with relevant details (including buttons)

I'm using the library https://github.com/bluejamesbond/FacebookMessengerBot.js and one of its examples as the bot

**Comment by Schmavery** [comment]
Interesting.  You're saying we're not properly exposing the attachments in this case?  Afaik no one has ever looked into supporting buttons.

**Comment by noamshemesh** [comment]
Thanks for the response.
It looks like a simple conversion that fails from the browser network data to the exposed data.

Please let me know if you're planning to work on this, if not I will take a look next week to fix it

**Comment by Schmavery** [comment]
I'm pretty busy these days so it would be awesome if you could look into it when you get a chance.  Let me know if I can help in any way.
