### ISSUE TITLE
Disconnects with 502

### ISSUE THREAD

**Issue by waecoo** [Schmavery/facebook-chat-api#405]
It works fine for about a day and disconnects with status code 400. After disconnect api looses connection and doesn't reconnect. 

How can I handle with error and reconnect automatically?

info listen Got answer in 8410
info listen Got answer in 50347
WARN parseAndCheckLogin Got status code 502 retrying...
ERR! listen Error: parseAndCheckLogin got status code: 400. Bailing out of trying to parse response.
ERR! listen     at /home/dimach/tools/node_modules/facebook-chat-api/utils.js:592:42
ERR! listen     at tryCatcher (/home/dimach/tools/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
ERR! listen     at Function.Promise.attempt.Promise.try (/home/dimach/tools/node_modules/facebook-chat-api/node_modules/bluebird/js/main/method.js:31:24)
ERR! listen     at /home/dimach/tools/node_modules/facebook-chat-api/utils.js:577:24
ERR! listen     at tryCatcher (/home/dimach/tools/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
ERR! listen     at Promise._settlePromiseFromHandler (/home/dimach/tools/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:510:31)
ERR! listen     at Promise._settlePromiseAt (/home/dimach/tools/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:584:18)
ERR! listen     at Promise._settlePromises (/home/dimach/tools/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:700:14)
ERR! listen     at Async._drainQueue (/home/dimach/tools/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:123:16)
ERR! listen     at Async._drainQueues (/home/dimach/tools/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:133:10)
ERR! listen     at Immediate.Async.drainQueues (/home/dimach/tools/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)
ERR! listen     at runCallback (timers.js:649:20)
ERR! listen     at tryOnImmediate (timers.js:622:5)
ERR! listen     at processImmediate [as _immediateCallback] (timers.js:594:5)
ERR! listen  Error: parseAndCheckLogin got status code: 400. Bailing out of trying to parse response.
ERR! listen     at /home/dimach/tools/node_modules/facebook-chat-api/utils.js:592:42
ERR! listen     at tryCatcher (/home/dimach/tools/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
ERR! listen     at Function.Promise.attempt.Promise.try (/home/dimach/tools/node_modules/facebook-chat-api/node_modules/bluebird/js/main/method.js:31:24)
ERR! listen     at /home/dimach/tools/node_modules/facebook-chat-api/utils.js:577:24
ERR! listen     at tryCatcher (/home/dimach/tools/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
ERR! listen     at Promise._settlePromiseFromHandler (/home/dimach/tools/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:510:31)
ERR! listen     at Promise._settlePromiseAt (/home/dimach/tools/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:584:18)
ERR! listen     at Promise._settlePromises (/home/dimach/tools/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:700:14)
ERR! listen     at Async._drainQueue (/home/dimach/tools/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:123:16)
ERR! listen     at Async._drainQueues (/home/dimach/tools/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:133:10)
ERR! listen     at Immediate.Async.drainQueues (/home/dimach/tools/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)
ERR! listen     at runCallback (timers.js:649:20)
ERR! listen     at tryOnImmediate (timers.js:622:5)
ERR! listen     at processImmediate [as _immediateCallback] (timers.js:594:5)
Unhandled rejection TypeError: Cannot read property 'senderID' of undefined
    at callback (/home/dimach/tools/bot.js:64:21)
    at /home/dimach/tools/node_modules/facebook-chat-api/src/listen.js:233:9
    at tryCatcher (/home/dimach/tools/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/dimach/tools/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/dimach/tools/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/dimach/tools/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/dimach/tools/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/dimach/tools/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/dimach/tools/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)

**Comment by Schmavery** [comment]
I'd imagine it's quite likely that this could be related to #202.

**Comment by Schmavery** [comment]
I'm going to close this so that we can track the single issue with #202.  If you think this could be a different issue, feel free to comment and I'll reopen it.
