### ISSUE TITLE
Getting the full size image URL for images received as thread history attachments

### ISSUE THREAD

**Issue by Dudelmoser** [Schmavery/facebook-chat-api#406]
Hey guys,

I'm finally done with my exams and working full time on my extended facebook messenger now - at least for a few weeks.

I can only find preview and thumbnail URLs in the attachments and I'm not sure how to resolve those URLs to one directing to the full size image.

Thanks in advance :)

**Comment by Schmavery** [comment]
Ahh, looks like #397 might be useful for you! @ivkos

**Comment by Dudelmoser** [comment]
Thanks a lot, I didn't notice the API got updated and therefore had empty ID properties etc. It would be great if you added that method to the start page docs. :)

**Comment by Schmavery** [comment]
It will be added to the docs as soon as it's merged, just waiting on a quick refactor.

**Comment by Schmavery** [comment]
@ivkos already wrote some docs here (that will be merged soon) if you didn't see those: https://github.com/ivkos/facebook-chat-api/blob/a02cf56aea30035ca7df2123fe7c058fd5cc44ab/DOCS.md#resolvePhotoUrl

**Comment by Dudelmoser** [comment]
Yes I saw those and used them to implement a photo viewer. I'm gonna test it as soon as the merge goes online..

**Comment by Schmavery** [comment]
Awesome, you can always sync to the PR branch to test but we'll try to get that merged soon

**Comment by Schmavery** [comment]
I just merged #397 😄

**Comment by Dudelmoser** [comment]
Thanks, you rock :)

**Comment by Schmavery** [comment]
Be sure to share what you make with us when it's ready, we can add a link to the readme :)
