### ISSUE TITLE
Creating new groups

### ISSUE THREAD

**Issue by jamesorlakin** [Schmavery/facebook-chat-api#407]
As far as I can work out there is no method to create a new Messenger group. I would assume the official Facebook client takes a list of participant IDs and a title and returns the new threadID (or perhaps refreshes the thread lists, with the new one being added into the UI there).

**Comment by Schmavery** [comment]
The current way to create a new group is to `sendMessage` to a group of people.  Sorry, this is perhaps poorly documented.
https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#sendMessage
The callback is an object containing the new threadID among other things.
```js
api.sendMessage('this is a new group', [id1, id2, id3], (err, msgInfo) => {
    console.log("My new threadID is " + msgInfo.threadID);
});
```

Does that do everything you need?  You can then set the title using [setTitle](https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#apisettitlenewtitle-threadid-callback).

**Comment by jamesorlakin** [comment]
Aah perfect! It wasn't obvious to me to look at the arguments closely for sendMessage, as I've always assumed that's only for existing groups or people. Thank you very much indeed.
