### ISSUE TITLE
Oauth Implemented

### ISSUE THREAD

**Issue by eaaliprantis** [Schmavery/facebook-chat-api#409]
Hello,

I was wondering if you were going to implement the token instead of username and password for logging in.

Thanks

**Comment by Schmavery** [comment]
Is it possible for you to be a little clearer? Afaik this isn't possible.  Remember, as the readme states, this api is not for the accessing the official chatbot api, this is for chatting as a user directly.

**Comment by eaaliprantis** [comment]
Oh, I apologize.  I thought that this was the facebook-chat-api that would handle either an actual account or a bot.

**Comment by Schmavery** [comment]
As far as I know, there isn't anything that will do both.  You can either use this (unofficial) api, which essentially pretends to log in as a regular facebook account, or attempt to use [this](https://developers.facebook.com/docs/messenger-platform) (official) api.  It all depends on your usecase.
Hope that helps!
