### ISSUE TITLE
getThreadHistory into a file, load into socket

### ISSUE THREAD

**Issue by troywingert21** [Schmavery/facebook-chat-api#410]
I'm having difficulty loading the return of getThreadHistory into a file use fs.writeFile so that I can send it as a packet to my client. I understand that it returns an object with a bunch of information, I just don't know how to split it up. I just want the messages listed in a file. Here is my code:

```javascript
api.getThreadHistory(event.threadID, 0, 5, null, function(err, history){
    if (err) throw err;

    for (var j = history.length - 2; j >= 0; j--){
        console.log(history[j]);
        fs.writeFile(fileName, history[j] + "\r\n", (err) => { //Writes retieved data to a file
            if(err) throw err;
            console.log('It\'s saved!');
        });
    }
    //console.log(event.body);
})
```

**Comment by Schmavery** [comment]
Sorry, I don't quite understand the problem.  What is the error?  Can you show an example of how it would work without using `getThreadHistory`?

**Comment by troywingert21** [comment]
I need to put the data from api.getThreadHistory into a .txt file.

**Comment by Schmavery** [comment]
Looks like you'll want to convert that object to a string of whatever representation you want.
I'd imagine `JSON.stringify` would be a good start.

I'm going to close this issue because it doesn't seem related to the api, but feel free to continue with your attempts to debug it here 😄
