### ISSUE TITLE
api.createPoll not working

### ISSUE THREAD

**Issue by tokelpl** [Schmavery/facebook-chat-api#411]
I have newest messenger and i only getting the message Bot created Poll: Example Poll and nothing more

**Comment by Schmavery** [comment]
Can you give any more info?
What code are you using the create the poll?
Can you provide a screenshot of what you see in the browser when the poll in created?

**Comment by GAMELASTER** [comment]
@Schmavery I don't think #412 fix this problem.

Some countries doesn't have already this "update". I have it here (Slovakia) same with message:
![image](https://cloud.githubusercontent.com/assets/1665373/23593548/93557ccc-0210-11e7-9f98-1ae6d0a0bd61.png)
Translate:
`User Natsumi-chan created poll: Example pool. Vote via mobile application.`

On phone Messenger:
![image](https://cloud.githubusercontent.com/assets/1665373/23593579/2581ade6-0211-11e7-8d1b-a792e3948598.png)
So there it is same, but without "Vote via mobile application" and without any poll.

**Comment by Schmavery** [comment]
Ah okay thanks @GAMELASTER, I guess some countries just don't support this yet :)
