### ISSUE TITLE
Messages with URLs failing to callback

### ISSUE THREAD

**Issue by ianw11** [Schmavery/facebook-chat-api#415]
I'm running into issues when messages include urls.  The symptom is that I'm not receiving a callback and I traced the issue all the way back to src/listen.js line 144 in that if messenger catches a link and then shows the preview pane the attach_type is 'share' instead of 'photo'.

For my usage, I don't need anything fancy, I just want the message body.  But I could imagine other people wanting other metadata about this share.

**Comment by ianw11** [comment]
After a little tinkering, I added this after line 151.  It works as far as I can tell

} else {
  globalCallback(null, utils.formatDeltaMessage(v));

**Comment by Schmavery** [comment]
Looks like some people ran into the same problem and used your solution, so thank you!  Do you think you could submit a quick PR with the fix?

**Comment by Schmavery** [comment]
@ianw11 Can you verify that this is fixed by #416?

**Comment by erdnaxeli** [comment]
Seems to be ok, I receive attachments of type "share".

**Comment by Schmavery** [comment]
woo, thanks @erdnaxeli

**Comment by erdnaxeli** [comment]
Maybe could we have a new release now this is fixed? :cat:

**Comment by GAMELASTER** [comment]
@erdnaxeli I think yes
