### ISSUE TITLE
Create Poll Error! Help Me Please :'(

### ISSUE THREAD

**Issue by Theblood** [Schmavery/facebook-chat-api#417]
Hello, I have an error implementing create poll, Here is the error log

`ERR! createPoll { __ar: 1,
ERR! createPoll   __sf: 'iw',
ERR! createPoll   payload:
ERR! createPoll    { status: 'failure',
ERR! createPoll      errorTitle: 'Error desconocido',
ERR! createPoll      errorMessage: 'Se produjo un error. Vuelve a intentarlo.',
ERR! createPoll      showUser: true },
ERR! createPoll   bootloadable: {},
ERR! createPoll   ixData: {},
ERR! createPoll   lid: '6395662424992233710' }
{ __ar: 1,
  __sf: 'iw',
  payload:
   { status: 'failure',
     errorTitle: 'Error desconocido',
     errorMessage: 'Se produjo un error. Vuelve a intentarlo.',
     showUser: true },
  bootloadable: {},
  ixData: {},
  lid: '6395662424992233710' }
`
And this is my code 

`var login = require("facebook-chat-api");

login({email: "USER", password: "PASS"}, (err, api) => {
    if(err) return console.error(err);

    api.listen((err, message) => {
        api.createPoll("Example Poll", message.threadID, {
        "Option 1": false,
        "Option 2": true
    }, (err) => {
        if(err) return console.error(err);
    });

    }, (err) => {
        if(err) return console.error(err);
    });
});`

# Please help me

**Comment by Schmavery** [comment]
Are you able to create a poll in the browser without using the api?

**Comment by Theblood** [comment]
@Schmavery Wow, then until it is activated in my profile you will not be able to use it, if that's how you could activate it?

**Comment by Schmavery** [comment]
If you can't use it in the browser, you can't use it in the api.  Sorry!  We have no control over this, it is facebook's decision to roll out functionality how they like.
