### ISSUE TITLE
Support to invite

### ISSUE THREAD

**Issue by Matheus-Garbelini** [Schmavery/facebook-chat-api#418]
Hello, there's a way to invite a given ID, so I could automatically start sending messages after isFriend from user info return true? This way i think its more flexible as the user don't need to send a friend request, nor the bot needs to accept the  invitation.

**Comment by Schmavery** [comment]
I don't totally understand this feature, maybe some screenshots of how to do it in the browser would help. Thanks 😄

**Comment by Matheus-Garbelini** [comment]
Sorry if I was not clear the first time. What I mean is that if is possible to add to friends list someone like this:
[https://img08.rl0.ru/9dc11e725b101d88d6cb46b94fe3f478/c1280x720/i.ytimg.com/vi/UVt0YwqWjM0/maxresdefault.jpg](url)

**Comment by Schmavery** [comment]
Thanks for clarifying, @Matheus-Garbelini!  Generally I try to keep this api focused on just chat-related functions, not general facebook stuff.
The bot should be able to accept message requests though, so you shouldn't need to be a friend just to talk to someone.

**Comment by Matheus-Garbelini** [comment]
@Schmavery thank you. I asked this because it was a little too hideous the place that i had to go when the bot is chatting with a non friend

**Comment by GAMELASTER** [comment]
@Matheus-Garbelini I wanted to do Facebook-API package, but it's really more complicated than chat (and chat is little complicated too).

**Comment by Schmavery** [comment]
I'm going to close this because the feature is outside the scope of the api, but please look into message requests if you run into problems here :)
