### ISSUE TITLE
Error: utils.formatDeltaReadReceipt is not a function

### ISSUE THREAD

**Issue by soczek98** [Schmavery/facebook-chat-api#419]
Given code:

    const fs = require("fs");
    const login = require("facebook-chat-api");

    // Simple echo bot. He'll repeat anything that you say.
    // Will stop when you say '/stop'

    login({appState: JSON.parse(fs.readFileSync('appstate.json', 'utf8'))}, (err, api) => {
        if(err) return console.error(err);

        api.setOptions({listenEvents: true});

        var stopListening = api.listen((err, event) => {
            if(err) return console.error(err);

            switch(event.type) {
                case "message":
                    if(event.body === '/stop') {
                        api.sendMessage("Goodbye...", event.threadID);
                        return stopListening();
                    }
                    api.markAsRead(event.threadID, (err) => {
                        if(err) console.log(err);
                    });
                    api.sendMessage("TEST BOT: " + event.body, event.threadID);
                    break;
                case "event":
                    console.log(event);
                    break;
            }
        });
    });

Throws an error:

    ERR! listen TypeError: utils.formatDeltaReadReceipt is not a function
    ERR! listen     at parsePackets (/home/pi/Sources/FBBot/node_modules/facebook-chat-api/src/listen.js:167:54)
    ERR! listen     at Array.forEach (native)
    ERR! listen     at /home/pi/Sources/FBBot/node_modules/facebook-chat-api/src/listen.js:107:12
    ERR! listen     at tryCatcher (/home/pi/Sources/FBBot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
    ERR! listen     at Promise._settlePromiseFromHandler (/home/pi/Sources/FBBot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:510:31)
    ERR! listen     at Promise._settlePromiseAt (/home/pi/Sources/FBBot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:584:18)
    ERR! listen     at Promise._settlePromises (/home/pi/Sources/FBBot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:700:14)
    ERR! listen     at Async._drainQueue (/home/pi/Sources/FBBot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:123:16)
    ERR! listen     at Async._drainQueues (/home/pi/Sources/FBBot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:133:10)
    ERR! listen     at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/Sources/FBBot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)
    ERR! listen     at processImmediate [as _immediateCallback] (timers.js:368:17)
    ERR! listen  [TypeError: utils.formatDeltaReadReceipt is not a function]
    [TypeError: utils.formatDeltaReadReceipt is not a function]

while I'm using the latest version from Github.

**Comment by GAMELASTER** [comment]
@bsansouci probably forgotten to add `formatDeltaReadReceipt` function to utils.js module.export.
If you want to fix this error, use NPM version, wait to fix or add this to [line 750](https://github.com/Schmavery/facebook-chat-api/blob/fa8a5cf4c66ff86a1c0f268705a394f3a5e2c587/utils.js#L750):
```js
formatDeltaReadReceipt: formatDeltaReadReceipt,
```

**Comment by Schmavery** [comment]
Gee thanks @GAMELASTER and @soczek98.  Can someone submit a quick PR?
