### ISSUE TITLE
Why this project do not use Zombie instead of request

### ISSUE THREAD

**Issue by tpphu** [Schmavery/facebook-chat-api#42]
When I read inside the code of this project, I don't understand one thing:
Why this project do not use Zombie instead of request?

**Comment by bsansouci** [comment]
Hey @tpphu, I think we were already talking about this here #37. I'm closing this issue because it's a duplicate of #37.

**Comment by tpphu** [comment]
Sorry, I don't know to use Github. Thank so much for your help.
