### ISSUE TITLE
Design Question - ThreadID

### ISSUE THREAD

**Issue by kabirvirji** [Schmavery/facebook-chat-api#422]
I'm making a bot script where when the user runs it, they can authenticate (with a Facebook account other than their own) and that account will act as the bot, and will send them a message. Something like this, 

> Enter the bot's username:
> Enter the bot's password:

However, to send them a message I need their FB thread ID, so I have an additional field that looks like,

> Enter YOUR Facebook ID:

This is so I am able to do things like so: <br>
Using [Conf](https://github.com/sindresorhus/conf) and [Inquirer](https://github.com/SBoudrias/Inquirer.js)

```
login({email: config.get('username'), password: config.get('password')}, function callback (err, api) {
    if(err) return console.error(err);
    var yourID = config.get('id');
    var msg = {body: "Hello world!"};
    api.sendMessage(msg, yourID);
});
```

Is there a better way to go about this? The user needs two Facebook account regardless (one for the bot, and one to send messages to the bot), but can I get the `Thread ID` just from an email or some other way? Seems a bit annoying for a user to have to look up their Facebook ID in their cookies. 

Let me know if you need any clarification, thanks!

**Comment by Schmavery** [comment]
What if you have the user send the bot a message? Then the id of that thread will be the user's id (from the bot's perspective).
Alternatively, I would also suggest trying out https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#getUserID

**Comment by kabirvirji** [comment]
Thanks for the reply, my goal is to do this from the command line. So I'm guessing having the user provide their user id is the only way to do that with a CLI app - unless I ask the user to send a message to the bot. 

So if I have the user send an initial message to the bot, how can I get the thread id from that interaction? What if more people send the bot a message?

**Comment by ravkr** [comment]
you can ask someone to give link to their profile and then extract username and using `api.getUserID` you will get their ID :smiley:

**Comment by kabirvirji** [comment]
@ravkr `getUserID` takes in the name, not profile link correct? So what if the search results that Facebook provides doesn't include my desired target as the first result (or first couple results)?

**Comment by Schmavery** [comment]
@kabirvirji unfortunately I still don't really understand the desired interaction between the user and the bot (and why there are 2 fb accounts etc) so I can't really answer your first questions.

It seems api.getUserID is designed for what you're trying to do, and if you have problems with that, we should look into those.  I think it just makes a call to a generic search endpoint, you might have success passing in an email or a username.

**Comment by kabirvirji** [comment]
@Schmavery Sorry, let me clarify a bit. 

I'm a making a Spotify Facebook Messenger bot wrapped in an npm package. People can message the bot and control their Spotify account through Facebook Messenger. 

Right now my interaction looks like this 

```
      $ singlespotify
      Enter your bot's Facebook username: mybot@gmail.com
      Enter your bot's Facebook password: **********
      Enter YOUR user id: 1301312
```

Using the facebook chat api the bot is logged in, and the bot knows where to send the first message because a user id was provided.

The reason I think that I need two Facebook accounts is because one is needed for the bot (to login, etc) and another is needed to message the bot (the account that is messaging the bot is the one that I need the thread id from, right?) 

Does this clarify my situation a bit? Let me know.

**Comment by bsansouci** [comment]
If having two accounts is an issue, you can get away with just one. You could make the user login with their own account and have them talk to themselves (which you can do). In order for this to work you need to enable it using `api.setOptions({selfListen: true})`. You will need to be careful to not enter infinite loops (a message from the bot triggers itself). You can pretty easily do that by checking if the message sent is part of the set of canned responses you give to people.

You don't need to ask for the user ID because you could use `api. getCurrentUserID` and compare with `message.threadID`. If they're equal, you know you're talking to yourself so you let the message through.

Hope that helps :D

**Comment by kabirvirji** [comment]
@bsansouci That's an interesting take on this, thanks for your response. 

How could I define the set of canned responses given what's available with this API? I'm thinking of only acting on messages that are of form `@spotify play <songname>` or `@spotify queue <songname>` 

However, take this sequence of messages for instance: (all messages to myself)

> Hi, my name is Spotify Bot     // initial message that the code sends to myself

> @spotify play *songname*   // my manual message to myself

> Sure, I'll play *songname*    // bot sends back this message 

So the message "Sure, I'll play *songname*" doesn't execute a command because it isn't in the form `@spotify play` or `@spotify queue` correct? Even though the bot will see it as something to potentially respond to.

**Comment by Schmavery** [comment]
@kabirvirji that sounds about right!  We've made bots that work like this in the past (using some command prefix).  You'll just make the bot look at the messages coming in and ignore everything that doesn't start a certain way.

**Comment by kabirvirji** [comment]
Cool! I'll try it that way since having a user create another fb account or find their thread id is a bit annoying. 

Thanks for all the help! I'll open another issue if I have any other questions 😊
