### ISSUE TITLE
Support for reactions

### ISSUE THREAD

**Issue by mangotec** [Schmavery/facebook-chat-api#424]
Messenger just added reactions, looking at the variables in the request it looks like it may be possible to use emojis other than the 7 that they give:

![image](https://cloud.githubusercontent.com/assets/20685777/24312014/97d01060-10ce-11e7-96da-ddf3015754f7.png)

**Comment by Schmavery** [comment]
Try it!  Would definitely be funny if we could support that.

**Comment by bsansouci** [comment]
Omg yes! That would be so much fun :) a PR that adds this will get lots of hearts!

**Comment by ravkr** [comment]
sadly, I don't have reactions yet :(

**Comment by GAMELASTER** [comment]
sadly, on slovakia reactions doesn't work, I can't implement it.
Please, implement it someone, I wanna try it :rofl:

**Comment by ravkr** [comment]
is there any way to "force" api to use some specific facebook server? maybe then it would be possible to use all new features instantly after their updates :(

**Comment by GAMELASTER** [comment]
@ravkr I don't think it's about Facebook Server. It's about scripts which Facebook send you.
For sample, in Messenger the feature is available before the officialy launched, but it's available only for some people.

**Comment by mangotec** [comment]
@GAMELASTER 
![image](https://cloud.githubusercontent.com/assets/20685777/24330779/e1e91e76-121d-11e7-8137-1c95a4c119d1.png)

**Comment by GAMELASTER** [comment]
@magnotec thank you, but now delete your image for security reasons

**Comment by Schmavery** [comment]
Merged!  Thanks guys.
