### ISSUE TITLE
TypeError in api.listen()

### ISSUE THREAD

**Issue by ravkr** [Schmavery/facebook-chat-api#426]
few days ago I started getting this error:
`[TypeError: Cannot read property 'otherUserFbId' of undefined]`

it happens after few hours of running this code:

```js
var stopListening = api.listen((err, event) => {
    if(err) return console.error(err); //    <- this line throws the error
    // ...rest of the code here...
}
```

also: the error is thrown all the time so I have to restart my script to use it again

It may be connected with some recent commits, because I am using the latest version from Github and it has never happened before.

**Comment by GAMELASTER** [comment]
huh, probably your "facebook api" version is different than this library works on.
I have updates of Messenger really late, my bot works nonstop running on latest library, and I don't have any issues already.

**Comment by Schmavery** [comment]
Is there a longer stacktrace for this error?  It would be nice if we could see the actual message received from facebook right before it crashes.  Can you enable verbose logging and show us what you get right before you fail?
```
api.setOptions({
    logLevel: "verbose"
});
```

**Comment by Schmavery** [comment]
Wow.  Looks like switch fallthrough here: https://github.com/Schmavery/facebook-chat-api/blob/fa8a5cf4c66ff86a1c0f268705a394f3a5e2c587/src/listen.js#L165
Classic.  @bsansouci will fix it.

Thanks for helping debug @ravkr

**Comment by bsansouci** [comment]
Can you pull from master and try again, this commit might fix this issue: https://github.com/Schmavery/facebook-chat-api/commit/b943eb6cfc6b9f4666fe35e743928f9aac3dbdad

**Comment by bsansouci** [comment]
It seems like the object is from a page trying to change the thread's name? Is that correct? (Just looking at `AdminTextMessage` and then `change_thread_nickname`

**Comment by Schmavery** [comment]
@bsansouci The old code used to fall through (for better or worse) to the generic utils.formatEvent function at the bottom of the switch.  Move the ReadReceipt case to the top and break after it (or very carefully refactor and test).

**Comment by Schmavery** [comment]
I believe https://github.com/Schmavery/facebook-chat-api/commit/d33a24306d47fb607bb822d33d6a32a5f86b3318 will fix this.  Can you confirm @ravkr ?

**Comment by ravkr** [comment]
I'll pull it in a minute and I will let you know if it crashes (or not)

**Comment by ravkr** [comment]
No errors after 3 hours... It seems to be fixed now :D Thanks!

**Comment by Schmavery** [comment]
Yay!
