### ISSUE TITLE
threadinfo.emoji is null?

### ISSUE THREAD

**Issue by y9y9l5m6** [Schmavery/facebook-chat-api#430]
i used the api.getThreadInfo method and the callback info array's emoji object is null. How do I use the group emoji?

**Comment by ravkr** [comment]
If emoji is null it means it is not set (so you have just that blue like button)

**Comment by Schmavery** [comment]
Does that help @y9y9l5m6?  The docs [here](https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#apigetthreadinfothreadid-callback) say that if the value is null, there is nothing custom set for that thread.
