### ISSUE TITLE
how to send emoji as message?

### ISSUE THREAD

**Issue by y9y9l5m6** [Schmavery/facebook-chat-api#431]
when I try to send emoji as message, node js doesn't recognize the special character. what should I do?

**Comment by kabirvirji** [comment]
How are you sending the message? 

I'm on node v7+ on a mac and sending a message like this works for me: 
```
api.sendMessage(`Playing ${songname} 😊`, message.threadID); 
```

There are some emojis on mac that are not supported in fb chat, which emojis are you trying to use?

**Comment by y9y9l5m6** [comment]
i just put the emoji, what does playing ${songname} do? maybe because im on version 6.10

**Comment by Schmavery** [comment]
@y9y9l5m6 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

**Comment by kabirvirji** [comment]
@y9y9l5m6 That's just an example of my code from a music bot thats working. Some more information would be helpful in debugging this such as: 

- how you're sending the message
- what emoji you're trying to send
- your operating system 
- any specific errors you're getting

**Comment by y9y9l5m6** [comment]
thank you

**Comment by Schmavery** [comment]
@y9y9l5m6 is it working for you now?

**Comment by y9y9l5m6** [comment]
yes thank you!
