### ISSUE TITLE
Message Pin Protection

### ISSUE THREAD

**Issue by GAMELASTER** [Schmavery/facebook-chat-api#433]
This is not issue at all, but just adding as Issue for remember in future use.
Situation:
In pull requests there is new type of classes, "Client payload". It's kind of simply encrypted JSON, which contains of course, client's payload. For now, it's contains most of time the add/change of reaction, but I found an interesting piece of code at Client payload parsing:
![image](https://cloud.githubusercontent.com/assets/1665373/24451395/eab8b7d8-147e-11e7-9c15-30f6ee970d42.png)
Looks like we can pin something in future? :blush:

**Comment by Schmavery** [comment]
haha cool

**Comment by GAMELASTER** [comment]
https://www.facebook.com/facebook/videos/10155650727166729/
huh maybe this?

**Comment by Schmavery** [comment]
I'm going to close this in favour of #444, which tracks the actual feature.  Thanks for doing this digging around though.
