### ISSUE TITLE
getThreadHistory message objects senderID's do not have "fbid:" stripped 

### ISSUE THREAD

**Issue by mangopearapples** [Schmavery/facebook-chat-api#438]
The senderID's retrieved from messages from getThreadHistory contain the "fbid:" prefix. 
The senderID will look something like: `fbid:100000619620090`
Is this intentional? It is a bit inconsistent from the rest of he api.
Looking at getThreadHistory, the error comes from [v.author](https://github.com/Schmavery/facebook-chat-api/blob/master/src/getThreadHistory.js#L52)

To reproduce:

                            api.getThreadHistory(threadID, 0, 10, undefined, (err, history) => {
					if (err) return console.log(err);

					history.forEach((msg, index) => {
                                            console.log(msg.senderID);
					});
				});

**Comment by Schmavery** [comment]
Fixed by #439
