### ISSUE TITLE
listen error and message is undefined

### ISSUE THREAD

**Issue by rezk2ll** [Schmavery/facebook-chat-api#443]
last time i updated my package the api became bugged. everytime i start the app i get
```
info login Logging in...
info login Logged in
info login Request to reconnect
info login Request to pull 1
info login Request to pull 2
info login Request to thread_sync
info login Done logging in.
info listen NaN
info listen NaN
info listen NaN
info listen NaN
info listen NaN
info listen NaN
info listen NaN
```

also the message object in undefined.

![image](https://cloud.githubusercontent.com/assets/6764881/24581375/e82d3e68-1711-11e7-9f5d-fbf3cb18818a.png)

am doing a regex on the received message , so now i'm getting this
![image](https://cloud.githubusercontent.com/assets/6764881/24581379/06f67198-1712-11e7-90a7-792e0ca52b8b.png)

this happened after i reinstalled the package today , yesterday everything was fine.
any clues ??

**Comment by GAMELASTER** [comment]
Oh, this looks weird. Could you send here an log with verbose mode enabled?
```
api.setOptions({logLevel: "silly"});
```

**Comment by rezk2ll** [comment]
here is some log ( should i post it somewhere like pastebin next time ? )
`info login Logging in...
info login Logged in
info login Request to reconnect
info login Request to pull 1
info login Request to pull 2
info login Request to thread_sync
info login Done logging in.
verb parseAndCheckLogin for (;;); {"t":"lb","lb_info":{"sticky":"446","pool":"frc3c09_chat-proxy"}}
info listen NaN
verb parseAndCheckLogin for (;;); {"t":"msg","seq":2,"u":100016133580459,"ms":[{"type":"qprimer","made":"1491077578894"},{"type":"chatproxy-presence","buddyList":{"100015591369533":{"lat":1491072970},"100012786527851":{"lat":1491077519,"p":2,"vc":74},"100003536000462":{"lat":1491077518,"p":2,"vc":8},"100014554532619":{"lat":1491070007},"100016010765886":{"lat":1491076136},"100009219235082":{"lat":1491077437},"100005519323012":{"lat":1491077521,"p":2,"vc":74},"100009468254245":{"lat":1491077499,"p":2,"vc":0},"100006901877549":{"lat":1491076758},"100013524071522":{"lat":1491077293},"100010843210804":{"lat":1491077521,"p":2,"vc":74},"100006182049801":{"lat":1491071057},"100006756090322":{"lat":1491077521,"p":2,"vc":74},"100011954147326":{"lat":1491075801},"100000220153185":{"lat":1491077231},"100015977703976":{"lat":1491077505,"p":2,"vc":0},"100013098333129":{"lat":1491072776},"100008609169767":{"lat":1491064473},"100006439957166":{"lat":1491067602},"100016136583852":{"lat":1491076380},"100012366094697":{"lat":1491077135},"100009112109438":{"lat":1491070466},"100012407260899":{"lat":1491077521},"100015993255772":{"lat":1491077146,"p":0,"vc":74},"100010227464440":{"lat":1491072709},"100009152881892":{"lat":1491077189},"100011386218952":{"lat":1491077498,"p":2,"vc":0},"100009424523479":{"lat":1491077484,"p":2,"vc":0},"100002477406411":{"lat":1491077511,"p":2,"vc":0},"100001061973800":{"lat":1491074415},"100009616721733":{"lat":1491077393,"p":0,"vc":10},"100006815047750":{"lat":1491076995,"p":0,"vc":10},"100012896478716":{"lat":1491077476},"100007775313210":{"lat":1491077510,"p":2,"vc":0},"100016160791918":{"lat":1491075338},"100013289642568":{"lat":1491076149},"100002607143223":{"lat":1491056113},"100002634092460":{"lat":1491076868},"100010759271189":{"lat":1491077488,"p":2,"vc":0},"100013980313368":{"lat":1491077503,"p":2,"vc":74},"100012948824725":{"lat":1491077490},"100004149285652":{"lat":1491054606},"100006217032149":{"lat":1491073037},"100013628261395":{"lat":1491071533},"100002497896832":{"lat":1491064789},"100015653772122":{"lat":1491067373},"100007461343219":{"lat":1491074923},"100015345210331":{"lat":1491077510,"p":2,"vc":10},"100008998082057":{"lat":1491076655},"100002561970664":{"lat":1491071388},"100006589476849":{"lat":1491076563},"1751978581":{"lat":1491073381},"100011342206026":{"lat":1491076649},"100004245109068":{"lat":1491072645},"1602574780":{"lat":1491077489,"p":2,"vc":74},"100015179776399":{"lat":1491073000},"100012441217223":{"lat":1491071247},"100013980062473":{"lat":1491070392},"100015507553284":{"lat":1491066730},"100014329483356":{"lat":1491076239},"100006853424204":{"lat":1491077353,"p":0,"vc":74},"100004274257291":{"lat":1491048789},"100001672657564":{"lat":1491077014},"100000941892654":{"lat":1491077499,"p":2,"vc":10},"100009794732281":{"lat":1491077496,"p":2,"vc":0},"100006778121411":{"lat":1491077343,"p":0,"vc":74},"100005498165902":{"lat":1491077505},"100015978585693":{"lat":1491077485,"p":2,"vc":74},"100010774605833":{"lat":1491077524,"p":2,"vc":74},"100013713391459":{"lat":1491076338},"100015283500488":{"lat":1491064681},"100011666044791":{"lat":1491076848},"100015573004317":{"lat":1491065940},"100006958217109":{"lat":1491077484,"p":2,"vc":0},"100001454620549":{"lat":1491077517,"p":2,"vc":74},"100002122932139":{"lat":1491069787},"100007568109882":{"lat":1491077513,"p":2,"vc":8},"100002789477392":{"lat":1491076026},"100010390361440":{"lat":1491075535},"100015057797992":{"lat":1491077518,"p":2,"vc":74},"100014070421428":{"lat":1491074153},"100015887173119":{"lat":1491069996},"1543002527":{"lat":1491045924},"100012335023407":{"lat":1491063437},"100000724021560":{"lat":1491077523,"p":2,"vc":74},"100000579304863":{"lat":1491073819,"p":0,"vc":74},"100015491896133":{"lat":1491077485,"p":2,"vc":74},"1214851079":{"lat":1491077498},"100005047114185":{"lat":1491074430},"100015518683634":{"lat":1491072879},"100016135230131":{"lat":1491077507,"p":2,"vc":0},"100014308959195":{"lat":1491077520,"p":2,"vc":74},"100008206362398":{"lat":1491062198},"100012554863683":{"lat":1491077482,"p":2,"vc":0},"100003376313139":{"lat":1491077515,"p":2,"vc":10},"100014240057807":{"lat":1491070507},"100011395079458":{"lat":1491077514,"p":2,"vc":10},"100000508277325":{"lat":1491069320},"100014433811012":{"lat":1491077311,"p":0,"vc":74},"100004171272592":{"lat":1491076036},"100011633776493":{"lat":1491077351},"100006726402833":{"lat":1491062735},"100005728306078":{"lat":1491077508,"p":2,"vc":10},"100004660295740":{"lat":1491077494,"p":2,"vc":0},"100012959055517":{"lat":1491054282},"100016088738066":{"lat":1491075712},"100006892141350":{"lat":1491077499},"100003216221767":{"lat":1491073950},"100007054146692":{"lat":1491075323,"p":0,"vc":74},"100009771004041":{"lat":1491076257},"100000847749462":{"lat":1491075992},"100011723010411":{"lat":1491077512,"p":2,"vc":74},"100007105590355":{"lat":1491071371},"100001568178086":{"lat":1491074509},"100000665844336":{"lat":1491066667},"100012504586644":{"lat":1491068863},"1544418493":{"lat":1491077487,"p":2,"vc":74},"100010484142885":{"lat":1491060299},"100011492200240":{"lat":1491050711},"100013144207274":{"lat":1491063136},"100015342521524":{"lat":1491058245},"100000927553413":{"lat":1491072902},"100015974225630":{"lat":1491077449,"p":2,"vc":0},"100015480406381":{"lat":1491076690},"100013441457637":{"lat":1491072035},"100001970010531":{"lat":1491077297,"p":0,"vc":74},"100008939402508":{"lat":1491071734},"100009481458128":{"lat":1491077518,"p":2,"vc":8},"100013333535099":{"lat":1491077014,"p":0,"vc":74},"100015368641736":{"lat":1491077283},"100013398826327":{"lat":1491075876},"100005271214238":{"lat":1491029208},"100015754714047":{"lat":1491069367},"100008008337913":{"lat":1491058240},"100002754108053":{"lat":1491077189,"p":0,"vc":10},"100005782786329":{"lat":1491077451},"100001547233414":{"lat":1491074706},"100008984175562":{"lat":1491076651},"100014280936320":{"lat":1491071249},"100014073605988":{"lat":1491075673},"100008967376075":{"lat":1491077520,"p":2,"vc":0},"100005288594319":{"lat":1491066024},"100001813669038":{"lat":1491077159},"100009325846632":{"lat":1491073870},"100010292521930":{"lat":1491076744},"100015284768184":{"lat":1491077512,"p":2,"vc":74},"100010186088356":{"lat":1491077494,"p":2,"vc":74},"100006931985821":{"lat":1491077510,"p":2,"vc":74},"100007948890721":{"lat":1491076346},"100001850378982":{"lat":1491077514,"p":2,"vc":74},"100003041713127":{"lat":1491072965},"100005966825475":{"lat":1491077484},"100015446404358":{"lat":1491072470},"100009994038788":{"lat":1491035059},"1456943117":{"lat":1491077493,"p":2,"vc":74},"100008816507856":{"lat":1491077511,"p":2,"vc":0},"100015349425481":{"lat":1491077513,"p":2,"vc":0},"100002468728754":{"lat":1491068692},"100001208880799":{"lat":1491075920},"100006086916440":{"lat":1491076293},"100012372405757":{"lat":1491077507,"p":2,"vc":10},"1569896308":{"lat":1491076741},"100012460415281":{"lat":1491072134},"100010000081560":{"lat":1491073262},"100014704241910":{"lat":1491068550},"100007821889192":{"lat":1491069369},"100011569907202":{"lat":1491077520,"p":2,"vc":8},"100010303657626":{"lat":1491045406},"100007005918741":{"lat":1491068701},"100002486385837":{"lat":1491074178},"100014023759454":{"lat":1491070711},"100013902279963":{"lat":1491064522},"100005448289081":{"lat":1491074298},"100015733866570":{"lat":1491077185},"100015279840571":{"lat":1491044091},"100009612666733":{"lat":1491072599},"100012047439490":{"lat":1491068187},"100013616830484":{"lat":1491074509,"p":0,"vc":74},"100015969126466":{"lat":1491077499},"100015209916162":{"lat":1491073976},"100015187860040":{"lat":1491053749},"100014886911545":{"lat":1491077502,"p":2,"vc":74},"100009663605646":{"lat":1491077514,"p":2,"vc":74},"100002492943584":{"lat":1491077521,"p":2,"vc":74},"100013040347212":{"lat":1491077517,"p":2,"vc":0},"100010302285178":{"lat":1491075754},"100004158398372":{"lat":1491075933},"100016077698872":{"lat":1491071992},"100006644884857":{"lat":1491035832},"100013286629778":{"lat":1491076032},"100009379315834":{"lat":1491049794},"100008183503806":{"lat":1491066836},"100015598926786":{"lat":1491073024},"100002984465826":{"lat":1491072658},"100001080141605":{"lat":1491076607},"100014367342898":{"lat":1491070998},"100012863013064":{"lat":1491075395},"100010852389043":{"lat":1491077511,"p":2,"vc":10},"100006770295266":{"lat":1491076751,"p":0,"vc":74},"100015754934382":{"lat":1491077043},"100008306613872":{"lat":1491069495},"100015813541611":{"lat":1491076594},"100002066433602":{"lat":1491071086},"100013953731021":{"lat":1491075441},"100001449488186":{"lat":1491073200},"100004407136459":{"lat":1491075949},"100008377479229":{"lat":1491077493,"p":2,"vc":10},"100008270230658":{"lat":1491077112},"100015049591912":{"lat":1491077502,"p":2,"vc":0},"100008265732301":{"lat":1491075320},"100003655812534":{"lat":1491030534},"100011202155005":{"lat":1491077498,"p":2,"vc":0},"100011782712091":{"lat":1491077517,"p":2,"vc":74},"100014119000535":{"lat":1491077089,"p":0,"vc":74},"100015660872239":{"lat":1491074749},"100013402955399":{"lat":1491070872},"100008676739199":{"lat":1491039735},"647672758":{"lat":1491077487,"p":2,"vc":74},"100001992345851":{"lat":1491066685},"100003523489208":{"lat":1491072088},"100014870809371":{"lat":1491077344},"100015062591367":{"lat":1491077509,"p":2,"vc":0},"100003614962747":{"lat":1491077521,"p":2,"vc":74},"100010023877691":{"lat":1491077507,"p":2,"vc":74},"100015804826959":{"lat":1491049212},"100014847463100":{"lat":1491076990},"100014148973670":{"lat":1491077523,"p":2,"vc":0},"100011205931990":{"lat":1491075674},"100013786007427":{"lat":1491072284},"100013366025366":{"lat":1491073302},"100011576389062":{"lat":1491075722},"100014601188217":{"lat":1491054418},"100011606859762":{"lat":1491038331},"100007037892680":{"lat":1491077329},"100015879633728":{"lat":1491076154},"100004431822086":{"lat":1491075888},"100014273194655":{"lat":1491064400},"100001266668633":{"lat":1491077519,"p":2,"vc":8},"100011571919251":{"lat":1491077485,"p":2,"vc":74},"100010838799650":{"lat":1491075658},"100014717349905":{"lat":1491077505,"p":2,"vc":0},"100009240949478":{"lat":1491077499,"p":2,"vc":0},"100011980879159":{"lat":1491070817},"100012212017649":{"lat":1491073869},"100009024672716":{"lat":1491075122,"p":0,"vc":74},"100015943635302":{"lat":1491077509,"p":2,"vc":74},"100006489253098":{"lat":1491074128},"100015520218144":{"lat":1491072293},"100007090628787":{"lat":1491076064},"100008207227904":{"lat":1491075570},"100015559929411":{"lat":1491077515,"p":2,"vc":8},"100010131438029":{"lat":1491076248},"100002845414787":{"lat":1491068603},"100012377146272":{"lat":1491076996},"100013383787428":{"lat":1491077505,"p":2,"vc":10},"100010027453371":{"lat":1491072961},"100014375262417":{"lat":1491077515,"p":2,"vc":0},"100009543665359":{"lat":1491077520,"p":2,"vc":8},"525066274":{"lat":1491077524,"p":2,"vc":74},"100015069797673":{"lat":1491077513,"p":2,"vc":8},"100014552057411":{"lat":1491071989},"100009604403049":{"lat":1491077499,"p":2,"vc":74},"100011581122911":{"lat":1491077522,"p":2,"vc":74},"100010762847355":{"lat":1491004876},"100016172970995":{"lat":1491077505,"p":2,"vc":0},"100015906094861":{"lat":1491072029},"100016110455612":{"lat":1491049800},"100008032869572":{"lat":1491077514,"p":2,"vc":0},"100007620016937":{"lat":1491072600},"100005410574714":{"lat":1491077505,"p":2,"vc":0},"100006506141640":{"lat":1491066261},"100014248262193":{"lat":1491073727},"100009596122618":{"lat":1491077387,"p":0,"vc":2},"100007629960907":{"lat":1491074910},"100012890496838":{"lat":1491056390},"100015210287714":{"lat":1491077519,"p":2,"vc":8},"100012558780539":{"lat":1491003847},"100010983155310":{"lat":1491074910},"100002375688035":{"lat":1491067984},"100009675678784":{"lat":1491068960},"100012127147583":{"lat":1491066848},"100014342387753":{"lat":1491067196},"100007669410528":{"lat":1491067814},"1832897718":{"lat":1491076039},"100014070910039":{"lat":1491062897},"100000082695696":{"lat":1491077491,"p":2,"vc":74},"100015843345325":{"lat":1491065951},"100016021022746":{"lat":1491077502,"p":2,"vc":0},"100007368369362":{"lat":1491073442},"100012351274450":{"lat":1491072094},"100010745477517":{"lat":1491053584},"100015508358560":{"lat":1491074256},"100003778506963":{"lat":1491071122},"100010792119515":{"lat":1491071719},"100011201498946":{"lat":1491077518,"p":2,"vc":8},"100000142067093":{"lat":1491073066},"100007920519664":{"lat":1491077519,"p":2,"vc":10},"100001235846983":{"lat":1491077158},"100005656606400":{"lat":1491075817},"100003106982595":{"lat":1491068909},"100010775028177":{"lat":1491071383},"100015244027968":{"lat":1491076757,"p":0,"vc":74},"100007714218769":{"lat":1491067458},"100014728743733":{"lat":1491076636},"100011349796774":{"lat":1491073528},"100014161399244":{"lat":1491077525,"p":2,"vc":74},"733500434":{"lat":1491070656},"100003549898574":{"lat":1491073541},"100009780162096":{"lat":1491069206},"100005136105947":{"lat":1491072344},"100014646881338":{"lat":1491043297},"100014812566565":{"lat":1491077521,"p":2,"vc":74},"100014410877996":{"lat":1491075602,"p":0,"vc":0},"100001616899487":{"lat":1491077196},"100004926555475":{"lat":1491077446,"p":2,"vc":74},"100011402548562":{"lat":1491071219},"100005956381390":{"lat":1491070617},"100001838672221":{"lat":1491075590,"p":0,"vc":10},"100003189176287":{"lat":1491074694},"100012547384596":{"lat":1491058550},"100003822717799":{"lat":1491075193},"100004576080398":{"lat":1491077513,"p":2,"vc":74},"100004265801098":{"lat":1491073989},"100016040702886":{"lat":1491076620},"100016102536561":{"lat":1491077521,"p":2,"vc":10},"100015982685743":{"lat":1491077494,"p":2,"vc":0},"100004079469214":{"lat":1491077512,"p":2,"vc":74},"100015226601266":{"lat":1491069838},"100009388893990":{"lat":1491077500,"p":2,"vc":74},"100008726293925":{"lat":1491075530},"100006885370846":{"lat":1491065651},"100009404219965":{"lat":1491073563},"100015484777036":{"lat":1491076335,"p":0,"vc":74},"100010529111862":{"lat":1491074195},"100009305279033":{"lat":1491062154},"100002240455972":{"lat":1491076767},"100015947479072":{"lat":1491077489,"p":2,"vc":0},"100012523488206":{"lat":1491076807},"1449996219":{"lat":1491077525,"p":2,"vc":74},"100002996186677":{"lat":1491073963},"100001128279198":{"lat":1491051305},"100005156027617":{"lat":1491077498,"p":2,"vc":10},"100006026315907":{"lat":1491077513,"p":2,"vc":74},"100000557857429":{"lat":1491075636},"100013643160198":{"lat":1491076120},"100015194327816":{"lat":1491077110,"p":0,"vc":8},"100009637148623":{"lat":1491075933},"100000532870958":{"lat":1491069973},"100001492754532":{"lat":1491076321},"100000639218568":{"lat":1491074129},"100010366815614":{"lat":1491076952},"100012865034327":{"lat":1491077516,"p":2,"vc":0},"100004402444797":{"lat":1491073477},"100014185873176":{"lat":1491069324},"100013597205481":{"lat":1491075079},"100000249048656":{"lat":1491063949},"100006279843790":{"lat":1491077491,"p":2,"vc":74},"100002227603527":{"lat":1491048499},"100006801161434":{"lat":1491077519,"p":2,"vc":74},"100006667506406":{"lat":1491076987,"p":0,"vc":10},"100004185586424":{"lat":1491074534},"100003327992798":{"lat":1491075945,"p":0,"vc":74},"100010327805726":{"lat":1491076964,"p":0,"vc":10},"100014818293434":{"lat":1491075174},"100013832058851":{"lat":1491077516,"p":2,"vc":0},"100008513795321":{"lat":1491077520,"p":2,"vc":74},"100003126970323":{"lat":1491076766},"100009577302108":{"lat":1491075479,"p":2,"vc":74},"100015660481761":{"lat":1491076406},"100002189245947":{"lat":1491076847,"p":0,"vc":74}},"userIsIdle":false,"chatNotif":0,"gamers":[]}]}
info listen NaN
verb parseAndCheckLogin for (;;); {"t":"msg","seq":3,"u":100016133580459,"ms":[{"st":1,"from":100005728306078,"to":100016133580459,"from_mobile":true,"attribution":null,"realtime_viewer_fbid":100016133580459,"type":"typ"}]}
info listen NaN
verb parseAndCheckLogin for (;;); {"t":"msg","seq":4,"u":100016133580459,"ms":[{"st":0,"from":100005728306078,"to":100016133580459,"from_mobile":true,"attribution":null,"realtime_viewer_fbid":100016133580459,"type":"typ"}]}
info listen NaN
verb parseAndCheckLogin for (;;); {"t":"msg","seq":7,"u":100016133580459,"ms":[{"type":"deltaflow","sequencer":"3177","fbid":"100016133580459"},{"ofd_ts":1491077604924,"delta":{"attachments":[],"body":"Ui","irisSeqId":"3177","messageMetadata":{"actorFbId":"100005728306078","messageId":"mid.$cAAAAArf0ZTVhXGvuKlbKyaeEIywj","offlineThreadingId":"6254032753870973987","tags":["source:chat:orca"],"threadKey":{"otherUserFbId":"100005728306078"},"timestamp":"1491077604906"},"class":"NewMessage"},"type":"delta","iseq":3177,"queue":100016133580459},{"unseen":4,"unread":5,"recent_unread":5,"seen_timestamp":0,"realtime_viewer_fbid":100016133580459,"type":"inbox"}]}
info listen NaN
verb parseAndCheckLogin for (;;); {"t":"msg","seq":8,"u":100016133580459,"ms":[{"ofd_ts":1491077606319,"delta":{"attachments":[],"body":"Ui","irisSeqId":"3178","messageMetadata":{"actorFbId":"100016133580459","messageId":"mid.$cAAAAArf0ZTVhXGvzqFbKyaof1vVs","offlineThreadingId":"6254032765073159532","tags":["source:chat:web"],"threadKey":{"otherUserFbId":"100005728306078"},"timestamp":"1491077606312"},"class":"NewMessage"},"type":"delta","iseq":3178,"queue":100016133580459}]}
info listen NaN
verb parseAndCheckLogin for (;;); {"t":"msg","seq":10,"u":100016133580459,"ms":[{"ofd_ts":1491077606559,"delta":{"deliveredWatermarkTimestampMs":"1491077606312","irisSeqId":"3179","messageIds":["mid.$cAAAAArf0ZTVhXGvzqFbKyaof1vVs"],"threadKey":{"otherUserFbId":"100005728306078"},"class":"DeliveryReceipt"},"type":"delta","iseq":3179,"queue":100016133580459},{"ofd_ts":1491077606906,"delta":{"actionTimestampMs":"1491077606886","irisSeqId":"3180","threadKey":{"otherUserFbId":"100005728306078"},"watermarkTimestampMs":"1491077606312","class":"ReadReceipt"},"type":"delta","iseq":3180,"queue":100016133580459}]}
info listen NaN
`

**Comment by rezk2ll** [comment]
`info listen NaN
verb parseAndCheckLogin for (;;);{"__ar":1,"__sf":"iw","payload":null,"jsmods":{"require":[["ServerRedirect","redirectPageTo",[],["https:\/\/scontent-cdg2-1.xx.fbcdn.net\/v\/t34.0-12\/17740958_610399062494365_600226375_n.jpg?oh=9792899a55dac8c3f0daa1b665ec3049&oe=58E1A441&dl=1",false,false],[]]]},"js":["efFZz"],"bootloadable":{},"resource_map":{"efFZz":{"type":"js","src":"https:\/\/static.xx.fbcdn.net\/rsrc.php\/v3i-F-4\/yK\/l\/en_US\/G82V9NdMR7h.js"}},"ixData":{},"lid":"6404129984126665504"}
verb parseAndCheckLogin for (;;); {"t":"msg","seq":49,"u":100016133580459,"ms":[{"unseen":5,"unread":6,"recent_unread":6,"seen_timestamp":0,"realtime_viewer_fbid":100016133580459,"type":"inbox"}]}
info listen NaN
`

**Comment by Schmavery** [comment]
Hmm, strange.  Are you on the latest version from npm or are you synced to master?

**Comment by rezk2ll** [comment]
i have the "4.2.0" version

**Comment by rezk2ll** [comment]
i upgraded npm and reinstalled the module , but still the same problem.

**Comment by Schmavery** [comment]
Could you possibly try updating to master and seeing if that solves the problem?  If so, I'll publish a new version to npm

**Comment by bsansouci** [comment]
Hey! @rezk2ll That's really strange we don't have a version of the api that's 4.2.0, the latest one is 1.3.0.
Trying master is a good idea @Schmavery 

Also could you show us your code that's using the api? `NaN` sounds something's trying to add a number with something other than a number or a string... I'm not sure where that message comes from.

**Comment by Schmavery** [comment]
@rezk2ll sorry, I think we misunderstood each other, I was asking about your version of the api, not about your version of npm 😝

**Comment by rezk2ll** [comment]
i installed the Bleeding edge version of the api now , everything is back to normal. ( currently i'm at the 1.3.0 version )
the npm version is just messed up.

**Comment by Schmavery** [comment]
Ok great.  Thanks for letting us know.

**Comment by bsansouci** [comment]
Awesome!
