### ISSUE TITLE
parseAndCheckLogin failing after resolvePhotoUrl

### ISSUE THREAD

**Issue by gamelaster** [Schmavery/facebook-chat-api#451]
![image](https://cloud.githubusercontent.com/assets/1665373/24591336/7c15b004-17ff-11e7-9195-64f7eb482311.png)
@bsansouci it's not related about the new updating of fb_dtsg?

**Comment by Schmavery** [comment]
@bsansouci you forgot to set it https://github.com/Schmavery/facebook-chat-api/blob/master/index.js#L58

**Comment by Schmavery** [comment]
@bsansouci ping

**Comment by Schmavery** [comment]
@GAMELASTER can you try my fix?

**Comment by GAMELASTER** [comment]
@Schmavery now it's fine, but after this fix I got this:
![image](https://cloud.githubusercontent.com/assets/1665373/24727263/a9436b7c-1a55-11e7-9b4a-6503601cbb5b.png)
no idea why

**Comment by GAMELASTER** [comment]
![image](https://cloud.githubusercontent.com/assets/1665373/24727379/13ea4ce8-1a56-11e7-8dd9-09c311ae3b52.png)

**Comment by Schmavery** [comment]
Hmm, I'm not sure what's going on either.  Don't have time to look at it now, will try to check later if you can't figure it out by then 😛

**Comment by bsansouci** [comment]
Seems to have been fixed. Closing.
