### ISSUE TITLE
Add option to turn off extra buddylist presence events

### ISSUE THREAD

**Issue by danielriddell21** [Schmavery/facebook-chat-api#452]
My FB Bot hasn't been up to any spammy activities. Ever since I added the presence to the set options, I recieve alot of console log about it showing all the people every couple of mins. Before It didnt do this it would only display when someone goes on of off. Never in a bulk. I am not sure whats happened. Since i updated it seems to do all this spammy console log stuff and It gets irritating. Is this due to your code or by a change by facebook. 

![image](https://cloud.githubusercontent.com/assets/25375432/24613498/67f903a6-1880-11e7-9935-cf07e5df5471.png)

**Comment by bobland1** [comment]
I am going to wait for the temp ban to be lifted and stop the presence calling for now. But for some reason ever since updating. I received a lot of spammy console log messages from presence.

**Comment by Schmavery** [comment]
I think there are 2 separate issues here.  The "presence spam" is as a result of https://github.com/Schmavery/facebook-chat-api/pull/413.  It's possible that we could add an option to turn this off or change the log priority, but remember that you can adjust the global logging level whenever you want.

Being temporarily banned is definitely not fun and we'd like to do all we can to avoid that happening.  Unfortunately it's also very hard to diagnose.  Please let us know if there's some idea you have of things people should avoid doing to avoid triggering this.

**Comment by Schmavery** [comment]
I have a hard time thinking that the new presence notifications are the cause of this, because I'm pretty sure we were already receiving this information before and throwing it away, and there's no extra calls that we being made.  @GAMELASTER can confirm.

@bobland1 what other api functionalities were you using?

**Comment by bobland1** [comment]
Aight thank you very much :) And, ill send you my code privately so you can see :) I have commented some stuff out so i dont get temp banned again.

**Comment by bobland1** [comment]
![image](https://cloud.githubusercontent.com/assets/25375432/24621909/18368aee-189b-11e7-874c-3351f7933f74.png)
![image](https://cloud.githubusercontent.com/assets/25375432/24621968/42e327b6-189b-11e7-9ada-30f99c27cf64.png)
Is why i got banned. I use this
![image](https://cloud.githubusercontent.com/assets/25375432/24622001/5a670a1a-189b-11e7-918b-e1c2a87dbbb7.png)

**Comment by bobland1** [comment]
But due to the spam at the start, i feel that is what caused the ban. Is there a way i am able to turn that off, so i dont receive the spam at the start?

**Comment by GAMELASTER** [comment]
Heya,
That spam is because at start and some intervals you getting all of your friends presences.
Actually, I have this integrated in one of my bots and it's working okay (the bot running a long time).
So it's all right

**Comment by GAMELASTER** [comment]
UPDATE:
Already checked my bot, I saw some HTML (error) maybe , but I still get presences and that bot account is not blocked.
![image](https://cloud.githubusercontent.com/assets/1665373/24622383/2009173c-18a5-11e7-9162-5e01ce5445e2.png)
Uh, this doesn't look okay.... Can anyone test getUserInfo?

**Comment by bobland1** [comment]
I feel it is because I check who actually is online, by using the get user info to convert. And by the large amount of requests its getting. I am counted as spamming

**Comment by Schmavery** [comment]
@bobland1 if you're calling getUserInfo in a loop for every presence update, I'm not surprised you're getting rate-limited.  If you can confirm that that's what your code was doing, I think we can consider this issue figured out.
@GAMELASTER if you suspect there's a getUserInfo problem, please open an issue for it :)

**Comment by Schmavery** [comment]
@GAMELASTER do we get any information from buddylist that we didn't already get?  We might want an option for this.

**Comment by bobland1** [comment]
If there is a way of being able to stop the spam at the start... or na. If not ill turn off that code initially

**Comment by GAMELASTER** [comment]
@Schmavery I saw only presences and one or two unknown property
@bobland1 you must disable whole presences listening

**Comment by bobland1** [comment]
Are you able to add a feature like @Schmavery said about changing how it logs?

**Comment by Schmavery** [comment]
@bobland1 I doubt that the logging is the problem here.
@GAMELASTER I'm saying I feel like we might want to have an option to turn off buddylist, since people are already getting login/logout notifications.  This is a bit of a design decision and I'm not totally sure what the best solution is.

**Comment by GAMELASTER** [comment]
@Schmavery getting login/logout notifications? huh?

**Comment by bobland1** [comment]
Oh okay :)

**Comment by bobland1** [comment]
Also I looked into the feature I was curious about, I have sent my foundings.

**Comment by bobland1** [comment]
#444

**Comment by ravkr** [comment]
is it really noisy? or it was just error in @bobland1's code?
![zrzut ekranu z 2017-04-08 00 47 52](https://cloud.githubusercontent.com/assets/3875202/24822411/3e0158fa-1bf5-11e7-8f1a-545a4d7332c4.png)
this condition will be always `true`

**Comment by bobland1** [comment]
It is quite noisy as, it tends to spam every 2 mins. Me and my friend have both tried it to see if it's just me and it's not. It's due to the buddy list thing. As well as checking when people log out and in, it also will show the buddy list as well every 2 mins

**Comment by Schmavery** [comment]
@ravkr you're right that this is the real fix.  I was just wondering if maybe most people don't need the added buddylist events and perhaps would want the option of turning them off.

**Comment by ravkr** [comment]
but what about this `if`?
there should be `===` instead of `=`
now it is just ignoring it

**Comment by bobland1** [comment]
Have presence on and check how frequently it outputs. I mean I have it turned of at the moment as I don't wish to carry on what I was doing till it is toned down to where the spamming every 2 mins is well less frequent or something

**Comment by bobland1** [comment]
@ravkr, the buddy list is part of presence so changing that shouldn't change anything... check the screenshots above. In the morning I'll change my code to what you have said I'll see if that fixes the issue if it does then 😂 Wow. Be sure to check back with you asap

**Comment by ravkr** [comment]
I'm not saying that it will fix everything...
but code from your screenshot runs everytime there is any event... not only on presence updates

**Comment by Schmavery** [comment]
@bobland1: @ravkr is right that you have a typo in `if (message.type = 'presence')`.  This is assignment not comparison, which would be `==` or `===`.
That said, I wouldn't be surprised if presence updates are the most frequent update and that the code will still call getUserInfo too frequently.  Specifically, buddylist presence updates call the callback many times in a row without any delay, which would trigger rate limiting if you made a call to facebook every time.

**Comment by bobland1** [comment]
I'll message you asap, also I have found a bypass to this by logging the messageID and checking it before sending messages but sometimes when a message takes longer to send due to bad connection. It receives two results and will hence result in two answers back. But this isn't really an issue any more as I have found a work around to it. But yeah thought I should let you know as well as others may be experiencing it.

**Comment by GAMELASTER** [comment]
I using this feature nonstop, all works okay. It's useful for me, because I can get older presences what doesn't arrived etc. It's true, it's sending all and the same presences (if user hasn't been active), so I just created the array where checking the last time, so I just skip it if it's an old presence which I registered. (resp. already it's handled by MySQL)

**Comment by bobland1** [comment]
I have changed the if = to if ==, Thank you about that btw

**Comment by bobland1** [comment]
![image](https://cloud.githubusercontent.com/assets/25375432/24831807/464dedbc-1c99-11e7-8ce4-4ebb090553a8.png)

**Comment by GAMELASTER** [comment]
Good idea!

**Comment by bobland1** [comment]
I would have a nack at trying this new feature. But looking at the code within the listen about presence. I have no clue what to do. If anyone else is willing to do this, that would be great but in the mean time. I'm gonna have a look into it a bit more :)

**Comment by Schmavery** [comment]
@bobland1 I can maybe help you with this.  Basically you should add another case [here](https://github.com/Schmavery/facebook-chat-api/blob/b89c914ea0c0b9c02aa306e26608f8c4475f36dd/src/listen.js#L124) to exit early if an option is set.

`setOptions` code lives [here](https://github.com/Schmavery/facebook-chat-api/blob/b89c914ea0c0b9c02aa306e26608f8c4475f36dd/index.js#L10).  Just add another case for  this (not sure what to call it).

The options defaults live [here](https://github.com/Schmavery/facebook-chat-api/blob/b89c914ea0c0b9c02aa306e26608f8c4475f36dd/index.js#L434).  Not sure what the default should be in this case.

Let us know if you have any other questions.

**Comment by bobland1** [comment]
Awh thanks alot! I'll be sure to put this into the works 😊. Message you once I've done some testing. Thanks again

**Comment by bobland1** [comment]
Maybe have presence and friendListPresence. As it updates the friend list Presence. Or buddyPresence

**Comment by bobland1** [comment]
Started work on it, tell me what if I make any mistakes. I am prone to typos.
