### ISSUE TITLE
Can deploy this app to heroku?

### ISSUE THREAD

**Issue by anhnamxtanh** [Schmavery/facebook-chat-api#454]
I want to deploy this app to heroku. 
Can you guide me or write on readme?

**Comment by mangopearapples** [comment]
You should be able to deploy it as a Node.js app. Try [this guide](https://devcenter.heroku.com/articles/getting-started-with-nodejs).

**Comment by Hongarc** [comment]
You can use node-js-getting-started code of heroku .
After add your code to project.
I was try but facebook block me (my IP diffrent that IP  region).

**Comment by Schmavery** [comment]
This can work (and we've done it in the past) but you can sometimes run into problems with facebook seeing logins from multiple IPs and temporarily blocking the account. You might be able to get around this using `api.getAppState`.

**Comment by Schmavery** [comment]
Hope this helped!  Let us know if you run into any problems 😄
