### ISSUE TITLE
creating a simple ai bot

### ISSUE THREAD

**Issue by radioactive0238** [Schmavery/facebook-chat-api#455]
how can i create a simple messenger bot which can understand user's message ( intents and entities) and executes functions according to them . Can anyone suggest a module to build and use a dictionary for the bot .

**Comment by bobland1** [comment]
Look into Markov chains or Cleverbot

**Comment by ravkr** [comment]
This "issue" have a little to do with facebook-chat-api
And making AI is not an easy task, you can make it semi-AI by just checking if some words are in the string:
User sends: Who is Beethoven?
Bot: I've found "who is", probably next words are name of someone, let's look on Wikipedia/google
And after few seconds bot responses with some info scraped from Google

Etc...

**Comment by bobland1** [comment]
If you want a ai bot. You need to work with neural networks so have fun

**Comment by radioactive0238** [comment]
what i want to do is execute queries on elasticsearch based on the question asked by the user . what will be the simplest way to do that ? i'm trying to use api.ai with it , is it a good option ?

**Comment by bobland1** [comment]
You are very unlikely able to integrate this api and api.ai together. Your best bet is to code it yourself.

**Comment by bobland1** [comment]
with if statements just check if the message.body has the question and then from that you can use api.sendMessage...

**Comment by Schmavery** [comment]
You can do pretty much wherever you want.  You have a `listen` callback that tells you what people are saying to you, and you've got `sendMessage` which will let you send a message to a person.  The rest should just be programming 😝 
I'm going to close this issue because it doesn't seem like there's an issue with the api, but feel free to keep chatting.

**Comment by kabirvirji** [comment]
Sounds like you're looking for something like https://wit.ai/ or https://api.ai/

**Comment by radioactive0238** [comment]
one more help , i want to send buttons as a message . the template will be sent as an attachment but when i try to send , it shows error that attachment should be a readable stream . what am i doing wrong ??

**Comment by GAMELASTER** [comment]
Buttons? It's not supported by normal user

**Comment by Schmavery** [comment]
@radioactive0238 it seems like you're trying to make a bot using the official chatbot api -- this is not the api for that.  Maybe check out https://developers.facebook.com/docs/messenger-platform and some of the other links people have posted :)

**Comment by radioactive0238** [comment]
thank you everyone for your help . i'll check the official chatbot api .
