### ISSUE TITLE
addUserToGroup error 1545052

### ISSUE THREAD

**Issue by alecmanabat** [Schmavery/facebook-chat-api#456]
"The user could not be added to the conversation. Please try again later."

I am new to Github so I apologize if this is not a proper "new issue". I get this error when I try to add a user to a one on one chat. I checked the user ID and thread ID that I put into addUserToGroup and they are correct. I was able to add people to a previously one on one chat before (around 2 weeks ago). I know the function is for adding to a group, but making a one on one chat into a group was a nice feature.

I read a issue submitted a while ago about this error popping up, but the user would be added to the group anyway, but now the user is not added.

Any help/feedback is appreciated!

**Comment by Schmavery** [comment]
With something like this, your best bet is to try doing it in the browser.  If it doesn't work there, it probably won't work in the API.  Does that help answer your question at all?

**Comment by alecmanabat** [comment]
I'm not sure if I understand "doing it in the browser" correctly. Do you mean turning a one on one conversation into a group message on facebook.com? That is possible and I was able to do it with the api before.

Thanks!

**Comment by bobland1** [comment]
Just look through the documentation. If you know nothing about nodejs. This isn't the api for you.

**Comment by bobland1** [comment]
He means by you doing it manually through the messenger.com. The user could of blocked the chat the bot or you. You will need to test by doing trial and error till you find your cause

**Comment by Schmavery** [comment]
@alecmanabat Hmm ok.  Yes, that's what I meant, I couldn't see a way to do it in messenger.com when I looked quickly but maybe it's possible on facebook.com.
If you're at all interested in helping investigate this problem, I'd try to see if it's happening consistently, like whether it's happening with any friend that you try this with.  If that's the case, then I'd go to the browser and perform this action while having some devtools open monitoring the network activity.  You should see some requests get sent when you add the friend to the conversation.  Recording those would be a first step to resolving this.

**Comment by alecmanabat** [comment]
Not sure how I was able to turn a one on one chat into a group before but I can't find it on messenger.com so I'll close this.

**Comment by Schmavery** [comment]
Either messenger.com or facebook.com should be fair game.  Feel free to let us know if you have any more developments.
