### ISSUE TITLE
Latest releases are unstable

### ISSUE THREAD

**Issue by GAMELASTER** [Schmavery/facebook-chat-api#458]
I don't know why, but the latest `master` releases is really unstable. While one my bot (running on some commits older) running nonstop for weeks, the latest one is really unstable. Already third times I got similar problem:
![image](https://cloud.githubusercontent.com/assets/1665373/24819448/ee7f436a-1be4-11e7-8529-50cf4a1c75ba.png)
There is SOCKET TIMEOUT
![image](https://cloud.githubusercontent.com/assets/1665373/24819460/fa8936e8-1be4-11e7-88ef-ba91781541db.png)
There is CONNECTION RESET (sorry, because of screen I can't scroll up)

Maybe it have something with new `fb_dstg`?

**Comment by Schmavery** [comment]
Do you know what is causing the "Cannot read property 'type' of undefined"?  I'm assuming you're checking `err` in the callback.

**Comment by GAMELASTER** [comment]
@Schmavery oh yeah.. I don't watching `err` , but that connection timeout errors is strange, I enable some logging to have more information

**Comment by Schmavery** [comment]
we should probably not call the callback with these errors when they happen, but I don't think this is an api stability problem if that's all it is.

**Comment by bobland1** [comment]
I am receiving errors with api.logout and uploading images since the newest release as well. The most recent patch for me did fix the resolvephotourl though

**Comment by Schmavery** [comment]
@bobland1 please open issues for any new problems you encounter and we can figure them all out one at a time 😄

**Comment by Schmavery** [comment]
@GAMELASTER if checking `err` fixes this problem, I think it's not really a bug in the api.  Feel free to continue discussion if you don't agree.

**Comment by GAMELASTER** [comment]
@Schmavery it's fixed a problem with interrupting the application, but anyway the timeout error is still there
