### ISSUE TITLE
Login using an existing cookie 

### ISSUE THREAD

**Issue by MarkehMe** [Schmavery/facebook-chat-api#46]
Instead of creating a new session, we should add an endpoint to the api to fetch the cookie, and also the ability to login with a cookie instead. 

e.g. ..

    login({ cookie: "...

From testing, I've created about 40 sessions! If you guys want I can implement this.

**Comment by MarkehMe** [comment]
![screenshot 2015-07-17 22 48 33](https://cloud.githubusercontent.com/assets/1357323/8747404/05db383e-2cd6-11e5-9d32-217054fdf940.png)

Yeah I think I will! Here are some ideas I'm gonna go with.

* Allow passing cookie to login along with email and password (email and password is fallback if cookie expires/crumbles)
* Add option to enable storing cookies in a cache (cookiecache.json) so when we login with an email and password, we'll first check the cache for for their email and password

Thoughts?

**Comment by bsansouci** [comment]
I think this is a good idea. You should check how `request`'s cookie jars work (they are the same as `tough-cookie`. 
I think cookie as a string is better than forcing the user to figure out how cookie jars work. It's an implementation detail that they shouldn't have to worry about. The downside is that we have to handle parsing the cookie and checking for errors. 

I'm not a huge fan of having this API handle storing the cookies in a jar. We did this for `login` before and it was a huge mess because we couldn't handle all the possible ways of load the credentials. I like to think that keeping the API surface as small as possible will guarantee the max power to the user while keeping it usable and maintainable. 
I think I'd rather simply have a getter for the cookies (maybe it returns an array of cookies).

What do you think?

**Comment by MarkehMe** [comment]
I guess that way if the user wanted to create a cache of sessions they could do it themselves which is probably better. 

So are you still saying we can allow loading a preexisting session? This is my main issue.

**Comment by bsansouci** [comment]
Yes. I'm saying add two things:
- a setter, potentially just another field inside the object given to login contains a properly formatted string of a cookie. I can't think of a better solution, but a formatted string is very loose in this case. By that I mean that any typo will just make the whole thing throw which kind of sucks, but I'm in favor of simplicity. So I think the format of the string should be the one you get from copy pasting cookies from Chrome (basically the most used way of getting cookies). What do you think @Schmavery?
- a getter, something like `api.getCookies` which would do https://github.com/SalesforceEng/tough-cookie#getcookiessynccurrenturl-options and then map over the array and call `toString` on it

**Comment by MarkehMe** [comment]
This sounds good to me! We'll just wait for some feedback.

**Comment by MarkehMe** [comment]
I've been thinking, we should priorities cookies in the login function. If the cookie fails to login, we can fallback to the users email and password. For example:

    login({ cookie: "COOKIE_DATA", email: "FB_EMAIL",  password: "FB_PASSWORD" }, function callback (err, api) {
        // .. do stuff <3 
    });

So if the cookie expired, or the session had been ended we would revert back to the email and password.

What're your thoughts on this @bsansouci and @Schmavery?

I'm really in need of this, so I'm going to write this up!

**Comment by Schmavery** [comment]
I'm fine with this format personally.  Login is currently one of the spaghettiest pieces of code left in the project, so we'll have to be careful not to break anything.  Thoughts @bsansouci?

**Comment by bsansouci** [comment]
@MarkehMe don't do a PR, we have some ideas and need to untangle the code a little. The idea would be to serialize the whole app state (including userId, clients, access_token etc..), not just the cookies. Then you can get it with something like `api.getAppState` and do `fs.writeFile("cache.json", JSON.stringify(api.getAppState()))` before quitting.
Then you would login like
```js
var appState = fs.readFileSync("cache.json", "utf8");

login({ appState: appState, email: "FB_EMAIL",  password: "FB_PASSWORD" }, function callback (err, api) {
    // .. do stuff <3 
});
```

Do you think that would be enough?

**Comment by MarkehMe** [comment]
That sounds good to me.

**Comment by keshavkaul** [comment]
@Schmavery @bsansouci 
Is there anyway to know if cookie login failed due to expired cookies? Do i get an error callback if this fails? I'm trying to login with **only** cookies.

**Comment by GAMELASTER** [comment]
@keshavkaul 
In all request is used an "parseAndCheckLogin", so If your cookies expired, all requests throw exception "You are not logged in!"
https://github.com/Schmavery/facebook-chat-api/blob/master/utils.js#L542
