### ISSUE TITLE
Message body inconsistencies between getThreadHistory() and from listen()

### ISSUE THREAD

**Issue by mangopearapples** [Schmavery/facebook-chat-api#461]
The body field in message objects returned from `api.listen` and `api.getThreadHistory` are inconsistent when empty. I.e. when the messages are attachments.

When the message consists of just an image, the body of the message received by `listen` is `undefined` if the message received was a photo. However, the same message from `getThreadHistory` will have a body of `''`.

This is a really low priority issue nothing is actually broken but I'd bring it up for the record. There's a design decision to made; whether to have it as `undefined` or an empty string. I personally think an empty string would be better IMO.

**Comment by Schmavery** [comment]
I think that `listen` is the most representative of the behaviour we'd like to have.  I think we try to encourage explicitly checking the message type and for this reason it's not critical for every message type to have a `body`.
Perhaps unrelatedly, I feel like this could be renamed to "Message inconsistencies between getThreadHistory() and from listen()"  😝. `getThreadHistory` returns a lot of useless fields that I'd love to be able to trim out, but it would probably take substantial reformatting work and should maybe be handled separately.

**Comment by Schmavery** [comment]
Though gee the docs for listen really need an overhaul.

**Comment by Schmavery** [comment]
@mangopearapples wait.  If you send a message consisting of just an image, what is the `msg.type`?  If it's `"message"` then you're right and this should be an empty string to match the definition in the docs.  I opened an issue #463 to rework these docs (even I don't completely understand them when reading quickly), hopefully someone will have time to help out with this soon.

**Comment by mangopearapples** [comment]
@Schmavery Yes when a message consists of just an image or even a sticker, e.g. file upload of image, the message type is `message`.

**Comment by Schmavery** [comment]
I see, it's a message with an attachment.  Ok, in that case, I think we should make sure to have the body be an empty string in formatMessage, I suppose.  I don't think the browser is able to properly distinguish between an empty string and undefined anyway.

**Comment by Schmavery** [comment]
5f114c7304deee75f16c508f89e773996501373c should fix this.
