### ISSUE TITLE
Refactor listen docs

### ISSUE THREAD

**Issue by Schmavery** [Schmavery/facebook-chat-api#463]
The docs for listen have gotten basically unreadable with the recent addition of several new types of message (no fault to anyone, thanks everybody for the contributions! 😄 ).  It would be great if these could be rewritten to be easier to read.  I'm imagining some tabular structure, maybe, with attempts to describe the fields where possible.
We might need a couple of tables, one to handle the types of messages (..this might just contain one thing?), one for the types of events and one for the types of attachments.  I feel like most solutions would be better than what we have now.

Unfortunately github markdown doesn't support lists inside of tables, but you can hack it ok with the `<br>` element.  Definitely open to suggestion here.  How do other apis solve this problem?

```
|  Event Type   |     Fields    |
| ------------- | ------------- |
| `"event"`  | `threadID`: The thread which the event was performed in.  <br> `author`: The person who performed the event. <br> ...|
| `"typ"`  | `threadID`: The thread which the event was performed in.  <br> `author`: The person who performed the event. <br> ... |
```

| Event Type  | Fields |
| ------------- | ------------- |
| `"event"`  | `threadID`: The thread which the event was performed in.  <br> `author`: The person who performed the event. <br> ...|
| `"typ"`  | `threadID`: The thread which the event was performed in.  <br> `author`: The person who performed the event. <br> ... |

**Comment by AllanWang** [comment]
I'll take a look at this after finals

**Comment by ravkr** [comment]
I will have some time after April 22nd so I'll try to help you guys :smile:
