### ISSUE TITLE
Info log got an error in listen.js module

### ISSUE THREAD

**Issue by hraph** [Schmavery/facebook-chat-api#466]
In the listen.js module, the log message "Got answer in" line 71 generates a NaN error because the time difference calculation is not surrounded by a parenthesis.

It should be :
`log.info("listen", "Got answer in " + (now - tmpPrev));`

Thanks :)

**Comment by bobland1** [comment]
It has been fixed

**Comment by GAMELASTER** [comment]
@hraph use Bleeding edge version (github)
```
npm uninstall facebook-chat-api
npm install https://github.com/Schmavery/facebook-chat-api
```

**Comment by Schmavery** [comment]
@hraph thanks for letting us know, I will publish to npm as soon as we get a little bit of stability on master
