### ISSUE TITLE
How can I accept filtered friends? Please can you help me?

### ISSUE THREAD

**Issue by Theblood** [Schmavery/facebook-chat-api#470]
Hello, I have this code to accept to the pending list
```
api.getThreadList(0, 7, 'pending', function(err, data) {
						if (err) return console.log(err)
						for (var i = 0; i < data.length; i++) {
							var datos = data[i].threadID;
							api.handleMessageRequest(datos, true, function(err, data) {
								if (err) return console.log(err)

							});
							api.sendMessage("Hola , Haz Sido Aceptado, Bienvenido a SudoAPP! Para Ver la lista de Comandos Solo Escribe AQUI \n sudo ayuda", datos);
							visitor.event("Aceptado", "Imprimiendo").send()
						}
					});
```

**But I also want to accept the filtered list How do I do it? ** @bobland1 @Schmavery

**Comment by bobland1** [comment]
You gotta give us a little more to go on here. What's the issue?

**Comment by Schmavery** [comment]
@Theblood what do you mean by "filtered friends"

**Comment by Theblood** [comment]
@Schmavery  
Are the requests that are in this url : https://www.facebook.com/messages/filtered

**Comment by Schmavery** [comment]
Would it be enough to just let getThreadList accept "filtered" instead of "pending"?

**Comment by Theblood** [comment]
@Schmavery  @bobland1  this error :C
ERR! listen { error: 'type can only be one of the following: inbox, pending, archived, other' }
{ error: 'type can only be one of the following: inbox, pending, archived, other' }

**Comment by Schmavery** [comment]
Right, can you tweak getThreadList to accept "filtered" to check if it works?

**Comment by Theblood** [comment]
wow, sorry after reading error
find my solution ! is other == filtered!

**Comment by Schmavery** [comment]
Great! So this works when using "other"?

**Comment by bobland1** [comment]
@TheBlood, has that fixed your issue are we able to close this

**Comment by bsansouci** [comment]
@Theblood Closing since it seems like it's working.
