### ISSUE TITLE
ForceLogin Bugged??

### ISSUE THREAD

**Issue by bobland1** [Schmavery/facebook-chat-api#471]
I went to relaunch my chat bot, and he got this error. 
![image](https://cloud.githubusercontent.com/assets/25375432/25402931/5f1c4922-29f2-11e7-8bfa-f8ccc532ed29.png)
I then added the force login to the settings and ran the same, and i got the same message. I logged in to facebook with that account and it was suspicious about that login for some reason. I checked all the login activity and I am unsure why it blocked it as it was always logged in from that area. Anyway i checked it to say it was me and tried again. I removed the force login tried again same message, and tried with force login same message. I am not sure what todo at the moment. Is there a cooldown period in which once you confirm that logon was you it allows logging in from that area again? Thanks

**Comment by Schmavery** [comment]
forceLogin can only do so much if the account is temporarily blocked 😛 
There are a number of factors that can cause this to happen.  If you describe how you were using the api, there might be some suggestions we can give to avoid it.

**Comment by bobland1** [comment]
I havn't changed how i have used the api. Ive been using it the same code for ages now and havnt modified it in months. I went to edit from refresh tokens for a completely different api. And i go to test it and it blocks it. I very much doubt the api refresh token change was the issue. I have changed the password and confirmed emails etc. But i still get the message. What i think im going todo is leave it 24 hours and try again as i feel maybe there is a cooldown?

**Comment by bobland1** [comment]
On the DOCS it says the force login is meant to accept it. I am just unsure as to why i am able to log on from my local PC and phone but the api doesn't

**Comment by bobland1** [comment]
Ur forceLogin is out of date, just checked

**Comment by Schmavery** [comment]
Quite likely.  As I said, it should probably be deprecated.
Unfortunately it is very hard to debug issues with blocking.

**Comment by bobland1** [comment]
As i currently work through a AWS server im going to migrate over to my own physical, so ive installed a virtual desktop which should enable me to do it manually from that as i cant do it from my end as its blocking the servers access without the approval. Im going to close this but ill be sure to comment any further findings to see if the forceLogin can be updated in the foreseeable future.

**Comment by Schmavery** [comment]
Sounds good, thanks @bobland1
I've found running on some servers (that sometimes move around) tricky for this reason.

**Comment by bobland1** [comment]
I tried running from a different server, and the error still percists, what is your work arround

**Comment by Schmavery** [comment]
We run from a machine that we own.  Seems to work alright for the most part.  Logging in using appstate can also help sometimes.

**Comment by bobland1** [comment]
I can log onto different accounts fine, just seems to be this account when logging in with this api. Not sure what the issue is. I cant get an appstate sadly as i need to login first :D Not sure what todo, anything you would recommend?

**Comment by Schmavery** [comment]
It's possible that the account has been flagged in some way.  It's very hard for us to know what facebook is doing to detect automated use of their system (as this api is clearly going against intended use).  Not always much we can do.

**Comment by bobland1** [comment]
Yeah hmm, well we will have to wait aha
