### ISSUE TITLE
unable to set pageID

### ISSUE THREAD

**Issue by sachin221193** [Schmavery/facebook-chat-api#473]

**Comment by bobland1** [comment]
How do you mean you are unable to set pageID? Please send over some screenshots of the error and your code.

**Comment by sachin221193** [comment]
login(credentials,{pageID: 117374798819566}, function callback (err, api) {
    if(err) return console.error(err);

   api.setOptions({listenEvents: true});


when i use only credentials then chat bot work will fine . but after adding the pageID neitheir page nor user account act like bot.give no response ........i dont know where am gone worng .....in log i found no error

**Comment by bobland1** [comment]
Your error is this. You are putting the pageID in the login. Put the page ID in the setOptions

**Comment by sachin221193** [comment]
ohhh.....but 

Do you support sending messages as a page?
Yes, set the pageID option on login (this doesn't work if you set it using api.setOptions, it affects the login process).

login(credentials, {pageID: xxxxx}, function(api) { ... }

that thing  written in offical page or i am getting not your point.
can you please send the write the in line of code 
how could it be 
thanks in advance

**Comment by bobland1** [comment]
This could be in relation to #468, but not sure. Be sure to test what I have said. You can't send messages as a page in a group chat but you can using PM. From what I've tested

**Comment by bobland1** [comment]
Login(cresidenitals, function(api) { 
api.setOptions({
listenEvents: true,
pageID: 117374798819566
});
... }

**Comment by bobland1** [comment]
Is console.log(message) within the api.listen

**Comment by sachin221193** [comment]
no, i didnt even try ,but i should 
thanks for the advnce

**Comment by bobland1** [comment]
Be sure to reply with your findings

**Comment by sachin221193** [comment]
![chatbot](https://cloud.githubusercontent.com/assets/18134582/25479588/0978cafa-2b63-11e7-8cee-fe609deff718.jpg)

its seems request goes to page but doesnt get any response

**Comment by bobland1** [comment]
Can you do add logLevel verbose on for me please. This can be set through the setOptions

**Comment by bobland1** [comment]
It may be easier, but I am available on Skype if you want: bobland12 is my username.

**Comment by bobland1** [comment]
Also update to bleading edge, see if that fixes the issue. You can do this by 

npm install Schmavery/facebook-chat-api

**Comment by sachin221193** [comment]
i have already done npm install facebook chat api and log level verbose , & ping on skype

**Comment by bobland1** [comment]
I have added you, and i mean install the bleading edge. Not the npm version. 

Do
npm install Schmavery/facebook-chat-api

**Comment by Schmavery** [comment]
Thanks for the help with debugging this @bobland1, were you two able to come to any solution?
I have a fairly strong feeling this must be related to #468, so I'm going to close this and if you could continue any discussion there that would be great 😄
