### ISSUE TITLE
Can't add user to the group?

### ISSUE THREAD

**Issue by yellgreniff** [Schmavery/facebook-chat-api#478]
<img width="566" alt="screen shot 2017-05-01 at 9 37 24 am" src="https://cloud.githubusercontent.com/assets/25307389/25580830/e39dafd4-2e51-11e7-8809-df169494b8bd.png">
Help!

**Comment by bobland1** [comment]
Does this happen to everybody? Please send your code

**Comment by ravkr** [comment]
I wonder if sometime people will share their code without begging them for it...

**Comment by Schmavery** [comment]
@y9y9l5m6 does it work in the browser?  Can you check if the user actually gets added in the api even though there's an error?  Facebook's addUser is classically flaky
Also a code example would be great, as the others have mentioned 😄

**Comment by y9y9l5m6** [comment]
```
function add(name){
            api.getUserID(name, (err, data) => {
                const id = data[0].userID; //user id for input name
                existsInGroup(id, message.threadID, (exists) => {
                    if (exists) { //the user is in this group chat
                        api.sendMessage(name + " is already in this groupchat", message.threadID);
                    } else { //the user isn't in this group chat
                    // setTimeout(() => { //delay between messages
                    //     api.sendMessage("welcome, " + name, message.threadID);
                    // }, 1);
                    api.addUserToGroup(id, message.threadID);
                }
            });
        });
    }
```
I have no idea why this happens, was working a few days ago. recently it would work on a user once and never again.

**Comment by bsansouci** [comment]
Is this still happening? 
Is the person you're trying to add to a conversation someone you don't know? It might be that FB's preventing you from doing that...

**Comment by Schmavery** [comment]
It's been several months with no developments so I'm going to close this for now.  Feel free to reopen if you'd still like to continue diagnosing this issue.
