### ISSUE TITLE
Attachment upload breaks on a new version of 'request' module

### ISSUE THREAD

**Issue by blazeu** [Schmavery/facebook-chat-api#48]
The attachment didn't get uploaded when using ```request@2.59.0``` (latest version).
However when using ```request@2.58.0``` the upload still works.

**Comment by jackwilsdon** [comment]
Here's a list of the changes made from request 2.58.0 to 2.59.0: https://github.com/request/request/blob/master/CHANGELOG.md#v2590-20150720

Not sure what change could cause the upload to fail though.

**Comment by bsansouci** [comment]
[request@2.60.0](https://github.com/request/request/blob/master/CHANGELOG.md#v2600-20150721) fixes this. Closing now :)
