### ISSUE TITLE
Facebook-Chat-api not talking with Messenger Platform Bot

### ISSUE THREAD

**Issue by miketamis** [Schmavery/facebook-chat-api#484]
When i try to get the facebook-chat-api to send a message to a messenger platform bot, I get the following error
```
ERR! getUserInfo { __ar: 1,
ERR! getUserInfo   __sf: 'iw',
ERR! getUserInfo   error: 1357004,
ERR! getUserInfo   errorSummary: 'Sorry, something went wrong',
ERR! getUserInfo   errorDescription: 'Please try closing and re-opening your browser window.',
ERR! getUserInfo   payload: null,
ERR! getUserInfo   bootloadable: {},
ERR! getUserInfo   ixData: {},
ERR! getUserInfo   lid: '6422424341438859408' }
```

**Comment by Schmavery** [comment]
We have no tested support for this, as far as I know.  What is the usecase?

**Comment by miketamis** [comment]
The use case is to test a messenger bot in production to get response time stats

**Comment by hoangdevelopers** [comment]
I also have the same error when bot reply messenger.  i guess phantom had problem. but i dont know clear phantom cache
![image](https://cloud.githubusercontent.com/assets/12141921/26302635/156caaec-3f0f-11e7-9ce8-b5694694eb73.png)

**Comment by Schmavery** [comment]
@hoangdevelopers this api doesn't use phantomjs, I'm not sure what you're talking about.  This error is very generic.  Are you also trying to communicate with a messenger platform bot?

@miketamis I think it wouldn't be a bad thing to support this, but I don't currently understand how these messenger platform bots are implemented, so we need to do some investigation.  Can you open your browser dev tools and inspect the network calls that are made when sending a message to a messenger platform bot?  If you could share those with us, it might help.

**Comment by codeforequity-at** [comment]
Some input on this topic: my test automation framework TestMyBot (https://github.com/codeforequity-at/testmybot) supports running automated conversations against a messenger platform bot. I'm actually using this library for the nuts&bolts.
I built a sample project: https://github.com/codeforequity-at/testmybot/tree/master/samples/fbdirect

I didn't do anything special, just a plain sample Facebook Messenger Bot deployed on Heroku.

**Comment by Schmavery** [comment]
@miketamis any chance this is working for you now too?

**Comment by bsansouci** [comment]
Moving discussion to #500
