### ISSUE TITLE
getThreadInfo formerParticipants is null

### ISSUE THREAD

**Issue by alecmanabat** [Schmavery/facebook-chat-api#485]
After removing a user from a group, formerParticipants for that group is still null. How is this property updated and does Facebook even give this information? I tried looking into this myself but I wouldn't know how to test it and got confused since getThreadInfo uses getUserInfo but getUserInfo's info does have the same properties.

Thanks!

**Comment by mangopearapples** [comment]
Hi @alecmanabat. I don't think Facebook provides this information anymore. They probably used to but has either stopped tracking this information or removed it from their payload on their messenger platform.
