### ISSUE TITLE
api.getThreadHistory returns and empty array

### ISSUE THREAD

**Issue by leonardlabuneti** [Schmavery/facebook-chat-api#486]
api.getThreadHistory returns and empty array version 1.4.0 called like the docs
getThreadHistory(threadID, amount, timestamp, callback)

**Comment by mangopearapples** [comment]
Do you get any errors? Are you sure the threadID is correct?

**Comment by gamelaster** [comment]
:thinking:

**Comment by Schmavery** [comment]
@leonardlabuneti please show us a sample of non-working code 😄

**Comment by leonardlabuneti** [comment]
The function returns no error and an empty array, the threadID is correct and the same code used to return messages a few days ago. I will come back with my code example. Thank you

**Comment by leonardlabuneti** [comment]
api.getThreadHistory(threadId, 10, undefined, 
            function (err, response) {
                console.log('getThreadHistory got response :', err, response);
});

getThreadHistory got response : null []
error-> null,
response -> empty array

**Comment by bsansouci** [comment]
Mmmh I just tried here with one of my chats and it worked. 

Are sure there are any messages in that thread? Are you sure the bot is in the thread?

**Comment by leonardlabuneti** [comment]
There are messages in the thread and I am in that thread, I will double check my code. Good to know it works. 
PS which version are you using ? 1.3 or 1.4  ?

**Comment by bsansouci** [comment]
I'm using master actually. There are definitely issues depending on where you live though, since FB rolls out changes weirdly across the world. Seems like 1.4 also works for me.

**Comment by leonardlabuneti** [comment]
const login = require("facebook-chat-api");

login({email: "<yourFbEmail>", password: "<yourFbpassword>"}, (err, api) => {
    if(err) return console.error(err);
    // Here you can use the api

    var threadID = '<ContactFbID>';

    api.getThreadHistory(threadID, 10, undefined, (err, history) => {
            if(err) return console.error('Err',err);
             console.log('History:', history);
        });
});

Could someone try this code please ?

**Comment by leonardlabuneti** [comment]
I doublechecked the issue was my testing fb account, it looks like you get some kind of block if you hammer the fb servers.

thank you guys

**Comment by Schmavery** [comment]
Thanks for following up @leonardlabuneti.  As we state at the top of our README, facebook employs a number of rate-limiting measures to avoid people hammering them and this api explicitly doesn't attempt to circumvent them.
