### ISSUE TITLE
delivery_receipts 

### ISSUE THREAD

**Issue by JLarky** [Schmavery/facebook-chat-api#49]
this is what facebook sending:
![image](https://cloud.githubusercontent.com/assets/7026/8790023/beb3f976-2efd-11e5-85d5-03a75dad29a6.png)
difference from code:
https://github.com/Schmavery/facebook-chat-api/blob/master/src/listen.js#L124
index is constructed in different way, and no `dyn` parameter

also in code it does not check if message was sent from user itself (facebook.com does not send it)

**Comment by MarkehMe** [comment]
The _dyn parameter is in a lot of requests that I've seen, not sure what its used for - is it required?

**Comment by bsansouci** [comment]
Nope, __dyn isn't required and is also very hard to generate, which is why we're doing without it. I'm all in for being more similar to the browser. Marking this as enhancement:
- [ ] make the indices not skip some messages
- [ ] avoid sending read receipts for messages that the user sent

**Comment by Schmavery** [comment]
Incidentally, if someone figures out a clean way of generating __dyn, we'd definitely be into adding it to `mergeWithDefaults` (in the spirit of being more similar to the browser).

**Comment by bsansouci** [comment]
If someone can get that to work, without requiring 95% of FB's code base, I would personally fly to that person's house and have a beer with them.

**Comment by Schmavery** [comment]
@bsansouci is this fixed for v1.0?

**Comment by bsansouci** [comment]
Yes it is :)
