### ISSUE TITLE
How to listen for when a new user joins a group chat?

### ISSUE THREAD

**Issue by Ptomerty** [Schmavery/facebook-chat-api#492]
Title. Say I want a callback to fire when User A joins my existing group chat. How can I do this?

**Comment by Schmavery** [comment]
You should be able to enable listenEvents in [setOptions](https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#setOptions).  Then the listen callback will be called whenever an "event" happens.  Someone joining a group should be an example of this.
