### ISSUE TITLE
{ error: 'Wrong username/password.' }

### ISSUE THREAD

**Issue by zephiron4fun** [Schmavery/facebook-chat-api#496]
Sigh.. I have node version 8.1.2 and npm version 5.0.3, I think those are the latest.. I tried on Elementary OS (Freya) and on Windows 10, with the same npm and node versions and I can't get this to work.. I always have that "Wrong username/password", I've searched on google, but all the answers didn't work for me.. I even tried with "forceLogin" set to true, I don't know what to do anymore. Strangely, the python api works flawlessly.

**Comment by Schmavery** [comment]
I'm assuming you don't have 2FA set up? That hasn't worked for us for a while.
When you say the python api, do you mean this? https://github.com/carpedm20/fbchat
Our login code is some of the oldest code in the api and I wouldn't be surprised if parts of it have gotten out of date. It's really useful information for us to know that our api doesn't work but the python one does -- that means we have a problem in the api and it's not just your account, so thanks.
I'll have to see if I can make some time to see how our login flow differs from the python api.  If anyone else wants to take a crack at starting this, I will gladly shower you with emoji hearts.
Sorry about the hassle.

**Comment by zephiron4fun** [comment]
At first I didn't have the 2FA set up, and it didn't work.. I've even tried with that 2FA too see it I'll get lucky.. but it left me long time ago.

Yes, I meant that I used **(and it does work)** the Python API from this [fbchat](https://github.com/carpedm20/fbchat) link.

And as for that inspection of the login flow of the both API's I really can't do anything about it.. there's too much for me to comprehend.. I'm relatively new to Python as well as Javascript. I mean I use those, but I do not have that advanced level.. :(

**Comment by bsansouci** [comment]
@zephiron4fun This error really means your credentials were wrong. Could you show us the code you're using to login?

**Comment by zephiron4fun** [comment]
I was using the [code](http://imgur.com/tkCaKWG) below to connect to the server (with my real credentials of course) and got that annoying error everytime, it couldn't be my info, I checked that again and again.. even ran the same thing on different platforms (Windows 10 and Elementary OS Freya), but fortunately, right now, I witnessed a miracle when I tried to run it again.. and it's working perfectly. I don't know what caused that error, I didn't install/uninstall anything since, but I do remember that I was on my brother network that time.. which I think it's using a proxy.. could that be the the problem? 
![VSCode - Facebook JavaScript code preview](https://preview.ibb.co/cqNdAF/Capture.jpg)

**Comment by bsansouci** [comment]
Mmh that's really weird. I could only guess as to what FB's doing...
But glad to hear that it works!

If you ever get a chance, could you print the exact request sent by fb_chat compared to the one we send?

**Comment by Schmavery** [comment]
Going to close this as it seems like it was a transient issue....?  Please reopen if it becomes a problem again 😄

**Comment by Programmer1061** [comment]
I dont think thats facebook .

**Comment by ram-web-developer** [comment]
> Going to close this as it seems like it was a transient issue....? Please reopen if it becomes a problem again smile

Please fix this issue
