### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by MadeOke** [Schmavery/facebook-chat-api#5]
I use the example code
```javascript
var login = require("facebook-chat-api");

// Create simple echo bot
login("config.json", function(err, api) {
    if(err) return console.error(err);

    api.listen(function callback(err, message) {
        api.sendMessage(message.body, message.thread_id);
    });
});
```

And every time someone chat, memory goes up by 200Kb~1Mb

**Comment by matteocontrini** [comment]
You shouldn't worry too much about memory, since the garbage collector will make its work with unused heap references when the memory value overtakes a certain threshold.

**Comment by bsansouci** [comment]
We haven't looked into this yet, but it's possible that because of how we implemented `listen` the closure of the function gets bigger and bigger without us releasing any memory.
This needs further investigation :p

**Comment by Schmavery** [comment]
This may be a related issue: https://github.com/mjkaufer/Messer/issues/1

**Comment by bsansouci** [comment]
Closing this for now. No idea how to solve. Hopefully fixed accidentally. Feel free to re-open.
