### ISSUE TITLE
Attachments aren't properly implemented

### ISSUE THREAD

**Issue by bsansouci** [Schmavery/facebook-chat-api#50]
We [loop over attachments](https://github.com/Schmavery/facebook-chat-api/blob/cc92ab22ce07d004fa78829fe10ac59bdd7b4cf4/utils.js#L126-L158) but breaks, so it takes the first one that matches. This is not only wrong because you can send multiple attachments, but also because we make a hard distinction between `type`s of messages (`"message"`, `"sticker"`, `"file"`, `"photo"` and `"animated_image"`) and any of those can be sent in the same message.

I propose a pretty simple fix that keeps backward compatibility. We call the callback multiple times, with a `"message"` if there's one, and with each of the attachments independently.

Thoughts?

**Comment by blazeu** [comment]
...

If only we handle this the right way from the start, we could only have 2 or 3 message type ```"message"``` (with an array of attachments), ```"sticker"``` and  ```"event"```. That way, it'll be nicer.

Oh, also there's ```"url"``` attachment too.
![ss 2015-07-22 at 12 40 50](https://cloud.githubusercontent.com/assets/1438859/8818726/10776564-306f-11e5-8b1b-15693bfe7210.jpg)

**Comment by bsansouci** [comment]
Yeah I wish we hadn't done this this way, but I don't think we can afford to just break the API. The fix I proposed should be enough for now. We can maybe keep a list of features/fix we want and make a v2.0 with breaking changes. @Schmavery what do you think?

Also it seems like the `attach_type` is `"share"` and not `"url"  (on my end at least)

**Comment by blazeu** [comment]
Why not v1.0? We don't have that.

Sorry, I haven't checked it, but I've figured out how to **send** it tho. I might make a pull request soon.

**Comment by Schmavery** [comment]
I think the model that @blazeu described is a very good option.  There are a number of other breaking changes I've been considering, so maybe we can work on putting together a list to release all at the same time.
