### ISSUE TITLE
Logout no longer working

### ISSUE THREAD

**Issue by theweavrs** [Schmavery/facebook-chat-api#505]
So, here's what I did:

I logged in using the api and tried a few things out. One of which was `logout`. I noticed that that the URL: https://www.facebook.com/bluebar/modern_settings_menu/?help_type=364455653583099&show_contextual_help=1 returns nothing. It is a blank URL and as a result of that the logout feature doesn't work because it can't get the updated `fb_dtsg`, `ref` and `h` values.

Hope there is a fix and FB hasn't simply blocked things out...

**Comment by Schmavery** [comment]
Hmm, sometimes things like this happen where facebook changes some endpoint.  Thanks for reporting.
You can help us diagnose the issue and find a fix by opening your browser dev tools and inspect the network calls that are made when logging out in the browser.  If you can see what endpoint gets hit and which parameters are passed, we can update the call.

**Comment by theweavrs** [comment]
I actually did that before reporting the issue, here's the info:

```
General:
Request URL:https://www.facebook.com/logout.php?button_name=logout&button_location=settings

Query String Parameters:
button_name:logout
button_location:settings

Form Data:
fb_dtsg:AQHZKi3LlTSq:AQHguZJFO3u_
ref:mb
h:AfeR6sOJ5KClfudm
```

I logged out a couple of times and the `ref` is always the same i.e. `mb` whereas `h` and `fb_dtsg` do change.

**Comment by Schmavery** [comment]
Awesome, great investigation.  If we're lucky, h isn't even needed 😛 (that happens sometimes).

It actually looks like we might have all of these values already getting passed into the call in https://github.com/Schmavery/facebook-chat-api/blob/master/src/logout.js, would just take someone updating the url to the new one and seeing if it makes a difference.  Want to give it a shot and let us know if it works?

**Comment by theweavrs** [comment]
@Schmavery Nopes. Doesn't work without `h`. And the whole `parseAndCheckLogin` function is useless when it comes to the new endpoint (which isn't much different from the previous one). The url in of itself returns nothing so basically, it is a redirection endpoint.

I tried to send a POST request to this URL with `fb_dstg` and `ref` only but it keeps giving `https://www.facebook.com/home.php` as its `Location` header. So, it isn't working. If it was working it would have `https://www.facebook.com/` as its `Location` header.

So, without `h` we cannot logout the correct way.

**Comment by theweavrs** [comment]
@Schmavery Good news! I assigned a hard-coded value to `h (AfeR6sOJ5KClfudm)` and I was able to log out correctly. Perhaps, this is a token of some kind that expires...or not. Anyhow, I was able to log out. Perhaps, I should make a pull request?

**Comment by theweavrs** [comment]
As I suspected, all these values `fb_dtsg`, `mb`, and `h` are in the response of this URL:
```
https://www.facebook.com/bluebar/modern_settings_menu/?help_type=364455653583099&show_contextual_help=1&dpr=1.5
```
Yup. The old URI works. The problem, now I found was with the absence of some form values. This is how Facebook sends the POST request:

```
Form Data:
pmid: 0
__user:100001835677406
__a:1
__dyn:5V4cjEzUGByK5A9UrEwlg94qbxqbAKGiyEyfirWo8ovyui9zob4q2i5UK3u2CEaUZ1ebkwy6UnGieKcVrDG4XzEa8iGt0gKum4UpKqqbAWCDxi5UWaAz8gAxu1iyECQum2m4oqyU9omUmC-Wx2vgqx-Eth8gUK69K5EG2eVQh1q48a9EdV8CXx6WK64qdKbyaBy8OcxO12zUryoK7Uy5uayGVGwFxCQExyUy-fU
__af:j0
__req:6
__be:-1
__pc:PHASED:DEFAULT
__rev:3189742
fb_dtsg:AQE53kQ-t_p3:AQGuQiNp3on-
jazoest:26581695351107814511695112515865817111781105781125111111045
__spin_r:3189742
__spin_b:trunk
__spin_t:1501309013
```

And this is how `facebook-chat-api` sends the request:
```
Form Data:
pmid: 0
```

So, if you do fill all the form data, you do get a good and valid response. Of course, I have absolutely no idea where things like `__dyn`, `jazoest, and `__spin_t` are. Hope you have some idea.

**Comment by Schmavery** [comment]
Wow, this is super great investigation you're doing, we really appreciate it.  Some of those parameters we're familiar with.  And actually, as far as I can tell, we are currently sending a lot of those.  

The defaultFunc.post [here](https://github.com/Schmavery/facebook-chat-api/blob/master/src/logout.js#L15) is actually a call to [here](https://github.com/Schmavery/facebook-chat-api/blob/master/utils.js#L675), where we "mergeWithDefault" to add [these](https://github.com/Schmavery/facebook-chat-api/blob/master/utils.js#L626-L637).  That's not everything, but it's a decent starting point.  Some (like __dyn), we've never found made a difference (thought that could always have changed).

You could try printing the actual form that gets sent to fb if that helps troubleshoot: printing `form` [here](https://github.com/Schmavery/facebook-chat-api/blob/master/utils.js#L49) would probably do it.

I do see some values commented out in the defaults, @bsansouci probably knows more about those.

I'm not sure if we also need to send those values to the logout.php call... I see we're only using `utils.post` (no defaults included) [there](https://github.com/Schmavery/facebook-chat-api/blob/master/src/logout.js#L33).

**Comment by bsansouci** [comment]
I just tried it and could logout fine. Is this still an issue?

**Comment by theweavrs** [comment]
@bsansouci Nope. Closing.
