### ISSUE TITLE
Changing thread colour not working? 

### ISSUE THREAD

**Issue by bobland1** [Schmavery/facebook-chat-api#506]
Anyone else being not able to use the change colour feature? I don't reseave and error but nor does the bot change the thread colour?

**Comment by Theblood** [comment]
I have the same problem @bobland1 :'(

**Comment by bobland1** [comment]
Yeah it's confusing, I'll do some testing. See what is actually happening as at the moment it doesn't give either response (error / work)

**Comment by Schmavery** [comment]
Thanks for looking into it, let us know if you need help or find anything out.

**Comment by bobland1** [comment]
Nothing shows up even with verbose, not sure what's going on to be honest

**Comment by AstroCB** [comment]
I have been running into this issue as well for the past month or so. It appears only to be a problem for hex values that are not in the palette on the actual website/app UI, so Facebook may have altered their backend to prevent the usage of custom values outside of those provided by them.

If this is the case, it would be nice to be able to programmatically access these acceptable values in some way (whether as a string with the name of the color or a list of hex values).

**Comment by Schmavery** [comment]
Hmm, good to know @AstroCB .  Can you share one or two values that you've found work so that bobland1 can see if this is the issue?

**Comment by AstroCB** [comment]
Apologies, it appears that those values no longer work either.

If you'd like to test them yourself, you can try these colors (which are all in the palette): `#44bec7`, `#fa3c4c`, and `#d4a88c`.

**Comment by Schmavery** [comment]
I don't see any changes in my browser environment that would indicate this being broken.  Can someone experiencing this problem check what message is getting sent in the browser to change color?

**Comment by bobland1** [comment]
Mauf - Custom Messenger Colors was the way you were able todo it. That is now not working and the creator is working on a fix.

**Comment by bobland1** [comment]
Request URL:https://www.messenger.com/messaging/save_thread_color/?&dpr=1&source=thread_settings
Request Method:POST
Status Code:200 
Remote Address:157.240.1.18:443
Referrer Policy:origin-when-cross-origin
Response Headers
access-control-allow-credentials:true
access-control-allow-method:OPTIONS
access-control-allow-origin:https://www.messenger.com
access-control-expose-headers:X-FB-Debug, X-Loader-Length
cache-control:private, no-cache, no-store, must-revalidate
content-encoding:br
content-security-policy:default-src * data: blob:;script-src *.facebook.com *.fbcdn.net *.facebook.net *.google-analytics.com *.virtualearth.net *.google.com 127.0.0.1:* *.spotilocal.com:* 'unsafe-inline' 'unsafe-eval' fbstatic-a.akamaihd.net fbcdn-static-b-a.akamaihd.net *.atlassolutions.com blob: data: 'self';style-src data: blob: 'unsafe-inline' *;connect-src *.facebook.com *.fbcdn.net *.facebook.net *.spotilocal.com:* *.akamaihd.net wss://*.facebook.com:* https://fb.scanandcleanlocal.com:* *.atlassolutions.com attachment.fbsbx.com ws://localhost:* blob: *.cdninstagram.com 'self' chrome-extension://boadgeojelhgndaghljhdicfkmllpafd chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm;
content-type:application/x-javascript; charset=utf-8
date:Thu, 03 Aug 2017 17:58:57 GMT
expires:Sat, 01 Jan 2000 00:00:00 GMT
pragma:no-cache
status:200
strict-transport-security:max-age=15552000; preload; includeSubDomains
vary:Accept-Encoding
vary:Origin
x-content-type-options:nosniff
x-fb-debug:yiL/3O9vjYkNvlLhqSuYR7iEUVFRImcx2vAehxufBP91pDzGC1jYH1AxYGh4Q416UuEzgvNoap4YetP4wjJo/Q==
x-frame-options:DENY
x-xss-protection:0
Request Headers
:authority:www.messenger.com
:method:POST
:path:/messaging/save_thread_color/?&dpr=1&source=thread_settings
:scheme:https
accept:*/*
accept-encoding:gzip, deflate, br
accept-language:en-US,en;q=0.8
content-length:172
content-type:application/x-www-form-urlencoded
cookie:datr=y-BAWfdtPnQ42P_7ihBn8UfW; sb=AgPhWLmIA28_cHBojn-SncuT; lu=gA_hueyE2m3SaS8qbjE3D5FA; c_user=100007819751912; xs=11%3Aa2JhXTDNyxKfSw%3A2%3A1501328981%3A15073%3A4439; act=1501783076094%2F6; presence=EDvF3EtimeF1501783134EuserFA21B07819751912A2EstateFDutF1501783134900CEchFDp_5f1B07819751912F23CC
origin:https://www.messenger.com
referer:https://www.messenger.com/t/george.hine1
user-agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
Query String Parameters
view source
view URL encoded
(empty)
dpr:1
source:thread_settings
Form Data
view source
view URL encoded
color_choice:#FF0000
thread_or_other_fbid:100003111636488
__user:100007819751912
fb_dtsg:AQG-Le7gNcGS:AQF9fQ-ZiMGO
__a:1
__req:f
__be:0
__pc:EXP1:messengerdotcom_pkg


Found this

**Comment by Schmavery** [comment]
Can you include the form data?
Is there a repo somewhere for this "Mauf" tool with an issue open about this?  Would be useful to see what their solution is.

**Comment by AstroCB** [comment]
I think @bobland1 is talking about [this extension/app](http://mauf.me/), but there doesn't seem to be a repo for it.

**Comment by bobland1** [comment]
I am talking about that. 
![image](https://user-images.githubusercontent.com/25375432/28941849-392f90aa-7891-11e7-9bee-03748ae51391.png)

**Comment by Schmavery** [comment]
@bobland1 how do you know the creator is working on a fix?
I don't see anything that stands out to me that's wrong.. Looks like this requires some more investigation.  You can look at what we're doing [here](https://github.com/Schmavery/facebook-chat-api/blob/master/src/changeThreadColor.js) and see that we're using the right url and seemingly sending the right stuff.
Hmm

**Comment by ravkr** [comment]
I've been experiencing the same problem last month :(

**Comment by bobland1** [comment]
He states on the extension he is working on a fix

**Comment by bobland1** [comment]
On the chrome store

**Comment by bobland1** [comment]
I sense something is happening with messenger as a few things so far have become not working. Logout, colour, mentions. Could be updates for there official api...

**Comment by Schmavery** [comment]
It is pretty normal that they make changes at fb and we have to fix things as a result :)

**Comment by bobland1** [comment]
Good ol' zuccerburg. I'll keep an eye out for the functionality of the chrome extension as it does it the exact same way we do it.

**Comment by lyneca** [comment]
I've been screwing around for ten minutes. It looks like they're filtering and restricting the colours we can set the chat to so that we can only set it to the ones in the pallette.

This is very disappointing. Now my chats with black colours are in the same state as the ones from before they filtered the 'set emoji' endpoint - those have things like ¯\_(ツ)_/¯ appear when you press the 'like' button.

**Comment by AstroCB** [comment]
I can confirm that setting the color to hex values in the palette appears to be working now.

Here's a list of all the colors in the palette:

- `null` (the default blue)
- `#44BEC7`
- `#FFC300`
- `#FA3C4C`
- `#D696BB`
- `#6699CC`
- `#13CF13`
- `#FF7E29`
- `#E68585`
- `#7646FF`
- `#20CEF5`
- `#67B868`
- `#D4A88C`
- `#FF5CA1`
- `#A695C7`

Perhaps we could get these values stored in the package somewhere for easy access?

**Comment by Schmavery** [comment]
Sure, I could imagine someone adding an `api.threadColors` dictionary?  Failing that we could validate the colors used up front in the changeThreadColors call and throw an error if it'd not one of these, then document all the usable colors in the docs (probably useful regardless).

**Comment by AstroCB** [comment]
I'll see if I can add that in. 

It's also worth noting that although Facebook's backend stores the thread color hex with capital letters when selected from the palette (which is why I listed them that way), it requires them to be lowercase when setting it through the API. Perhaps we could `toLowerCase` inputs to make sure this isn't a problem (it seems to do nothing rather than error out if caps are used, similar to if a non-palette color is passed).

**Comment by Schmavery** [comment]
Ah, that's a very good observation regarding case.  Maybe that's what's been causing issues for people.  `toLowerCase`ing the hex inputs sounds very reasonable.

**Comment by Schmavery** [comment]
Should be fixed by #512, lmk if there are more problems :)
