### ISSUE TITLE
api.sendMessage with mentions no longer working

### ISSUE THREAD

**Issue by 7222-SIMON** [Schmavery/facebook-chat-api#507]
Some time within the last 2 days this function broke, and the API gets HTTP error 500, followed by error 404 when trying to send this message. Attached below is the GitHub sample code in the documentation.

```
const login = require("facebook-chat-api");

login({email: "EMAIL", password: "PASSWORD"}, (err, api) => {
    if(err) return console.error(err);

    api.listen((err, message) => {
        if (message && message.body) {
            // Getting the actual sender name from ID involves calling
            // `api.getThreadInfo` and `api.getUserInfo`
            api.sendMessage({
                body: 'Hello @Sender! @Sender!',
                mentions: [{
                     tag: '@Sender',
                     id: message.senderID,
                     fromIndex: 9, // Highlight the second occurrence of @Sender
                }],
            }, message.threadID);
        }
    });
});
```

**Comment by Schmavery** [comment]
Seems like we might be missing a new field "profile_xmd[i][type]".  In my tests so far it's always been equal to 'p'.  Do you want to try adding this line and seeing in it helps?
https://github.com/Schmavery/facebook-chat-api/blob/master/src/sendMessage.js#L262-L264

![image](https://user-images.githubusercontent.com/2154522/28946842-7a836be2-7861-11e7-9a84-38529bdcc177.png)

**Comment by 7222-SIMON** [comment]
Can confirm that this solves the issue for me.

**Comment by Schmavery** [comment]
Awesome!  Any chance you want to submit a PR with that change? :)

**Comment by Schmavery** [comment]
Thanks again @7222-SIMON :smile:

**Comment by kentnek** [comment]
Hi, this has stopped working again, although there's no error. 😢

**Comment by 23phy** [comment]
```javascript
switch (message.body) {
    case 'mention': {
        api.sendMessage({
            body: 'This is @you, and this is @me',
            mentions:
                [{
                    tag: '@you',
                    id: message.senderID,
                },
	        {
	            tag: '@me',
                    id: api.getCurrentUserID()
	        }],
        }, message.threadID);
    }
}
```

This works with the lastest Schmavery/facebook-chat-api

**Comment by shellcxd3** [comment]
@kentnek there seems to be a bug when tag is at offset 0
check issue #857 , I created a new PR for it #858.

**Comment by kentnek** [comment]
@shellcxd3 thanks! but I actually stopped using this library altogether as it seemed to cause my accounts to be flagged and banned by Facebook...
