### ISSUE TITLE
Is friend online?

### ISSUE THREAD

**Issue by sh5dow** [Schmavery/facebook-chat-api#509]
Hello guys!

I am wondering, is there a way of how to get friend's status? I mean if he is online or if he is offline?

I cant find it anywhere.

BR,
Daniel

**Comment by Schmavery** [comment]
If you enable "listenEvents" in [setOptions](https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#setOptions), you should get "presence" events which let you know when people log on/off. I don't think there's currently a way to directly query the status of a given person.

**Comment by sh5dow** [comment]
Thanks a lot for comment! Unfortunately it is not suitable for my application, so i guess i will have to find another way of getting it, if possible. Will update you, if i find anything. For the meantime, i will close the issue.

Thanks and take care!

**Comment by Hongarc** [comment]
You can use https://graph.facebook.com/fql to get "online_presence".
This API has pass and username so it can get token (not re-login , if you open "view-source:https://www.facebook.com/{{YourUsername}}"  you can find "access_token:"EAAAA...." )
I think it can  be new feature of this API.

**Comment by gamelaster** [comment]
Using graph is not good idea, mainly when this is unofficial "emulator" of Messenger chat. Easier is look `presence` events, and look the last active time.

**Comment by Schmavery** [comment]
Great, thanks for the tip @Hongarc! Hopefully this can help @sh5dow.
As alluded to by @gamelaster, any graph features won't be added to this api as there are already plenty of fb graph apis 😄
