### ISSUE TITLE
Kicking someone with api.removeUserFromGroup does not update participant information

### ISSUE THREAD

**Issue by jackwilsdon** [Schmavery/facebook-chat-api#51]
As the title states, kicking a user with `api.removeUserFromGroup` does not update `participant_ids` or `participant_names`.

Kicking a different user from the web interface updates `participant_ids` and `participant_names` fine, but the user who was kicked with `api.removeUserFromGroup` remains.

**Comment by Schmavery** [comment]
@bsansouci was work done on #31 that would cause this?

**Comment by bsansouci** [comment]
Not sure how you got this. Can you send a snippet of code? Works fine here.

**Comment by Schmavery** [comment]
I'm closing this for now, please reopen if necessary
