### ISSUE TITLE
Mentions not working

### ISSUE THREAD

**Issue by ritu99** [Schmavery/facebook-chat-api#513]
Mentions is undefined when receiving messages with mentions in them.

```javascript 
fb({email: username, password: password}, (err, api) => {
    fbapi = api;
    api.listen((err, event) => {
      if(event.type === "message"){
        console.log(event.mentions); 
```

**Comment by Schmavery** [comment]
I'm assuming you're on master?  This was just merged today. @cthuluhoop123

**Comment by cthuluhoop123** [comment]
Does the message contain any mentions?

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ritu99** [comment]
Using master fixed it  - thank you!

**Comment by cthuluhoop123** [comment]
Excellent

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
