### ISSUE TITLE
Multiple logins from the same computer blocked by Facebook.

### ISSUE THREAD

**Issue by mukulhase** [Schmavery/facebook-chat-api#515]
Unable to login to more than 10 accounts from the same computer. Facebook forces you to change your password. Any solutions?
Login [here](http://pebblemessenger.mukulhase.com) to understand the error.
It's a service that lets you send messages from your pebble watch.

**Comment by Schmavery** [comment]
If this is consistent and repros in the browser, there's not much we can do about it on the api end unfortunately.

**Comment by bobland1** [comment]
Same with me, Facebook IP bans. Change the IP and it should be fine. Sometimes anyway, I currently run from an AWS server so I made a new server and put it on that it didn't have the block message at first but a few days it did. May be due to the location as well, but I'm not entially aure.

**Comment by mukulhase** [comment]
@Schmavery I'll try to reproduce it on a browser.
@bobland1 Yeah, eventually, it will block new sign-ins. Thinking of using Tor-Requests in the library instead, so that it will keep cycling ip addresses.  Also looking into whether facebook drops these security measures when 2-factor login is enabled. In that case I can ask my users to just enable 2-factor.

**Comment by bobland1** [comment]
Have you found out is 2F helps?

**Comment by mukulhase** [comment]
No.

**Comment by knyzorg** [comment]
Something that I found is that if you just keep trying to login, it will eventually let you in. Maybe after 20 tries but it still lets you in.

**Comment by Schmavery** [comment]
Our goal isn't to circumvent facebook rate-limiting/abuse prevention strategies. This api logs in as a user account and is treated as such by facebook's backend.
