### ISSUE TITLE
sendMessage with attachment will send unordered `__req`

### ISSUE THREAD

**Issue by bsansouci** [Schmavery/facebook-chat-api#52]
If you look [here](https://github.com/Schmavery/facebook-chat-api/blob/cc92ab22ce07d004fa78829fe10ac59bdd7b4cf4/src/sendMessage.js#L29) you'll see that we call `mergeWithDefaults` (say `__req` is `"a"`) and then call `api.uploadAttachment`. The latter will also call `mergeWithDefaults` [here](https://github.com/Schmavery/facebook-chat-api/blob/cc92ab22ce07d004fa78829fe10ac59bdd7b4cf4/src/uploadAttachment.js#L18) (say `__req` is `"b"` now) and will send first, after which `"a"` is sent, out of order.

This is a little annoying because it could be caused anywhere due to the nature of how we "cache" the form first, and then send the request (in two steps). I'd love to fix this everywhere, but I'm not too sure how.

Thanks to @jlarky for finding this.

**Comment by Schmavery** [comment]
In this particular instance, can't it be fixed by uploading the attachment before we create the sendMessage form?  We could change our convention to only mergeWithDefault immediately before sending off a form.  Could we maybe even integrate it into the post?  Just spitballing.

**Comment by bsansouci** [comment]
We can't integrate into the post without being sure that it won't break certain post request that don't have all those fields. We don't know what FB's doing with our requests.

I think the only way would be to be very consistent, or have two different functions `post` and `postWithDefaults`.

**Comment by Schmavery** [comment]
I wouldn't be against a `postWithDefaults` to enforce consistency.  We could even go so far as to remove the ability to call `mergeWithDefaults` directly.
