### ISSUE TITLE
Auto reconnect on error

### ISSUE THREAD

**Issue by checkium** [Schmavery/facebook-chat-api#522]
Is it possible to make the API auto reconnect when it errors? I keep getting a lot of socket disconnected or 502 errors after some hours, and I need it to run continuously

**Comment by Schmavery** [comment]
I believe that @bsansouci is using pm2 or something similar to handle restarting after transient network issues.

**Comment by bsansouci** [comment]
Yup http://pm2.keymetrics.io
Really good stuff, just use that for those reconnections.
