### ISSUE TITLE
No longer able to use API: Cookie not in this host's domain

### ISSUE THREAD

**Issue by alecmanabat** [Schmavery/facebook-chat-api#524]
ERR! login Error: Cookie not in this host's domain. Cookie:www.facebook.com Request:www.messenger.com

Any idea what is causing this/how to fix?

**Comment by Schmavery** [comment]
If I remember right, we use messenger.com for some calls and facebook.com for other calls. Maybe we need to be more careful about what cookies we're sending. Seems strange though. Do you see this during a specific call?
cc @bsansouci

**Comment by alecmanabat** [comment]
I'm not sure when it occurs exactly, but seems to be right when the boot tries to log in. Can't do testing until later, but for now I attached a part of the console log that captures the error.
[max-chatbot-logs-1504799617701.txt](https://github.com/Schmavery/facebook-chat-api/files/1285686/max-chatbot-logs-1504799617701.txt)

**Comment by Schmavery** [comment]
Hmm ok, if this happens before login completes, that helps narrow it down a little. Thanks

**Comment by alecmanabat** [comment]
Thanks for looking into it, bot was running fine until last night. I can post my code too if the log isn't enough

**Comment by RandallKent** [comment]
I also started seeing this error on September 7th. 

A call to `getFriendsList()` results in:

```
ERR! login Error: Cookie not in this host's domain. Cookie:www.facebook.com Request:www.messenger.com
ERR! login     at CookieJar.setCookie (/app/node_modules/facebook-chat-api/node_modules/request/node_modules/tough-cookie/lib/cookie.js:941:13)
ERR! login     at CookieJar.setCookieSync (/app/node_modules/facebook-chat-api/node_modules/request/node_modules/tough-cookie/lib/cookie.js:1305:18)
ERR! login     at RequestJar.setCookie (/app/node_modules/facebook-chat-api/node_modules/request/lib/cookies.js:26:20)
ERR! login     at /app/node_modules/facebook-chat-api/utils.js:725:11
ERR! login     at Array.forEach (native)
ERR! login     at /app/node_modules/facebook-chat-api/utils.js:720:13
ERR! login     at tryCatcher (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
ERR! login     at Promise._settlePromiseFromHandler (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:507:31)
ERR! login     at Promise._settlePromiseAt (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:581:18)
ERR! login     at Promise._settlePromises (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:697:14)
ERR! login     at Async._drainQueue (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:123:16)
ERR! login     at Async._drainQueues (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:133:10)
ERR! login     at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)
ERR! login     at processImmediate [as _immediateCallback] (timers.js:383:17)
ERR! login  [Error: Cookie not in this host's domain. Cookie:www.facebook.com Request:www.messenger.com]
```

In the past when things break, I just generate a new AppState and am good to go. Not this time as I've documented @ https://github.com/Schmavery/facebook-chat-api/issues/139#issuecomment-328278345

**Comment by Schmavery** [comment]
Thanks for this investigation @RandallKent, this looks a little like some sort of hack on our end that must no longer work. @bsansouci do you remember why we're doing this?

**Comment by bsansouci** [comment]
I think it's because we're super inconsistent regarding whether we hit Facebook.com or messenger.com. We tried to cover our asses by doing that hack, which may or may not be correct anyway.
I vote for removing it if it works for you @RandallKent :)

**Comment by Schmavery** [comment]
@alecmanabat thanks for confirming the fix.
This generally seems good, if it breaks some obscure functionality, we probably need to fix that instead of leaving in this hack.

@RandallKent any chance we could convince you to submit a quick PR with the change?
