### ISSUE TITLE
Multiple message callbacks for listen

### ISSUE THREAD

**Issue by Vinetos** [Schmavery/facebook-chat-api#525]
Hey !
When we use the method `listen`, we can use only one callback.  

To explain, i have this example:
```javascript
api.setOptions({
        listenEvents: true,
        logLevel: "silent"
});
// After...
api.listen((err, message) => {
    console.log("not called");
});
api.listen((err, message) => {
    console.log("called");
});
```  
and the output is:
```  
info login Logging in...
info login Logged in
info login Request to reconnect
info login Request to pull 1
info login Request to pull 2
info login Request to thread_sync
info login Done logging in.
called
called
called
```

I think that's a good idea to add multiple 'listener' of message :)

**Comment by Schmavery** [comment]
Why can't you just handle the listening inside one callback?

**Comment by Vinetos** [comment]
If i made a listening system for my bot, i'll use one function per command:
!ping -> ping.js
!help -> help.js
etc...

It's better and easier. I think that i'm not alone which would be happy to have this feature

**Comment by Schmavery** [comment]
You can still have one function/file per command.
```
var functions = {
  '!ping': require('./ping'),
  '!help': require('./help'),
}
api.listen((err, message) => {
    if (functions[message]) {
        functions[message]();
    } else {
        console.log(message + " is not a function");
    }
});
```
Can you explain to me why something like this doesn't solve your problem?
