### ISSUE TITLE
Stop listening to message/event if I start chatting

### ISSUE THREAD

**Issue by scitbiz** [Schmavery/facebook-chat-api#530]
How can I know whenever I start chatting to stop the bot on the current thread?

**Comment by scitbiz** [comment]
For example: My friends started chatting with the bot. And after a sort conservation, I jump in. But the bot keep working so I want to stop it (only when I chat), and re-enable after the conversation.

So is it possible? Thanks in advance!

**Comment by Schmavery** [comment]
Have you tried playing with [selfListen](https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#setOptions)? It will let you listen to messages sent by the bot account.

Then there are at least 2 options I can think of:
- Have some chat command like "!botstart", "!botstop" or something that the bot can watch for and start/stop chatting as necessary.
- Have some fancy logic that watches messages sent by your own account (that the bot didn't send) and makes the bot be quiet for a while until it stops seeing messages sent by you.

**Comment by scitbiz** [comment]
Thanks, I will try both.

**Comment by Schmavery** [comment]
Great, feel free to reopen if necessary 😄 
If you get something cool working, you can also open a PR to add it to the list of projects on the readme!
