### ISSUE TITLE
Error Not logged in

### ISSUE THREAD

**Issue by tmagnier** [Schmavery/facebook-chat-api#531]
Hi, 

I have an issue since yesterday. Indeed, when I want to set a reaction to an message, create a poll or just get user info, I have this error in my logs : 

`ERR! setReaction { error: 'Not logged in.' }`

`ERR! getUserInfo Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.`

But I am connected yet : I can receive and send messages.

The problem is maybe caused by the api ? 

Thank you

**Comment by tmagnier** [comment]
@Schmavery Can't you help me?

I have try with a second account and I have the same issue ...

**Comment by bsansouci** [comment]
@tmagnier Thanks for reporting! Je vois que tu es français. On peut parler français si tu veux.
Est-ce que tu peux te login sur Chrome, ouvrir le developer console sur le tab "network" et mettre une reaction sur un message. Tu devrais voir un packet envoyer, est-ce que tu peux paste tout l''info a propos du GET request?

**Comment by tmagnier** [comment]
Oui ça sera plus simple pour moi merci beaucoup de m'aider en tout cas.

J'espère que c'est ce que tu voulais : 

`General:
Request URL:https://www.messenger.com/webgraphql/mutation/?doc_id=1491398900900362&variables=%7B%22data%22%3A%7B%22client_mutation_id%22%3A%220%22%2C%22actor_id%22%3A%22100015562514073%22%2C%22action%22%3A%22ADD_REACTION%22%2C%22message_id%22%3A%22mid.%24gAAY3g4cs435k3RJsQ1eq80YHgMOc%22%2C%22reaction%22%3A%22%F0%9F%98%A0%22%7D%7D&dpr=1.25
Request Method:POST
Status Code:200 
Remote Address:179.60.192.3:443
Referrer Policy:origin-when-cross-origin

Query String Parameters:
doc_id:1491398900900362
variables:{"data":{"client_mutation_id":"0","actor_id":"100015562514073","action":"ADD_REACTION","message_id":"mid.$gAAY3g4cs435k3RJsQ1eq80YHgMOc","reaction":"😠"}}
dpr:1.25

Form Data:
__user=100015562514073
__a=1
__dyn=7AgNeS-aF398jgDxKy1l0BwRAKGgS8zXrWo466EeAq2i5U4e2CGwEyFojyR88wPGii6FXDG4XzEa8iACwh9VobohyUCexi5Uuzaxa5U5S9J0Px66EK3PxqqUnyk6ErKu7E425EG2ut1O0xVUhCK6pES6aBy8pwnU-m5oCbwExnyAcKu13KcoKcU-26m4oszUmzUR0
__af=h0
__req=j
__be=-1
__pc=PHASED%3Amessengerdotcom_pkg
__rev=3318731
fb_dtsg=AQFAqvEhbxCn%3AAQHQr5trR-pv
jazoest=2658170651131186910498120671105865817281114531161148245112118
`

**Comment by bsansouci** [comment]
Je crois que ça été causé par https://github.com/Schmavery/facebook-chat-api/pull/527. Est-ce que tu peux remettre ces deux lignes et confirmer que ça marche?
On va essayer de trouver un fix au plus vite.

**Comment by tmagnier** [comment]
Alors en rajoutant la ligne : 
`      var c2 = c.replace(/domain=\.facebook\.com/, "domain=.messenger.com");		
      jar.setCookie(c2, "https://www.messenger.com");`

les réactions fonctionnent mais GetUserInfo toujours pas.

data:    bot.js:29326 - ERR! getUserInfo Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
data:    bot.js:29326 - ERR! getUserInfo     at /home/pi/Documents/MessengerBot/node_modules/facebook-chat-api/utils.js:727:42
data:    bot.js:29326 - ERR! getUserInfo     at tryCatcher (/home/pi/Documents/MessengerBot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
data:    bot.js:29326 - ERR! getUserInfo     at Function.Promise.attempt.Promise.try (/home/pi/Documents/MessengerBot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/method.js:31:24)
data:    bot.js:29326 - ERR! getUserInfo     at /home/pi/Documents/MessengerBot/node_modules/facebook-chat-api/utils.js:697:24
data:    bot.js:29326 - ERR! getUserInfo     at tryCatcher (/home/pi/Documents/MessengerBot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
data:    bot.js:29326 - ERR! getUserInfo     at Promise._settlePromiseFromHandler (/home/pi/Documents/MessengerBot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:510:31)
data:    bot.js:29326 - ERR! getUserInfo     at Promise._settlePromiseAt (/home/pi/Documents/MessengerBot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:584:18)
data:    bot.js:29326 - ERR! getUserInfo     at Promise._settlePromises (/home/pi/Documents/MessengerBot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:700:14)
data:    bot.js:29326 - ERR! getUserInfo     at Async._drainQueue (/home/pi/Documents/MessengerBot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:123:16)
data:    bot.js:29326 - ERR! getUserInfo     at Async._drainQueues (/home/pi/Documents/MessengerBot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:133:10)
data:    bot.js:29326 - ERR! getUserInfo     at Immediate.Async.drainQueues (/home/pi/Documents/MessengerBot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)
data:    bot.js:29326 - ERR! getUserInfo     at runCallback (timers.js:800:20)
data:    bot.js:29326 - ERR! getUserInfo     at tryOnImmediate (timers.js:762:5)
data:    bot.js:29326 - ERR! getUserInfo     at processImmediate [as _immediateCallback] (timers.js:733:5)

**Comment by bsansouci** [comment]
Ok parfait! On va fixer ça dès que possible :)

**Comment by Schmavery** [comment]
Note: This is a potential patch to the problem but not really a viable fix as it simply reverts the fix for #524

**Comment by Tasakafei** [comment]
Bonjour, cette erreur est toujours d'actualité pour l'envoie de reactions aux messages. Je l'ai fixed en local, il suffit simplement de changer l'URL, c'est dorénavant : https://www.facebook.com/webgraphql/mutation/ (dans le fichier sendMessageReaction).

**Comment by ravkr** [comment]
@Tasakafei english please...

**Comment by bsansouci** [comment]
@ravkr lol calm down the whole thread is in French :p

@Tasakafei C'est juste un URL change? Est-ce que tu peux ouvrir un PR, on le merge directe.
