### ISSUE TITLE
getThreadInfo imageSrc undefined

### ISSUE THREAD

**Issue by Beaudan** [Schmavery/facebook-chat-api#532]
Trying to get chat thread icons displaying in an app and was getting undefined for the imageSrc, tracked it down to this line (43) in getThreadInfo.js:
`threadData.image_src = userData != null && userData.thumbSrc != null ? userData.thumbSrc : threadData.imageSrc;`

threadData.imageSrc doesn't seem to exist (plus would be pretty redundant if it did), pretty sure it is simply mean to be:
`threadData.image_src = userData != null && userData.thumbSrc != null ? userData.thumbSrc : `**`threadData.image_src;`**

With this change everything works as intended for my application.

**Comment by Schmavery** [comment]
Thanks for catching this and tracking down the cause.
For a while I was thinking thumbSrc looked wrong as well, but [apparently not](https://github.com/Schmavery/facebook-chat-api/blob/master/src/getUserInfo.js#L16).

Can you submit a quick PR for this? Thanks again!
