### ISSUE TITLE
ETIMEDOUT error mostly with sendMessage

### ISSUE THREAD

**Issue by KevinSalmon** [Schmavery/facebook-chat-api#535]
For several weeks, my app has random timeouts errors mostly when it calls sendMessage with an attachment. Therefore, this happens sometimes with login or when sending a simple text message.

> ERR! uploadAttachment Error: ETIMEDOUT
> ERR! uploadAttachment     at Timeout._onTimeout (/app/node_modules/request/request.js:846:19)
> ERR! uploadAttachment     at ontimeout (timers.js:386:11)
> ERR! uploadAttachment     at tryOnTimeout (timers.js:250:5)
> ERR! uploadAttachment     at Timer.listOnTimeout (timers.js:214:5)
> ERR! uploadAttachment  { Error: ETIMEDOUT
> ERR! uploadAttachment     at Timeout._onTimeout (/app/node_modules/request/request.js:846:19)
> ERR! uploadAttachment     at ontimeout (timers.js:386:11)
> ERR! uploadAttachment     at tryOnTimeout (timers.js:250:5)
> ERR! uploadAttachment     at Timer.listOnTimeout (timers.js:214:5)
> ERR! uploadAttachment   cause:
> ERR! uploadAttachment    { Error: ETIMEDOUT
> ERR! uploadAttachment        at Timeout._onTimeout (/app/node_modules/request/request.js:846:19)
> ERR! uploadAttachment        at ontimeout (timers.js:386:11)
> ERR! uploadAttachment        at tryOnTimeout (timers.js:250:5)
> ERR! uploadAttachment        at Timer.listOnTimeout (timers.js:214:5) code: 'ETIMEDOUT', connect: true },
> ERR! uploadAttachment   isOperational: true,
> ERR! uploadAttachment   code: 'ETIMEDOUT',
> ERR! uploadAttachment   connect: true }

**Comment by bsansouci** [comment]
Hey thanks for reporting this error, could we have the full stack trace? I'm not sure why uploadAttachment is getting called here.

**Comment by KevinSalmon** [comment]
Finally the error disappeared the next day, strange.
