### ISSUE TITLE
Quick Reply

### ISSUE THREAD

**Issue by chaze117** [Schmavery/facebook-chat-api#537]
Hi! 

Is this possible to send a message with Quick Reply?
Like this: 
![choices](https://user-images.githubusercontent.com/304397/31546803-34608a86-b025-11e7-949d-d7dbcf160bfc.PNG)

**Comment by Schmavery** [comment]
If there's a way for a user to send a message like that then it might be possible to support.
Otherwise you probably want to be using this: https://developers.facebook.com/docs/messenger-platform/send-messages/quick-replies
