### ISSUE TITLE
Getting { error: 'Not logged in.' }

### ISSUE THREAD

**Issue by RtzLi** [Schmavery/facebook-chat-api#539]
This error occurs when I try use changeThreadEmoji(), changeNickname() and changeThreadColor(). The functions do not work and just return an object saying { error: 'Not logged in.' }
![image](https://user-images.githubusercontent.com/30946735/31583572-0360bf3e-b1ea-11e7-98ff-ab98396970e4.png)

**Comment by knyzorg** [comment]
Check out #531 and #536

**Comment by RtzLi** [comment]
@knyzorg thanks for the advice. I can see that we are having some issues with some people not being able to log in with the code from #536. I would just like to confirm that I am having no issues with using the code from #536, and I would advise others to use it unless it causes problems.
