### ISSUE TITLE
Add support for "waving with hand"

### ISSUE THREAD

**Issue by tokelpl** [Schmavery/facebook-chat-api#541]
Like in title

**Comment by gamelaster** [comment]
It's already implemented in Browser-based Messenger? I saw this feature only on mobile-based messenger. It's required to have this feature in Browser-based Messenger

**Comment by tokelpl** [comment]
It is in web Messenger, when i will be back home, i will send screenshot

**Comment by Schmavery** [comment]
I can't see it in my web messenger, feel free reopen with more details or a PR :wink:

**Comment by Bjornskjald** [comment]
@Schmavery @gamelaster I could update this issue with an example request, will it be enough to implement it?

**Comment by baptx** [comment]
@ravkr do you remember what was the URL of the HTTP request? Facebook Messenger removed the wave feature this year but maybe it is just hidden and the API call still works.
