### ISSUE TITLE
Is it possible to view the "previous" message?

### ISSUE THREAD

**Issue by Ptomerty** [Schmavery/facebook-chat-api#543]
Say a bot receives message A1. Is it possible to find the message directly before, some A0?

Example:

Joe: message1
Bob: message2

On "message2", find the message message1.

Is there a way to do that now, or should I just cache the previous message?

**Comment by Schmavery** [comment]
You can take the timestamp of the message and use it to call the [getThreadHistory](https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#getThreadHistory) function with `amoun`t set to 1.  They're ordered from oldest to newest so the one you want should be the first one in the array.
```javascript
var stopListening = api.listen(function(err, event) {
    if(event.type === "message") {
      api.getThreadHistory(event.threadID, 1, event.timestamp, function(err, data) {
        if (err) {
          throw err;
        }
        
        let previousMessage = data[0];
      });
    }
  });
```
