### ISSUE TITLE
error by receiving a thumb

### ISSUE THREAD

**Issue by txs** [Schmavery/facebook-chat-api#545]
I think it might happened with the issue that the thumb sticker is just a image

ERR! listen Error: unrecognized attach_file `{"sticker_attachment":{"id":"369239263222822","pack":{"id":"227877430692340"},"label":"Like, thumbs up","frame_count":1,"frame_rate":83,"frames_per_row":1,"frames_per_column":1,"sprite_image_2x":null,"sprite_image":null,"padded_sprite_image":null,"padded_sprite_image_2x":null,"url":"https://scontent.xx.fbcdn.net/v/t39.1997-6/851557_369239266556155_759568595_n.png?_nc_ad=z-m&_nc_cid=0&oh=8bfd127ce3a4ae8c53f87b0e29eb6de5&oe=5A761DDC","height":70,"width":70}}`

**Comment by Schmavery** [comment]
Hmm, looks like facebook must be making some changes to the format of attachments (see #544 also)
Do you also get an error when sending just an image (not a sticker)?

**Comment by txs** [comment]
I haven't try it. I'll do it and give you the test result.

**Comment by RtzLi** [comment]
Hello, from my testing facebook seems to have changed the json format for all attachments. I have included some json results for most of the attachment types in the file attached here.

[attachments.txt](https://github.com/Schmavery/facebook-chat-api/files/1423897/attachments.txt)

Right now it looks like the entire _formatAttachment function will have to be rewritten.

**Comment by Schmavery** [comment]
Great, thanks a lot guys.  I'm going to merge this into #544 to track progress.
