### ISSUE TITLE
Reliable friend monitoring.

### ISSUE THREAD

**Issue by Qualitymix** [Schmavery/facebook-chat-api#549]
So am I missing it or is there currently no way of properly maintaining a consistent list of online friends?

using the api.listen with updatePresence option on,  I get two statuses: 0 for offline and 2 for online.
Problem is, about every 2 minutes, facebook sends an "update", and if I'm understanding it correctly, it's using 0 to indicate that the user's status hasn't changed.  

That makes it near impossible, as far as I can tell, to reliably monitor who is classified as 'online' or 'offline'.

Am I missing something?

**Comment by Schmavery** [comment]
It's possible there is a bit of a problem in the current user status code. I'll try to give some background of the current state.
There are two kinds of messages we are getting from facebook that we are returning as status updates. If I remember right, one is called "buddylist_overlay" and one is "chatproxy-presence". As far as I understand, the former is the more reliable one, that gives you information about people logging in and out.  The latter was added in #413 in an attempt to gain more up-to-date presence information, but has been problematic since then for various reasons.
There is an open PR #464 that half-fixed this issue, but unfortunately was abandoned before implementing the full solution explained [here](https://github.com/Schmavery/facebook-chat-api/pull/464#issuecomment-293328225). Unfortunately I never got around to fixing it myself but I'd definitely be happy to help anyone who wanted to give it another shot.

**Comment by Qualitymix** [comment]
Is there a way to detect the difference between when FB is throwing you an automatic update, versus when receiving an actual user generated event?

**Comment by bobland1** [comment]
What would be cool is to if we were able to request it. So having the ablity to on command check all users previous login state

**Comment by Schmavery** [comment]
@Qualitymix the answer is that no, something equivalent to #464 needs to be fixed and merged.
@bobland1 This would increase the complexity of the api to cache this information, so it's fairly unlikely I'll add it any time soon. We try pretty hard to avoid doing any caching on our end because of the unpredictable and hard-to-diagnose problems it can cause.

**Comment by forcemagic** [comment]
Any news on this? Will #464 be merged or are there any plans for some kind of graphql magic? Also, what's up with that "last active 6m ago" thing that shows up when I click on someone?

I'll happily implement something if needed, I just want some pointers on what to do. :smiley:

**Comment by Schmavery** [comment]
@forcemagic  I don't have much time to implement/test many api fixes these days unfortunately, so I haven't been able to pick up the ball on #464. That said, I think the design I described there still applies, assuming we're still getting spammed by those events.

I would be happy to help answer questions and get it merged if you want to work on this.

Not sure what you're referring to with the "last active" thing. It seems like the presence object tries to return a timestamp, which might be what you want (assuming it's populated).

**Comment by forcemagic** [comment]
@Schmavery I'm at the "planning" stage, which means Chromium, developer tools and whatnot, and waiting for Facebook to do its magic... So basically, my plan is to rewrite the whole presence parsing thing and make it simpler if that's possible. Here's just a little dump of what I found out today.

## :warning: Excessively verbose dump starts here :warning: 

The event `chatproxy-presence` is for returning "last active times" for ALL of your friends. This is stored in a variable called `lat`. (Who would've guessed? **LAT** = **L**ast **A**ctive **T**ime) Example:

![chatproxy-presence](https://user-images.githubusercontent.com/25160976/35286751-af552518-0015-11e8-9f91-85e9878c3ca3.png)

Notice however that there are `p` and `vc` variables on the last user. If `p` is present AND it's set to 0, the user **went offline** at max 20-30 minutes before the chatproxy broadcast. If it's set to 2, then the user is currently **online**. The `vc` variable.... I have absolutely no idea. Its values are usually `0`, `10` and `74`. **It's important to keep in mind that these are just assumptions**

The next event we have is `buddylist_overlay`. This event represents one user going either online or offline. We have the same "last active time" here, but instead it's in `la` and it **SHOULD** (in theory) match the time right NOW. Example:

![buddylist_overlay](https://user-images.githubusercontent.com/25160976/35287622-9858cb6a-0017-11e8-99a9-58033984b35f.png)

I'm just gonna make a quick table explaining all these _compacted_ variables:

|Name|Type|Value(s)|
|--------|------|------------|
|`a`|Integer|`2` for online, `0` for offline|
|`c`|Integer|I absolutely have no idea. (And it's not even always present!)|
|`la`|Integer|Last online time, should be approximately equal to `new Date().valueOf()/1000`|
|`s`|String|`push` always|
|`vc`|Integer|Mentioned it before, still gets the same values, and I still don't know what to do with it.|

### Now with all this information, I can start implementing.

**Comment by gamelaster** [comment]
@forcemagic doesn't https://github.com/Schmavery/facebook-chat-api/pull/413 doing the same?

**Comment by forcemagic** [comment]
@gamelaster Not really. My idea is that we should have either:

1. Two events for presence:

   - One for the `chatproxy-presence` (the spammy stuff), and it should return something like this:

      ```json
      {
          "statuses": "<presenceObj.p>",
          "timestamp": "<presenceObj.lat>",
          "userID": "<presenceObj.key>",
          "type": "proxy-presence",
      }
      ```

      _The `p` (or `statuses`) should be left as-is_, if it's not present it should be `undefined` or `null`. This makes sure that if the client wants to calculate with this value, `null` should indicate a "not changed" state.

   - One for the `buddylist_overlay` like this:

      ```json
      {
          "statuses": "<presenceObj.a>",
          "timestamp": "<presenceObj.la>",
          "userID": "<presenceObj.key>",
          "type": "buddy-presence",
      }
      ```

   Then end-user should be able to disable both of these in the [config](https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#setOptions).

2. One event for the presence:
   And fire the `chatproxy-presence` events **only at the first time**. This ensures that the end-user (or bot) has a basic knowledge of everybody's presence in the friend list. If - while the API is `listen()`-ing - a user's presence _changes_, the `buddylist_overlay` should be able to inform the end-user (or bot) about the change. There's no need for any more `chatproxy`ing.

For both solutions (and I recommend doing this ASAP), a documentation clarification is in order: the `timestamp`'s description is the following:

> How old the presence information is.

This is ambiguous as it can both mean the exact time the according information was _retrieved_ and it can also refer to the real meaning: when the user was last online. So I guess it would be more appropriate to rename it to something like:

> The time when the user was last online

**Comment by gamelaster** [comment]
Well, it was long time ago, but since my pull request has been merged, the `chatproxy-presence` has been implemented into `presence` event when `updatePresence` is enabled, so... this is already done

**Comment by forcemagic** [comment]
@gamelaster My point was being unable to **differentiate** between the 2 types of presences. 

> This is the main problem with the current implementation: you can't decide whether 0 is just a not changed value or a went offline value.

**Comment by Schmavery** [comment]
Hey @forcemagic!
We really appreciate your time and input.
If there's an easy clarification to the docs we can make right now, please feel free to submit a quick PR and we can get that merged!

Originally, I was hoping we could just have one kind of presence event, for better forward compatibility with whatever facebook decides to do. Unfortunately, the "new" kind of presence can be a little spammy, which is more or less the subject of this issue.

As a solution to this "problem" is concerned, if people in general can agree that we only need the noisier chatproxy-presence events the first time it fires, that sounds like a possible solution.

However, for simplicity, I've been recommending a 2-event approach for several months on this issue, as you can see here: https://github.com/Schmavery/facebook-chat-api/pull/464#issuecomment-293328225

Assuming nothing has changed in facebook's behaviour on these functions, all that remains is for someone with a little time to implement it. @forcemagic if you're interested I'd be happy to review the change.

**Comment by forcemagic** [comment]
@Schmavery I'm happy to implement the changes, but we need to somehow agree on the design. Basically there's the two-event approach, and there's the non-splitting approach with the _fire-only-first-chatproxy_, which only needs minor tweaking. This needs extensive testing as we do not yet know whether Facebook fires **every** presence change in the `buddylist` way. About the docs.. I'll get right to it :smiley:

**Comment by Schmavery** [comment]
I think that either fix is an improvement on what we have now so right now I would greenlight whichever you think best. If someone who uses the api has a different opinion, they can obvs feel free to make it known.

If you get partway through an implementation and get stuck on some decision, feel free to push what you have to a PR and I can take a look and we can talk about it.
