### ISSUE TITLE
Login fail

### ISSUE THREAD

**Issue by senhly** [Schmavery/facebook-chat-api#55]
I've just play around with this API for few day, it's fun but today i got login error. I find out that facebook redirect to https://www.facebook.com/common/invalid_request.php?__req=5 when I login. Anyone know why? on version 0.2.10

**Comment by bsansouci** [comment]
Are you on v0.2.11? We just fixed a login issues yesterday.

**Comment by Schmavery** [comment]
Please reopen this if there is still an issue after updating to 0.2.11. :)

**Comment by senhly** [comment]
I can't login when I enable option <b>login approvals </b>
![login-approval](https://cloud.githubusercontent.com/assets/2818416/9083089/7580dd40-3b92-11e5-8adb-722994895f1e.PNG)

**Comment by blazeu** [comment]
See #22 and #53

**Comment by Schmavery** [comment]
@senhly Login approvals are now supported in the prerelease branch.  Give it a try!
