### ISSUE TITLE
Receiving messages with attachments such as stickers or pictures

### ISSUE THREAD

**Issue by unipeg** [Schmavery/facebook-chat-api#557]
I've tried the simple [chatbot](https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#apisetoptionsoptions) from the docs.
It works fine, as long as messages are plain ol' text without attached GIFs, pictures or anything fancy. When this happens, I receive a flood of error messages of the type:

`[Error: unrecognized attach_file `{"sticker_attachment":  ...`

I use the latest version (1.4.0).

Is this a bug or am I using it wrong?

**Comment by theweavrs** [comment]
The API has changed.

**Comment by unipeg** [comment]
Meaning?

**Comment by theweavrs** [comment]
@unipeg Meaning that almost everything related to attachments need to rewritten. The whole structure of the response message has changed.

**Comment by unipeg** [comment]
Ok. I did manage to work around the issue with caching the error and
logging on again. But very nice.

Is the rewriting in progress already?
ons. 15. nov. 2017 kl. 14.26 skrev theweavr <notifications@github.com>:

**Comment by theweavrs** [comment]
@unipeg Don't know. You will have to ask @Schmavery.

**Comment by mitchcapper** [comment]
@theweavrs @unipeg yes it has been check master, we are working to finalize a few other items right now for more-stable handling of api changes but master has been updated in the mean time.

**Comment by Schmavery** [comment]
@unipeg sorry about this, please bear with us as we try to get this stabilized.  I've unfortunately been pretty busy so still trying to make time to get on top of these attachment issues.

**Comment by Abgaryan** [comment]
@Schmavery  Any updates form the issue?

**Comment by txs** [comment]
@Schmavery  Any updates?

**Comment by Schmavery** [comment]
Sorry about this one everyone, forgot this issue existed somehow. I think (gee I hope) this should be improved now, but let us know if not.
