### ISSUE TITLE
getThreadInfo() failing with 404

### ISSUE THREAD

**Issue by ivkos** [Schmavery/facebook-chat-api#559]
`getThreadInfo()` fails with this 404 error:
```
Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
    at ...\project\node_modules\facebook-chat-api\utils.js:843:42
    at tryCatcher (...\project\node_modules\facebook-chat-api\node_modules\bluebird\js\main\util.js:26:23)
    at Function.Promise.attempt.Promise.try (...\project\node_modules\facebook-chat-api\node_modules\bluebird\js\main\method.js:31:24)
    at ...\project\node_modules\facebook-chat-api\utils.js:813:24
    ...
```

I'm using the latest master and running this on node v8.9 on Windows. Let me know if there's additional info I can provide to help debug this.

**Comment by SomewhatDisoriented** [comment]
I get an identical error for both getThreadInfo and getThreadHistory as of one or two days ago.

**Comment by ivkos** [comment]
Enhancements in PRs #560 by me and #556 by @KevinSalmon will hopefully make the *GraphQL functions good-enough replacements for the old ones.

**Comment by federico-fiorini** [comment]
@ivkos I'm getting the same error. Are the new * GraphQL versions available already?

**Comment by Qualitymix** [comment]
This doesn't seem to fix it for me?  Does this still work for you?

**Comment by bsansouci** [comment]
@Qualitymix Are you saying that the graphQL functions do not work for you?

**Comment by Qualitymix** [comment]
Actually, it seems they do.   The code I was calling to invoke getThreadInfo and getThreadHistory is apparently now deprecated.   Is there any documentation on how to use these new getThreadInfoGraphQL and getThreadHistoryGraphQL?   I hope I don't just have to type random function names to figure it out!

**Comment by ravkr** [comment]
Well.. these are still in beta so there is no documentation, you just have to look at code

**Comment by Schmavery** [comment]
@bsansouci ^

**Comment by ravkr** [comment]
as `getThreadInfo` uses GraphQL, we can close it @Schmavery
