### ISSUE TITLE
Creating a Group Chat

### ISSUE THREAD

**Issue by Schmavery** [Schmavery/facebook-chat-api#56]
It seems we don't support creating a new group chat.  It might be possible to do it with `api.addUserToGroup`, but it's still not clear what to set as the `thread_id` and what the id of the new group chat will be.

**Comment by JoseRoman** [comment]
The ID of chat group seem to be "Conversation-Thread_ID"

**Comment by Schmavery** [comment]
This should be fixed by 7c88010 in v1.0
