### ISSUE TITLE
getThreadHistory Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response

### ISSUE THREAD

**Issue by kobihoang** [Schmavery/facebook-chat-api#561]
getThreadHistory Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response

**Comment by Qualitymix** [comment]
Yep, same here

**Comment by jrwiebe** [comment]
I encountered this yesterday. Apparently `getThreadHistory` has been causing problems [for over six months](https://github.com/Schmavery/facebook-chat-api/search?utf8=%E2%9C%93&q=getThreadHistory&type=). I recommend switching to `getThreadHistoryGraphQL`.

 I assume `getThreadHistory` will soon be deprecated -- or perhaps replaced with the GraphQL version?

**Comment by anirudhaima** [comment]
same issue

**Comment by ravkr** [comment]
getThreadHistory uses GraphQL now
@Schmavery, we can close it
