### ISSUE TITLE
Problem parsing message object: TypeError: Cannot read property 'image' of null

### ISSUE THREAD

**Issue by warhost** [Schmavery/facebook-chat-api#563]
Hey,

when people send links which get rendered within the chatbox with their open-graph stuff, I am sometimes getting this error.

```
{ error: 'Problem parsing message object. Please open an issue at https://github.com/Schmavery/facebook-chat-api/issues.',
  detail: TypeError: Cannot read property 'image' of null
    at _formatAttachment (/opt/app/node_modules/facebook-chat-api/utils.js:448:44)
    at attachments.map.v (/opt/app/node_modules/facebook-chat-api/utils.js:502:55)
```

I am wondering if there would be the possiblity of having a `listen` method which does not try to parse. I am mainly using it to get threadIDs from the message objects, but it often fails due to the stuff goin gon in utils, this being one example. Is there a better way if I am just interestd in the threadID of incoming messages?

**Comment by Schmavery** [comment]
If you used the npm version when getting this error, please try updating and see if you still get this error. We fixed a lot of attachment issues :)
