### ISSUE TITLE
getThreadInfo API is broken

### ISSUE THREAD

**Issue by tarungog** [Schmavery/facebook-chat-api#567]
Looks like the threadinfo request runs into a 404 -- the URI must be old or broken. Does anyone know a workaround for this?
```
ERR! getThreadInfo Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
```

**Comment by Schmavery** [comment]
There's getThreadInfoGraphQL which unfortunately is not yet documented @bsansouci

**Comment by tarungog** [comment]
@Schmavery thank you; works great on master. Please cut a 1.5.0 tag including these graphQL api variants soon!

**Comment by bilyanhadzhi** [comment]
@Schmavery I'm having some errors with getThreadHistoryGraphQL currently, any ideas?

![screenshot_20180110_221435](https://user-images.githubusercontent.com/17789351/34793432-023524ac-f654-11e7-8e51-23219c6092f0.png)

**Comment by adminy** [comment]
ThreadInfoGraphQL is working in giving you a pretty up to date info, what I found strange is that you get unread messages but they are your unread messages, what about the person you talk to unread messages? Messenger has it, even facebook, why doesn't this API have anything for it?

**Comment by ravkr** [comment]
is everything okey now? can we close?

**Comment by Schmavery** [comment]
@tarungog getThreadInfo has been updated in npm and github to use the graphql version. :)
