### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by senhly** [Schmavery/facebook-chat-api#57]
I've tried to logout by clear cookie(set <b>ctx</b> to default value) but I don't think it is a good solution. I think we can logout through http://www.facebook.com/logout.php.
It seem facebook require parameter <b>fb_dtsg</b>,<b>h</b> and <b>ref</b> and then redirect to https://www.facebook.com/?stype=lo&jlou=...&smuh=....&lh=...
Does anyone know where is parameter <b>h</b> hiding? little help plz

**Comment by Schmavery** [comment]
I agree that we should have this feature.  If you give us a couple days, we can probably find the time to look at it a little more closely.  We'll have to check exactly what information is being sent in the form before we can know how to emulate it.

**Comment by senhly** [comment]
Cool ! now we can logout. :D
:( 
but the request after logout, facebook will ask for login to continue and next request will response html document so it cause error in <b>parseResponse</b>. any idea?

**Comment by Schmavery** [comment]
@bsansouci now that you made the [change](f957e85) that all errors throw exceptions, can we simply throw an error "User Not Logged In" or something in `parseResponse`?

**Comment by bsansouci** [comment]
@senhly what function does the request _after_ you've logged out?

@Schmavery though it would make sense in this case, I don't think it's a good error message. `parseReponse` makes the assumption that it receives JSON and it gets html, which can be caused by many things. 
We should be catching any error that parseResponse throws and calling the callback with it, so if you logout and do something you'll get an error. That seems about right to me.

**Comment by Schmavery** [comment]
I think @senhly is talking about using other API functionality after logging out.  This should definitely cause an error, but it would be nice if it was a specific error and not just a parse problem.  I was assuming we would do some basic parsing of the html in `parseResponse` to verify that this was actually the problem.

**Comment by bsansouci** [comment]
Mmh Ok, maybe we could make another `parseResponse` that will throw an error `{error: "Not logged in."}` that we use everywhere where we _are_ supposed to be logged in. The only place where we'd use the regular `parseReponse` is during the login process I'm guessing.

**Comment by senhly** [comment]
@Schmavery was right, it cause error when call other function after logging out. By this way, I also notice that after logging out complete the pulling request in function <code>listen</code> still running. We could stop listen after log out. Am I right?

**Comment by Schmavery** [comment]
Reopening so that we don't forget to fix this in listen.
