### ISSUE TITLE
getThreadList error

### ISSUE THREAD

**Issue by StevenSuh** [Schmavery/facebook-chat-api#570]
Starting yesterday, getThreadList() returns a `[]`. I thought this was weird, because it's not throwing any errors, but it just returns an empty array regardless of input.

**Comment by Schmavery** [comment]
Hmm, they might have finally switched it to use graphql instead, like they did with getThreadInfo and getThreadHistory. @bsansouci

**Comment by blueset** [comment]
Where is the current GraphQL API captured and analysed from? `facebook.com` or `messenger.com`? Desktop or Mobile? Web or App? Thanks.

**Comment by Schmavery** [comment]
All of our api queries run against the web version of Facebook and messenger (depending on the query). The other graphql calls use an endpoint called `https://www.facebook.com/api/graphqlbatch/`, I believe.

**Comment by blueset** [comment]
Thanks for the reply.
And I think I've found the the getThreadList equivalent for GraphQL, just note it down here.

```
"batch_name": "MessengerGraphQLThreadlistFetcherRe"
```

```
"queries": {
    "o0":{
        "doc_id":"1349387578499440",
        "query_params":{
            "limit":12, // Length 
            "before": <millisecond_UNIX_timestamp>, // show threads that was active before this time
            "tags":["INBOX"], // source
            "includeDeliveryReceipts":true,
            "includeSeqID":false
        }
    }
}
```

**Comment by Theblood** [comment]
@blueset Hi, friend, can you have the code of this solution to be able to integrate it into my project

**Comment by ravkr** [comment]
I just tried to at least start coding this...
so much work to do 😢 
![obraz](https://user-images.githubusercontent.com/3875202/34890012-9015670a-f7d0-11e7-8632-8f4a5b909015.png)

**Comment by ravkr** [comment]
#572
