### ISSUE TITLE
Errors in getThreadInfoGraphQL

### ISSUE THREAD

**Issue by AstroCB** [Schmavery/facebook-chat-api#578]
`getThreadInfoGraphQL` is currently broken for me, failing with

```
ERR! getThreadInfoGraphQL Error: well darn there was an error_result
```

With a little digging, it can be traced back to [this line](https://github.com/Schmavery/facebook-chat-api/blob/513fb77aa635e46e6d2621e0763cc5d6a13957ce/src/getThreadInfoGraphQL.js#L99), which seems to check whether the backend is indicating a failure and bail out if it is.

The response payload for this is in the form

```js
Array(2) [Object, Object]
length: 2
0: Object {o0: Object}
1: Object {successful_results: 0, error_results: 1, skipped_results: 0}
```
As you can see, the payload is reporting an error_result and no successful_results despite the data being successfully obtained from the backend (the first item in the array contains valid info about the thread).

A monkey patch for this is disabling the error-checking to allow the response through without throwing the error. This obviously isn't a permanent solution, but I'm not quite sure why the response is reporting an error_result even though it successfully retrieved the information.

**Comment by Schmavery** [comment]
Is there any chance you could check if this happens in the browser as well, and if not, how the browser's query differs from ours?

**Comment by Toohpick** [comment]
Seems like it's [doc_id](https://github.com/Schmavery/facebook-chat-api/blob/master/src/getThreadInfoGraphQL.js#L76). 1527774147243246 produces that result, while 1498317363570230 from the browser request works fine.

**Comment by AstroCB** [comment]
I can confirm that this appears to fix the issue.
