### ISSUE TITLE
changeThreadColor - custom color?

### ISSUE THREAD

**Issue by forcemagic** [Schmavery/facebook-chat-api#583]
This is more like a question, rather than an issue. Would it be possible to change the code in a way that we can set custom colors or is Facebook blocking us from sending everything else than the presets in `api.threadColors`?

**Comment by ravkr** [comment]
No, it is not possible... Facebook started to check colors with their whitelist.
Before that change it was possible and this API was not limiting anything (current checks are just to avoid unnecessary errors from Facebook servers)

**Comment by forcemagic** [comment]
That's a shame :pensive: Now I understand the extra checks, thanks for the info. And curse Facebook engineers for whitelisting colors.
