### ISSUE TITLE
Change title in group by message

### ISSUE THREAD

**Issue by TheKnown44** [Schmavery/facebook-chat-api#585]
Not sure if this is the correct place to ask, but I can't seem to figure out how to change group title by message e.g. if I type settitle [custom title]

I would really appreciate any help

**Comment by Schmavery** [comment]
Not sure I understand, are you saying that this call isn't working? https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#setTitle

**Comment by ravkr** [comment]
You have to `listen` for messages, then check `if` there is `settitle ` on the beginning, then use `setTitle` with what's left after cutting `settittle ` from the message

**Comment by TheKnown44** [comment]
Thanks a lot! I'm getting somewhere now haha.
