### ISSUE TITLE
getThreadInfoGraphQL not working(?)

### ISSUE THREAD

**Issue by forcemagic** [Schmavery/facebook-chat-api#586]
This is what I get when I try to use `getThreadInfoGraphQL()`. It worked before with the exact same arguments! (Silly logging shows nothing)

```
{"__ar":1,"error":1357004,"errorSummary":"Garr! It be lost in the mists!","errorDescription":"Abandon ship! Then re-launch yer skiff.","payload":null,"bootloadable":{},"ixData":{},"gkxData":{},"lid":"<redacted random long number>"}
```

I will investigate further when I have time, but for now I'll just leave this here.

(Btw as you can see I'm using pirate FB, this error basically means log out and log back in)

**Comment by Schmavery** [comment]
Do you have this fix in your version https://github.com/Schmavery/facebook-chat-api/pull/579 ?
If so, first thing to do would be to check if the doc changed again in the browser.

**Comment by forcemagic** [comment]
Yes, I'm using bleeding edge, freshly cloned from `master`. Couldn't we somehow scrape that `doc_id`? I don't think it's a great idea to do commits and change it every 1-2months.

**Comment by Schmavery** [comment]
I was pretty sure the whole point of graphql was that these endpoints didn't go out of service. Obviously if that's wrong we have to change strategies. Any thoughts @bsansouci ?

**Comment by bsansouci** [comment]
@forcemagic Could you do what was done here https://github.com/Schmavery/facebook-chat-api/issues/578#issue-293305931 and print the whole returned message? As far as I understand the error was merely a warning, but the doc_id still worked (it's supposed to work for forever).

**Comment by Toohpick** [comment]
This is unrelated to #578 , I believe this happens when you get redirected to another facebook subdomain like web.facebook.com, which depends on ISP. I have no idea why exactly that causes the defaultFuncs.post requests to fail with this error but not defaultFuncs.get requests. I no longer have access to the ISP that forced the redirection and caused this so I can't investigate it.

**Comment by forcemagic** [comment]
Okay, temporary issue, fixed it with an app restart (as adviced :P) Thank you all for the quick response and from now, I'll declare this issue closed.
