### ISSUE TITLE
Can't send message

### ISSUE THREAD

**Issue by ammarfaizi2** [Schmavery/facebook-chat-api#592]
I have tried the echo bot example and it is thrown an error when I send a message to the bot.

The bot didn't reply my message and here is the error.
![asd](https://user-images.githubusercontent.com/26004054/36642252-61d87320-1a6f-11e8-9eac-9f25425aa2d0.png)

and the code
![qweasd](https://user-images.githubusercontent.com/26004054/36642279-da7e0b14-1a6f-11e8-86ad-bbed408195fa.png)

**Comment by 23phy** [comment]
It's definitely working on my end, do you use this repository or the module on npm?

**Comment by ammarfaizi2** [comment]
@23phy I use this repository.

**Comment by 23phy** [comment]
Changed the module with this repo but.. still working to me.

![github](https://user-images.githubusercontent.com/11774416/36726127-5c047edc-1bc1-11e8-9e7d-30fa9861d0ac.JPG)

**Comment by Toohpick** [comment]
Does accessing Facebook through your browser redirect to some subdomain like web.facebook.com?

**Comment by chocorho** [comment]
Unfortunately, I don't yet know the cause of this (when I use api.sendMessage it works fine), but I think Toohpick is on the right track.
As a side note, isn't it potentially dangerous to be running a web script as root?

**Comment by ammarfaizi2** [comment]
@Toohpick Yes, it does. 
When I access https://www.facebook.com it always redirects to https://web.facebook.com.
So also with https://m.facebook.com always redirect to https://mobile.facebook.com.
Probably the redirection caused that error, right?

@chocorho Oh right that it is dangerous, just coincidentally I'm using root user.

**Comment by Toohpick** [comment]
Apologies for the very late reply. I managed to verify that the redirection is definitely the culprit here, but couldn't find why. I tried replicating the app's request on the browser but there was nothing wrong with its response. I'll try looking more into it when I have the time.
As a workaround, consider deploying your app to a web platform.

**Comment by Schmavery** [comment]
@Toohpick thanks for helping debug this issue. Does it seem like we're not handling redirection properly on the api side? I don't completely understand what you mean talking about "deploying your app to a web platform".

**Comment by Toohpick** [comment]
For some ISPs, Facebook does a redirection with the meta tag, which the request module doesn't pick up. 
As for the workaround, I simply meant using a cloud platform such as heroku, as Facebook doesn't redirect on requests done from their server. Sorry for the confusion. I will submit a PR that seemed to fix this for me.

**Comment by Schmavery** [comment]
Thanks everyone! Feel free to follow up here if the fix doesn't work
