### ISSUE TITLE
Typing indicator Info

### ISSUE THREAD

**Issue by adminy** [Schmavery/facebook-chat-api#595]
I don't see anything typing indicator related in the docs.

My program is sending a tying indicator for every character typed, but that's not right, so I was thinking maybe it should be as long as you have something in the input bar, send it once.

**Is there a need for untyping function ? if so any way to do it?**

Another question is, yes great we can say we're typing, but what about someone else typing to us?

**Comment by ravkr** [comment]
did you read documentation?
https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#sendTypingIndicator

`sendTypingIndicator` returns function that will hide typing indicator when called
e.g.
```js
var end = api.sendTypingIndicator("0000000000", () => { ... });
setTimeout(end, 2000);
```

but AFAIK we can't (yet!) check other people's indicators

**Comment by ravkr** [comment]
update: 
if you use `api.setOptions({listenEvents: true});` before `api.listen();` you will get event of type `typ`
![obraz](https://user-images.githubusercontent.com/3875202/36934832-bb5f90fc-1eef-11e8-87fa-295f13f97a92.png)

**Comment by adminy** [comment]
@ravkr that's what it is, thanks, there was nothing about api.setOptions()
Thanks again 🥇
