### ISSUE TITLE
Use it in the browser

### ISSUE THREAD

**Issue by epakompri** [Schmavery/facebook-chat-api#596]
Hello :-)

Is there some port to run this in the browser ?

Thanks you :-) !

**Comment by Schmavery** [comment]
This isn't really supported by us but some people have tried in the past. Not sure what the current status there is.

https://github.com/Schmavery/facebook-chat-api/issues/345
https://github.com/Schmavery/facebook-chat-api/issues/290
https://github.com/Schmavery/facebook-chat-api/issues/103

**Comment by epakompri** [comment]
Ok ;-)
