### ISSUE TITLE
know who use my app

### ISSUE THREAD

**Issue by epakompri** [Schmavery/facebook-chat-api#597]
Hello :-) 

How can I know if my correspondant use my app too ?
My aim is to encrypt data between users

**Comment by 23phy** [comment]
I was wondering that too, and searching a way to send custom data through facebook, but I doubt it's possible, then I was thinking that you could do a ping-pong thing with ``` api.sendTypingIndicator```, but there is no way to listen for one... So I am looking for another way.

**Comment by ravkr** [comment]
you can also use external server, or some fanpage where bot would send something like "hello, I'm here, save in database that I'm using this app"
and another users could use your API on server or use the same fashion to ask fanpage
(of course it could instantly remove all messages from this thread, so users will not see it)

**Comment by epakompri** [comment]
I don't want to use a centralised server to know who use the app, encrypted messages will travel inside a decentralized virtual network like Tor.

With a decentralized user database, how can I be sure that nobody say wrong, and add an user who don't use the app ?

**Comment by 23phy** [comment]
You could also use Firebase in your app, so when a user logged in to Facebook within your app, you could store that in Firebase alongside his/her name, and you can always query with another one to see if their friends uses the app. That's what I cam up with, and I think it'll work.

**Comment by epakompri** [comment]
Same answer : I don't want to use a centralised server to know who use the app, encrypted messages will travel inside a decentralized virtual network like Tor.

With a decentralized user database, how can I be sure that nobody say wrong, and add an user who don't use the app ?

**Comment by adminy** [comment]
Actually if you are encrypting your messages the way to identify whether it's using your app or not add an identifier in the message, like a magic header.

**Comment by epakompri** [comment]
I need to identify who dn't use my app to don't send them encrypted message

**Comment by epakompri** [comment]
You're rigth @23phy :-) !
It's possible to send binary data over a ping-pong thing with a combination of `api.sendTypingIndicator`, `api.listen`

It's really nice :-) !

**Comment by epakompri** [comment]
I have a speed of 1Mbit/hour :joy:
