### ISSUE TITLE
use coding style?

### ISSUE THREAD

**Issue by ALiangLiang** [Schmavery/facebook-chat-api#599]
Do we use any coding style? If we use some style like [standard](https://github.com/standard/standard) or [airbnb](https://github.com/airbnb/javascript), the code will look more comfortable. I suggest use [standard](https://github.com/standard/standard) on this project. And add a .eslintrc file to help developer to lint code.

**Comment by Schmavery** [comment]
Is there some pattern that you think is making it hard to contribute?

**Comment by ALiangLiang** [comment]
- Adding [.eslintrc](https://eslint.org/docs/user-guide/configuring) is useful for auto-lint code. Developer do no need to create eslint configuration file themeselves.
- It makes it easy to unify code style and make it beautiful.
- Some contributers [dosen't follow exactly camel case](https://github.com/Schmavery/facebook-chat-api/pull/556/files#diff-f05127a8eefa1bf9353a037143b591dbR217). Let some variables or object key like "foo_bar", some like "fooBar". This will confuse the user.
- Most large projects also use eslintrc to unify code style.

**Comment by Schmavery** [comment]
I'm not entirely against the idea of aiming for some sort of unified style, though I'm not that into no semicolons (as standard appears to be).
Maybe something like prettier? Downside of having to touch every file and adding another step to development (would also be required of linting), upside of no manual (and error-prone) work to change and maintain style. I guess you would maybe still want a linter to enforce camelCase for instance. Would be nice to have a check for that.
@bsansouci thoughts?

**Comment by ALiangLiang** [comment]
We can just create a lint configure file (.eslintrc). And let developers include that into editor by themselves.
Or you can also use "husky"+"lint-stage", to force developer auto lint codes before commit.

**Comment by ALiangLiang** [comment]
[ref](https://hackernoon.com/what-javascript-code-style-is-the-most-popular-5a3f5bec1f6f)

**Comment by Schmavery** [comment]
Thanks for the link @ALiangLiang, looks like my preference for with-semicolon style is justified by science 😜 

Looks like @ravkr created https://github.com/Schmavery/facebook-chat-api/pull/611 to try out some changes. How do people feel about the airbnb style guide? From looking at it briefly it seems to match most closely what we're doing here already (in terms of semicolons, indentation and use of single-quotes for strings).
@bsansouci

**Comment by ALiangLiang** [comment]
I agree. airbnb is more like current coding style. But... Airbnb style is very strict and annoying. QQ
You can try it and run `npm run lint`. Or use linter plugin of your editor.
https://github.com/ALiangLiang/facebook-chat-api/commit/8ad192e1fd2d970bfd103938a22bc5abbd4429a1

btw. I found a funny service called "stickler-ci". It can help you to check lint before merge every PR.
Below is my test result:
https://github.com/ALiangLiang/pchome-api/pull/3

**Comment by ALiangLiang** [comment]
let me die...
https://github.com/ALiangLiang/facebook-chat-api/commit/4ba63031f17e2e363bbfe35e6a3cc5430e48b36e

**Comment by Schmavery** [comment]
Haha oh no, I didn't mean for you to spend a much of work manually converting files!
What I'm honestly thinking at this point is that @bsansouci and I will spend time this weekend trying to merge any outstanding PRs (so we don't break them with formatting), and then simply run [prettier](https://github.com/prettier/prettier) over the codebase. Let's see how that goes unless anyone has big objections? 😄

**Comment by ALiangLiang** [comment]
😂Don't worry. It's just show how annoying as airbnb style. I never want to PR this commit.

**Comment by Schmavery** [comment]
Thanks for the feedback, we've formatted the whole codebase with prettier for now.
