### ISSUE TITLE
can't send messages

### ISSUE THREAD

**Issue by ZDevelop** [Schmavery/facebook-chat-api#6]
i cant seem to be able to send messages to new people,
if i try to send to a friend who i already had a conversation with it works fine.
if i try to send to someone who i never had a conversation with i always get 
{ error: 'Send message failed.' }

im using the sendMessage Method, here my code
```javascript
var login = require("facebook-chat-api");

login("config.json", function(err, api) {
    if(err) return console.error(err);
  
    api.getUserId("Friend Name", function(err1, data) {
        if(err1) return console.error(err1);
        
        console.log(data);
        api.sendMessage("Test From Script", data.entries[0].uid, function(err2,data2){
	        if(err2) return console.error(err2);
	    });
    });
});
```
appreciate the help

**Comment by Schmavery** [comment]
This should solve your problem.  Thanks for the bug report! :D

**Comment by ZDevelop** [comment]
thanks man the fix you added works perfectly
