### ISSUE TITLE
api.getThreadList(start, end, callback) returns an empty array.

### ISSUE THREAD

**Issue by KonradLinkowski** [Schmavery/facebook-chat-api#605]
Maybe I'm using it in a wrong way, but api.getThreadList() returns an empty array for arguments: 0, 10, (err, threads) => {}).
Other methods works as exprected.
https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#getThreadList

**Comment by 23phy** [comment]
Yes, Facebook changed their api endpoints, they are changing to GraphQL, I suppose you use the npm module, you can use this repo and use the beta one named: ```getThreadListGraphQL```

**Comment by ravkr** [comment]
Look at #572
You can use development version with: `npm i ravkr/facebook-chat-api`

**Comment by KonradLinkowski** [comment]
@ravkr ok, but how to use it? require('ravkr/facebook-chat-api') or require('facebook-chat-api') not working.
@23phy  What do you mean by "this repo"?

**Comment by ravkr** [comment]
@23phy was wrong.. This function is only in my repo (not yet merged with this one) 

Not working? O.o
Seems weird.. 
How about:
```
git clone https://github.com/ravkr/facebook-chat-api 
cd facebook-chat-api 
npm i
```
And then `require("./facebook-chat-api")`? *if I remember correctly*

**Comment by KonradLinkowski** [comment]
@ravkr Ok, my bad. I installed yours with --save option, but after that I uninstalled original one.
I tried to run
`api.getThreadListGraphQL(0, 100, (err, info) => {
    if (err) {
      console.error('Error happened', err);
    }
    console.log(info)
  })`
and I've got
`{ error: 'getThreadListGraphQL: need callback' }`
What is wrong?

**Comment by ravkr** [comment]
Just read new docs: https://github.com/ravkr/facebook-chat-api/blob/master/DOCS.md#getThreadListGraphQL

**Comment by ravkr** [comment]
There is new parameter before a callback (*maybe I should make it optional?*)

**Comment by KonradLinkowski** [comment]
Ok, so I suppoused that function that you have written getThreadListGraphQL is exactly the same  as getThreadList, but I see you changed the parameters. After changing my arguments to `100, new Date(), 'INBOX', (err, info) => {}`, it still throw up JSON.parse Error.
Maybe I misunderstood the second parameter now.

**Comment by ravkr** [comment]
I will make it more clear in the next commit... 
For `timestamp` you can use `null` for "now" 
And `tags` is not a string but an array with string(s)

**Comment by KonradLinkowski** [comment]
After changing the timestamp to null it started to work as expected. After all I recommend to make your function idiot proof.
Thanks 👍

**Comment by ravkr** [comment]
Yeah, I know.. I should probably check type of every parameter and print detailed error messages :/

**Comment by KonradLinkowski** [comment]
@ravkr getThreadListGraphQL creates threadList_raw.json every time it runs. Is there any chance to turn it off?

**Comment by ravkr** [comment]
Oh, sorry, this is still development version. You can comment it out in src/getThreadListGraphQL.js (lines 64-67)

**Comment by ravkr** [comment]
can we close it now?
