### ISSUE TITLE
Error retrieving userId.

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [Schmavery/facebook-chat-api#61]
I'm always getting this error even if I enter from the browser and mark the login attempt as trust wordy. 

[Error: Error retrieving userId. This can be caused by a lot of things, including getting blocked by Facebook for logging in from an unknown location. Try logging in with a browser to verify.]

**Comment by Karlheinzniebuhr** [comment]
Ok

**Comment by Schmavery** [comment]
Glad you were able to figure out your problem :)
We're working on supporting login approvals but it's taking a little longer than expected.  Hopefully it'll be finished up soon!

**Comment by Schmavery** [comment]
@Karlheinzniebuhr login approvals are now supported in the prerelease branch.  Give it a try!
