### ISSUE TITLE
Port to use in java/kotlin and compile app to mobile?

### ISSUE THREAD

**Issue by etiaro** [Schmavery/facebook-chat-api#610]
I am ready to try that, but i don't have much experience with web-client programming

**Comment by Schmavery** [comment]
Feel free, we're happy to answer questions where we can. There's also https://github.com/carpedm20/fbchat, which is a port of this library to python, if you need more inspiration :)
Personally I don't have time to work on a port of this library to java so I'll close this issue for now but feel free to ask questions here.
