### ISSUE TITLE
Hi, I am making the port to java, and i have problem with pulls

### ISSUE THREAD

**Issue by etiaro** [Schmavery/facebook-chat-api#614]
On 1st pull i am getting statuscode 400 - bad request. I have problem with re-write encodeURIComponent, persence encode and decode functions for now, but after few checks in browser, i dont think that here is the fault. I tried to use all/part of your header, with no effect. Have you got any ideas?

**Comment by ravkr** [comment]
you didn't even show your code, how can we help? just guess?

**Comment by bsansouci** [comment]
if i had to guess i'd say that this is due to you not encoding the data for the request correctly
obviously it'd be easier to help if we could see the packet you're actually sending ;)

**Comment by etiaro** [comment]
Of course, i dont know how can i miss it... Anyway i got the problem - i had bad default params
