### ISSUE TITLE
Audio/Video call

### ISSUE THREAD

**Issue by 23phy** [Schmavery/facebook-chat-api#615]
Hello everyone, 

I just noticed that you can send images, audio and other files, and I'm playing with those right now, and I was wondering if there's a possibility to make, as the title suggests, an audio or video call with this api. Is it possible? If so, how?

**Comment by ravkr** [comment]
It is not yet possible, but if you want, you can try to implement it.
Probably sending fake information about calls would be easy, but making actual audio/video call will take more work

**Comment by 23phy** [comment]
Aaalrighty then, I'll see what I can do. Thanks.

**Comment by a4smanjorg5** [comment]
I think using [webrtc](https://github.com/node-webrtc/node-webrtc) like from browser to do calling. Please do debug on browser.
