### ISSUE TITLE
Error: unrecognized attach_file 

### ISSUE THREAD

**Issue by mr-sonj** [Schmavery/facebook-chat-api#618]
Send sticker from iphone error

 Error: unrecognized attach_file `{"sticker_attachment":{"id":"1302631776532460","pack":{"id":"1301708839958087"},"label":"Hi, girl bursting out of screen with text \"hello!\"","frame_count":12,"frame_rate":83,"frames_per_row":4,"frames_per_column":3,"sprite_image_2x":{"uri":"https://scontent-cdg2-1.xx.fbcdn.net/v/t39.1997-6/22159631_1302631779865793_4374612864594345984_n.png?_nc_ad=z-m&_nc_cid=0&oh=362cc9b5945e732e66c6a0d2b8cfe7aa&oe=5B2FE182"},"sprite_image":{"uri":"https://scontent-cdg2-1.xx.fbcdn.net/v/t39.1997-6/s480x480/22159631_1302631779865793_4374612864594345984_n.png?_nc_ad=z-m&_nc_cid=0&oh=a71003d3a9536ae80561ec5ae2c08389&oe=5B46C199"},"padded_sprite_image":{"uri":"https://scontent-cdg2-1.xx.fbcdn.net/v/t39.1997-6/s600x600/22159613_1302631789865792_8208739923604275200_n.png?_nc_ad=z-m&_nc_cid=0&oh=04a27abb57c88d1a60fd5dfe045cb03d&oe=5B3A7E13"},"padded_sprite_image_2x":{"uri":"https://scontent-cdg2-1.xx.fbcdn.net/v/t39.1997-6/22159613_1302631789865792_8208739923604275200_n.png?_nc_ad=z-m&_nc_cid=0&oh=93540f96cdf230c0cd10b8b102ec63b1&oe=5B4E5421"},"url":"https://scontent-cdg2-1.xx.fbcdn.net/v/t39.1997-6/21977696_1302631783199126_7791802932508229632_n.png?_nc_ad=z-m&_nc_cid=0&oh=5d9baa44400ab27eebd75a81c51b41a1&oe=5B4E0AA6","height":240,"width":240}}`
ERR! listen     at _formatAttachment (D:\Dropbox\sellerai\node_modules\facebook-chat-api\utils.js:354:13)
ERR! listen     at attachments.map.v (D:\Dropbox\sellerai\node_modules\facebook-chat-api\utils.js:376:55)
ERR! listen     at Array.map (<anonymous>)
ERR! listen     at Object.formatDeltaMessage (D:\Dropbox\sellerai\node_modules\facebook-chat-api\utils.js:376:46)
ERR! listen     at resolveAttachmentUrl (D:\Dropbox\sellerai\node_modules\facebook-chat-api\src\listen.js:159:40)
ERR! listen     at resolveAttachmentUrl (D:\Dropbox\sellerai\node_modules\facebook-chat-api\src\listen.js:168:30)
ERR! listen     at parsePackets (D:\Dropbox\sellerai\node_modules\facebook-chat-api\src\listen.js:171:19)
ERR! listen     at Array.forEach (<anonymous>)
ERR! listen     at D:\Dropbox\sellerai\node_modules\facebook-chat-api\src\listen.js:109:12
ERR! listen     at tryCatcher (D:\Dropbox\sellerai\node_modules\bluebird\js\main\util.js:26:23)

**Comment by ravkr** [comment]
did you fixed it? or just going from npm to github version did the job?
