### ISSUE TITLE
GraphQL

### ISSUE THREAD

**Issue by etiaro** [Schmavery/facebook-chat-api#620]
(Java porting)
1. How are You getting doc_id? Is it changing?
2. If i set before(value not matters) i AM getting error. Without that value everything works. That's interesting.

**Comment by ravkr** [comment]
1. We are getting it from requests from browser 
It shouldn't change.. But it happened once times already 

2. You didn't specify request you were trying to send... So I can't help yet

**Comment by Schmavery** [comment]
This seems answered
