### ISSUE TITLE
Can we sent a message as a template?

### ISSUE THREAD

**Issue by thaspoom** [Schmavery/facebook-chat-api#621]
Can facebook-chat-api sent a template question as the picture below? 

<img width="572" alt="capture" src="https://user-images.githubusercontent.com/33860831/37693579-2ae47b2a-2cf3-11e8-92b8-14a91d4b4a30.PNG">

**Comment by 23phy** [comment]
Are you chatting with a bot on messenger?

**Comment by Schmavery** [comment]
@thaspoom this api can only do things that users can do. Afaik, users can't send a template message. You probably want to use something like this: https://developers.facebook.com/docs/messenger-platform

**Comment by codeforequity-at** [comment]
While the templates are always sent from the "other side", that is the chatbot code through the messenger-platform, it would be cool if we could simulate pressing on one of the buttons from the template - a postback occurs there, and I don't know how to simulate this.

**Comment by 23phy** [comment]
I believe that functionality is only available to pages and their users and not available to one-to-one and group messages.

**Comment by Schmavery** [comment]
I think the original question is answered. Not sure about interacting with chatbot templates, but that can probably be it's own thing if people really want it.
