### ISSUE TITLE
Investigate and add admin toggling capabilities

### ISSUE THREAD

**Issue by tarungog** [Schmavery/facebook-chat-api#624]
New messenger features allow users to remove and add admins in messenger group chats

**Comment by ravkr** [comment]
New getThreadList have this commented out, I will change it when I get back home

**Comment by AstroCB** [comment]
This also ties into membership approval requests, which the API may be able to field.

In my testing, it seems the API cannot freely add people as before when admin approval for membership is turned on, even if the controlling account is an admin, so it would be nice if we could add functionality to approve/deny these requests as needed.

**Comment by Schmavery** [comment]
I think this was added in https://github.com/Schmavery/facebook-chat-api/pull/659?? If there's some issue with it we can reopen. Thanks all!
