### ISSUE TITLE
Can't get access token

### ISSUE THREAD

**Issue by vanhung89** [Schmavery/facebook-chat-api#63]
Hi
I don't know why I can't get access token to use facebook api. Do have anything with api.getAccessToken()?

**Comment by Schmavery** [comment]
Sorry @vanhung89, this functionality has been removed, but we forgot to update the README.  The access token returned by our API was not a proper access token and behaved unpredictably.  Please use the regular way of obtaining an access token.  Thanks!

**Comment by vanhung89** [comment]
Could you tell me some option? I don't know any way to get access token. It's note relate, but could you tell me how to get group by search key word? And how to get all user of group. Thanks you very much

**Comment by Schmavery** [comment]
This should give you plenty of information to get started on access tokens: https://developers.facebook.com/docs/facebook-login/access-tokens
You'll probably want to use it with an API like this one: https://github.com/Thuzi/facebook-node-sdk

We currently don't have functionality to search for groups (AFAIK, @bsansouci?).  All participants of a group chat are sent with every message received from that chat.

You can get the information about all threads and filter yourself using `api.getThreadList()`, which is returns a list of all threads with information about their participants among other things.  Full info in README.
