### ISSUE TITLE
Send Messange Issue

### ISSUE THREAD

**Issue by RaviDhiman21** [Schmavery/facebook-chat-api#634]
Hi,

I got this error when i tried to send one to one message

WARN sendMessage Got error 1545012. This might mean that you're not part of the
conversation 130567794450062
 
Please Help

**Comment by ravkr** [comment]
`130567794450062` is an ID of a group and not an ID of any user....
you should try this: `100002706844979`

**Comment by Schmavery** [comment]
Can your bot account send a message to that conversation in the browser?

**Comment by RaviDhiman21** [comment]
Yes and all set.

I have one question regarding to node js.
How can i run my code on browser. i.e Node Js file?

**Comment by RaviDhiman21** [comment]
And is there any way to post request to Node Js file in json format. i.e using Postman?

**Comment by Schmavery** [comment]
if you search the issues for "browser" or similar, you might be able to find some issues talking about trying to get the api running in the browser, though it's not a supported scenario currently.

Are you still having the original issue or can we close?
