### ISSUE TITLE
blob is not defined

### ISSUE THREAD

**Issue by Energiiz** [Schmavery/facebook-chat-api#635]
Hi,

When I use the `getThreadHistory` method, I get the error `ReferenceError: blob is not defined`.
It seems that this error is only triggered when I'm getting a message containing a gif.
The error is in `getThreadHistory` at line 65 when accessing the blob variable, which seems to never be defined.

Thank you for your help.

**Comment by Schmavery** [comment]
Thanks for opening this, looks like there was a bug in our new getThreadHistory function, where "blob" isn't defined..

https://github.com/Schmavery/facebook-chat-api/blob/0bd932de5489b4513902b601326429cc485d3b9e/src/getThreadHistory.js#L65-L76

**Comment by Toohpick** [comment]
This bug was introduced by 84618857653c9d0ac863d2c556145c402e5324c5. The attachment in this case is the blob_attachment itself
https://github.com/Schmavery/facebook-chat-api/blob/0bd932de5489b4513902b601326429cc485d3b9e/src/getThreadHistory.js#L405
The object is structured like this
```json
"blob_attachments": [{
    "__typename": "MessageAnimatedImage",
    "attribution_app": null,
    "attribution_metadata": null,
    "filename": "gif-1234567890",
    "animated_image": {
      "uri": "https:\/\/cdn.fbsbx.com\/v\/t59.2708-21\/1234567890_1234567890_1234567890_n.gif?_nc_cat=0&oh=1234567890abcdef&oe=1234ABCD",
      "height": 358,
      "width": 272
    },
    "legacy_attachment_id": "1234567890",
    "preview_image": {
      "uri": "https:\/\/cdn.fbsbx.com\/v\/t59.2708-21\/1234567890_1234567890_1234567890_n.gif?_nc_cat=0&oh=1234567890abcdef&oe=1234ABCD",
      "height": 358,
      "width": 272
    },
    "original_dimensions": {
      "x": 272,
      "y": 358
    }
  }
]
```
So basically, a copy/paste slip up from utils.js, and the fix is as simple as replacing blob with attachment.

**Comment by bilyanhadzhi** [comment]
So, are `getThreadHistory` and `getThreadHistoryGraphQL` one now?
I see that there is no `getThreadHistoryGraphQL` function.

**Comment by Schmavery** [comment]
@bilyanhadzhi getThreadHistoryGraphQL was always a bit of an experimental api and has now been promoted to replace the mostly broken original getThreadHistory call (which is still available as getThreadHistoryDeprecated but we are planning to remove it -- please let us know if there's a reason we shouldn't)

**Comment by shade** [comment]
You should consider publishing this fix to npm, it's pretty critical.

**Comment by Schmavery** [comment]
will do

**Comment by Schmavery** [comment]
@shade 1.5.1 published
