### ISSUE TITLE
How to use access_token??

### ISSUE THREAD

**Issue by standnguyen197** [Schmavery/facebook-chat-api#640]
How to use access_token??

**Comment by bsansouci** [comment]
Sorry, I don't know what you're talking about. We don't use access_token anywhere in our codebase.

**Comment by forcemagic** [comment]
I believe he's talking about the Graph API's access token, which is not the concern of this API.

This just uses a username and a password for authentication.

**Comment by bsansouci** [comment]
Ah that makes sense.
The reason we use email/password is that we basically do exactly what the browser would do when you fill up the login form and hit enter, just server side.

**Comment by Schmavery** [comment]
This seems to answer the question, you can let us know if we misunderstood. Thanks!
