### ISSUE TITLE
How to get access_token from facebook-chat-api???

### ISSUE THREAD

**Issue by standfv** [Schmavery/facebook-chat-api#645]
How to get access_token from facebook-chat-api???

**Comment by forcemagic** [comment]
Please refer to #640

**Comment by standfv** [comment]
No!!! Is mean "When I use my account and password to log into the modules then modules can output to me the token_access of that account."

**Comment by forcemagic** [comment]
I'm sorry, but I don't understand your question. It is clear (I've just searched for it now) that the codebase does not contain any token related.. things.

What kind of "token" are you looking for in particular? Could you give an example?

**Comment by standfv** [comment]
For example, when I use the account for facebook-chat-api modules I can get my access_token: EAAAAUAZA8jlABAJ3fD81QYrFYGGgA2QpwplIUJ1b8sTAuMmj3q9C9uBzhXuqn47KnUKKSIOw9WAyV0llh7CzHTF1vZC4VkmZCWojoqH7 ..... ???

**Comment by forcemagic** [comment]
Hmm.. is this a cookie? You might be able to extract it from the cookie object. Have a look here: https://github.com/Schmavery/facebook-chat-api/blob/master/index.js#L60

**Comment by standfv** [comment]
is this a access_token

**Comment by bsansouci** [comment]
@standfv You can call `api.getAppState` (see documentation) to get all the cookies, which contains tokens like these. I'm not sure this is exactly what you're looking for, just print what this function returns and you'll see for yourself.

Otherwise I don't know what you're talking about.
