### ISSUE TITLE
How to know i send message ??

### ISSUE THREAD

**Issue by anhdhbn** [Schmavery/facebook-chat-api#646]
I have idea, when i'm offline, I will integrate bot simsimi and when i send any message, simsimi will off, I want to know event i sent message to anybody for i turnoff simsimi ??

**Comment by Schmavery** [comment]
I don't understand this question so hopefully the answer above helps. We can reopen if there's something missing.

**Comment by Hongarc** [comment]
@Schmavery his mean is "he send msg" vs "bot send msg".
I think that :)
