### ISSUE TITLE
Can't get userInfo of array UID

### ISSUE THREAD

**Issue by vanhung89** [Schmavery/facebook-chat-api#65]
Hi
I use getFriendsList method to get list friend, It will return array UID. Then I use getUserInfo method to get user information of that array but it throw error: ERR! Error in getUserInfo TypeError: first argument must be a string or Buffer
Could you tell me how to fix it?

**Comment by Schmavery** [comment]
You should be able to pass an array of users into getUserInfo, so it's possible that this is a bug.  Can you give a short code example of what is producing the error?

**Comment by bsansouci** [comment]
Closing this for now. I have no idea how you get this error, this specific message isn't in the current version.
