### ISSUE TITLE
changeGroupImage failing

### ISSUE THREAD

**Issue by AstroCB** [Schmavery/facebook-chat-api#650]
`api.changeGroupImage` is failing for me with the following error:

```
ERR! changeGroupImage { __ar: 1,
ERR! changeGroupImage   error: 1545065,
ERR! changeGroupImage   errorSummary: 'Message Not Sent',
ERR! changeGroupImage   errorDescription: 'These people aren\'t receiving messages right now.',
ERR! changeGroupImage   payload: null,
ERR! changeGroupImage   bootloadable: {},
ERR! changeGroupImage   ixData: {},
ERR! changeGroupImage   gkxData: {},
ERR! changeGroupImage   lid: '6561607085230422615' }
```

Any ideas why?

**Comment by choyg** [comment]
`setTitle` might be failing with the same error. Noticed that in the test suite

**Comment by Schmavery** [comment]
Hmm, not sure. Maybe some api changed. Can someone try changing these things in a browser while listening to network activity?

**Comment by ArthurGarnier** [comment]
Can confirm, fails since 05/30. 
Sending a gif seems not working either ? (to check, tried only one time.

**Comment by ArthurGarnier** [comment]
Just checked call from the webui : 
In this API you are using : https://www.facebook.com/messaging/send/

But now it seems to be : https://www.messenger.com/messaging/set_thread_image/

Please see the parameters POSTed to this URL : 

<img width="680" alt="capture" src="https://user-images.githubusercontent.com/3818749/40929697-d5603856-6825-11e8-94d2-62e31a79285c.PNG">

**Comment by Schmavery** [comment]
Thanks for checking @ArthurGarnier 
Pretty much all of those are straightforward and should be handled automatically (By `defaultFuncs.post`) except for thread_image_id. It's fairly possible that it's the same type of id as we pass to the old endpoint, so you could try to just update the endpoint here: https://github.com/Schmavery/facebook-chat-api/blob/master/src/changeGroupImage.js#L101

and then update this form to just have thread_id and thread_image_id:
https://github.com/Schmavery/facebook-chat-api/blob/dca1eb4e564e570f78aae0a7000671937284b1ad/src/changeGroupImage.js#L94-L98
