### ISSUE TITLE
Query server info

### ISSUE THREAD

**Issue by erikleo** [Schmavery/facebook-chat-api#657]
What is best way to query server info of a message

**Comment by ravkr** [comment]
The easiest way is to make sure your system time is correct... have you tried just synchronising with some NTP server?

**Comment by ravkr** [comment]
But if you can't (or don't want to) mess with system time, you can try to set reactions to messages, and listen for `message_reaction` event as it includes timestamp and you can easly remove that reaction later

**Comment by erikleo** [comment]
Thanks, finally got this working using the timestamp from a test message then later deleted it.  Had to convert the functions to return promises for it work though.  Surprised the the api does not do this natively.

**Comment by Schmavery** [comment]
This seems resolved. Thanks all
