### ISSUE TITLE
Receiver name missing in response

### ISSUE THREAD

**Issue by jijoamt** [Schmavery/facebook-chat-api#66]
If i ( say A) make a post to somebody else (say B), i am not getting the receiver's name in response. Is there any way to include the name of the receiver in response for the  listen command

**Comment by Schmavery** [comment]
This is generally expected to stay constant?  I don't really understand the question.

**Comment by jijoamt** [comment]
I have configured the account A using this library.  So whenever A receive a message from B or C, i get the sender_name ( the person who has sent the message to A) . But when A  sent a message to B or C from facebook itself or from a messenger, the api response does not have any reference about  B's name. it just gives B unique id in facebook. Is there any way to get B's name as well

**Comment by Schmavery** [comment]
Ah, I assume you're using the `selfListen` option set to `true` then.  You can always get information about  a `userID`, including the full name, with a call to `api.getUserInfo()`.
I hope that helps.

**Comment by Schmavery** [comment]
I'm marking this as resolved, please reopen the issue if you have further problems with this. :smile:
