### ISSUE TITLE
getThreadHistoryGraphQL TypeError: Cannot read property 'ranges' of null

### ISSUE THREAD

**Issue by mrcyclo** [Schmavery/facebook-chat-api#660]
ERR! getThreadHistoryGraphQL TypeError: Cannot read property 'ranges' of null
--
  | ERR! getThreadHistoryGraphQL     at /opt/app-root/src/node_modules/facebook-chat-api/src/getThreadHistory.js:396:19
  | ERR! getThreadHistoryGraphQL     at Array.map (<anonymous>)
  | ERR! getThreadHistoryGraphQL     at formatMessagesGraphQLResponse (/opt/app-root/src/node_modules/facebook-chat-api/src/getThreadHistory.js:361:47)
  | ERR! getThreadHistoryGraphQL     at /opt/app-root/src/node_modules/facebook-chat-api/src/getThreadHistory.js:622:24
  | ERR! getThreadHistoryGraphQL     at tryCatcher (/opt/app-root/src/node_modules/bluebird/js/main/util.js:26:23)
  | ERR! getThreadHistoryGraphQL     at Promise._settlePromiseFromHandler (/opt/app-root/src/node_modules/bluebird/js/main/promise.js:510:31)
  | ERR! getThreadHistoryGraphQL     at Promise._settlePromiseAt (/opt/app-root/src/node_modules/bluebird/js/main/promise.js:584:18)
  | ERR! getThreadHistoryGraphQL     at Promise._settlePromises (/opt/app-root/src/node_modules/bluebird/js/main/promise.js:700:14)
  | ERR! getThreadHistoryGraphQL     at Async._drainQueue (/opt/app-root/src/node_modules/bluebird/js/main/async.js:123:16)
  | ERR! getThreadHistoryGraphQL     at Async._drainQueues (/opt/app-root/src/node_modules/bluebird/js/main/async.js:133:10)
  | ERR! getThreadHistoryGraphQL     at Immediate.Async.drainQueues (/opt/app-root/src/node_modules/bluebird/js/main/async.js:15:14)
  | ERR! getThreadHistoryGraphQL     at runCallback (timers.js:789:20)
  | ERR! getThreadHistoryGraphQL     at tryOnImmediate (timers.js:751:5)
  | ERR! getThreadHistoryGraphQL     at processImmediate [as _immediateCallback] (timers.js:722:5)
  | ERR! getThreadHistoryGraphQL  TypeError: Cannot read property 'ranges' of null
  | ERR! getThreadHistoryGraphQL     at /opt/app-root/src/node_modules/facebook-chat-api/src/getThreadHistory.js:396:19
  | ERR! getThreadHistoryGraphQL     at Array.map (<anonymous>)
  | ERR! getThreadHistoryGraphQL     at formatMessagesGraphQLResponse (/opt/app-root/src/node_modules/facebook-chat-api/src/getThreadHistory.js:361:47)
  | ERR! getThreadHistoryGraphQL     at /opt/app-root/src/node_modules/facebook-chat-api/src/getThreadHistory.js:622:24
  | ERR! getThreadHistoryGraphQL     at tryCatcher (/opt/app-root/src/node_modules/bluebird/js/main/util.js:26:23)
  | ERR! getThreadHistoryGraphQL     at Promise._settlePromiseFromHandler (/opt/app-root/src/node_modules/bluebird/js/main/promise.js:510:31)
  | ERR! getThreadHistoryGraphQL     at Promise._settlePromiseAt (/opt/app-root/src/node_modules/bluebird/js/main/promise.js:584:18)
  | ERR! getThreadHistoryGraphQL     at Promise._settlePromises (/opt/app-root/src/node_modules/bluebird/js/main/promise.js:700:14)
  | ERR! getThreadHistoryGraphQL     at Async._drainQueue (/opt/app-root/src/node_modules/bluebird/js/main/async.js:123:16)
  | ERR! getThreadHistoryGraphQL     at Async._drainQueues (/opt/app-root/src/node_modules/bluebird/js/main/async.js:133:10)
  | ERR! getThreadHistoryGraphQL     at Immediate.Async.drainQueues (/opt/app-root/src/node_modules/bluebird/js/main/async.js:15:14)
  | ERR! getThreadHistoryGraphQL     at runCallback (timers.js:789:20)
  | ERR! getThreadHistoryGraphQL     at tryOnImmediate (timers.js:751:5)
  | ERR! getThreadHistoryGraphQL     at processImmediate [as _immediateCallback] (timers.js:722:5)
  | TypeError: Cannot read property 'ranges' of null
  | at /opt/app-root/src/node_modules/facebook-chat-api/src/getThreadHistory.js:396:19
  | at Array.map (<anonymous>)
  | at formatMessagesGraphQLResponse (/opt/app-root/src/node_modules/facebook-chat-api/src/getThreadHistory.js:361:47)
  | at /opt/app-root/src/node_modules/facebook-chat-api/src/getThreadHistory.js:622:24
  | at tryCatcher (/opt/app-root/src/node_modules/bluebird/js/main/util.js:26:23)
  | at Promise._settlePromiseFromHandler (/opt/app-root/src/node_modules/bluebird/js/main/promise.js:510:31)
  | at Promise._settlePromiseAt (/opt/app-root/src/node_modules/bluebird/js/main/promise.js:584:18)
  | at Promise._settlePromises (/opt/app-root/src/node_modules/bluebird/js/main/promise.js:700:14)
  | at Async._drainQueue (/opt/app-root/src/node_modules/bluebird/js/main/async.js:123:16)
  | at Async._drainQueues (/opt/app-root/src/node_modules/bluebird/js/main/async.js:133:10)
  | at Immediate.Async.drainQueues (/opt/app-root/src/node_modules/bluebird/js/main/async.js:15:14)
  | at runCallback (timers.js:789:20)
  | at tryOnImmediate (timers.js:751:5)
  | at processImmediate [as _immediateCallback] (timers.js:722:5)

**Comment by ravkr** [comment]
`api.getThreadHistoryGraphQL` was in dev version
you should update to the newest version (even on NPM there is now 1.6.0) and try to use [api.getThreadHistory](https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#getThreadHistory)

**Comment by mrcyclo** [comment]
![image](https://user-images.githubusercontent.com/13806369/41479795-837a6ce4-70f6-11e8-9a91-cc6597bdf39d.png)
![image](https://user-images.githubusercontent.com/13806369/41479818-9d882a86-70f6-11e8-98ae-6002e4a4b21b.png)

@ravkr I use newest version, and get this error :(

**Comment by ravkr** [comment]
oh :/
could you post that code here, I'll try to fix it today

**Comment by mrcyclo** [comment]
![image](https://user-images.githubusercontent.com/13806369/41480898-3263ef02-70fa-11e8-93ec-7ab2e24b26f8.png)
![image](https://user-images.githubusercontent.com/13806369/41480902-3cf86fc4-70fa-11e8-8033-1f54841f3ada.png)
When I open getThreadHistory.js and add some console.log, I think may be he forget to check d.message is null.

**Comment by Schmavery** [comment]
If I understand correctly, this is fixed by https://github.com/Schmavery/facebook-chat-api/pull/661. Thanks!
