### ISSUE TITLE
Login Approvals.

### ISSUE THREAD

**Issue by vakkendwarf** [Schmavery/facebook-chat-api#663]
Facebook just won't take it that i login normally from poland, but my server wants to login from Oregon. How do i fix this?

**Comment by Schmavery** [comment]
We haven't found a consistently reliable way to support this afaik, sorry! Open to ideas but generally we have a policy of not circumventing facebook abuse-detection mechanisms.

**Comment by vakkendwarf** [comment]
Even if i confirm 10 times that the oregon IP is correct, facebook still rejects any login attempts made from it, is that a bug? Can i use the personal application password to login instead? Will it have access to my threads?

**Comment by ravkr** [comment]
I've had the same problem few weeks ago... while trying to log in from friend's account (150km from me)

you can try to use `forceLogin`
or just use some proxy

**Comment by vakkendwarf** [comment]
The service that i am using does not support VPNs or proxies, i have to use the Oregon IP, i'll look into forceLogin, though.

**Comment by ravkr** [comment]
yes, you can try
It should work

**Comment by ravkr** [comment]
but you have to set `forceLogin` before logging in (as a login parameter)

**Comment by vakkendwarf** [comment]
How? it's not explained in the docs

**Comment by vakkendwarf** [comment]
Actually appstate just works.
![image](https://user-images.githubusercontent.com/19872682/41560701-373ce63c-7348-11e8-8367-28478000b957.png)
