### ISSUE TITLE
setTimeout duration in listen.js

### ISSUE THREAD

**Issue by alexis12** [Schmavery/facebook-chat-api#664]
Hello! I tried to increase the `setTimeout` duration in `currentlyRunning = setTimeout(listen, Math.random() * 200 + 50)` to reduce the frequency of polling for messages to the equivalent of five minutes or so, but it doesn't seem to work as expected (basically no messages were received as far as I can tell). Does anyone know why this is the case? Thank you!

**Comment by ravkr** [comment]
It doesn't work this way... Facebook uses long pooling, so this api sends new request just after getting the response for the last one.

**Comment by alexis12** [comment]
Now it makes sense, thanks for your reply!
