### ISSUE TITLE
How to solve ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by chenhongjie1314** [Schmavery/facebook-chat-api#665]
info listen Got answer in 50530
info listen Got answer in 51026
ERR! listen Error: ESOCKETTIMEDOUT
ERR! listen     at ClientRequest.<anonymous> (E:\GroupChatMessage\node_modules\r
equest\request.js:778:19)
ERR! listen     at Object.onceWrapper (events.js:314:30)
ERR! listen     at emitNone (events.js:105:13)
ERR! listen     at ClientRequest.emit (events.js:207:7)
ERR! listen     at TLSSocket.emitTimeout (_http_client.js:722:34)
ERR! listen     at Object.onceWrapper (events.js:314:30)
ERR! listen     at emitNone (events.js:105:13)
ERR! listen     at TLSSocket.emit (events.js:207:7)
ERR! listen     at TLSSocket.Socket._onTimeout (net.js:402:8)
ERR! listen     at ontimeout (timers.js:469:11)
ERR! listen     at tryOnTimeout (timers.js:304:5)
ERR! listen     at Timer.listOnTimeout (timers.js:264:5)
ERR! listen  { Error: ESOCKETTIMEDOUT
ERR! listen     at ClientRequest.<anonymous> (E:\GroupChatMessage\node_modules\r
equest\request.js:778:19)
ERR! listen     at Object.onceWrapper (events.js:314:30)
ERR! listen     at emitNone (events.js:105:13)
ERR! listen     at ClientRequest.emit (events.js:207:7)
ERR! listen     at TLSSocket.emitTimeout (_http_client.js:722:34)
ERR! listen     at Object.onceWrapper (events.js:314:30)
ERR! listen     at emitNone (events.js:105:13)
ERR! listen     at TLSSocket.emit (events.js:207:7)
ERR! listen     at TLSSocket.Socket._onTimeout (net.js:402:8)
ERR! listen     at ontimeout (timers.js:469:11)
ERR! listen     at tryOnTimeout (timers.js:304:5)
ERR! listen     at Timer.listOnTimeout (timers.js:264:5)
ERR! listen   cause:
ERR! listen    { Error: ESOCKETTIMEDOUT
ERR! listen        at ClientRequest.<anonymous> (E:\GroupChatMessage\node_module
s\request\request.js:778:19)
ERR! listen        at Object.onceWrapper (events.js:314:30)
ERR! listen        at emitNone (events.js:105:13)
ERR! listen        at ClientRequest.emit (events.js:207:7)
ERR! listen        at TLSSocket.emitTimeout (_http_client.js:722:34)
ERR! listen        at Object.onceWrapper (events.js:314:30)
ERR! listen        at emitNone (events.js:105:13)
ERR! listen        at TLSSocket.emit (events.js:207:7)
ERR! listen        at TLSSocket.Socket._onTimeout (net.js:402:8)
ERR! listen        at ontimeout (timers.js:469:11)
ERR! listen        at tryOnTimeout (timers.js:304:5)
ERR! listen        at Timer.listOnTimeout (timers.js:264:5) code: 'ESOCKETTIMEDO
UT', connect: false },
ERR! listen   isOperational: true,
ERR! listen   code: 'ESOCKETTIMEDOUT',
ERR! listen   connect: false }
{ Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (E:\GroupChatMessage\node_modules\request\reque
st.js:778:19)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at ClientRequest.emit (events.js:207:7)
    at TLSSocket.emitTimeout (_http_client.js:722:34)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at TLSSocket.emit (events.js:207:7)
    at TLSSocket.Socket._onTimeout (net.js:402:8)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
  cause:
   { Error: ESOCKETTIMEDOUT
       at ClientRequest.<anonymous> (E:\GroupChatMessage\node_modules\request\re
quest.js:778:19)
       at Object.onceWrapper (events.js:314:30)
       at emitNone (events.js:105:13)
       at ClientRequest.emit (events.js:207:7)
       at TLSSocket.emitTimeout (_http_client.js:722:34)
       at Object.onceWrapper (events.js:314:30)
       at emitNone (events.js:105:13)
       at TLSSocket.emit (events.js:207:7)
       at TLSSocket.Socket._onTimeout (net.js:402:8)
       at ontimeout (timers.js:469:11)
       at tryOnTimeout (timers.js:304:5)
       at Timer.listOnTimeout (timers.js:264:5) code: 'ESOCKETTIMEDOUT', connect
: false },
  isOperational: true,
  code: 'ESOCKETTIMEDOUT',
  connect: false }
info listen Got answer in 86026

**Comment by ravkr** [comment]
Do you have a stable internet connection?

**Comment by chenhongjie1314** [comment]
Yes！It's possible to happen once a few days！

**Comment by chenhongjie1314** [comment]
I want to put all the requests in the array, then create the thread to work, and then release the thread after completion, but I don't know how to create the thread and release the thread.

**Comment by chiendevit** [comment]
Error ESOCKETTIMEDOUT is due to feedback timeout. Try checking the stability and speed of your network and it is blocked by the firewall?
