### ISSUE TITLE
Adding ability to remove self from a group chat

### ISSUE THREAD

**Issue by 7osCraft** [Schmavery/facebook-chat-api#666]
Hello,
  I can't seem to find a way with this api to remove the user I use from a group chat.
I've tried `api.removeUserFromGroup` but it doesn't seem to work.

**Comment by ravkr** [comment]
Could you show us your code? Did you noticed any error messages?

**Comment by 7osCraft** [comment]
Sorry, but can't show the code right now.
And no, there aren't any errors it works fine whwn removing other users from a group but doesn't work with the user I'm using.

**Comment by 7osCraft** [comment]
Yes. First I got the user ID from the function then wrote it to a file so I don't use the function every time.

**Comment by alencar** [comment]
I am also trying this API from master branch and got the following error when calling removeUserFromGroup with the current user ID (from api.getCurrentUserID) and threadID (from api.getThreadList).

```js
{ __ar: 1,
  error: 1545003,
  errorSummary: 'Invalid Action',
  errorDescription: 'You cannot perform that action.',
  payload: null,
  bootloadable: {},
  ixData: {},
  bxData: {},
  gkxData: {},
  qexData: {},
  lid: '<redacted>'
}
```

**Comment by Schmavery** [comment]
That's interesting, I'm guessing "leaving a chat" might be a different endpoint than "removing someone". If someone is interested and really needs this functionality, they might want to try both actions in a browser with the devtools open to the network tab and see what the difference in the requests is.

**Comment by 7osCraft** [comment]
It's working now on the latest update. I don't know what the problem was but it's ok now. Thanks.

**Comment by Schmavery** [comment]
Ok sounds great, thanks for following up :)

**Comment by alencar** [comment]
@7osCraft I have updated to the current version and I am still getting the same error, can you share what branch you are using?

Relevant code to remove the current user from a list of threads (groups)

```js
    let currentUser = api.getCurrentUserID();
    let threads = api.getThreadList(10, null, ["ARCHIVED"], function(err, list) {
      if (err) {
        console.log(err);
      };
      for (var item in list) {
        thread = list[item];
        console.log(thread['threadID'], thread['name']);
        api.removeUserFromGroup(currentUser, thread['threadID'], function(err) { console.log(err)});
      }
    });
````

Results with the current version

```bash
node:app user$ npm install Schmavery/facebook-chat-api
+ facebook-chat-api@1.6.1
updated 2 packages and audited 127 packages in 125.75s
found 0 vulnerabilities

node:app user$ node index.js 
info login Logged in
info login Request to reconnect
info login Request to pull 1
info login Request to pull 2
info login Request to thread_sync
info login Done logging in.
21819079******** Thread 1
19654870******** Thread 2
17164872******** Thread 3
17653762******** Thread 4
20098674******** Thread 5
19586484******** Thread 6
17980678******** Thread 7
20666455******** Thread 8
16936918******** Thread 9
17617104******** Thread 10
ERR! removeUserFromGroup { __ar: 1,
ERR! removeUserFromGroup   error: 1545003,
ERR! removeUserFromGroup   errorSummary: 'Invalid Action',
ERR! removeUserFromGroup   errorDescription: 'You cannot perform that action.',
ERR! removeUserFromGroup   payload: null,
ERR! removeUserFromGroup   bootloadable: {},
ERR! removeUserFromGroup   ixData: {},
ERR! removeUserFromGroup   bxData: {},
ERR! removeUserFromGroup   gkxData: {},
ERR! removeUserFromGroup   qexData: {},
ERR! removeUserFromGroup   lid: '6648676049*********' }
{ __ar: 1,
  error: 1545003,
  errorSummary: 'Invalid Action',
  errorDescription: 'You cannot perform that action.',
  payload: null,
  bootloadable: {},
  ixData: {},
  bxData: {},
  gkxData: {},
  qexData: {},
  lid: '6648676049*********' }
```

**Comment by 7osCraft** [comment]
@alencar Maybe those threads aren't chat groups so you must check if they are really groups. And also sometimes messenger keeps group threads event if you leave them so make sure those are threads you are in.

**Comment by alencar** [comment]
@7osCraft I see what this was not working for me.

I was trying with ARCHIVED group conversations. When I changed to INBOX, calls to removeUserFromGroup(...) started working.

@Schmavery so, the way it works for INBOX group conversations is different from the way it should work for ARCHIVED group conversations.
