### ISSUE TITLE
Error when message contain link

### ISSUE THREAD

**Issue by mrcyclo** [Schmavery/facebook-chat-api#667]
![image](https://user-images.githubusercontent.com/13806369/42469266-66218b7a-83e1-11e8-8d6a-48cb093d010b.png)
![image](https://user-images.githubusercontent.com/13806369/42469282-72ba5c5e-83e1-11e8-9dfb-f14233415513.png)

**Comment by ravkr** [comment]
Which version are you using? Npm or bleeding edge?

**Comment by Schmavery** [comment]
I can't read this error message but fwiw facebook does seem to like putting captchas and stuff on messages containing links when they suspect an account isn't real.

**Comment by Hongarc** [comment]
I send message contain link but don't have any problem.
Should be close this issue.

**Comment by Schmavery** [comment]
Thanks for checking, @Hongarc. As I mentioned, this may succeed for one user but fail for another because of facebook's abuse prevention heuristics. The best advice as always is to do your best to avoid spamming messages or logging in and out frequently.
