### ISSUE TITLE
Cookie fail with messenger.com API

### ISSUE THREAD

**Issue by ArthurGarnier** [Schmavery/facebook-chat-api#668]
Hi,
Since today or yesterday it seems Facebook change the way to set cookie with messenger.com API.

It seems every methods like sendMessage work, but every methods that use messenger.com fail with : 

```
ERR! changeGroupImage { error: 'Not logged in.' }
```

I also checked changeThreadColor (use messenger API too), same result.

**Comment by AstroCB** [comment]
This is also a problem with `setTitle`.

**Comment by AstroCB** [comment]
I'm also getting this error with `setTitle`

**Comment by AstroCB** [comment]
@Schmavery any thoughts?

**Comment by bobland1** [comment]
![image](https://user-images.githubusercontent.com/25375432/43046741-64ba50c6-8dc5-11e8-803e-011e282b61d7.png)

**Comment by bobland1** [comment]
Just did it in the browser to see what it returned

**Comment by Schmavery** [comment]
Not sure, @bobland1 seems to have the right idea though you might want to be looking at the cookies. I think this is where we set them on login.
https://github.com/Schmavery/facebook-chat-api/blob/7470cfe9b29d30f082f76cacc08748e4e19e8c15/index.js#L365-L369

I think the `saveCookie` function also does a bit of a hack to support messenger and facebook apis:
https://github.com/Schmavery/facebook-chat-api/blob/7470cfe9b29d30f082f76cacc08748e4e19e8c15/utils.js#L1108-L1120

**Comment by Theblood** [comment]
Test Post Color Obtains 

> POST /messaging/save_thread_color/?source=thread_settings&dpr=1 HTTP/1.1
> Host: www.facebook.com
> User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0
> Accept: */*
> Accept-Language: es-CL,es;q=0.8,en-US;q=0.5,en;q=0.3
> Accept-Encoding: gzip, deflate, br
> Referer: https://www.facebook.com/
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 617
> Cookie: fr=0SAVutN26ENbCsMy2.AWUKXQFX_xonlLFajGtWj9o1bU8.Ba0Blw.BE.FtF.0.0.BbVfin.AWWAh7RG; sb=_CvQWu2U9llHfMbCWZuScb4W; wd=1295x630; datr=_CvQWp_Vr7jBeExhqBqUW3NY; c_user=100007502617855; xs=36%3ArjizAn_QTGVdqw%3A2%3A1523592203%3A14997%3A12965; spin=r.4129119_b.trunk_t.1532360868_s.1_v.2_; presence=EDvF3EtimeF1532360930EuserFA21B07502617855A2EstateFDt3F_5bDiFA2user_3a1B04989069223A2ErF1EoF1EfF2C_5dElm3FA2user_3a1B04989069223A2Eutc3F1532360877291G53236093B6CEchFDp_5f1B07502617855F11CC; act=1532360926455%2F3
> Connection: keep-alive
> Pragma: no-cache
> Cache-Control: no-cache

**Comment by Schmavery** [comment]
Thanks @Theblood. I've redacted a couple of fields from your cookie information. As a reminder to everyone, sharing your cookies publicly for most sites is equivalent to providing the public with your login information, they can generally just get access to your logged in session. You may want to log out and back in on that machine to be safe, even though I deleted the creds.

**Comment by bobland1** [comment]
Any progress on what the underlining issue is here? found its not working with anything where u set or add something. like add reaction or set title

**Comment by bobland1** [comment]
The request header cookies:

> :authority: www.messenger.com
:method: POST
:path: /webgraphql/mutation/?doc_id=1491398900900362&variables=%7B%22data%22%3A%7B%22client_mutation_id%22%3A%220%22%2C%22actor_id%22%3A%22100007819751912%22%2C%22action%22%3A%22ADD_REACTION%22%2C%22message_id%22%3A%22mid.%24gAAblGMtGYeVrNkiJCllBQM1csw5l%22%2C%22reaction%22%3A%22%F0%9F%98%8D%22%7D%7D&dpr=1
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
content-length: 480
content-type: application/x-www-form-urlencoded
cookie: datr=iJZUW0hCNloD0_aVj3bTLho1; sb=l5ZUWwNpt-MZu7maHRMrJiyn; c_user=100007819751912; xs=19%3ASJFpp9xpQnK0pQ%3A2%3A1532270231%3A15073%3A4439; wd=661x947; presence=EDvF3EtimeF1533387771EuserFA21B07819751912A2EstateFDutF1533387771565CEchFDp_5f1B07819751912F2CC; act=1533387783218%2F5; pnl_data2=eyJhIjoib25hZnRlcmxvYWQiLCJjIjoiWE1lc3NlbmdlckRvdENvbU1haW5Db250cm9sbGVyIiwiYiI6ZmFsc2UsImQiOiIvdC8xOTQwNzQ0NTEyNjI3MTczIiwiZSI6W119
origin: https://www.messenger.com
referer: https://www.messenger.com/t/1940744512627173
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

>

**Comment by Schmavery** [comment]
@MzHub Mostly the latter. I have not much time for this repo these days but luckily many issues get fixed by the community. Feel free to take a shot at this one! I tried to provide some relevant code locations and am happy to provide any advice I can as I'm available. I can't imagine it will be that crazy of a fix, just seems like no one has had the opportunity/motivation to look at it yet. I'm sure everyone would be happy if it was taken care of :)

**Comment by powder** [comment]
I get the same error with changeNickname, I suspect it's similar/related.  Doubt this actually helps much, but, it's another function that doesn't appear to be working right at the moment.

**Comment by ArthurGarnier** [comment]
Tried a bit to fix this tonight. After some reseach, the problem come from the cookie "xs". 
I tried to set it manually once (sorry for the ugly code, don't really know JS) : 

![image](https://user-images.githubusercontent.com/3818749/44494939-2ad4c280-a66e-11e8-9911-e9ba05b69a1d.png)

Then revert changes, and now it works. 
Not sure to have some time soon to fix this, but now we have a precise idea of what's wrong. 
More over, the value seems to differ between facebook.com and messenger.com, but : 
* Using the value from messenger.com on facebook.com is not an issue
* Usieng the value from facebook.com on messenger.com doesn't log you. 

If I understood the code correctly, the cookies values are found on facebook.com only, so the issue is here.

**Comment by AstroCB** [comment]
@ArthurGarnier when you set the value manually, what were you setting it to?

**Comment by ArthurGarnier** [comment]
xs cookie valu from messenger.com if I remind correctly

**Comment by cevantes** [comment]
Does `forwardAttachment` use the same API? I get the same error.

**Comment by ArthurGarnier** [comment]
Yes, it's messenger.com api too

**Comment by 7osCraft** [comment]
Any news on when is this gonna be fixed?

**Comment by PixelHir** [comment]
Bump, looking for a fix

**Comment by szakes1** [comment]
Me too, I also have the same problem, but it seems that it has not been resolved, yet.

**Comment by cevantes** [comment]
Hi @ArthurGarnier perhaps you could describe how to approach this issue in some more details?

**Comment by ArthurGarnier** [comment]
Hello @cevantes 
If I knew how to fix it, I would already did it :)
 I shared all the details I have, but I'm not a JS dev (not even a dev in fact ;) )

**Comment by cevantes** [comment]
Ah no problem, I might take a look at it, just wanted to save time if anyone has already put effort into it.

**Comment by PiotrWegrzyn** [comment]
dump

**Comment by Schmavery** [comment]
I haven't had the time to dig into this deeply.
I linked to some relevant code and thanks a lot to the people who have put some work into investigating.

It seems like the hack we used in saveCookies (below) to reuse facebook sessions on messenger is no longer working. Maybe someone should compare their facebook cookies to their messenger cookies and see if it's potentially a simple format change (we're probably not that lucky though).
https://github.com/Schmavery/facebook-chat-api/blob/7470cfe9b29d30f082f76cacc08748e4e19e8c15/utils.js#L1108-L1120

More likely it seems that we'd have to either switch the entire login flow to use messenger 😨 or hopefully just remove this part from saveCookies:
https://github.com/Schmavery/facebook-chat-api/blob/7470cfe9b29d30f082f76cacc08748e4e19e8c15/utils.js#L1115-L1116
and then add something along the lines of this somewhere in index.js:
```javascript
utils
  .get("https://messenger.com", ctx.jar, form, globalOptions)
  .then(utils.saveCookies(ctx.jar));
```

Those parameters might need a lot of tweaking but if we're lucky that might be enough to "harvest" the messenger.com cookies. Otherwise we might need to add some code that tries to step through the messenger.com login flow (seems like a reasonably high chance that would be the case and would be more involved, but still basically just submitting requests in sequent).

**Comment by AstroCB** [comment]
I have tested this fix and can confirm that it works on `changeThreadEmoji`, `changeNickname`, `setTitle`, `changeGroupImage`, `changeThreadColor`, `changeAdminStatus`, `setMessageReaction`, `createPoll`, and `forwardAttachment`, which all had a messenger.com endpoint in common (surprise, surprise).

I believe this covers everything that errors were reported for 🙂. @lequanglam has packaged this into a PR [here](https://github.com/Schmavery/facebook-chat-api/pull/704) (just to directly link it to this thread).

I'm glad it was such a simple fix but it's hilarious that this little thing caused all these months of confusion. @Schmavery could we get a merge on that PR?

**Comment by Schmavery** [comment]
Thanks for testing @AstroCB. We knew those had the messenger.com endpoint in common, it was because facebook.com didn't used to expose those endpoints. Great to have it resolved, will merge.

**Comment by ArthurGarnier** [comment]
Can confirm it works ! 
That's weird I tried to change the domain several weeks ago and it didn't work. 

Thank you for the fix !
