### ISSUE TITLE
setMessageReaction and changeThreadColor throwing errors

### ISSUE THREAD

**Issue by slothdude** [Schmavery/facebook-chat-api#676]
I am having a lot of fun with this api but ran into 2 issues. When I try to send a reaction to a message with 
`api.setMessageReaction(":like:", message.threadID);`, I get `ERR! setReaction { error: 'Not logged in.' }`. My other issue is that when I try to change chat color to MessengerBlue with `api.changeThreadColor("#0000ff", message.threadID);`, I get `{ error: 'The color you are trying to use is not a valid thread color. Use api.threadColors to find acceptable values.' }` even though the same color is used in the example on https://github.com/Schmavery/facebook-chat-api/blob/HEAD/DOCS.md#apichangethreadcolorcolor-threadid-callback

In context: 
```
login(credentials, function callback (err, api) {
api.listen(function callback(err, message) {
if(message.type == 'message'){
  api.changeThreadColor("#0000ff", message.threadID);
  ...
  if(course != undefined){
    request('https://api.umd.io/v0/courses/' + course, function (error, response, body) {
      if (!error && response.statusCode == 200) {
        var jsonResponse = JSON.parse(body);
        api.sendMessage(jsonResponse.description,message.threadID);
        api.setMessageReaction(":like:", message.threadID);
      }
    });
  }
}
}
}
```

Here is a link to the full file if it is helpful: https://github.com/slothdude/facebook-chatbot/blob/master/index.js

**Comment by bobland1** [comment]
#668

**Comment by Schmavery** [comment]
thanks for the detailed info, going to track this in 668 as bobland said.

**Comment by gokaybiz** [comment]
Endpoint changed.

**Comment by Schmavery** [comment]
@gokaybiz the changeThreadColor api is pretty simple right now, if it's not too complicated of a change, feel free to submit a fix :)

**Comment by gokaybiz** [comment]
I have a matriculation tomorrow. Nevertheless I checked a little bit, It seems will hard to use because now colors have id's.
