### ISSUE TITLE
Getting videos with getThreadPictures

### ISSUE THREAD

**Issue by 7osCraft** [Schmavery/facebook-chat-api#677]
Hello,
  Is there a way to get sent and received videos in thread using getThreadPictures?
It only gets files with either .png or .jpg and not any .mp4 or other video extentions.

Edit: I know it says "getThreadPictures" but in messenger videos and pictures are in the same place.

**Comment by 7osCraft** [comment]
Anyone?

**Comment by ravkr** [comment]
This Facebook endpoint returns only pictures, we would have to modify it to use graph API instead... 
If you want to get videos, you have to use getThreadHistory, there should be everything (messages, photos, videos, other files, stickers...)

**Comment by 7osCraft** [comment]
Ok thank you!
