### ISSUE TITLE
changeAdminStatus returns 'Not logged in.'.

### ISSUE THREAD

**Issue by 7osCraft** [Schmavery/facebook-chat-api#682]
As the title says, when I try to use changeAdminStatus it returns { error: 'Not logged in.' }.
But everything else in the api is working fine.
And yes I'm using changeAdminStatus in a group chat and the account is an admin there.

**Comment by ravkr** [comment]
this is probably linked to #668

**Comment by Schmavery** [comment]
Going to close as duplicate of 668, thanks
