### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by unitpas** [Schmavery/facebook-chat-api#688]
I receive the following errors 
(STDERR) info login Logging in...
(STDERR) ERR! login Wrong username/password.

but the user/pass are correct, I can login in facebook using the same credentials.

Ive tried from two different ips with the same error

thanks

**Comment by ravkr** [comment]
are you using e-mail, phone number, your Facebook ID or nickname to login?
phone numbers sometimes need to be in form `+48123456789` instead of `123456789` (Country calling code)

**Comment by unitpas** [comment]
> are you using e-mail, phone number, your Facebook ID or nickname to login?
> phone numbers sometimes need to be in form `+48123456789` instead of `123456789` (Country calling code)

I'm using the email to login

**Comment by unitpas** [comment]
The code was working before, I didn't do any changes, shame version, same ip addresses, it just stopped working and I get "Wrong username/password." error, tested user/pass on fb from the same ip and it worked

**Comment by unitpas** [comment]
nevermind, tested into a fresh directory the readme example and it worked, I will debug my code, thank you
