### ISSUE TITLE
getting user access token

### ISSUE THREAD

**Issue by ZDevelop** [Schmavery/facebook-chat-api#7]
since the code logs in as the user provided i wondered if there is an option
to extract the access token from somewhere in index.js in order to work with facebook's graph api
in order to get list of friends, likes etc

**Comment by Schmavery** [comment]
In the future we might consider adding support for graph API calls but for now, we're not using an access token in the login process so it unfortunately it doesn't seem trivial to provide one.  Our code currently logs in as the user directly.

Is there a feature in particular that you want to use from the graph API?  There may be another way we can access it.

**Comment by ZDevelop** [comment]
Well currently my main objective is to get a list of all my friends on facebook

**Comment by bsansouci** [comment]
We made the access token available at api.getAccessToken() which returns a string.

This is a bit of a hack because it's using the Graph API Explorer's app ID. It has all permissions so drive safely ;)

**Comment by Schmavery** [comment]
Just to let you know, you're probably going to want to use the /me/friends endpoint to get the list of all your friends.
