### ISSUE TITLE
Block face account

### ISSUE THREAD

**Issue by vanhung89** [Schmavery/facebook-chat-api#70]
Sometime I was blocked face account because it detect I logged in other location. I use openshift server. Can you fix it? Or do we have any solution for that problem?

**Comment by blazeu** [comment]
Just do the verification process and it should be fine.

**Comment by vanhung89** [comment]
I know. But my user don't like that. Sometimes they can't verify because they have alot of friends and they don't remember all of their friends.

**Comment by bsansouci** [comment]
We can't do anything about that, all we can do is automate some things. So if FB asks you to confirm it was you who logged in from that location, we can automate that (with the `forceLogin` option coming in v1.0). But recognizing your friends for you... nope.

**Comment by Schmavery** [comment]
> Sometimes they can't verify because they have alot of friends and they don't remember all of their friends.

This is kind of the design of facebook we're talking about here, I don't think it makes sense to try and solve this problem here.  Sorry :)
Like @bsansouci said, you should definitely try out the `forceLogin` option.
