### ISSUE TITLE
How can i sign in with @yahoo.com.vn instead @gmail.com

### ISSUE THREAD

**Issue by aqquan2017** [Schmavery/facebook-chat-api#701]
I used with gmail , it works... But i can not sign in with my old Fb account which end @yahoo.com.vn
Is anyone suggest any solution ?? Thank in advance

**Comment by gamelaster** [comment]
Hello, every email should work. Please, what is output from console ?

**Comment by aqquan2017** [comment]
output says "wrong username or password", but when i try to sign in with gmail, it works...I have already signed in with gmail, just report can not sign in with yahoo..thank for answer!!

**Comment by gamelaster** [comment]
Nothing more? Then you really have wrong username or password.

**Comment by ravkr** [comment]
are you sure that you don't have any extra characters? maybe spaces?

**Comment by gamelaster** [comment]
@aqquan2017 Do you have \ character in your password?

**Comment by aqquan2017** [comment]
i just have _

**Comment by ravkr** [comment]
does using this email address on facebook.com work? maybe you are using address that is not confirmed

**Comment by aqquan2017** [comment]
yep gmail address is already work...just for you guy know i cant sign in with @yahoo.com, may be problem come from my fb account...Yahoo is very old

**Comment by ravkr** [comment]
so... is it  `@yahoo.com` or `@yahoo.com.vn`? and can you login on facebook.com (manually - in browser) with that address?

**Comment by aqquan2017** [comment]
it normally work in browser...and it @yahoo.com.vn

**Comment by ravkr** [comment]
I'm almost 100% sure that you just have a typo somewhere.... double check it
or try with clean project like another user did recently #688

**Comment by aqquan2017** [comment]
https://drive.google.com/drive/u/0/folders/1AmWcuA89R2aUswvx_l3IWvCMtUdrNQDk
you can see problem here...video inside

**Comment by Schmavery** [comment]
Yeah, we don't process the email in any way as far as I can tell. You can check if the browser escapes it or something by watching the login request go through in the browser and comparing it to the one we make.

**Comment by ravkr** [comment]
Can we close it?

**Comment by aqquan2017** [comment]
thank for your help...i doing great...close!!

**Comment by Schmavery** [comment]
Thanks everyone
