### ISSUE TITLE
What is this "skywalk" thing?

### ISSUE THREAD

**Issue by forcemagic** [Schmavery/facebook-chat-api#702]
I was just skimming through Facebook's requests, when I got this response to a `/pull` request.

```json
"ms": [{
  "payload": {
    "feedback_typing_subscribe": {
      "__typename":"FeedbackStartTypingResponsePayload",
      "feedback": {
        "id":"base64-encoded string: 'feedback:2043..8 chars..1290'",
        "is_eligible_for_real_time_updates":true,
        "feedback_typers":{"friend_count":0,"other_count":1},
        "subscription_target_id":"2043..8 chars..1290"
      }
    }
  },
  "type": "skywalker",
  "topic": "gqls/feedback_typing_subscribe/feedback_id_2043..8 chars..1290",
  "view_id": "11"
}]
```

Can anyone decipher what it means? If yes, and it's useful, maybe it should get implemented ;)

**Note:** I have searched the code, and the issues for "skywalker".

**Comment by Schmavery** [comment]
Probably just some internal analytics. If anyone has reason to believe otherwise, feel free to comment/reopen.
