### ISSUE TITLE
Can't send a message with a number with two decimal places.

### ISSUE THREAD

**Issue by miketamis** [Schmavery/facebook-chat-api#72]
You can send "this is a number 1"
You can send "this is a number 1.2"
But you can't send "this is a number 1.23"

weird bug

**Comment by Schmavery** [comment]
This seems to work for me in my initial testing.
Can you specify the branch you're working with and a small snippet of code that exhibits the problem?

**Comment by bsansouci** [comment]
Can't replicate here either. I'm closing this unless you can tell us how to replicate this :p
