### ISSUE TITLE
Cookies, Data, Privacy?

### ISSUE THREAD

**Issue by Dacetylan** [Schmavery/facebook-chat-api#748]
What happens when facebook tries to save a cookie? Where is that cookie saved? What kind of data is sent to the facebook servers? Is this a more private way of using messenger?

Thank you for your time and effort!

-Dacetylan

**Comment by Schmavery** [comment]
When facebook tries to save a cookie, we save it in `ctx.jar` which is just basically just some object that gets sent with requests iirc. Obvs no information is sent to facebook other than the messages etc that you send.
As far as "privacy" is concerned, this is about equivalent to if you were to use a browser exclusively for sending messages, and not do any other browsing on it.
Not sure if that's what you were looking for?

**Comment by Dacetylan** [comment]
> When facebook tries to save a cookie, we save it in `ctx.jar` which is just basically just some object that gets sent with requests iirc. Obvs no information is sent to facebook other than the messages etc that you send.
> As far as "privacy" is concerned, this is about equivalent to if you were to use a browser exclusively for sending messages, and not do any other browsing on it.
> Not sure if that's what you were looking for?

Thanks a lot, this is what I was looking for. I really appreciate you putting time into developing this.
