### ISSUE TITLE
api.unsendMessage doesn't work

### ISSUE THREAD

**Issue by xnerhu** [Schmavery/facebook-chat-api#749]
Hi! If I use this method, I get `TypeError: api.unsendMessage is not a function`.

# Details
- Node.js: v12.2.0
- facebook-chat-api: v1.6.1

**Comment by lequanglam** [comment]
`api.unsendMessage` isn't on npm yet, but you can use code directly from GitHub to get that function.

```shell
npm install Schmavery/facebook-chat-api
```
