### ISSUE TITLE
Chat history

### ISSUE THREAD

**Issue by Twelve-60** [Schmavery/facebook-chat-api#75]
Is it possible to access the chat history of a particular thread?

**Comment by Schmavery** [comment]
This should be possible using the getThreadHistory function I just added to the pre-release branch.  Docs for it should be out soon but we try to match the format of the messages returned by the listen function as  closely as possible, so if you want to get a head start, feel free to look at the code for it in `src/getThreadHistory.js`.

**Comment by Twelve-60** [comment]
Excellent, I'll have a look. Is it designed to fetch the entire history? The browser client fetches history in batches as requested (as you scroll up).

**Comment by bsansouci** [comment]
@Twelve-60 It follows the way the browser queries it, meaning you give it a [start and end point](https://github.com/Schmavery/facebook-chat-api/blob/71b3fbb23bd0d6d15072c90dd7a8c60fafb5c1d4/src/getThreadHistory.js#L7).
