### ISSUE TITLE
Any tips on how to not get identity verification prompts?

### ISSUE THREAD

**Issue by Th3OnlyN00b** [Schmavery/facebook-chat-api#753]
I'm just trying to run a simple echo bot, but within 10 minutes the account gets locked out and I have to send them a picture to verify that I'm human. I've done this three times, and I've even added a wait statement before sending messages in order to attempt to make it seem more realistic. 
```
const login = require("facebook-chat-api");

const sleep = (milliseconds) => {
    return new Promise(resolve => setTimeout(resolve, milliseconds))
}

login({email: "email@gmail.com", password: "password1234"}, (err, api) => {
    console.log("Logging in!");
    if(err) return console.error(err);

    api.listen((err, message) => {
        sleep(500 + Math.floor(Math.random()*500)).then(() => {
            if(message.body.split(" ").includes("blockchain")){
                api.sendMessage("All hail the blockchain", message.threadID);
                //api.sendMessage(message.body, message.threadID);
            }
        });
    });
});
```
Note that this is not my actual login info. 

I'm leaving the program running, so it shouldn't be logging in repeatedly from what I understand so that shouldn't be it. What am I doing wrong?

**Comment by KovalRomanK** [comment]
I get verification prompts, but they happen once every ~3 days and I have to enter a code that they sent to the bots email. But you should really be logging in with the app state, this isn't hard to implement, once the bot logs in you can do `api.getAppState()` to get the sate and save it. This is how I'm currently doing it:
```js
let saveAppState = false
let cred = {}
try {
  const appState = Fs.readFileSync(
    Path.resolve(process.env.FB_APP_STATE_PATH),
    'utf8'
  )
  cred.appState = JSON.parse(appState)
} catch (err) {
  cred.email = process.env.FB_EMAIL
  cred.password = process.env.FB_PASS

  saveAppState = true
}

const api = await login(cred, { logLevel: 'silent' })

if (saveAppState) {
  Fs.writeFileSync(
    Path.resolve(process.env.FB_APP_STATE_PATH),
    JSON.stringify(api.getAppState())
  )
}
```
For the first login, the app state will be saved and any future loggins will use the app state.
You can try this and see if you still get verification prompts, and if they slow down.

**Comment by lequanglam** [comment]
also you might want to change the user agent, and makes the bot send "seen" state (`api.markAsRead`)

**Comment by Th3OnlyN00b** [comment]
It was the `markAsRead`. Thanks!

**Comment by Schmavery** [comment]
Interesting, if people are conclusively seeing that sending the markAsRead query causes the account to be blocked less, I'd be happy to accept a PR that automatically sends markAsRead when it receives messages. Unless there people have objections/worries?
