### ISSUE TITLE
Tensorflow support

### ISSUE THREAD

**Issue by bobland1** [Schmavery/facebook-chat-api#764]
Hi, i've been following this repo for a while now. I was wondering if anyone knows of a way to integrate tensorflow with this.

I was planning on running a tensorflow docker container. And really want to integrate the two

Thanks in advance

**Comment by Schmavery** [comment]
Can you just install the package in your container? Not sure what the problem is

**Comment by Schmavery** [comment]
Feel free to reopen with an error message etc

**Comment by bobland1** [comment]
I have managed to integrate with a tensorflow 2.0 chatbot
