### ISSUE TITLE
Cannot receive message_reaction events

### ISSUE THREAD

**Issue by andybui01** [Schmavery/facebook-chat-api#769]
currently logging all event.types in a chat and most of them show up except for message_reaction. Could this be happening because I'm using api.listenMqtt()? Although I recall the docs saying something about how functionality should be the same.

Thanks

**Comment by 7osCraft** [comment]
It's working fine for me over mqtt. Could you check your code again?

**Comment by Schmavery** [comment]
cc @7osCraft

**Comment by andybui01** [comment]
@7osCraft How are you detecting the reacts? I'm just printing out all of the events and message_reaction doesn't appear once.

```

login({appState: JSON.parse(fs.readFileSync('appstate.json', 'utf8'))}, (err, api) => {
    if(err) return console.error(err);

    api.listenMqtt((err, event) => {
        console.log(event);
    });
});

```

**Comment by andybui01** [comment]
Ok I've found the issue, I didn't set

```
api.setOptions({listenEvents: true});
```
