### ISSUE TITLE
Logged-in as Page is not working properly.

### ISSUE THREAD

**Issue by rivc** [Schmavery/facebook-chat-api#772]
Hi, i have tried using whitehat account & my own account, and it's working perfectly, but when i trying to use my facebook page, it's not receiving any events. Tried using `listenMqtt` and only outputted `presence` object, not messages.

is there any way to make it working?, i want to make facebook page bot, using official messenger bot always rejected for individual/non-business bot.

this is my simple code
![image](https://user-images.githubusercontent.com/42661836/71257958-982e5b80-2367-11ea-880a-d5e31e1fb2e5.png)

Sorry about my bad english tho.

**Comment by 7osCraft** [comment]
Pages are not tested and not working yet on MQTT. I'll try to get it working as soon as I can.

**Comment by tienchung123** [comment]
it is not working right now

**Comment by lequanglam** [comment]
added support in version 1.7.0

**Comment by locmai0808** [comment]
@lequanglam login as page is now support in version 1.7.0? 
I tried using `api.listenMqtt` and callback function just return undefined.
