### ISSUE TITLE
Have checkpoint when login

### ISSUE THREAD

**Issue by tienchung123** [Schmavery/facebook-chat-api#774]
Hi, I have checkpoint when i try to login into my real facebook account. Every time I log in, it gets like that.
This is my code
```
login({email: "...", password: "..."}, (err, api) => {
    if(err) return console.error(err);
    fs.writeFileSync('appstate.json', JSON.stringify(api.getAppState()));
    console.log('sucsess')
});
```
How can fix this? Thanks

**Comment by tienchung123** [comment]
i can't login into my account

**Comment by lequanglam** [comment]
try changing user agent.

**Comment by tienchung123** [comment]
how can i changing user agent? I don't have any idea. Thanks
