### ISSUE TITLE
MQTT bug?

### ISSUE THREAD

**Issue by lequanglam** [Schmavery/facebook-chat-api#775]
![image](https://user-images.githubusercontent.com/29724654/71648145-21b03700-2d33-11ea-86bf-eaceb397aa71.png)
@7osCraft

**Comment by 7osCraft** [comment]
Yeah it looks like mqtt doesn't send all the data everytime. So we must put some undefined checks everywhere. I'll try to fix that.

**Comment by lequanglam** [comment]
https://github.com/fca-unofficial/fca-unofficial/commit/5067a0a79d65e2dc96a3e092b19e6f4e24d99874
