### ISSUE TITLE
listenMqtt issues (again)

### ISSUE THREAD

**Issue by lequanglam** [Schmavery/facebook-chat-api#787]
![image](https://user-images.githubusercontent.com/29724654/73645348-b21ec600-46a9-11ea-83e7-abf5a0ae3c3e.png)
and this thing
![image](https://user-images.githubusercontent.com/29724654/73656571-05514280-46c3-11ea-8c00-250000cb0916.png)
_yes i'm using my own repo, but error part is identical._

**Comment by Schmavery** [comment]
cc @7osCraft

**Comment by 7osCraft** [comment]
I think there is a problem with the formatting of ForcedFetch responses, but it should be the same kind of message in ``getThreadHisrory``, I'll look into it.
And for the second image, are you using pages or a normal account?

**Comment by lequanglam** [comment]
normal account.

**Comment by lequanglam** [comment]
Update: Data inside image 1:
![image](https://user-images.githubusercontent.com/29724654/74588191-e345b180-502c-11ea-89d6-16d59a70b744.png)
look like we need to check if it's null.
