### ISSUE TITLE
Facebook logs me out every 3 days and asks for a password change

### ISSUE THREAD

**Issue by abriginets** [Schmavery/facebook-chat-api#792]
Since Facebook migrated to MQTT and I updated my bot to the newest version I started getting logged out every 3 days and asked to change my password. Bot says:

```
ERR! Error: Connection refused: Server unavailable 
Connection refused: Server unavailable
ERR! login Error retrieving userID. This can be caused by a lot of things, including getting blocked by Facebook for logging in from an unknown location. Try logging in with a browser to verify.
{
  error: 'Error retrieving userID. This can be caused by a lot of things, including getting blocked by Facebook for logging in from an unknown location. Try logging in with a browser to verify.'
}
```

I have 2FA enabled in my Facebook account and still getting promted with "reset your password" thing. Everything I do is logging in and listening for one exact chat, nothing more. Is there something `facebook-chat-api` doing that might cause this behavior? Or is there something that can help me prevent this?

**Comment by tutyamxx** [comment]
Yep, same

**Comment by Turbine1991** [comment]
I've not even got 2FA and it disabled my messanger only Facebook account after a handful of logins, due to "suspicious activity".

**Comment by Schmavery** [comment]
#852
