### ISSUE TITLE
HTML Received instead of JSON in pull request.

### ISSUE THREAD

**Issue by vakkendwarf** [Schmavery/facebook-chat-api#794]
Trying to login:

```
ERR! login Error inside first pull request. Received HTML instead of JSON. Logging in inside a browser might help fix this.
{ error: 'Error inside first pull request. Received HTML instead of JSON. Logging in inside a browser might help fix this.' }
```

Login code:
```
const obj = {email: "**[REDACTED]**", password: "**[REDACTED]**"};

login(obj, (err, api) => {

    if(err) {

        switch (err.error) {

            case 'login-approval':
    
                console.log('Enter code > ');
    
                rl.on('line', (line) => {
                    err.continue(line);
                    rl.close();
                });

                break;

            default:

                console.error(err);

        }

        return;

    }
```

**Comment by DRaichev** [comment]
I have the same problem, and pretty simillar login code.

**Comment by RandallKent** [comment]
I was able to resolve this by generating a new app state.

**Comment by vakkendwarf** [comment]
This code is used to generate apostate.

**Comment by PusanStudio** [comment]
> I was able to resolve this by generating a new app state.

is works

**Comment by vakkendwarf** [comment]
What if this is the code that generates my appstate, and it does not work

**Comment by lequanglam** [comment]
Facebook removed pull.

*yes, i'm working on it*

**Comment by AstroCB** [comment]
I'm also getting this error now, regardless of whether I'm logging in from an appstate or a fresh login.

**Comment by PusanStudio** [comment]
I can't login today. 
and generating new appstate is not work.

```
info login Logging in...
info login You have login approvals turned on.
ERR! login login-approval
Enter code >
******
info login Logged in
info login Request to reconnect
info login Request to pull 1
ERR! login Error inside first pull request. Received HTML instead of JSON. Logging in inside a browser might help fix this.
{
  error: 'Error inside first pull request. Received HTML instead of JSON. Logging in inside a browser might help fix this.'
}
```

**Comment by 7osCraft** [comment]
I think facebook pushed this change to everyone now.

**Comment by RandallKent** [comment]
I'm now seeing the same error as @PusanStudio as unable to generate a new app state 😭

**Comment by KMatuszak** [comment]
Any updates on this?

**Comment by AstroCB** [comment]
@lequanglam Any updates?

**Comment by lequanglam** [comment]
> @lequanglam Any updates?

you can use my forked repo (`fca-unofficial`) to bypass that pull request. i'm still working on it through.

**Comment by AstroCB** [comment]
@lequanglam Cool, seems to be working great so far. I'm using this in [BotCore](/AstroCB/BotCore) now if anyone is looking for a way to abstract away their login issues (and I'll switch this back to mainline once the fix gets merged).

**Comment by JosephBBa** [comment]
@lequanglam @AstroCB Any way to login in as detailed as possible, 
Best regards to everyone.

**Comment by AstroCB** [comment]
@JosephBBa You can take a look at the docs [here](https://github.com/AstroCB/BotCore/blob/master/DOCS.md#login-1).

The easiest way to get running is this:

```js
const botcore = require("messenger-botcore");
botcore.login.login({
    EMAIL: "your@email.com",
    PASSWORD: "your_password"
}, (err, api) => {
    // Your code here
});
```
You can then use the API as usual. You might also need some credentials from [Memcachier](https://www.memcachier.com) as explained in the docs. If you run into any issues, feel free to post on the repo – I don't want to clutter this thread.

**Comment by PusanStudio** [comment]
(`fca-unofficial`)  Why `Connection closed.` 
Shortly after running the bot. 
```
info login Logged in
info login Request to base pull
WARN login Error inside first pull request. Received HTML instead of JSON. Facebook might removed pull request for this account.
WARN login Bad response from base pull (t: pull-removed)
info login Done logging in.

{
  type: 'message',
  senderID: '******',
  body: '🎉',
  threadID: '******',
  messageID: '******',
  attachments: [],
  mentions: {},
  timestamp: '******',
  isGroup: true
}
Connection closed.
```

**Comment by lequanglam** [comment]
> (`fca-unofficial`) Why `Connection closed.`
> Shortly after running the bot.
> 
> ```
> info login Logged in
> info login Request to base pull
> WARN login Error inside first pull request. Received HTML instead of JSON. Facebook might removed pull request for this account.
> WARN login Bad response from base pull (t: pull-removed)
> info login Done logging in.
> 
> {
>   type: 'message',
>   senderID: '******',
>   body: '🎉',
>   threadID: '******',
>   messageID: '******',
>   attachments: [],
>   mentions: {},
>   timestamp: '******',
>   isGroup: true
> }
> Connection closed.
> ```

ignore it, MQTT will automatically make a new connection.

**Comment by PusanStudio** [comment]
When the connection is closed
MyBot no listen event come in.

**Comment by japaodsc** [comment]
Any updates? I'm still having this problem atm

`info login Logging in...
info login You have login approvals turned on.
ERR! login login-approval
Enter code >

info login Logged in
info login Request to reconnect
info login Request to pull 1
ERR! login Error inside first pull request. Received HTML instead of JSON. Logging in inside a browser might help fix this.
{
  error: 'Error inside first pull request. Received HTML instead of JSON. Logging in inside a browser might help fix this.'
}`

**Comment by 7osCraft** [comment]
I'll make a PR in a moment to fix this issue.

**Comment by nabildroid** [comment]
I still facing the same issue
```javascript 
const login = require("facebook-chat-api");
const creaditial = {
    email: "email",
    password: "password"
};

login(creaditial, (err, api) => {
	console.log(err);
});
```
returns 
```
info login Request to pull 1

ERR! login Error inside first pull request. Received HTML instead of JSON. Logging in inside a browser might help fix this.

{ error:
   'Error inside first pull request. Received HTML instead of JSON. Logging in inside a browser might help fix this.' }
```

**Comment by 7osCraft** [comment]
Please use the latest bleeding edge version from github.
