### ISSUE TITLE
No option to suppress console.log?

### ISSUE THREAD

**Issue by Tankenstein** [Schmavery/facebook-chat-api#8]
In my application, i'd like to create my own messages to the console, and not be bogged down in a constant stream of "Got answer in  3125". To do this, i just deleted all of the damn console.log-s, but i feel like you should implement a logger. Thanks for this module by the way, works great.

**Comment by Schmavery** [comment]
@Tankenstein Is this something like what you're looking for?

**Comment by Tankenstein** [comment]
This is better, since i can now override that and disable the messages, most optimal would be an option like login.disableMessages(), which i might implement and make a pull request. Thanks!

**Comment by Schmavery** [comment]
Go for it! :D
