### ISSUE TITLE
Listen can be run only once for an api instance

### ISSUE THREAD

**Issue by zanstro** [Schmavery/facebook-chat-api#801]
After I upgraded from 1.6.1 to 1.7.0 I am not able to run api.listenMqtt() again for the same api instance. I use login() to create an api instance and then I export this instance and use it in my code to listen for Facebook messages based on specific requests I receive (I have a http.createServer listening for requests and I use these requests to send messages to FB with api.sendMessage()). 

After each response from my server, I run stopListening() as I don't wait for any more messages from Facebook. Everything works fine for the first request but when I get a second request api.listenMqtt() is not working.

**Comment by KMatuszak** [comment]
I think that these variables should be resetted after stopListening
```js
var identity = function () {};
var mqttClient = undefined;
```

**Comment by zanstro** [comment]
Any idea of how can I access these variables through the api instance? Thank you in advance

**Comment by KMatuszak** [comment]
try to modify listenMqtt in your node_modules

**Comment by zanstro** [comment]
Thank you. I tried it but it didn't help :/

**Comment by stergios-tegos** [comment]
I have the same issue with listenMqtt :( 
Any idea how this could be resolved?
Thanks in advance

**Comment by returnmk** [comment]
This is a major issue for me too. Please advice.

**Comment by Schmavery** [comment]
@7osCraft can we add the mqttClient variable to the API context instead of making it a global variable? sorry I missed this during review

https://github.com/Schmavery/facebook-chat-api/blob/3227d2ef8b8354bcb0f3eab5d293421d4c85f524/index.js#L67-L75

**Comment by 7osCraft** [comment]
Sure. I'll look into it and do some tests. Thanks for notifying me.
I'll try to make a fix soon.

**Comment by returnmk** [comment]
@7osCraft thank you for looking into it!

Do we have any updates on this?

**Comment by 7osCraft** [comment]
Hello,
Sorry for the delay, I'll try to get a PR today.
