### ISSUE TITLE
Source code in Github and Npmjs are different.

### ISSUE THREAD

**Issue by thangl3** [Schmavery/facebook-chat-api#805]
I do not know why maybe it occurs with only me or with anyone.

I run `npm install facebook-chat-api` package in node_modules like that.

![image](https://user-images.githubusercontent.com/15165794/78327128-589e1f00-75a6-11ea-9fe3-ddb469ef2650.png)

Code in Github

![image](https://user-images.githubusercontent.com/15165794/78326146-ceed5200-75a3-11ea-809c-20336e24c980.png)

Because running, it always throw to me `Error inside first pull request. Received HTML instead of JSON. Logging in inside a browser might help fix this.`.

**Comment by lequanglam** [comment]
of course, because you are viewing code in `master` branch ('bleeding edge' version).

**Comment by thangl3** [comment]
Thank you.
