### ISSUE TITLE
Z_DATA_ERROR incorrect data check

### ISSUE THREAD

**Issue by bbatliner** [Schmavery/facebook-chat-api#82]
I'm working with the [Electron](https://github.com/atom/electron) framework on a messaging application. Occasionally when I make an API request with facebook-chat-api, I will receive a `Z_DATA_ERROR` from the zlib library. There seems to be no pattern to when this error is thrown, and the entire API request is cancelled and fails. I could not find the source of this error beyond the line number shown below (`zlib.js` doesn't exist in my node_modules, though...). I'm not sure if this is an issue with Electron or the Facebook API, but I would appreciate some discussion to get to the bottom of this!

Thanks everyone, see below for my console outputs.

The Error object:
```
[9584:1002/173425:INFO:CONSOLE(0)] { [Error: incorrect data check]
  cause: { [Error: incorrect data check] errno: -3, code: 'Z_DATA_ERROR' },
  isOperational: true,
  errno: -3,
  code: 'Z_DATA_ERROR' }
```
Line number:
```
[9584:1002/173425:INFO:CONSOLE(0)] Error in login:
[9584:1002/173425:INFO:CONSOLE(0)]      at Zlib._handle.onerror (zlib.js:363:17)
```

**Comment by Schmavery** [comment]
I guess there's no chance for a minimal example of code that results in this issue?

**Comment by bbatliner** [comment]
It happens to me when I try to log in. If it happens elsewhere I'll let you know. The last console output from the module is ["Logging in..."](https://github.com/Schmavery/facebook-chat-api/blob/40213bf33403ac5978ba81d71023b9c6587f6096/index.js#L146), and then it spits out the error. Here is a [full console output](http://pastebin.com/Pf0tunw7) from when it last happened. 

Below you'll find the code snippet from how I'm logging in.

```js
login({email: username, password: password}, function (err, tmpApi) {
    if (err) {
        console.error(err);
        return ipc.send(ipcChannels.facebookLoginError, JSON.stringify(err));
    }
    // Store the api for future use
    api = tmpApi;
    // Get the user's name and send it back to the client
    afterLogin();

    ...

**Comment by Schmavery** [comment]
@bbatliner @bsansouci Knowing nothing about Electron or zlib, I'd be inclined to say investigating this is out of the scope of this api...
That said, if you find a solution that involves tweaking the api, we'd love a pull request.

**Comment by bsansouci** [comment]
@Schmavery agreed, we can't help here... My guess is that electron overwrites something without following the specs. (so maybe they have their own get request thing or something along those lines)
