### ISSUE TITLE
Allow sending of url & file in 1 message

### ISSUE THREAD

**Issue by Schmavery** [Schmavery/facebook-chat-api#83]
#### Docs:
- [x] add entry for `deleteThread()`
- [x] update method of retrieving userID
- [ ] Fix url/file problem (thanks @blazeu)

Feel free to suggest any other small issues that need to be touched up!

**Comment by bbatliner** [comment]
See #84 :smile:

**Comment by blazeu** [comment]
I just found out that you can send both url & file/image attachment in 1 message.
![image](https://cloud.githubusercontent.com/assets/1438859/10260996/3a5b670e-69ae-11e5-8466-b2a138b63324.png)

The current **sendMessage** function can only send **1** type of attachment/message.

**Comment by Schmavery** [comment]
This issue will be tracked by #184.
