### ISSUE TITLE
Account block

### ISSUE THREAD

**Issue by Dutch77** [Schmavery/facebook-chat-api#833]
I wrote a super simple bot above this api https://github.com/Dutch77/chatbot and we had a lot of fun with it..

But fb now recognizes this api and block account after few minutes, even if it's run from my local computer with my real account...

I guess this api is over. Or does anyone have any workaround? Does anyone have similar issues last few days? Thx

**Comment by d-rusev** [comment]
I have the same problem. On same computer, same user agent, even fb open in browser at same time.  Its been happening for me since March.

**Comment by PixelHir** [comment]
Same, looks like we need to change how the api is connecting to the servers

**Comment by PixelHir** [comment]
> I'm afraid there is some heuristic protection that recognizes unusual behaviour. :/

My guess is that API is using some obsolete way to connect or sends some incorrect headers

**Comment by Schmavery** [comment]
#852
