### ISSUE TITLE
Sending a message starting with a mention doesn’t display the mention

### ISSUE THREAD

**Issue by ryanmohta** [Schmavery/facebook-chat-api#848]
The documentation reveals that this is the proper way to mention a chat participant in a message:
```javascript
api.sendMessage({
    body: 'Hello @Sender! @Sender!',
    mentions: [{
         tag: '@Sender',
         id: message.senderID,
         fromIndex: 9, // Highlight the second occurrence of @Sender
    }],
}, message.threadID);
```

While this method works if the mention is in the middle of the message, it does not take effect when the mention is at the very _start_ of the message. In this example I attempt to send a message starting with the mention…

```javascript
api.sendMessage({
    body: '@Sender hello!',
    mentions: [{
        tag: '@Sender',
        id: participantID,
    }],
}, message.threadID);
```

…and got this instead:
<img width="420" alt="Screen Shot 2020-11-23 at 19 59 53" src="https://user-images.githubusercontent.com/19882060/100047812-3b81bf00-2dc8-11eb-86d2-6f9caffe9e8f.png">

However, if I add a character before the start of the message (notice the ‘a’ in line 2)…

```javascript
api.sendMessage({
    body: 'a@Sender hello!',
    mentions: [{
        tag: '@Sender',
        id: participantID,
    }],
}, message.threadID);
```

…the program works as expected:
<img width="463" alt="Screen Shot 2020-11-23 at 19 59 46" src="https://user-images.githubusercontent.com/19882060/100047817-40df0980-2dc8-11eb-8d34-03f00156db05.png">

Not sure if there’s anything I need to do on my end for this to work, but any help is appreciated! FYI, I’m on version 1.8.0, which I believe is the latest version publicly available.

**Comment by wangpatrick57** [comment]
I’m getting this issue too!

**Comment by AstroCB** [comment]
This seems to be a Facebook bug that I've witnessed in the wild from real (non-bot) users as well. For now, I'm working around this by prepending my bot's mention messages with a [zero-width space](https://www.fileformat.info/info/unicode/char/200b/index.htm).

You can represent this in a JS string as `\u200B`, so `"\u200B@Sender"` becomes just `"@Sender"` when it's displayed, and gets around this bug because the mention isn't technically at the beginning of the string.

**Comment by ryanmohta** [comment]
@AstroCB this worked perfectly, thank you so much!
