### ISSUE TITLE
Feature request: command-line chat client

### ISSUE THREAD

**Issue by sid-kap** [Schmavery/facebook-chat-api#86]
Hi,

Is anyone considering building a command-line chat client? I would love to be able to send facebook messages without opening up a browser window.

**Comment by Schmavery** [comment]
This shouldn't be too complicated to make with using the api, but I don't think it's within the scope of this particular project.
It looks like there are a couple people working on this:
https://github.com/mjkaufer/Messer
https://github.com/maxtuck21/termchat
