### ISSUE TITLE
Message collectors?

### ISSUE THREAD

**Issue by hoangvu12** [Schmavery/facebook-chat-api#863]
Right so what I want my bot to do is wait for a message from the user so "!spec" when it gets that message I want it to respond with "See or Change?" then wait for you to type back "see" or "change". I see discord.js made an "awaitMessage" method or Message Collector class to do this. So i'm here to ask if anyone made a similar one or any suggestion. Thank you

**Comment by Schmavery** [comment]
I haven't heard of anyone having already implemented this but you could do it in your code on top of listen/listenMqtt
Something like this??
```javascript
let awaiters = [];
let awaitMessage = () => {
  const promise = new Promise((resolve) => awaiters.push(resolve))
};

api.listenMqtt((err, msg) => {
  if (err) return;
  awaiters.forEach(resolve => resolve(msg))
  awaiters = [];
})

/// your application code:
api.sendMessage("See or Change?")
const response = await awaitMessage();
api.sendMessage("k thx")
```

Concievably you might want to make it so that you can await on a channel or something but that's not a big change.
