### ISSUE TITLE
wrong username/password error

### ISSUE THREAD

**Issue by realrecordzLab** [Schmavery/facebook-chat-api#867]
After two days of usage without problems, my node cli script that use this library has stopped working. I'm unable to login from the script and I always get wrong username/password message. I've tried to login from the browser and all is working fine, also tried to get a new ip but without success. Is there a fix I can use for this problem?
The only way to make things work is to use an appstate.json file but now I've changed the password so the file will not work anymore. 

I've saved my credentials insida a dedicated `.env` file

**Comment by mpadlein** [comment]
I having same problem. Maybe Zucc changed something.

**Comment by sebasbe91** [comment]
Same here :(

**Comment by sebasbe91** [comment]
What I can see, they changed the way to send the password, new is encrypted on the field "encpass".

`curl 'https://www.facebook.com/login/device-based/regular/login/?login_attempt=1&lwv=101' \
  -H 'authority: www.facebook.com' \
  -H 'pragma: no-cache' \
  -H 'cache-control: no-cache' \
  -H 'sec-ch-ua: "Chromium";v="88", "Google Chrome";v="88", ";Not A Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'upgrade-insecure-requests: 1' \
  -H 'origin: https://www.facebook.com' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36' \
  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-mode: navigate' \
  -H 'sec-fetch-user: ?1' \
  -H 'sec-fetch-dest: document' \
  -H 'referer: https://www.facebook.com/login/?privacy_mutation_token=eyJ0eXBlIjowLCJjcmVhdGlvbl90aW1lIjoxNjEzNjgzMzIwLCJjYWxsc2l0ZV9pZCI6MzgxMjI5MDc5NTc1OTQ2fQ%3D%3D' \
  -H 'accept-language: en' \
  -H 'cookie: sb=RNIuYD2p5SjVAhO_ny_YU2xl; datr=RNIuYNA7wjxywgmhU0NzmTup; dpr=2; locale=en_US; wd=318x1146; fr=1VGCgSV9BosoWCJpu.AWXQH9OzcYDSPWzfIXM4tHEwxSs.BgLtJE.lR.AAA.0.0.BgLts8.AWUKc6--GOI' \
  --data-raw 'jazoest=21059&lsd=AVoKdwgVctc&display=&enable_profile_selector=&isprivate=&legacy_return=0&profile_selector_ids=&return_session=&skip_api_login=&signed_next=&trynum=1&timezone=180&lgndim=eyJ3IjoyNTYwLCJoIjoxNDQwLCJhdyI6MjU2MCwiYWgiOjE0MTcsImMiOjI0fQ%3D%3D&lgnrnd=132517_ClfE&lgnjs=1613683517&email=sdasdas&prefill_contact_point=sd&prefill_source=browser_dropdown&prefill_type=contact_point&first_prefill_source=last_login&first_prefill_type=contact_point&had_cp_prefilled=true&had_password_prefilled=false&ab_test_data=v%2FffAvAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAAAAAl%2FMlAAAAAAIAAA&encpass=%23PWD_BROWSER%3A5%3A1613683849%3AAfJQAOMlndN7kSidFG776kuFzQGip4Ms6dt4bkk3b40T5t17EO2H%2F%2B900xSnhVKrIzPZl3ScrX6yEnYOeX1%2But2%2BTgU0K7cTQFitd1%2F0hujcSjoWPXmy6EGO0OOYI86RiSSe617sL66GBl0%2F' \
  --compressed`

**Comment by realrecordzLab** [comment]
> What I can see, they changed the way to send the password, new is encrypted on the field "encpass".

Where do you find that field? Please can you show a screen of this field?

**Comment by realrecordzLab** [comment]
@sebasbe91  I've done some debug and I've found the field encpass you've writed about in the headers, I think that to make the library working again the headers needs to be intercepted. I'm not sure how the field is generated, seems to be a `base64` string combined uding `:` with a cipher and a key?

**Comment by sebasbe91** [comment]
I was checking it deeper, it uses a Facebook library that encrypts it with a public key got from the form field. I think it necessary to replicate the same behavior.

**Comment by realrecordzLab** [comment]
> I was checking it deeper, it uses a Facebook library that encrypts it with a public key got from the form field. I think it necessary to replicate the same behavior.

Is this library available on github? I want to try logging in using puppeteer or another headless browser, not sure if I will have success

**Comment by sebasbe91** [comment]
I used dev tools in chrome to check it, needs further investigation.

**Comment by realrecordzLab** [comment]
> I used dev tools in chrome to check it, needs further investigation.

let me know if you have any news about. The simplest solution I can think now is to copy the script you've found and then implement it inside the library to send the password crypted in the `encpass` field? or get cookies after login from chrome, but this will be more tricky

**Comment by realrecordzLab** [comment]
I've used [puppeteer](https://pptr.dev) to login in messenger, I need to test also with facebook. This way seems working without problems. I'm able to get the needed cookies, I will try to implement it inside this library to replace the actual login method and to provide the needed informations for the correct creation of the `appstate.json` file.

**Comment by tungnnt** [comment]
> I've used [puppeteer](https://pptr.dev) to login in messenger, I need to test also with facebook. This way seems working without problems. I'm able to get the needed cookies, I will try to implement it inside this library to replace the actual login method and to provide the needed informations for the correct creation of the `appstate.json` file.

Can you show me how to get Facebook cookie as JSON format like appstate.json ?

**Comment by realrecordzLab** [comment]
> > I've used [puppeteer](https://pptr.dev) to login in messenger, I need to test also with facebook. This way seems working without problems. I'm able to get the needed cookies, I will try to implement it inside this library to replace the actual login method and to provide the needed informations for the correct creation of the `appstate.json` file.
> 
> Can you show me how to get Facebook cookie as JSON format like appstate.json ?

The cookies that are created after the login with puppeteer are a bit different from the structure of the `appstate.json` file, I've opted to trying using a different `userAgent` into the options of the script and seems working. You can reference [this issue](https://github.com/Schmavery/facebook-chat-api/issues/836) for more details. 

If you want to use puppeteer to get the cookies, you can use something like this:
``` 
const puppeteer = require('puppeteer');
const fs = require('fs');
const path = require('path');

( async () => {

(async () => {
    const browser = await puppeteer.launch({
        headless: false
    });
    
    const page = await browser.newPage();
    
    await page.goto('https://facebook.com/login, {
        waitUntil: ['load', 'networkidle2']
    });
    
    const cookieBanner = await page.$('[data-testid="cookie-policy-banner-accept"]');
    await cookieBanner.click();
    
    const emailField = await page.waitForSelector('[name="email"]', {timeout: 3000});
    await emailField.type(process.env.FB_EMAIL, {delay: 100});

    const passwordField = await page.waitForSelector('[name="pass"]', {timeout: 3000});
    await passwordField.type(process.env.FB_PASSWORD, {delay: 100});

    const submitButton = await page.waitForSelector('[name="login"]', {timeout: 3000});
    await submitButton.click();

    page.waitForNavigation().then( await (response) => {
       console.log(response.url(), response.headers(), response.method());
       // to get the correct cookies you need to pass the url to the cookies() method 
       // use await or .then() the promise return an object with all the needed info
       const cookies = await page.cookies(response.url());   
       // save your cookies to a file or use them in your code using fs.writeFileSync(...)
    });
   
})();
```

**Comment by trangcongloc** [comment]
> The cookies that are created after the login with puppeteer are a bit different from the structure of the `appstate.json` file, I've opted to trying using a different `userAgent` into the options of the script and seems working. You can reference [this issue](https://github.com/Schmavery/facebook-chat-api/issues/836) for more details.
> 
> If you want to use puppeteer to get the cookies, you can use something like this:
> 
> ```
> const puppeteer = require('puppeteer');
> const fs = require('fs');
> 
> ( async () => {
> 
> (async () => {
>     const browser = await puppeteer.launch({
>         headless: false
>     });
>     
>     const page = await browser.newPage();
>     
>     await page.goto('https://facebook.com/login, {
>         waitUntil: ['load', 'networkidle2']
>     });
>     
>     const cookieBanner = await page.$('[data-testid="cookie-policy-banner-accept"]');
>     await cookieBanner.click();
>     
>     const emailField = await page.waitForSelector('[name="email"]', {timeout: 3000});
>     await emailField.type(process.env.FB_EMAIL, {delay: 100});
> 
>     const passwordField = await page.waitForSelector('[name="pass"]', {timeout: 3000});
>     await passwordField.type(process.env.FB_PASSWORD, {delay: 100});
> 
>     const submitButton = await page.waitForSelector('[name="login"]', {timeout: 3000});
>     await submitButton.click();
> 
>     page.waitForNavigation().then( await (response) => {
>        console.log(response.url(), response.headers(), response.method());
>        // to get the correct cookies you need to pass the url to the cookies() method 
>        // use await or .then() the promise return an object with all the needed info
>        const cookies = await page.cookies(response.url());   
>        // save your cookies to a file or use them in your code using fs.writeFileSync(...)
>     });
>    
> })();
> ```

I'm using your code to get Cookie but the API showing this error
```
ERR! login Error: Cookie not in this host's domain. Cookie:www.facebook.com Request:www.messenger.com
```

I tried to get cookie from `https://www.messenger.com/` and getting this error

```
ERR! login Error retrieving userID. This can be caused by a lot of things, including getting blocked by Facebook for logging in from an unknown location. Try logging in with a browser to verify.
{
  error: 'Error retrieving userID. This can be caused by a lot of things, including getting blocked by Facebook for logging in from an unknown location. Try logging in with a browser to verify.'
}
```

i double-check but my bot account didn't get any Checkpoint

**Comment by realrecordzLab** [comment]
@trangcongloc the library will create a different structure for the cookies that will be saved inside the `appsate.json` file. If you want to use puppeteer to get only the cookies, after the login you will need to format them to to reflect the appState expected structure otherwise the library will not work. 

The wrong username/password error can be fixed by setting a different user-agent instead of the default one used from the library. Please refer to [this issue](https://github.com/Schmavery/facebook-chat-api/issues/836) for details.

**Comment by vakkendwarf** [comment]
> > The cookies that are created after the login with puppeteer are a bit different from the structure of the `appstate.json` file, I've opted to trying using a different `userAgent` into the options of the script and seems working. You can reference [this issue](https://github.com/Schmavery/facebook-chat-api/issues/836) for more details.
> > If you want to use puppeteer to get the cookies, you can use something like this:
> > ```
> > const puppeteer = require('puppeteer');
> > const fs = require('fs');
> > 
> > ( async () => {
> > 
> > (async () => {
> >     const browser = await puppeteer.launch({
> >         headless: false
> >     });
> >     
> >     const page = await browser.newPage();
> >     
> >     await page.goto('https://facebook.com/login, {
> >         waitUntil: ['load', 'networkidle2']
> >     });
> >     
> >     const cookieBanner = await page.$('[data-testid="cookie-policy-banner-accept"]');
> >     await cookieBanner.click();
> >     
> >     const emailField = await page.waitForSelector('[name="email"]', {timeout: 3000});
> >     await emailField.type(process.env.FB_EMAIL, {delay: 100});
> > 
> >     const passwordField = await page.waitForSelector('[name="pass"]', {timeout: 3000});
> >     await passwordField.type(process.env.FB_PASSWORD, {delay: 100});
> > 
> >     const submitButton = await page.waitForSelector('[name="login"]', {timeout: 3000});
> >     await submitButton.click();
> > 
> >     page.waitForNavigation().then( await (response) => {
> >        console.log(response.url(), response.headers(), response.method());
> >        // to get the correct cookies you need to pass the url to the cookies() method 
> >        // use await or .then() the promise return an object with all the needed info
> >        const cookies = await page.cookies(response.url());   
> >        // save your cookies to a file or use them in your code using fs.writeFileSync(...)
> >     });
> >    
> > })();
> > ```
> 
> I'm using your code to get Cookie but the API showing this error
> 
> ```
> ERR! login Error: Cookie not in this host's domain. Cookie:www.facebook.com Request:www.messenger.com
> ```
> 
> I tried to get cookie from `https://www.messenger.com/` and getting this error
> 
> ```
> ERR! login Error retrieving userID. This can be caused by a lot of things, including getting blocked by Facebook for logging in from an unknown location. Try logging in with a browser to verify.
> {
>   error: 'Error retrieving userID. This can be caused by a lot of things, including getting blocked by Facebook for logging in from an unknown location. Try logging in with a browser to verify.'
> }
> ```
> 
> i double-check but my bot account didn't get any Checkpoint

It doesn't work for me. I tried using it as TS and as JS and there's errors in both (unfortunately i'm too new to the programming paradigm that javascript uses so i have no idea how to fix this.

TS:
![image](https://user-images.githubusercontent.com/19872682/110259806-e601a480-7fa9-11eb-8ab5-8f95f35fcf7b.png)

JS:
![image](https://user-images.githubusercontent.com/19872682/110259842-003b8280-7faa-11eb-9c3a-c5e6ed2d3b8a.png)

**Comment by realrecordzLab** [comment]
> > > The cookies that are created after the login with puppeteer are a bit different from the structure of the `appstate.json` file, I've opted to trying using a different `userAgent` into the options of the script and seems working. You can reference [this issue](https://github.com/Schmavery/facebook-chat-api/issues/836) for more details.
> > > If you want to use puppeteer to get the cookies, you can use something like this:
> > > ```
> > > const puppeteer = require('puppeteer');
> > > const fs = require('fs');
> > > 
> > > ( async () => {
> > > 
> > > (async () => {
> > >     const browser = await puppeteer.launch({
> > >         headless: false
> > >     });
> > >     
> > >     const page = await browser.newPage();
> > >     
> > >     await page.goto('https://facebook.com/login, {
> > >         waitUntil: ['load', 'networkidle2']
> > >     });
> > >     
> > >     const cookieBanner = await page.$('[data-testid="cookie-policy-banner-accept"]');
> > >     await cookieBanner.click();
> > >     
> > >     const emailField = await page.waitForSelector('[name="email"]', {timeout: 3000});
> > >     await emailField.type(process.env.FB_EMAIL, {delay: 100});
> > > 
> > >     const passwordField = await page.waitForSelector('[name="pass"]', {timeout: 3000});
> > >     await passwordField.type(process.env.FB_PASSWORD, {delay: 100});
> > > 
> > >     const submitButton = await page.waitForSelector('[name="login"]', {timeout: 3000});
> > >     await submitButton.click();
> > > 
> > >     page.waitForNavigation().then( await (response) => {
> > >        console.log(response.url(), response.headers(), response.method());
> > >        // to get the correct cookies you need to pass the url to the cookies() method 
> > >        // use await or .then() the promise return an object with all the needed info
> > >        const cookies = await page.cookies(response.url());   
> > >        // save your cookies to a file or use them in your code using fs.writeFileSync(...)
> > >     });
> > >    
> > > })();
> > > ```
> > 
> > 
> > I'm using your code to get Cookie but the API showing this error
> > ```
> > ERR! login Error: Cookie not in this host's domain. Cookie:www.facebook.com Request:www.messenger.com
> > ```
> > 
> > 
> > I tried to get cookie from `https://www.messenger.com/` and getting this error
> > ```
> > ERR! login Error retrieving userID. This can be caused by a lot of things, including getting blocked by Facebook for logging in from an unknown location. Try logging in with a browser to verify.
> > {
> >   error: 'Error retrieving userID. This can be caused by a lot of things, including getting blocked by Facebook for logging in from an unknown location. Try logging in with a browser to verify.'
> > }
> > ```
> > 
> > 
> > i double-check but my bot account didn't get any Checkpoint
> 
> It doesn't work for me. I tried using it as TS and as JS and there's errors in both (unfortunately i'm too new to the programming paradigm that javascript uses so i have no idea how to fix this.
> 
> TS:
> ![image](https://user-images.githubusercontent.com/19872682/110259806-e601a480-7fa9-11eb-8ab5-8f95f35fcf7b.png)
> 
> JS:
> ![image](https://user-images.githubusercontent.com/19872682/110259842-003b8280-7faa-11eb-9c3a-c5e6ed2d3b8a.png)

You can't use `await` in that way. inside the `then()` you can use `async`. Change the code in this way

```js
.then( async (response) => {  ... });
```

**Comment by mobaradev** [comment]
"ERR! login Error retrieving userID. This can be caused by a lot of things, including getting blocked by Facebook for logging in from an unknown location. Try logging in with a browser to verify.
{
  error: 'Error retrieving userID. This can be caused by a lot of things, including getting blocked by Facebook for logging in from an unknown location. Try logging in with a browser to verify.'
}
"

Cookies are valid, but I cannot login

**Comment by TuanNV95** [comment]
I also got this error when logging in with cookies, however I don't know how to fix it :( 
![image](https://user-images.githubusercontent.com/61636758/110966087-816a8f00-8387-11eb-89aa-32587434867e.png)

**Comment by realrecordzLab** [comment]
@mobaradev @TuanNV95  Have you tried to set a different user agent as suggested [here](https://github.com/Schmavery/facebook-chat-api/issues/836)?

**Comment by realrecordzLab** [comment]
> > @mobaradev @TuanNV95 Have you tried to set a different user agent as suggested [here](https://github.com/Schmavery/facebook-chat-api/issues/836)?
> 
> Yes, I tried it but I still get the same error result. I'm not sure, here's my code.
> ![image](https://user-images.githubusercontent.com/61636758/110987216-5a20bb80-83a1-11eb-804b-3de6fe6f11fe.png)

You need to change the user agent of the facebook-chat-api script, not the one exposed from puppeteer. 
**NB: I've not tested yet with the cookies retrived from puppeter so I don't know if cookies created with it are working with this library.**

**Comment by TuanNV95** [comment]
> > > @mobaradev @TuanNV95 Have you tried to set a different user agent as suggested [here](https://github.com/Schmavery/facebook-chat-api/issues/836)?
> > 
> > 
> > Yes, I tried it but I still get the same error result. I'm not sure, here's my code.
> > ![image](https://user-images.githubusercontent.com/61636758/110987216-5a20bb80-83a1-11eb-804b-3de6fe6f11fe.png)
> 
> You need to change the user agent of the facebook-chat-api script, not the one exposed from puppeteer.
> **NB: I've not tested yet with the cookies retrived from puppeter so I don't know if cookies created with it are working with this library.**

Thank you, I made a mistake there, but after changing it, it still returns the same error. Maybe cookie retrieved from puppeteer don't really fit this library.
![image](https://user-images.githubusercontent.com/61636758/110996799-0d43e180-83af-11eb-9c7a-5dde807171e8.png)

**Comment by AFalseHuman** [comment]
Im also facing the same problem , I copied the one with puppeteer but when I run the js file nothing happens

**Comment by hoangvu12** [comment]
> @trangcongloc the library will create a different structure for the cookies that will be saved inside the `appstate.json` file. If you want to use puppeteer to get only the cookies, after the login you will need to format them to to reflect the appState expected structure otherwise the library will not work.
> 
> This is the required structure of the `appstate.json` file.
> 
> ```
>     {
>         "key": "locale",
>         "value": "en_US",
>         "domain": "messenger.com",
>         "path": "/",
>         "secure": true,
>         "hostOnly": false,
>         "creation": "2021-02-23T12:07:23.715Z",
>         "lastAccessed": "2021-02-23T12:07:26.469Z"
>     }
> ```
> 
> It's completely different from the cookies that are retrived using puppeteer. the fields `key` in puppeteer is called `name` and the `hostOnly` field isn't present inside the cookies of puppeteer. There can be also other differences but I don't remember exactly
> 
> The wrong username/password error can be fixed by setting a different user-agent instead of the default one used from the library. Please refer to [this issue](https://github.com/Schmavery/facebook-chat-api/issues/836) for details.


Uh try this. Tell me if it works!

https://github.com/Schmavery/facebook-chat-api/issues/862#issuecomment-762436951

**Comment by hoangvu12** [comment]
> ```js
> const options = {
>     userAgent: 'Mozilla/5.0 (Linux; Android 6.0.1; Moto G (4)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Mobile Safari/537.36',
>     listenEvents: true
> }
> ```

```js
const options = {
  userAgent:
    "Mozilla/5.0 (Linux; Android 6.0.1; Moto G (4)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Mobile Safari/537.36",
  listenEvents: true,
};

login(loginData, options, (err, api) => {
  if (err) {
    switch (err.error) {
      case "login-approval":
        console.log("Enter code > ");
        rl.on("line", (line) => {
          err.continue(line);
          rl.close();
        });
        break;
      default:
        console.error(err);
    }
    return;
  }
  fs.writeFileSync("appstate.json", JSON.stringify(api.getAppState()));

  // Logged in!
});
```

![image](https://user-images.githubusercontent.com/68330291/112240119-4bc48080-8c7a-11eb-9e5e-a82563aa012e.png)


This is what I've tried. Still got the error.

**Comment by realrecordzLab** [comment]
> > ```js
> > const options = {
> >     userAgent: 'Mozilla/5.0 (Linux; Android 6.0.1; Moto G (4)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Mobile Safari/537.36',
> >     listenEvents: true
> > }
> > ```
> 
> ```js
> const options = {
>   userAgent:
>     "Mozilla/5.0 (Linux; Android 6.0.1; Moto G (4)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Mobile Safari/537.36",
>   listenEvents: true,
> };
> 
> login(loginData, options, (err, api) => {
>   if (err) {
>     switch (err.error) {
>       case "login-approval":
>         console.log("Enter code > ");
>         rl.on("line", (line) => {
>           err.continue(line);
>           rl.close();
>         });
>         break;
>       default:
>         console.error(err);
>     }
>     return;
>   }
>   fs.writeFileSync("appstate.json", JSON.stringify(api.getAppState()));
> 
>   // Logged in!
> });
> ```
> 
> ![image](https://user-images.githubusercontent.com/68330291/112240119-4bc48080-8c7a-11eb-9e5e-a82563aa012e.png)
> 
> This is what I've tried. Still got the error.

The error is clear, you have the login approval turned on. Check the documentations about how to solve the problem

**Comment by hoangvu12** [comment]
> > > ```js
> > > const options = {
> > >     userAgent: 'Mozilla/5.0 (Linux; Android 6.0.1; Moto G (4)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Mobile Safari/537.36',
> > >     listenEvents: true
> > > }
> > > ```
> > 
> > ```js
> > const options = {
> >   userAgent:
> >     "Mozilla/5.0 (Linux; Android 6.0.1; Moto G (4)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Mobile Safari/537.36",
> >   listenEvents: true,
> > };
> > 
> > login(loginData, options, (err, api) => {
> >   if (err) {
> >     switch (err.error) {
> >       case "login-approval":
> >         console.log("Enter code > ");
> >         rl.on("line", (line) => {
> >           err.continue(line);
> >           rl.close();
> >         });
> >         break;
> >       default:
> >         console.error(err);
> >     }
> >     return;
> >   }
> >   fs.writeFileSync("appstate.json", JSON.stringify(api.getAppState()));
> > 
> >   // Logged in!
> > });
> > ```
> > 
> > ![image](https://user-images.githubusercontent.com/68330291/112240119-4bc48080-8c7a-11eb-9e5e-a82563aa012e.png)
> > 
> > This is what I've tried. Still got the error.
> 
> The error is clear, you have the login approval turned on. Check the [documentations](https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#login) to solve the problem.

Well I solved this problem by remove the current 2fa method, then add new one and it just work.

**Comment by CongTuHaoHoa** [comment]
I have a solution here _https://youtu.be/y9_yd5a3scM_

Please tell me if it's works!

**Comment by pollmix** [comment]
@CongTuHaoHoa I am facing `TypeError: appState.map is not a function` error.
