### ISSUE TITLE
are there someting like this but for Android?

### ISSUE THREAD

**Issue by GinesMendoza** [Schmavery/facebook-chat-api#87]
I would like to know if there are something similar to this or some way to implement this on android.

Anyway thanks a lot for share your source :)

**Comment by bsansouci** [comment]
Hey @GinesMendoza, unfortunately I don't know of anyone who implemented this for android. @Schmavery Any idea?
If you feel courageous, you could implement something similar for your needs in Java. Feel free to ask questions.

**Comment by Schmavery** [comment]
@GinesMendoza I'd probably be interested in contributing to this if you start one.  Let us know if you do!
