### ISSUE TITLE
TypeError: event.senderID is not a function

### ISSUE THREAD

**Issue by valentino1337** [Schmavery/facebook-chat-api#874]
hello. i am trying to make a bot that listens to one and only groupchat, and if one particular person says something, it activates the section at the bottom, and if it doesnt, it just returns. for some rason im getting the error in console. it is a part of a discord bot im working on, thats why its in "discordbot" folder
i tried getting rid of the "event" altogether and just do message.senderID, but that did basically the same thing

> /home/valentino/Desktop/discordbot/events/messenger.js:12
>         if(!event.senderID("100055076242106") || !event.threadID("4724817374202750")){//there is the problem
>                   ^
> 
> TypeError: event.senderID is not a function
>     at /home/valentino/Desktop/discordbot/events/messenger.js:12:19
>     at /home/valentino/Desktop/discordbot/node_modules/facebook-chat-api/src/listenMqtt.js:159:26
>     at MqttClient.<anonymous> (/home/valentino/Desktop/discordbot/node_modules/facebook-chat-api/src/listenMqtt.js:159:60)
>     at MqttClient.emit (node:events:378:20)
>     at MqttClient._handlePublish (/home/valentino/Desktop/discordbot/node_modules/mqtt/lib/client.js:1162:12)
>     at MqttClient._handlePacket (/home/valentino/Desktop/discordbot/node_modules/mqtt/lib/client.js:351:12)
>     at work (/home/valentino/Desktop/discordbot/node_modules/mqtt/lib/client.js:283:12)
>     at Writable.writable._write (/home/valentino/Desktop/discordbot/node_modules/mqtt/lib/client.js:294:5)
>     at doWrite (/home/valentino/Desktop/discordbot/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:428:64)
>     at writeOrBuffer (/home/valentino/Desktop/discordbot/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:417:5)
>     at Writable.write (/home/valentino/Desktop/discordbot/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:334:11)
>     at Duplexify.ondata (/home/valentino/Desktop/discordbot/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:619:20)
>     at Duplexify.emit (node:events:378:20)
>     at addChunk (/home/valentino/Desktop/discordbot/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:291:12)
>     at readableAddChunk (/home/valentino/Desktop/discordbot/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:278:11)
>     at Duplexify.Readable.push (/home/valentino/Desktop/discordbot/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:245:10)

```
const fs = require('fs');
const Discord = require('discord.js')
const login = require("facebook-chat-api");

login({appState: JSON.parse(fs.readFileSync('appstate.json', 'utf8'))}, (err, api) => {
    if(err) return console.error(err);
    api.listenMqtt( (err, event) => {
        if(err){ 
            return console.log(err);
        }
        //api.setOptions({selfListen: true})//to test it on myself
        if(!event.senderID("100055076242106") || !event.threadID("4724817374202750")){//there is the problem
            console.log('test')
            return;
        }
        api.markAsRead(message.threadID);
        //var yourID = "4724817374202750"; 
        //var msg = {body: "test"};
        //api.sendMessage(msg, yourID); //commented it out, so i dont spam the groupchats
        console.log('jodej')//this is instead of spamming
    });
});
```

**Comment by KMatuszak** [comment]
```
if(event.senderID !== "100055076242106" || event.threadID !== "4724817374202750")
```
