### ISSUE TITLE
Larger example of usage

### ISSUE THREAD

**Issue by mrkno** [Schmavery/facebook-chat-api#90]
If you would like another very large example of this projects usage within a bot we are using it within https://github.com/mrkno/Kassy

**Comment by Schmavery** [comment]
We'd be happy to include this, as long as you can confirm that it's using v2.x of the api.  @bsansouci thoughts?

**Comment by mrkno** [comment]
Yes, uses v1.x of your api as of a push earlier today.

**Comment by bsansouci** [comment]
Sure! Can you give us one sentence that would best describe Kassy?

**Comment by mrkno** [comment]
"Kassy is a modular, easily extensible general purpose chat bot".

Don't know if that really describes it all that well. Basically the idea is that small node.js modules are written for it then placed in a folder. They will load on startup and become part of what the chat bot provides. The current pre-installed modules are [here](https://github.com/mrkno/Kassy/tree/master/modules). They include a variety of functionality from getting animated gifs to running arbitrary sandboxed javascript code, voting and giving karma.

**Comment by bsansouci** [comment]
I add it on the readme! Nice project btw. If you need anything from us don't hesitate to ask :)
