### ISSUE TITLE
Unhandled rejection TypeError: Cannot read properties of undefined (reading 'messageCount')

### ISSUE THREAD

**Issue by tddaij** [Schmavery/facebook-chat-api#900]
api.listenMqtt(function callback(err, message) {
    api.getThreadInfo(message.threadID, function(err, thread) {
        if (message.body === "count") {
            api.sendMessage("Total: " + thread.messageCount, message.threadID);
        }
    });
});

**Comment by BadAimWeeb** [comment]
your account has been blocked for calling API too much.
do not call API before checking if the message is the command to bot.

```ts
api.listenMqtt(function callback(err, message) {
    if (message.body === "count") {
        api.getThreadInfo(message.threadID, function (err, thread) {
            if (err) {
                // Blocked?
                return console.error(err);
            }
            api.sendMessage(`Total: ${thread.messageCount}`, message.threadID);
        });
    }
}
```
