### ISSUE TITLE
Can getUserInfo provide Cover picture?

### ISSUE THREAD

**Issue by nripendra** [Schmavery/facebook-chat-api#93]
I'm thinking of a ui where I'd also like to show user's cover picture? But I don't want to resort to some other api that requires access tokens. 

Is is possible to get cover picture url?

**Comment by Schmavery** [comment]
I'd imagine this will be possible, but will require some investigation.  If you submit a PR with this change, I'd definitely consider it.  @bsansouci

**Comment by nripendra** [comment]
Thanks for the reply. I'll fork the project and check if I can figure out.
