### ISSUE TITLE
getOnlineUsers() statuses is undefined

### ISSUE THREAD

**Issue by nripendra** [Schmavery/facebook-chat-api#94]
Hi,

When getting data from getOnlineUsers, there is a field named statuses but it's value is undefined.

**Comment by Schmavery** [comment]
Sounds like Facebook has either changed the format of their data or doesn't send us this information anymore.  Happens pretty frequently.
If you print out the value of `data[key]` at [this position](https://github.com/Schmavery/facebook-chat-api/blob/master/src/getOnlineUsers.js#L8), you might be able to see what the data we receive looks like.

**Comment by nripendra** [comment]
Data looks like this:

500936670: Object
a: 2
c: 10
i: false

503030566: Object
a: 1
c: 10
i: false

504252011: Object
a: 2
c: 0
i: false

507166671: Object
a: 2
c: 10
i: false

509843233: Object
a: 2
c: 8
i: false

**Comment by bsansouci** [comment]
Nice catch, they did change their format. I'm not sure how to interpret the new `statuses` field because it looks like `{ i: false, a: 2, c: 8 }`. I'll look into it.

**Comment by bsansouci** [comment]
@nripendra I updated the docs, this should do it.

**Comment by nripendra** [comment]
Thanks!!
