### ISSUE TITLE
getUserId by Email

### ISSUE THREAD

**Issue by rikka94** [Schmavery/facebook-chat-api#99]
I wonder if its possible to implement get user by email instead of name , as name is really not reliable..

Since this api simulate facebook browsing and the searching function in facebook is capable to return result by email, i think it is possible right ?

**Comment by rikka94** [comment]
Nevermind , i look into the source code and realize i can use email as argument and work the same..

Thanks for the api , its working great !

**Comment by bsansouci** [comment]
Haha glad you like it. Please open issues for questions, requests, bugs or feedback :)
